### ISSUE TITLE
Incorrect order behavior using PayPal Express Checkout

### ISSUE THREAD

**Issue by farior** [magento/magento2#10142]
### Preconditions
1. PHP 7.0.10
2. Mysql 5.7.15
3. Fresh Magento CE 2.1.7 installation
4. Sample Data deployed
5. PayPal Express Checkout sandbox configured

### Steps to reproduce
1. Go to Admin > Products > Catalog, find "Hero Hoodie" product and ensure all configurations have **100** qty
1. Go to home page and click on "Hero Hoodie" product
2. Choose **Black** color, **XS** size, input qty=**100** and Add product to cart
3. Continue through checkout process, choose PayPal and place order
4. Click Pay Now in PayPal window

### Expected result
1. User is redirected to checkout success page
2. Order is successfully created with invoice
3. Order confirmation email is sent
4. Stock qty is correctly decreased to 0

### Actual result
**For the first try:**
1. User is redirected to /checkout/cart page
2. A bunch of errors presented (We can't place order, We can't initialize Express Checkout, Some products are out of stock)

![pp_error](https://user-images.githubusercontent.com/10270387/27832839-e9947882-60d8-11e7-9ecb-646d116dc2c9.jpg)

3. Order confirmation is not sent
4. PayPal payment is successful, but order doesn't contain invoice
5. "Hero Hoodie" Product with configurations (Black, XS) now 200 at stock

![3c67d34edf](https://user-images.githubusercontent.com/10270387/27832933-44aad8c4-60d9-11e7-91ab-0ea00bcb38c7.jpg)

**Next attempts with another size:**
1. User is redirected to /paypal/express/review/
2. "We can't place the order." error displayed
3. Order confirmation is not sent
4. PayPal payment is successful, but order is not created
5. Stock qty is correctly decreased to 0

**Comment by YevSent** [comment]
Hi, @farior, please, enable debug mode for PayPal Express Checkout and attach `debug.log` and `exception.log` to this ticket.

**Comment by farior** [comment]
@joni-jones  Here are debug.log and system.log (renamed with txt extension to allow github to attach it)

exception.log was empty

[debug.txt](https://github.com/magento/magento2/files/1124168/debug.txt)
[system.txt](https://github.com/magento/magento2/files/1124170/system.txt)

**Comment by vishveskrish** [comment]
Hi @joni-jones 

We are facing the same issue on frontend site. When customers try to place an order with equal numbers of quantity persist in the system.
@farior did you found any patch for that?

Let us know the solution ASAP!

**Comment by ambergithub** [comment]
I am facing the same issue please do resolve it Here is the request and response it creating.

main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'DoExpressCheckoutPayment' => 
  array (
    'TOKEN' => 'EC-4NJ05029WA561225K',
    'PAYERID' => 'CEWCZJ8F9LRZE',
    'PAYMENTACTION' => 'Authorization',
    'AMT' => '101.00',
    'CURRENCYCODE' => 'AUD',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
    'NOTIFYURL' => 'http://localproduction.junaidjamshed.com/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'SHIPPINGAMT' => '0.00',
    'ITEMAMT' => '101.00',
    'TAXAMT' => '0.00',
    'L_NUMBER0' => NULL,
    'L_NAME0' => 'JLAWN-S-AU-17-102/S Geometrica ',
    'L_QTY0' => 1,
    'L_AMT0' => '101.00',
    'BUSINESS' => NULL,
    'EMAIL' => 'IsabelleDempster@teleworm.us',
    'FIRSTNAME' => 'Isabelle',
    'LASTNAME' => 'Dempster',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'AU',
    'STATE' => 'NSW',
    'CITY' => 'MELINGA',
    'STREET' => '27 Aquatic Road',
    'ZIP' => '3241',
    'PHONENUM' => '(02) 4925 3070',
    'SHIPTOCOUNTRYCODE' => 'AU',
    'SHIPTOSTATE' => 'NSW',
    'SHIPTOCITY' => 'MELINGA',
    'SHIPTOSTREET' => '27 Aquatic Road',
    'SHIPTOZIP' => '3241',
    'SHIPTOPHONENUM' => '(02) 4925 3070',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'Isabelle Dempster',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-4NJ05029WA561225K',
    'SUCCESSPAGEREDIRECTREQUESTED' => 'false',
    'TIMESTAMP' => '2017-07-11T12:11:04Z',
    'CORRELATIONID' => 'cdc11099ec5ac',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '35915193',
    'TRANSACTIONID' => '4SS64028GD219152L',
    'TRANSACTIONTYPE' => 'cart',
    'PAYMENTTYPE' => 'instant',
    'ORDERTIME' => '2017-07-11T12:11:03Z',
    'AMT' => '101.00',
    'TAXAMT' => '0.00',
    'CURRENCYCODE' => 'AUD',
    'PAYMENTSTATUS' => 'Pending',
    'PENDINGREASON' => 'authorization',
    'REASONCODE' => 'None',
    'PROTECTIONELIGIBILITY' => 'Eligible',
    'INSURANCEOPTIONSELECTED' => 'false',
    'SHIPPINGOPTIONISDEFAULT' => 'false',
    'PAYMENTINFO_0_TRANSACTIONID' => '4SS64028GD219152L',
    'PAYMENTINFO_0_TRANSACTIONTYPE' => 'cart',
    'PAYMENTINFO_0_PAYMENTTYPE' => 'instant',
    'PAYMENTINFO_0_ORDERTIME' => '2017-07-11T12:11:03Z',
    'PAYMENTINFO_0_AMT' => '101.00',
    'PAYMENTINFO_0_TAXAMT' => '0.00',
    'PAYMENTINFO_0_CURRENCYCODE' => 'AUD',
    'PAYMENTINFO_0_PAYMENTSTATUS' => 'Pending',
    'PAYMENTINFO_0_PENDINGREASON' => 'authorization',
    'PAYMENTINFO_0_REASONCODE' => 'None',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITY' => 'Eligible',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE' => 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    'PAYMENTINFO_0_SECUREMERCHANTACCOUNTID' => 'RKPZ7EGZ6HYHU',
    'PAYMENTINFO_0_ERRORCODE' => '0',
    'PAYMENTINFO_0_ACK' => 'Success',
  ),
) {"is_exception":false} []

**Comment by farior** [comment]
@joni-jones @alena-marchenko Any updates on this ticket? I think it's pretty major issue

**Comment by vishveskrish** [comment]
Hello All,

Any one get the solution of this issue?

**Comment by YevSent** [comment]
Hi, guys. The internal ticket is already created (`MAGETWO-70500`) and will be fixed according to its priority. Unfortunately, I can't provide any estimation now.

**Comment by andidhouse** [comment]
Same here on 2.1.7 - frustrating if a payment method implemented by magento is not working as expected. Not shure how other payment provider should built an working payment extension if even the magento core team fails!

At the moment PayPal is not usable with magento2 our problem is exact:

- Put the last configurable article in the cart
- Checkout with PayPal 
- as soon as you get redirect after the payment to the Webshop (normally success page) magento redirects to the shopping cart page (like above) with 3-4 errors.

--> The customer thinks the order is not placed - but he has payed for it.
So the service overloads at all.

For the moment the only solution is to deactivate PayPal at all in magento2.

And i really hope the @magento-team offers a solution for 2.1.7 in the next days (not month - not years) and not for 2.2.x.

I am shure this is one of the priority one+ bugs - can the magento team pls confirm that they are actively working on this with a solution in days?

I think PayPal would not be very happy to read this here also.
Thanks!

**Comment by pboisvert** [comment]
@andidhouse The event directly above your post shows that the dev team is "in progress" on this specific issue. As noted on your more recent report, #10464 that issue has been addressed in 2.1.8 released today. Please try that version and let us know if the issue you have seen is resolved.

**Comment by okorshenko** [comment]
@farior, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by muksSoni** [comment]
Hello All,

I am using magento 2.1.7 and facing issue in paypal payment method, getting error from paypal response "We can't place the order". After that I have applied the ( https://github.com/magento/magento2/commit/f954a9150aef87d58ccc4f400815f6337234f09a ) fix suggested on github but still not able to fix the payment and getting new error "We can't initialize Express Checkout".
I have searched on google and found this tread https://github.com/magento/magento2/issues/10142 where others also facing same issue. And here magento team is fixed this issue in magento 2.2.0 version. I want to confirm does this issue is fixed in magento 2.1.10 or latest 2.1.x version. Because other extension installed on site also need to compatible with magento 2.2.0 version.
[debug.txt](https://github.com/magento/magento2/files/1534579/debug.txt)
 
Thanks,
Mukesh Soni

**Comment by ebaschiera** [comment]
Adding https://github.com/magento/magento2/commit/27d3565877d97593521b2c22ff2803d5996ffefa fixed the issue on a Magento 2.1.10 installation.

**Comment by yosefkurniawan** [comment]
hi @okorshenko 
is there any workaround or patch fix that we can apply on 2.1.8?

**Comment by umeshsainee** [comment]
Hello All,

I updated website from 2.17 to 2.1.10  also applied the patch 27d3565 but I have issue where orders not being confirmed from cart and user getting a notification of paying through PayPal.

Thanks,

**Comment by vinothinik2010** [comment]
Hi,

We facing the same issue in 2.2.2 , the patch codes are already  had in the core module. We faced samething as mentioned in the top of the page. 

We enabled the debug mode too, but we didn't get anything in debug log file. 

If anyone provide solution, it will help us.

Thanks

**Comment by deepakgairola25** [comment]
The issue is still there in version 2.3, if we order same quantity which is available and process through  checkout.
as soon as you get redirect after the payment magento redirects to the shopping cart page  with 3-4 errors.
--> The customer thinks the order is not placed - but he has payed for it.
So the service overloads at all.
After that when next time we increate the quantitym the default stock is quantity + last failed order quantity.

![image](https://user-images.githubusercontent.com/5247953/54886070-a0f70d00-4e7b-11e9-9b20-1e1271afe2bf.png)
