### ISSUE TITLE
Checkout place order exception when using a new address

### ISSUE THREAD

**Issue by mbijnsdorp** [magento/magento2#10583]
### Preconditions
1. Magento 2.1.8 CE
2. PHP 7.0
3. Have a plugin on `\Magento\Customer\Api\Data\CustomerInterface` (any function, the plugin doesn't have to do anything)

### Steps to reproduce
1. Register as new customer
2. Add a product to your cart
3. Go to the checkout page
4. Fill in your address details and go through the checkout steps
5. Place an order

### Expected result
1. Order is placed and the address is added to your address book

### Actual result
1. The checkout displays the error message "An error occurred on the server. Please try to place the order again."

The actual error message is this: InvalidArgumentException: Getter return type must be specified using @return annotation. See Magento\Customer\Model\Data\Customer\Interceptor::getDefaultBilling() in vendor/magento/framework/Reflection/TypeProcessor.php on line 305

This error is caused in: `\Magento\Quote\Model\Quote::updateCustomerData()` by 
`$this->dataObjectHelper->mergeDataObjects(get_class($quoteCustomer), $quoteCustomer, $customer);`

The `$quoteCustomer` is the interceptor, and the `TypeProcessor` can't retrieve the required docblock information from it.

**Comment by ArthurTransoftgroup** [comment]
@mbijnsdorp We've created internal ticket MAGETWO-71981 to address this issue.

**Comment by Tjab** [comment]
We seem to be having the same issue. We do not however have the issue in the front-end, but do have it in the back-end. A customer that uses our plugin had the message described as above (`getDefaultBilling()`). In my test environment, after saving an order in the back-end, I get:

    Order saving error: Getter return type must be specified using @return annotation.
    See Magento\Customer\Model\Data\Customer\Interceptor::getExtensionAttributes()

Our method, which causes the error above:

    * @return \Magento\Customer\Api\Data\CustomerExtensionInterface
    */
    public function afterGetExtensionAttributes(

It is the same as other plugins we have (the order, invoice, creditmemo and product plugin):

    * @return \Magento\Sales\Api\Data\OrderExtensionInterface
    */
    public function afterGetExtensionAttributes(

These methods do work.

I'd like to point out the same as @mbijnsdorp said: the method can be empty, it doesn't need to have any functionality in it, it always results in an error.

**Comment by Bobstar040** [comment]
I'm having the same issue with magento admin orders!

**Comment by mamreezaa** [comment]
Having same issue when do reorder from admin. 
![screenshot from 2017-09-14 15-36-19](https://user-images.githubusercontent.com/8044896/30427873-8da4bdf8-9962-11e7-9e50-3019ef393ba1.png)

**Comment by Bobstar040** [comment]
I am getting this error btw: Order saving error: Getter return type must be specified using @return annotation. See Magento\Customer\Model\Data\Customer\Interceptor::getDefaultBilling()

Any idea how to solve this?

**Comment by Bobstar040** [comment]
My issue is solved now, it was due to an extension which uses api to transfer orders from M2 to my bookkeeping software. 

But it would be nice if M2 can generate a proper error log to debug this issue faster.

**Comment by Tjab** [comment]
For the record, I'd like to point out that there's a problem in Magento 2 and if you call upon certain functionality, things break. As soon as you do not call upon that functionality (disable the plugin/remove code from the plugin), the problem "is solved" but the main problem still persists with Magento 2.

For our plugin, we need functionality on Orders, Products, etc. (which works), but as soon as we enable the same functionality for Customers, M2 breaks down. To the developers @ M2 I'd like to point this out, that there's still a problem :)

**Comment by PascalBrouwers** [comment]
@mbijnsdorp you still have this issue or do you have a fix?

**Comment by mbijnsdorp** [comment]
My personal fix was replacing `get_class($quoteCustomer)` with `CustomerInterface::class`. Haven't submitted it as a fix, as I thought there might be a specific reason behind using `get_class`.

**Comment by YevSent** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @mbijnsdorp. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1286 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by arendarenko** [comment]
Issue is swill present in 2.3.5
It's reproducing after you create plugin for AddressInterface.

@magento-team mentioned link is not working

I used #25965 patch to fix this issue locally, but probably it's need to be fixed on the Magento side.
