### ISSUE TITLE
Magento 2.1.9  wysiwyg upload images broken in frontend 

### ISSUE THREAD

**Issue by Ayaname0330** [magento/magento2#11131]
# Preconditions
1.Magento 2.1.9

# Steps to reproduce
1.click the Insert/Edit image
2.choose a  image 
3.save

# Expected result
1.the image show in frontend

# Actual result
1.the image broken
2.the url contains '/cms/wysiwyg/directive/___directive'

**Comment by magento-engcom-team** [comment]
@Ayaname0330, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by barryvdh** [comment]
I have the same issue when editing Content -> Pages. After inserting image via the editor -> Insert Image -> browse, the link looks like `http://mydomain.com/admin_123/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5cqLWRlLWtpcC5wbmcifX0%2C/key/2cda8ae0fd4ce300714c145c72b7c42a99a3fb2fa2485584/`
This link isn't replaced when saving and will 404 when shown on the frontend.

**Comment by PieterCappelle** [comment]
Hi, this is related to this issue https://github.com/magento/magento2/issues/10417 and fixed with my PR https://github.com/magento/magento2/pull/11048

**Comment by magento-engcom-team** [comment]
@Ayaname0330, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by erikkubica** [comment]
@magento-engcom-team @PieterCappelle this happens when you copy paste content from wysiwyg A to wysiwyg B where is image, the image url in this case is special url that requires to be logged in into admin to be able to see the image. At least this was our case. After we inserted/replaced image manually using the insert image in wysiwyg B, the image started working.

**Comment by damjess** [comment]
Experiencing the same issue here. The image is saved with a backend url that is not visible to anyone outside of the admin account that "placed" the image using wysiwyg. I've tried uploading again and placing each image (no copy + paste) and the problem still occurs. Running 2.1.10

**Comment by carloricci84** [comment]
I fixed this problem in 2.1.11 by overriding the class Magento\Framework\Event\ObserverInterface\CatalogCheckIsUsingStaticUrlsAllowedObserver

I added a verification on the store id to set it to 0 if it is an empty string and it works correctly now. It will only works if you have the setting "Use Static URLs for Media Content in WYSIWYG for Catalog" set to yes in Configuration -> General -> Content Management.


```
public function execute(\Magento\Framework\Event\Observer $observer){
        $storeId = $observer->getEvent()->getData('store_id');
        $result = $observer->getEvent()->getData('result');

        if($storeId == ""){
            $storeId = 0;
        }

        $result->isAllowed = $this->catalogData->setStoreId($storeId)->isUsingStaticUrlsAllowed();
}
```
