### ISSUE TITLE
User.ini files specify 768M - Docs recommend at least 1G

### ISSUE THREAD

**Issue by pmcmanaman** [magento/magento2#11322]
### Preconditions

1. Magento 2.2 and PHP-FPM

### Steps to reproduce

1. The .user.ini files at /.user.ini and /pub/.user.ini have memory_limit = 768M
2. Magento documentation ( http://devdocs.magento.com/guides/v2.2/install-gde/trouble/php/tshoot_php-set.html ) recommned 1GB for normal use or at least 2GB for debugging.

### Expected result

1. For values specified in files to match the documentation.

**Comment by lewisvoncken** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82747

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release soon

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82780

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82781

**Comment by andy-rush-beerhawk** [comment]
I have just upgraded to 2.2.3 and this issue persists in pub/.user.ini.

**Comment by DavidLambauer** [comment]
This issue has never been fixed. Even in 2.3.1, the .user.ini says 754MB of memory_limit. Can someone explain why the docs and the .user.ini do recommend two different memory_limits?

**Comment by ihor-sviziev** [comment]
> This issue has never been fixed. Even in 2.3.1, the .user.ini says 754MB of memory_limit. Can someone explain why the docs and the .user.ini do recommend two different memory_limits?

Hi @DavidLambauer,
Thank you for raising this issue, I hope it's described good enough in my comment https://github.com/magento/magento2/pull/24533#issuecomment-530219625
