### ISSUE TITLE
How to Fix the wrong input format of Customer date of birth 

### ISSUE THREAD

**Issue by selusi** [magento/magento2#11332]
### Preconditions
1. PHP 7.0.22
2. MySql 5.7
3. Apache 2.4
4. Magento 2.2.0

### Steps to reproduce
1. Login to frontend
2. Edit Customer information

### Expected result
1. The year of birth date should be in the format: yyyy.

### Actual result
1. The actual format is yy

### To fix the issue
To solve the issue have to modify the file:
vendor\magento\module-customer\Block\Widget\Dob.php
Actually the line 113 is:
```php
$data['format'] = $this->getDateFormat(); 
``` 
(that return MM/dd/yy format in English locale)
This format is good for javascript datepicker configuration but it is wrong for the form input text.
I wrote a method that return the correct date format:
```php
protected function getDateFormatForInput()
{
    $formatArr = explode(' ', preg_replace("/[^a-zA-Z]/",' ',$this->getDateFormat())) ;
    $reseteFormat = array();
    foreach($formatArr as $k){
        if($k != ''){
            if(substr($k,0,1) == 'y' ){
                $reseteFormat[] = 'yyyy';
            } else {
                $reseteFormat[] = $k;
            }
        }
    }
    return implode("/", $reseteFormat);
}
```
the new 113 line:
```php
$data['format'] = $this->getDateFormatForInput(); 
```
Obviously this is my code though not very elegant, but it solves the problem.

**Comment by magento-engcom-team** [comment]
@selusi, thank you for your report.
We've created internal ticket(s) MAGETWO-81452 to track progress on the issue.

**Comment by manuelson** [comment]
Can i work in this issue? Thanks!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81580

**Comment by okorshenko** [comment]
Hi @selusi the issue has been fixed in 2.2-develop branch and will be available in 2.2.2 soon

**Comment by magento-engcom-team** [comment]
Hi @selusi. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1361 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 716f9afd694b6d7e5423bd2dbdabeeb45797886b
 - 595527a919eafd309f8b2a1d1339b312f6546f7b
 - 8c05a29b711ca03ecb866fc384122b3e46c08ccd
 - 63958cdc14bf3b44ad5fd95aafc626d8e25ca3e3
 - 78c2c2159b6c5aacc27e4fc918a1ed56a9df9b5f
 - 7f2dc2965a2d46e935770a7acdef8f260bd5fdc6
 - aee74586a9d28c1f47fd2ba3bae5e5871b779be9
 - 92f85860ce9725e34922a523e5137e656322c394
 - bf178ca5c3c10a50e3eba6e64fdf905e75d0b4c5
 - ecafa804c26054499b42c6820f0996035eb39dbc
 - a15208e96c06248d740ee65d154eda30226c848a
 - 76716b84a92f009253039cd06b9e47367384655f
 - 490785fffd885f85a7292c9144783cf2576b6b66
 - 6fe62802f5a529cd113697df79021bdb1dda9f53
 - 33e40ece8246363429be614440622600394a4516
 - 7b1bec8edb2eedea399eb78f891f1d6873cb1955
 - dbe5fc792279802f83d7110285c15fb2eede8d95
 - 22c6937f6db6a2ed17188f24097e0f9a194dc295
 - ca7da3fd58edca05b70a2af1768743ffc0294b72
 - b55a5d1a497279f72735e577ba60327dba178b6e
 - 65b745f7a94b2ba699a68f2825a63c9d78615f1c
 - b0a5a52df60a765748f15a7e0391f6b50535de21
 - 97dd9ad59c7d6bf9d4cf673a8e22708c480b1967
 - aa28366cc7378a972497e186fa8fb955684f74aa
 - 0fc86d89ab491fe7fc246d025662658844cd15a4
 - f11994acc1e220eb620d3baa63da8427d53e5797
 - 04445d07887870ba47dd2e97006c94d656f85942

The fix will be available with the upcoming 2.3.0 release.

**Comment by brana946** [comment]
To solve this issue need to modify or override below file.

**vendor\magento\module-customer\Block\Widget\Dob.php**

    public function getHtmlExtraParams()
    {
        $validators = [];
        if ($this->isRequired()) {
            $validators['required'] = true;
        }
        $validators['validate-date'] = [
            'dateFormat' => $this->getDateFormat()
        ];
        return 'data-validate="' . $this->_escaper->escapeHtml(json_encode($validators)) . '"';
    }

changes in above function as below
Old

        $validators['validate-date'] = [
            'dateFormat' => $this->getDateFormat()
        ];
Updated

        $validators['validate-dob'] = [
            'dateFormat' => $this->getDateFormat()
        ];

It fix the validation message of dob "please enter valid date" in customer registration and edit page in front-end.

**Comment by lewisje** [comment]
As of Magento 2.3.5-p1, the relevant method looks like this:

```php
public function getHtmlExtraParams()
{
    $validators = [];
    if ($this->isRequired()) {
        $validators['required'] = true;
    }
    $validators['validate-date'] = [
        'dateFormat' => $this->getDateFormat()
    ];
    $validators['validate-dob'] = true;

    return 'data-validate="' . $this->_escaper->escapeHtml(json_encode($validators)) . '"';
}
```

The same change as above works, as long as the new line of code is also removed; that is, change

```php
$validators['validate-date'] = [
        'dateFormat' => $this->getDateFormat()
];
$validators['validate-dob'] = true;
```

to

```php
$validators['validate-dob'] = [
        'dateFormat' => $this->getDateFormat()
];
```

---
Here's the complete override using the [preference mechanism](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/di-xml-file.html#override-a-method-using-preference-nodes), in a new custom module in `app/code/StoreName/Customer`:

**registration.php**

```php
<?php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'StoreName_Customer',
    __DIR__
);
```

**composer.json**

```javascript
{
    "name": "storename/customer",
    "description": "StoreName extension to Magento Customer module",
    "require": {
        "php": "~5.5.0|~5.6.0|^7.0.0",
        "magento/module-customer": "^1.0.0"
    },
    "type": "magento2-module",
    "version": "1.0.0",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "autoload": {
        "files": [ "registration.php" ]
    }
}
```

**etc/module.xml**

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="StoreName_Customer" setup_version="1.0.0">
        <sequence>
            <module name="Magento_Customer" />
        </sequence>
    </module>
</config>
```

**etc/di.xml**

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Customer\Block\Widget\Dob" type="StoreName\Customer\Block\Widget\Dob" />
</config>
```

**Block/Widget/Dob.php**

```php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace StoreName\Customer\Block\Widget;

use Magento\Customer\Api\CustomerMetadataInterface;
use Magento\Framework\Api\ArrayObjectSearch;

/**
 * Class Dob
 *
 * @SuppressWarnings(PHPMD.DepthOfInheritance)
 */
class Dob extends \Magento\Customer\Block\Widget\Dob
{
    /**
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param \Magento\Customer\Helper\Address $addressHelper
     * @param CustomerMetadataInterface $customerMetadata
     * @param \Magento\Framework\View\Element\Html\Date $dateElement
     * @param \Magento\Framework\Data\Form\FilterFactory $filterFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Customer\Helper\Address $addressHelper,
        CustomerMetadataInterface $customerMetadata,
        \Magento\Framework\View\Element\Html\Date $dateElement,
        \Magento\Framework\Data\Form\FilterFactory $filterFactory,
        array $data = []
    ) {
        parent::__construct($context, $addressHelper, $customerMetadata, $dateElement, $filterFactory, $data);
    }

    /**
     * @inheritdoc
     */
    public function _construct()
    {
        parent::_construct();
    }

    /**
     * Sanitizes time
     *
     * @param mixed $value
     * @return bool|int
     */
    private function filterTime($value)
    {
        $time = false;
        if ($value) {
            if ($value instanceof \DateTimeInterface) {
                $time =  $value->getTimestamp();
            } elseif (is_numeric($value)) {
                $time = $value;
            } elseif (is_string($value)) {
                $time = strtotime($value);
                $time = $time === false ? $this->_localeDate->date($value, null, false, false)->getTimestamp() : $time;
            }
        }

        return $time;
    }

    /**
     * Return data-validate rules
     *
     * @return string
     */
    public function getHtmlExtraParams()
    {
        $validators = [];
        if ($this->isRequired()) {
            $validators['required'] = true;
        }
        $validators['validate-dob'] = [
            'dateFormat' => $this->getDateFormat()
        ];

        return 'data-validate="' . $this->_escaper->escapeHtml(json_encode($validators)) . '"';
    }
}
```

**Comment by jmonrove** [comment]
This bug is still present in Magento 2.3.5-p1

The code suggested by @lewisje fixes the issue on the customer registration page, otherwise the system will only let people born after 2000 register.... #ageism!

**Comment by lewisje** [comment]
To be clear, @jmonrova, customers could still register without entering a DoB, as long as that field is not made mandatory (which it isn't by default).
