### ISSUE TITLE
Product Image on Product Page width/height 1px

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#11754]
So on my product page for some reason the width and height of the fotorama divs are 1px and therefor not showing my image.

Stack link :
[Magento product image size](https://magento.stackexchange.com/questions/198698/magento-product-images-size-1px
)
### Preconditions
1.  Magento 2.2.0
2. PHP 7.1.8 

### Steps to reproduce
1.  Create a custom theme with blank theme inherited
2.  Copy/paste etc/view.xml from Magento blank theme
3.  Add product with 1 product image

### Expected result
1.  Product image is shown in width/height that you defined within your view.xml

### Actual result
1.  Product image url and width are fine
2, Fotorama div's have width/height of 1px and therefor not showing the image
3, If you set the width/height of the inline styling of fotorama to desired px in inspector and click the image (so it goes to fullscreen) and close it again the inline styling is back to 1px
4, Fullscreen does work
5, Product images are shown (with wrong size , only 182px instead of 700px that i defined in the view.xml) when you have multiple images

**Divs that have wrong inline px height and width**

```
<div class="fotorama__stage" data-fotorama-stage="fotorama__stage" style="width: 1px; height: 1px;">

<div class="fotorama__stage__shaft" tabindex="0" data-gallery-role="stage-shaft" style="transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); margin-left: 0px; width: 1px;">
```

Full fotorama html :
```
<div class="fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows" style="min-width: 0px; max-width: 100%;">
        <div class="fotorama__stage" data-fotorama-stage="fotorama__stage" style="width: 1px; height: 1px;"><div class="fotorama__fullscreen-icon" data-gallery-role="fotorama__fullscreen-icon" tabindex="0" aria-label="Exit fullscreen" role="button"></div>
            <div class="fotorama__arr fotorama__arr--prev fotorama__arr--disabled" tabindex="-1" role="button" aria-label="Previous" data-gallery-role="arrow" disabled="disabled" style="display: none;">
                <div class="fotorama__arr__arr"></div>
            </div>
            <div class="fotorama__stage__shaft" tabindex="0" data-gallery-role="stage-shaft" style="transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); margin-left: 0px; width: 1px;">
            <div class="fotorama__stage__frame fotorama__active fotorama_horizontal_ratio fotorama__loaded fotorama__loaded--img" aria-hidden="false" data-active="true" href="image_url(removed)" style="left: 0px;"><img src="image_url(removed)" class="fotorama__img" aria-hidden="false"></div></div>
            <div class="fotorama__arr fotorama__arr--next fotorama__arr--disabled" tabindex="-1" role="button" aria-label="Next" data-gallery-role="arrow" disabled="disabled" style="display: none;">
                <div class="fotorama__arr__arr"></div>
            </div>
            <div class="fotorama__video-close"></div>
            <div class="fotorama__zoom-in zoom-in-loaded" data-gallery-role="fotorama__zoom-in" aria-label="Zoom in" role="button" tabindex="0"></div>
            <div class="fotorama__zoom-out zoom-out-loaded" data-gallery-role="fotorama__zoom-out" aria-label="Zoom out" role="button" tabindex="0"></div>
            <div class="fotorama__spinner"></div>
        </div>
        <div class="fotorama__nav-wrap" data-gallery-role="nav-wrap" style="display: none;">
            <div class="fotorama__nav" style="height: 94px;">

                <div class="fotorama__thumb__arr fotorama__thumb__arr--left fotorama__arr--disabled" role="button" aria-label="Previous" data-gallery-role="arrow" tabindex="-1" disabled="disabled">
                    <div class="fotorama__thumb--icon"></div>
                </div>
                <div class="fotorama__nav__shaft">
                    <div class="fotorama__thumb-border"></div>
                </div>
                <div class="fotorama__thumb__arr fotorama__thumb__arr--right fotorama__arr--disabled" role="button" aria-label="Next" data-gallery-role="arrow" tabindex="-1" disabled="disabled">
                    <div class="fotorama__thumb--icon"></div>
                </div>
            </div>
        </div>
    </div>
```

**Note :** 
`php bin/magento catalog:images:resize` does not change anything

**Screenshot catagory (working):**
![image](https://user-images.githubusercontent.com/18028151/32030315-644b21f0-b9fa-11e7-94d7-48bb37e1f03e.png)

**Screenshot Product page (not working):**
![image](https://user-images.githubusercontent.com/18028151/32030325-77111f2e-b9fa-11e7-8b65-4b7ab5786bac.png)

**Comment by versdivers** [comment]
Any update on this?

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details in steps to reproduce.

**Comment by versdivers** [comment]
Let me ask you a question so i can provide more information. What defines the displayed width and height of a product ? And don't say "the view.xml' because thats faulty. view.xml defines the width and height of the image in its url but not in its div. (so an image is 500*500 but the div 'fotorama__stage__shaft' is 700*700 for example)

**Comment by p-bystritsky** [comment]
@versdivers, please provide more detailed steps to reproduce. Current seems not complete and unclear.

**Comment by magento-engcom-team** [comment]
@versdivers, please provide more detailed steps to reproduce. Current seems not complete and unclear.

**Comment by WMV-SYSTEMS** [comment]
What worked for me to get it all working is to add a ccs entry to .gallery-placeholder{ width: 100%; }
What i think is it is getting the size of the container but if images are not ready the fotorama wrapper has no width.

**Comment by magento-engcom-team** [comment]
@versdivers, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by versdivers** [comment]
I fixed this myself by using bootstrap and giving them an a flex width. This can be closed

**Comment by ghost** [comment]
Can you explain how you did this? I'm having the same issue.

**Comment by versdivers** [comment]
Well what happened for me what the images where getting an auto-size. But what Magento does is calculating the size in the view.xml and using that in JS filles to manually set the css to X px. 

Are you using bootstrap? Or anything that resizes the images?

**Comment by ghost** [comment]
Yes I'm using bootstrap framework for a custom theme.

**Comment by versdivers** [comment]
I wraped my .product.media div and added classes to it like this
Not sure if that was the trick that did it since this is a long time ago.

I use Bootstrap 4
I know it has something to do with the flex that you need to give a width or you need to change in a block or something.

`<div class="product-general-row row no-gutters"><div class="product media col-12 col-md-auto mx-auto"></div`

**Comment by crantron** [comment]
I'm having this issue too on magento 2.2.0

**Comment by versdivers** [comment]
The key in this whole thing is that Magento calculates the height and width based on the pictures height and width. If you use bootstrap then that picture becomes a flex image (i think). Anyways , it has no defined height and width since its responsive (again bootstrap). 

I fixed this on my part of the code i can tell you that and out of the box Magento does seem to work just fine so i think this is an compatibility issue with the new flex box systems of Bootstrap 4. 

I believe that the system what bootstrap is using in its 4 version will be new the new way of making things responsive. Flex is just such a nice css system that gains compatibility in all the browsers

**Comment by crantron** [comment]
@versivers can you provide the fix implemented?

**Comment by versdivers** [comment]
@crantron I wrote my fix 3 comments ago with the side notification that i'm not sure if that is what fixed it. I developed a whole theme so i would need to look into it. But try what i did above if you use bootstrap.

**Comment by crantron** [comment]
The easiest solution is adding the css declaration `.gallery-placeholder{ width: 100%; }` to your theme. @WMV-SYSTEMS thanks bruh.

**Comment by magejunkie** [comment]
I was facing the same issue on Magento 2.2.3 and got this fixed by css declaration
.gallery-placeholder{ width: 100%; }

**Comment by wcladesh** [comment]
I am also facing this issue while I override blank theme. I fixed this issue by CSS declaration
.gallery-placeholder{ width: 100%; } but I need to know what is the main cause of this issue.

**Comment by altravista** [comment]
I have same problem using Bootstrap 4.1.0.

**Comment by crantron** [comment]
@wcladesh its because javascript is calculating dimensions of a image and applying them to the container, that hasn't been loaded yet. cheers.

**Comment by anil90** [comment]
> @wcladesh its because javascript is calculating dimensions of a image and applying them to the container, that hasn't been loaded yet. cheers.

hi crantron, Could you please post the solution if it's working for you. i am using magento 2.2.3 and tried .gallery-placeholder{ width: 100%; } but still not resolved.

**Comment by satishhit** [comment]
Hi, I have same issue solve this using this css .gallery-placeholder{ width: 100%; }  But not done in mobile view.

**Comment by saigadekar** [comment]
Hi 

.gallery-placeholder{ width: 100%; } not working on magento 2.3.3

**Comment by amitmaurya191** [comment]
> Hi, I have same issue solve this using this css .gallery-placeholder{ width: 100%; } But not done in mobile view.

I am also facing same issue on mobile view. Have you get any fix @satishmv26 ?

**Comment by satishmv26** [comment]
Hello @amitmaurya191, I just replaced the gallary.css file with core file

**Comment by amitmaurya191** [comment]
> Hello @amitmaurya191, I just replaced the gallary.css file with core file

Where did you find the gallery.css

**Comment by satishmv26** [comment]
For your reference take a look at this how-to override the gallery.less file

https://magento.stackexchange.com/questions/147633/magento-2-how-to-override-gallery-css?rq=1

**Comment by sagarppanchal** [comment]
<script type="text/javascript">
    require(
    [
        'jquery',
        'jquery/ui'
    ],
    function(
        $
    ) {
        $(window).load(function(){
            console.log("readyyy");
            $(".fotorama__stage").height($(".fotorama__img").height());

            $( window ).resize(function() {
                console.log("resize");
              $(".fotorama__stage").height($(".fotorama__img").height());
            });
        })
    });
</script>

**Comment by sagarppanchal** [comment]
This solution worked for me.

I have added this code just after default code in gallery.phtml file
```
<script type="text/javascript">
    require(
    [
        'jquery',
        'jquery/ui'
    ],
    function(
        $
    ) {
        $(window).load(function(){
            console.log("readyyy");
            $(".fotorama__stage").height($(".fotorama__img").height());

            $( window ).resize(function() {
                console.log("resize");
              $(".fotorama__stage").height($(".fotorama__img").height());
            });
        })
    });
</script>
```

**Comment by maxvelikodnev** [comment]
I had the same problem. I confirm the bug is fixed with this css: **gallery-placeholder {width: 100%; }**

Perhaps the bug takes place only in templates where bootstrap 4 is used.  The image on the product page disappears (set to 1 pixel) when exiting full screen mode or when the browser is resized
