### ISSUE TITLE
The option <var name="allowfullscreen">false</var> for mobile device don't work in product view page gallery

### ISSUE THREAD

**Issue by novakivskiy** [magento/magento2#12285]
### Preconditions

1.  Magento 2.1.9

### Steps to reproduce

1. edit file `<theme>/etc/view.xml`
2.  add  `<var name="allowfullscreen">false</var>` to mobile breakpoints
Example: 

```
   <var name="breakpoints">
            <var name="mobile">
                <var name="conditions">
                    <var name="max-width">767px</var>
                </var>
                <var name="options">
                    <var name="options">
                        <var name="navigation">dots</var>
                        <var name="allowfullscreen">false</var>
                    </var>
                </var>
            </var>
        </var>
```
3. clean cache and open source html
4. find plugin "mage/gallery/gallery" init  options  on html page.  The reason is in the type of the option "allowfullscreen" value, false as string, instead boolean.

`  "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"navigation":"dots","allowfullscreen":"false"}}}}            }`

### Expected result
For screens smaller than <720px, do not open the gallery full screen

### Actual result

1. Screen http://take.ms/CfOWC

**Comment by magento-engcom-team** [comment]
@novakivskiy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by KirillLitvinenko** [comment]
Can reproduce on magento 2.2 by following steps.
## Steps are the same:
1. in `<theme>/etc/view.xml` in `<var name="breakpoints">` option `<var name="allowfullscreen">` to `false`

**Code after changes:**
```
<var name="breakpoints">
    <var name="mobile">
        <var name="conditions">
            <var name="max-width">767px</var>
         </var>
         <var name="options">
             <var name="options">
                 <var name="nav">dots</var>
                 <var name="allowfullscreen">false</var>
             </var>
         </var>
    </var>
</var>
```

2. Clear cache

## Expected result:
fullscrreen is disabled on mobile screens

## Actual result:
fullscreen is working

Can be because of json that set to window object contains only string as value for breakpoints (example:  "allowfullscreen": **"false"**) object (should be bool for allowfullscreen key)
```
"breakpoints": {
  "mobile": {
    "conditions": {
      "max-width": "767px"
    }, 
    "options": {
      "options": {
        "nav": "dots", 
        "allowfullscreen": "false"
      }
    }
  }
}
```

**Comment by joebordo** [comment]
Just Posted the Same issue my self on magento 2.2.1.

**Comment by magento-engcom-team** [comment]
@novakivskiy, thank you for your report.
We've created internal ticket(s) MAGETWO-84793 to track progress on the issue.

**Comment by joebordo** [comment]
@KirillLitvinenko 

You are correct.  As a temporary solution i hard coded it in 

module-catalog/view/frontend/templates/product/view/gallery.phtml
(in my theme)

I replaced 

`  "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>`

with 

` "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"dots","allowfullscreen":false}}}}    }`

Now it works as it should.

false was getting rendered as a string.

Thanks, your post really helped me!

cheers

**Comment by novakivskiy** [comment]
As a solution, create a plugin for the class  \Magento\Catalog\Block\Product\View\Gallery
```
    public function aroundGetBreakpoints(
        \Magento\Catalog\Block\Product\View\Gallery $subject,
        \Closure $proceed
    )
    {
        $json=  $proceed();
        $json = str_replace(['"true"','"false"'],['true','false'],$json);
        return $json;
    }
```

Or write a recursive function to bypass all nodes in the array. Where will the conversion be done from the string type to the type of booleans("true"->true)

**Comment by okorshenko** [comment]
Hi @novakivskiy 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by novakivskiy** [comment]
cool, thanks

**Comment by magento-engcom-team** [comment]
Hi @novakivskiy. Thank you for your report. 
The issue has been fixed in magento/magento2#15022 by @gwharton in 2.3-develop branch
Related commit(s):
 - [163d4cc63d19c3a3bd94697dd02c0d96696df799](https://github.com/magento/magento2/commit/163d4cc63d19c3a3bd94697dd02c0d96696df799)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @novakivskiy. Thank you for your report. 
The issue has been fixed in magento/magento2#15021 by @gwharton in 2.3-develop branch
Related commit(s):
 - [435b165e37048955fdefd4c4d9537ac1dc2d260e](https://github.com/magento/magento2/commit/435b165e37048955fdefd4c4d9537ac1dc2d260e)
 - [4113f26f34e1c2e7035b0f294999aa8add6e6c52](https://github.com/magento/magento2/commit/4113f26f34e1c2e7035b0f294999aa8add6e6c52)
 - [c0b9e8f5ed1accb05cf2e1f1effa401ae1946d4c](https://github.com/magento/magento2/commit/c0b9e8f5ed1accb05cf2e1f1effa401ae1946d4c)
 - [05b15123dcba09047122bab99d7dd3dfdf615e8e](https://github.com/magento/magento2/commit/05b15123dcba09047122bab99d7dd3dfdf615e8e)
 - [2701a4f7223694f8c7d7a2adb4abb62417c2b5a5](https://github.com/magento/magento2/commit/2701a4f7223694f8c7d7a2adb4abb62417c2b5a5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @novakivskiy. Thank you for your report. 
The issue has been fixed in magento/magento2#15020 by @gwharton in 2.2-develop branch
Related commit(s):
 - [8ef039ec281a7fc6af014b42fc69a9d77e4bf277](https://github.com/magento/magento2/commit/8ef039ec281a7fc6af014b42fc69a9d77e4bf277)

The fix will be available with the upcoming 2.2.5 release.

**Comment by tmotyl** [comment]
2 days later the commit 8ef039ec281a7fc6af014b42fc69a9d77e4bf277 was reverted 
in branch 2.2-develop without an explanation by @gwharton :
https://github.com/magento/magento2/commit/ca3245fc9c80247dfd637e5699914bea1b1e8df8#diff-49a84585354f5715382cc2b014a3d961

So the issue is still valid and gallery doesn't work.
Please also keep in mind that according to https://github.com/magento/magento2/pull/12639 annotation `@escapeNotVerified` should NOT be used.

**Comment by gwharton** [comment]
Yes, that was my fault. I have no idea how both I didnt see it, and the reviewers didnt see it, but yes it was accidentally reverted in a commit for another issue.

The revertion was corrected in PR #16594 in August though and should be available in 2.2.7.

**Comment by tmotyl** [comment]
@gwharton I've just seen your revert of the revert, but for some reason this change is not reflected in the file content, and the file history:
see https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml

**Comment by gwharton** [comment]
@tmotyl If you have time, can you take a look at the above PR and comment on changes.
