### ISSUE TITLE
"Total Amount" cart rule without tax

### ISSUE THREAD

**Issue by Chei20** [magento/magento2#12396]
It seems that if I want to create a cart Price rule that takes account the subtotal of a subselection of products, that subtotal is calculated without taxes, also if in tax configuration everything is configurated as “including tax”.
I want to create a fixed amount discount for whole cart (10€) to all users that have in their cart 60€ of products from one category (123456)

### Preconditions
1.	Magento 2

### Steps to reproduce
1.	Go to Marketing -> Cart Price Rules
2.	Create a Specific coupon like
1.	(conditions) If “total amount” equals or greater than 59.99 for a subselection of items in cart matching ALL of this conditions
                                    Category is 123456 (category_id)
2.	(actions) Fixed amount discount for whole cart
               Discount Amount 10

3.	On FrontEnd go to that category 123456, and add products where the subtotal is above 60€ but the subtotal (without tax) is bellow 60€
Summary
	Subtotal (without tax): €57,55
	Subtotal (with tax):       €70,21
	Tax (22%):                     €12,66
Total :                                        €70,21
4.	In that case the coupon can not be used because the subtotal (without tax) < €59.99 
My tax configuration is like 

![image](https://user-images.githubusercontent.com/33896227/33124714-38ba0d14-cf7e-11e7-9167-6b4b1164e7c8.png)

### Expected result
1.	I expected that if products price are configurated with including tax, The Total Amount should be calculated with tax, otherwise is difficult to explain to the customer that the coupon will only be used if the subtotal without tax is more than 60€

### Actual result
1.	The coupon will be used only if Subtotal without tax is greater than 60€

**Comment by magento-engcom-team** [comment]
@Chei20, thank you for your report.
We've created internal ticket(s) MAGETWO-84316 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Chei20. Thank you for your report. 
The issue has been fixed in magento/magento2#21288 by @AleksLi in 2.3-develop branch
Related commit(s):
 - [6ae859aaa233261b03a6bccf946dccdb369926b6](https://github.com/magento/magento2/commit/6ae859aaa233261b03a6bccf946dccdb369926b6)
 - [c25656b228b365c3bf6ee9f3be8120f4f830bb64](https://github.com/magento/magento2/commit/c25656b228b365c3bf6ee9f3be8120f4f830bb64)
 - [23ed0157aa854945d1d7b20cfe4d4bc7ab5eb89a](https://github.com/magento/magento2/commit/23ed0157aa854945d1d7b20cfe4d4bc7ab5eb89a)
 - [e9389ee3ad302d82973b1b9c73152d090addd8eb](https://github.com/magento/magento2/commit/e9389ee3ad302d82973b1b9c73152d090addd8eb)
 - [571f0556a4b9847ddc04869ca598d67a90e81fca](https://github.com/magento/magento2/commit/571f0556a4b9847ddc04869ca598d67a90e81fca)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @Chei20. Thank you for your report. 
The issue has been fixed in magento/magento2#21845 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [9529d318c284fc153b4edba9c24b428e57395b95](https://github.com/magento/magento2/commit/9529d318c284fc153b4edba9c24b428e57395b95)
 - [362bbf239373ed70d11da43b04a861b76e5d4190](https://github.com/magento/magento2/commit/362bbf239373ed70d11da43b04a861b76e5d4190)
 - [a5608f0d6c9c476d18f9dfe59a9053b7fac29393](https://github.com/magento/magento2/commit/a5608f0d6c9c476d18f9dfe59a9053b7fac29393)

The fix will be available with the upcoming 2.2.9 release.

**Comment by praniljoshi13** [comment]
Hey same issue i am getting in magento2.2.6 . how to fix it?

**Comment by mihaifaget** [comment]
@magento-engcom-team 
This is not fixed. If you read the issue's description:

> (conditions) If “total amount” equals or greater than 59.99 for a subselection of items in cart matching ALL of this conditions

 That "total amount" is still without tax, this PR  adds 'subtotal excl tax'  to condition cart attributes, but doesn't fix the issue in this task

**Comment by tramov** [comment]
This is still an issue in 2.3.5 

My migrated Magento 1 coupon is set for E 70, incl. taxes for free shipping. 

However, it does not trigger until the ex. taxes are over E 70. 

I can fix partly fix this by specifiying a lower amount. But my customers can mix products with different tax rates. Eg. 9% for food, and 21% for the remainder. I need the free shipping to trigger on the total amount including taxes.

**Comment by praniljoshi13** [comment]
Dear,

please check this


Final Solution -

changed "base_row_total" to "row_total_incl_tax"  in

/var/www/html/partsvillage/vendor/magento/module-sales-rule/Model/Rule/Condition/Product/Subselect.php


public function loadAttributeOptions()
    {
        $this->setAttributeOption(['qty' => __('total quantity'),
'row_total_incl_tax' => __('total amount')]);
        return $this;
    }

Got below solution on issue -

https://magento.stackexchange.com/questions/193717/cart-rule-condition-based-on-price-including-tax



Changed on core file


You have to override it by creating a custom module.
