### ISSUE TITLE
Subscribe to Newsletter. Multistore. (version 2.2.2)

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#13258]
For example you have 3 websites.
The newsletter subscription rules seem to be defined in a way that a user can't be subscribed to different websites. When subscribing to one and trying to subscribe afterwards to the other 2 websites, it considers that this email address is already subscribed

### Preconditions

1. Magento 2.2.2
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. Subscribe to newsletter on one site.
2. Go to Magento>Marketing>Newsletters subscribers in admin panel. You can see this guest there.
3.Try to subscribe to newsletter on another site.

### Expected result

1. Subscription is successfully completed.

### Actual result

1. This email address is already subscribed.

**Comment by magento-engcom-team** [comment]
@AleksLi, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AleksLi** [comment]
@magento-engcom-team, thanks. I'll be waiting for solution.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Any news on this? It's an issue on 2.1.x, which I see has been acknowledged.

**Comment by ricardojaferreira** [comment]
Hi, Actually this is simple to solve. At this moment Magento is only searching results based on the email address, you have to query the database with the store ID and the email.

--

I would like to propose this fix to magento, how can I do that? 

Regards,
Ricardo

**Comment by ricardojaferreira** [comment]
I've made a pull request for solve this...
I am not sure if I've done it right since it is my first contribution to this project.
The pull is: https://github.com/magento/magento2/pull/14162

Regards.

**Comment by OnYXCoding** [comment]
This issue still persists in 2.2.5. Managed to fix the issue by overwriting \Magento\Newsletter\Model\ResourceModel\Subscriber::loadByEmail() in a custom module

    public function loadByEmail($subscriberEmail)
    {    
        $select = $this->connection->select()->from($this->getMainTable())->where('subscriber_email=:subscriber_email AND store_id=:store_id');

        $result = $this->connection->fetchRow($select, ['subscriber_email' => $subscriberEmail,'store_id' => $this->getStoreId()]);

        if (!$result) {
            return [];
        }

        return $result;
    }
    
    protected function getStoreId() 
    {
    	return $this->_storeManager->getStore()->getId();
    }

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by novikor** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by novikor** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @novikor, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-13258-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-13258-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-13258-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by novikor** [comment]
The issue is already fixed in 2.2 and 2.3, so can be closed

**Comment by balodisu** [comment]
On 2.2.5 CE this issue is not fixed.

**Comment by novikor** [comment]
@balodisu , please reopen  the issue if steps to reproduce and the problem are still actual.
Note: please check on 2.2-develop if possible. I failed to reproduce the problem on it.

**Comment by heldchen** [comment]
this is still a problem in 2.2.6 - here are the repo steps:

1. create a website with 2 storeviews: f.e. EN (default) + DE
2. register a customer in the EN store view 
3. login as this customer in the EN store view
4. go to `/newsletter/manage/` and register for the newsletter
5. in the backend, verify that the user is subscribed to the EN storeview newsletter
6. in the frontend, switch to the DE store view
7. go to `/newsletter/manage/` and register for the newsletter

*expected result:*
- subscriber is registered to EN + DE newsletters in the backend
- user sees his subscription in the DE frontend

*actual result:*
- subscriber is registered to EN **+ EN** newsletters (i.e. two subscriptions to the same store view) in the backend
- user does not see his subscription in the DE frontend (because there is none in this store view)

the problem seems to be that in the `module-newsletter`'s manage save controller uses `getExtensionAttributes()` do determine the subscription status instead of properly using the `$this->subscriberFactory` to check in the correct (current) store view.

please reopen this tissue.

**Comment by Microguru** [comment]
Still this bugs exist in magento 2.2.6.in enterprise edition.
please reopen this issue.

**Comment by heldchen** [comment]
still an issue in 2.3.1
