### ISSUE TITLE
"cart" section data gets loaded 3 times on cart page (2.2.2)

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#13765]
The `customer/section/load` gets called 4 times when loading the cart for the first time. 3 of those times, cart data gets returned. On Magento 2.1, I believe only two calls are made to `customer/section/load`.

### Preconditions
1. Install Magento 2.2.2 with sample data

### Steps to reproduce
1. Add any product to cart
2. Go to cart page `/checkout/cart` with the "Network" panel open in DevTools.

### Expected result
1. The `/customer/section/load` url should only get called twice. For example, these are the two urls that get called on a Magento 2.1 install:
```
https://magento22.dev/customer/section/load/?sections=&update_section_id=false&_=1519190370042
https://magento22.dev/customer/section/load/?sections=directory-data&update_section_id=false&_=1519190370043
```

### Actual result
1. The `/customer/section/load` url will get called four times:
```
https://magento22.dev/customer/section/load/?sections=&update_section_id=false&_=1519190370042
https://magento22.dev/customer/section/load/?sections=directory-data&update_section_id=false&_=1519190370043
https://magento22.dev/customer/section/load/?sections=cart&update_section_id=false&_=1519190370045
https://magento22.dev/customer/section/load/?sections=cart&update_section_id=false&_=1519190370046
```

Note: if you refresh the cart, there will only be two calls made to `/customer/section/load`.

![23-27-41 shopping cart-4cloy](https://user-images.githubusercontent.com/129031/36464516-ef5eea36-1695-11e8-92c6-91d195d32a8c.jpg)

Some more info, to help the developer that reviews this issue: When reviewing XHR requests, it's helpful to understand what initiated those requests:

![23-30-55 shopping cart-neuqj](https://user-images.githubusercontent.com/129031/36464574-3b297666-1696-11e8-901b-e628e41793f0.jpg)

Here are the contents of the call stacks for each of the bottom two requests: 

```
send | @ | jquery.js:10254
-- | -- | --
  | ajax | @ | jquery.js:9738
  | jQuery.(anonymous function) | @ | jquery.js:9890
  | getJSON | @ | jquery.js:9871
  | getFromServer | @ | customer-data.js:89
  | reload | @ | customer-data.js:329
  | initialize | @ | minicart.js:104
  | (anonymous) | @ | wrapper.js:109
  | UiClass | @ | class.js:49
  | initComponent | @ | layout.js:137
  | fire | @ | jquery.js:3232
  | fireWith | @ | jquery.js:3362
  | deferred.(anonymous function) | @ | jquery.js:3461
  | fire | @ | jquery.js:3232
  | fireWith | @ | jquery.js:3362
  | deferred.(anonymous function) | @ | jquery.js:3461
  | (anonymous) | @ | layout.js:120
  | execCb | @ | require.js:1650
  | check | @ | require.js:866
  | (anonymous) | @ | require.js:1113
  | (anonymous) | @ | require.js:132
  | (anonymous) | @ | require.js:1156
  | each | @ | require.js:57
  | emit | @ | require.js:1155
  | check | @ | require.js:917
  | (anonymous) | @ | require.js:1113
  | (anonymous) | @ | require.js:132
  | (anonymous) | @ | require.js:1156
  | each | @ | require.js:57
  | emit | @ | require.js:1155
  | check | @ | require.js:917
  | (anonymous) | @ | require.js:1113
  | (anonymous) | @ | require.js:132
  | (anonymous) | @ | require.js:1156
  | each | @ | require.js:57
  | emit | @ | require.js:1155
  | check | @ | require.js:917
  | enable | @ | require.js:1143
  | init | @ | require.js:774
  | callGetModule | @ | require.js:1170
  | completeLoad | @ | require.js:1544
  | onScriptLoad | @ | require.js:1671
```

and 

```
send | @ | jquery.js:10254
-- | -- | --
  | ajax | @ | jquery.js:9738
  | jQuery.(anonymous function) | @ | jquery.js:9890
  | getJSON | @ | jquery.js:9871
  | getFromServer | @ | customer-data.js:89
  | reload | @ | customer-data.js:329
  | (anonymous) | @ | totals.js:26
  | execCb | @ | require.js:1650
  | check | @ | require.js:861
  | enable | @ | require.js:1143
  | init | @ | require.js:774
  | callGetModule | @ | require.js:1170
  | completeLoad | @ | require.js:1544
  | onScriptLoad | @ | require.js:1671
```

**Comment by magento-engcom-team** [comment]
@erikhansen, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mslabko** [comment]
Internal ticket: MAGETWO-81818

**Comment by koenner01** [comment]
The minicart is firing the customerData.reload(['cart']) and the cart page itself is probably also firing the customerData.reload(['cart'])

**Comment by andrewbess** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
Hi @erikhansen. Thank you for your report. 
The issue has been fixed in magento/magento2#14314 by @andrewbess in 2.2-develop branch
Related commit(s):
 - [d2c6bd06cbfb427d2a802c4ba73d630429873ded](https://github.com/magento/magento2/commit/d2c6bd06cbfb427d2a802c4ba73d630429873ded)
 - [42350cd52e72bb4885e6e599a1760a2b14607d06](https://github.com/magento/magento2/commit/42350cd52e72bb4885e6e599a1760a2b14607d06)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @erikhansen. Thank you for your report. 
The issue has been fixed in magento/magento2#14782 by @andrewbess in 2.3-develop branch
Related commit(s):
 - [c442f768f1a899f9328289f05fbf60679ee47d43](https://github.com/magento/magento2/commit/c442f768f1a899f9328289f05fbf60679ee47d43)
 - [5befa84a04c577faf4f587cfe6aedc6a793b4863](https://github.com/magento/magento2/commit/5befa84a04c577faf4f587cfe6aedc6a793b4863)

The fix will be available with the upcoming 2.3.0 release.

**Comment by k4emic** [comment]
Reopened due to the PR being rolled back: https://github.com/magento/magento2/pull/14314#issuecomment-400291235

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @erikhansen this issue fixed by core team, and customer/section loads only 2 times, look at screenshot
![selection_265](https://user-images.githubusercontent.com/40756439/51038252-53c50800-15bb-11e9-819e-e098d5058010.png)

**Comment by Ctucker9233** [comment]
@magento-engcom-team This is not fixed in 2.2. The fix is still sitting in 2.2-develop and hasn't been released. This is a major breaking bug.

**Comment by magento-engcom-team** [comment]
Hi @erikhansen. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [232e5c0ead667df345683734f84ba436c6a041df](https://github.com/magento/magento2/commit/232e5c0ead667df345683734f84ba436c6a041df)
 - [80097417b82c87669e73c1c8b4782ce821b6184e](https://github.com/magento/magento2/commit/80097417b82c87669e73c1c8b4782ce821b6184e)
 - [4ae59e03fc287827522eaa0e926be907e393f0d2](https://github.com/magento/magento2/commit/4ae59e03fc287827522eaa0e926be907e393f0d2)

The fix will be available with the upcoming `2.3.3` release.

**Comment by scne** [comment]
I've magento version 2.3.3 but this issue produce the same hang up!

**Comment by anotte** [comment]
Me too, version 2.3.0

**Comment by scne** [comment]
up!!

**Comment by k4emic** [comment]
@scne Can you provide a screenshot of the dev tools network tab showing this is still a problem?

**Comment by scne** [comment]
@k4emic 
![image](https://user-images.githubusercontent.com/9977806/78119549-e6440800-7408-11ea-8775-f39f54ffcf78.png)

**Comment by swathishs** [comment]
@magento I am working on this

**Comment by swathishs** [comment]
@magento give me 2.4 instance

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-13765-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-13765-2-4-develop.instances.magento-community.engineering/admin_84e2](https://i-13765-2-4-develop.instances.magento-community.engineering/admin_84e2)
Login: `6e0fc9ae` Password: `e93294773679`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
The issue is not reproducible in Magento 2.4-develop instance. Please find the attachments below :
![image](https://user-images.githubusercontent.com/58288685/82211943-55c97480-992f-11ea-9824-9437bca26fb2.png)

**Comment by k4emic** [comment]
Does this mean that no fix is planned for 2.3?

**Comment by daweedco** [comment]
I have same issue no fix for 2.3?
