### ISSUE TITLE
REST products update category_ids cannot be removed

### ISSUE THREAD

**Issue by siliconalchemy** [magento/magento2#14038]
###  Preconditions and Steps to Reproduce
For example, if a product currently has custom_attribute { 'category_ids': '['10127', '10048', '10123', '10126'] }, and I want to remove two of the categories from the product by setting this to { 'category_ids': '['10127', '10048'] }.

I then update the product with /rest/all/V1/products/<sku> with the updated data.  I get a success returned, and any other product data is successfully updated, and categories can be added to, but trying to remove categories such as above fail silently.  The category_ids remain with the original 4 categories, as in the example above.

1. Magento 2.2.3
2. Php 7.1, Mysql 5.7 (Percona Xtradb Cluster)

### Expected Result
1. I expect to be able to remove categories.  This worked until 2.2 upgrade.

### Actual result
1. See description.  Categories are not updated, but the update command reports success.

**Comment by magento-engcom-team** [comment]
@siliconalchemy, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by siliconalchemy** [comment]
@magento-engcom-team Thanks for the quick response.  If there is any workaround or commit/patch that I can manually backport to the live codebase please let me know, as it is affecting our live site.

**Comment by siliconalchemy** [comment]
This is a huge bug, as it essentially prevents accurate sync between Magento and other systems.  I've tried to work out where the bug is but the codebase is so complex it's not easy to find.
If anyone has any clues or workarounds it would be appreciated.

**Comment by siliconalchemy** [comment]
OK I've tracked this down to faulty logic somewhere in module-catalog/Model/Category/Link/SaveHandler.php:
Magento\Catalog\Model\Category\Link\SaveHandler->execute()
It calls $this->mergeCategoryLinks with the old and supposedly new category links, but it doesn't remove any links that are not present in the new category links.

By replacing:
`$processLinks = $this->mergeCategoryLinks($dtoCategoryLinks, $modelCategoryLinks);`
with 
`$processLinks = $modelCategoryLinks;`
the old categories are removed as expected, but I don't what other effects this might have.

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia

**Comment by sanjay-wagento** [comment]
@magento-engcom-team , I cannot reproduce the issue in the latest 2.2-develop branch (Magento ver. 2.2.6-dev)

**Comment by magento-engcom-team** [comment]
Hi @sanjay-wagento Thank you for your research. 
@siliconalchemy Could you please confirm that latest `2.2-develop` works fine for you?

**Comment by siliconalchemy** [comment]
The problem is still present in 2.2.4.  I don't have a develop branch to test on.

**Comment by siliconalchemy** [comment]
@sanjay-wagento As the @magento-engcom-team has reproduced this earlier in 2.2 and 2.3 and I can still reproduce it in 2.2.4, please start by reproducing it in 2.2.4.

**Comment by sanjay-wagento** [comment]
@siliconalchemy Please setup project by https://github.com/magento/magento2 and check issue.

**Comment by siliconalchemy** [comment]
@sanjay-wagento I'm not setting up a completely separate git install and database for you.  I've reported the issue, and it's been reproduced by @magento-engcom-team.

**Comment by sanjay-wagento** [comment]
@siliconalchemy It is solved in the latest 2.2-develop branch. So you need to ask @magento-engcom-team to provide a patch.

**Comment by siliconalchemy** [comment]
@sanjay-wagento Can you point to commit that fixes it?  It should be referenced here.  If it's fixed for the next release, that's great.

**Comment by kervin** [comment]
Do you have any updates on this? Could you point to the commit so that I can backport it to 2.2.5.

Thanks.

**Comment by siliconalchemy** [comment]
The problem is still present in 2.2.5.  @magento-engcom-team please ignore @sanjay-wagento comments, this issue is still outstanding.

**Comment by siliconalchemy** [comment]
@magento-engcom-team Can you please unassign this from @sanjay-wagento, and mark it as needing attention?  This is a critical bug in the REST api that prevents integration of other systems to provide product data.

**Comment by HamishBlank** [comment]
I can confirm this issue is still relevant in Magento 2.2.5, is there any update on fixes?

**Comment by diegosucaria** [comment]
Issue still persist in 2.2.6.

**Comment by siliconalchemy** [comment]
Unfortunately I think this issue has disappeared into a black hole since it was assigned to the wrong person and the Event:dmcindia tag.  @magento-engcom-team, can this please be unassigned and looked at?

**Comment by DStreichert** [comment]
@siliconalchemy To remove a product mapping to a category
catalogCategoryLinkRepositoryV1 can be used.
Which can then be controlled via operation delete and the path /V1/categories/{categoryId}/products/{sku}

**Comment by siliconalchemy** [comment]
As this issue seems to have got stuck in purgatory, I've opened a fresh copy: #20481

**Comment by ghost** [comment]
Hi @siliconalchemy i'm closing this one, as we have the new one https://github.com/magento/magento2/issues/20481

**Comment by gdvisser** [comment]
As long as this is not fixed in Magento you can take this approach: https://stackoverflow.com/questions/68622618/magento-2-rest-api-cant-remove-category-ids/68623022#answer-68623022
