### ISSUE TITLE
backend wysiwig add image creates broken link

### ISSUE THREAD

**Issue by treii28** [magento/magento2#14569]
Magento v2.2.2

In any admin menu/editor that includes the wysiwig editor (product content, content pages, content blocks, etc) , when you use the icon to insert/edit image, it appears to be running some kind of url sanitize code on the template and/or angular mark-up for the image reference that is left in place when you add an image to the first line of the 'general' tab after clicking the 'browse' icon, selecting an image and clicking 'insert file'.

Upon returning to the pop-over, it shows the image URL as something like:
`{{media url="wysiwyg/logo.png"}}`
but the preview below it is a broken image.

If you then click 'insert' you get a similar broken image icon in the editor. If you then right click the broken icon and click 'insert/edit image', the image URL has now changed slightly to show something like:
`{{media%20url="wysiwyg/logo.png"}}`
again with the preview as a broken image

If you actually view the html and/or turn the wysiwig off to examine the image in the raw mark-up, it appears as:
`<p><img src="{{media%20url=&quot;wysiwyg/logo.png&quot;}}" alt="test" /></p>`

I have figured out as of this point that if you replace the %20 with a space and replace each &quot; with a " character such that the raw html looks like:
`<p><img src="{{media url="wysiwyg/logo.png"}}" alt="test" /></p>`

 it will function properly when you return to the editor mode (until and if you try to edit it in the same manner again using the 'browse' button)

Consequently if you then go back to view the raw HTML code again, it now changes yet one more time to now show similar to the following:
`<p><img src="https://www.oursite.com/admin_123/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvbG9nby5wbmcifX0,/key/41a39fb2aff93949f1d592e918b6948760f226289e96de3f035c2f55624c63bd/" alt="test" /></p>`

**Comment by lewisvoncken** [comment]
should be solved in 2.2 https://github.com/magento/magento2/pull/11048

**Comment by treii28** [comment]
I'm using 2.2

**Comment by treii28** [comment]
What specific version of the magento/module-cms does that change first appear within? (I can't seem to find a repository on it and it's  not specifically listed in my composer.json with the default magento 2.2.2 install setup.)  I may be able to name it specifically in the composer.json to force it up to a newer cms and/or figure out what is calling it as a dependency.

**Comment by treii28** [comment]
FYI, I copied the change made in the patch - still getting the same result:

`<div><img src="{{media%20url=&quot;wysiwyg/image.jpg&quot;}}" /></div>`

**Comment by ghost** [comment]
@treii28, thank you for your report.
This issue is already fixed.

**Comment by mokadev** [comment]
Hi 

i'm using 2.2.6 and it's not fixed at all....
