### ISSUE TITLE
Requesting products via REST API using store code in URL returns products from all stores

### ISSUE THREAD

**Issue by Vossie1975** [magento/magento2#15461]
### Preconditions

- Magento 2.4-develop;
- Integration created;

### Steps to reproduce

1. Create a website with code `wb2`.
2. Create a store `st2` and assign it to the `wb2` website.
3. Create a store view with code `sv2` and assign to the new store.
![image](https://user-images.githubusercontent.com/51680850/82812137-fcb39080-9e9a-11ea-9c69-3538c625a511.png)

4. Create product and assign only to `wb2` website.
![image](https://user-images.githubusercontent.com/51680850/82813005-e0b0ee80-9e9c-11ea-9a53-f7cf10d56f8c.png)

5. Perform REST API GET request using the store code in the URL, eg:
GET /rest/`default`/V1/products/?searchCriteria[currentPage]=10

### Expected result
Only products assigned to the test website are returned (or no products if none assigned).

### Actual result
All products in the Magento instance are returned.
![image](https://user-images.githubusercontent.com/51680850/82812215-2ff61f80-9e9b-11ea-84e5-d45b895c3942.png)

**Comment by ghost** [comment]
@Vossie1975, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Vossie1975** [comment]
any idea when this bug wil be fixed (again)?

**Comment by paul-blundell** [comment]
Typical Magento. Another major bug that is being left to gather dust...

**Comment by Tiberriver256** [comment]
Any update?

**Comment by Vossie1975** [comment]
probably not....
Does not seem interesting for Magento to solve this.
This bug was previously in the system and would have been resolved then.
But is there again / still in it.
I have now reported this almost a year ago, but not a single update since that time.
Recently also other bugs found (in MSI function) but why would you still take the trouble to report it if nothing is done with it ....

**Comment by razza12** [comment]
Will this be resolved? Am still seeing this issue on 2.3.1

**Comment by Arkadij-MP** [comment]
Magento 2.2.6. Of course I can see it.
_(it is written just to update the issue)_

**Comment by Cyclonecode** [comment]
This is a huge problem for me right now. Is there anyway to work around this?

**Comment by Cyclonecode** [comment]
I am running magento 2.2.6 and this is a huge problem for us right now. Is there anyway to workaround this?

**Comment by Vossie1975** [comment]
dont think this will ever be fixed.
this is second time that this problem is in Magento and i have posted this more then a year ago and no response anymore in that time.
Only sollution (what we are also working on nowe) is to stop using magento.
We are building a new webshop now on other ecommerce software becouse of this problem.

**Comment by mshifo** [comment]
are there any updates ?

**Comment by Vossie1975** [comment]
now after more than 2.5 years, but this problem remains.
Fixing bugs like this is clearly not a priority.
I have not even reported other bugs.
In the meantime, therefore, also busy with dumping Magento and switching to other webshop software that is more user-friendly and where problems are solved.

**Comment by Vossie1975** [comment]
Just go use other software. This Wil never be solved by magento

**Comment by ihor-sviziev** [comment]
I'm re-opening this issue since it's high prior issue

**Comment by ihor-sviziev** [comment]
Hi @Vossie1975,

I just checked - it looks like the listed above get request is NOT applying a filter by Website ID or Store ID.

Example:
**Categories:**
```
curl --location -g --request GET 'https://www.mymagentowebsite.com/rest/mysecondstore/V1/categories?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
--header 'Authorization: Bearer 0009rkkbehqgapdfvuemyza3zdeq1yjq'
```

✔ Listed the only categories for the selected store (store code is `mysecondstore`)


**Products:**
```
curl --location -g --request GET 'https://www.mymagentowebsite.com/rest/mysecondstore/V1/categories?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
--header 'Authorization: Bearer 0009rkkbehqgapdfvuemyza3zdeq1yjq'
```
❌ Listed products NOT only from the selected store (store code is `mysecondstore`)

But, here is a workaround - we can apply filter by store code using search criteria:

```
curl --location -g --request GET 'https://www.mymagentowebsite.com/rest/mysecondstore/V1/products?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=mysecondstore&searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
--header 'Authorization: Bearer 0009rkkbehqgapdfvuemyza3zdeq1yjq'
```
✔ Listed the only products for the selected store (store code is `mysecondstore`)

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment]
I can confirm that the issue still reproducing on 2.4-develop branch.
1. created website, store and store view:
![image](https://user-images.githubusercontent.com/1873745/133429682-5d769adc-a807-4edf-91b7-8aacc4dc023a.png)
2. created new root category and sub-category for 2nd store
![image](https://user-images.githubusercontent.com/1873745/133429899-7e13d95d-bb41-4d0b-966f-996ad535aaf0.png)
3. created simple product, assigned to 2nd website:
![image](https://user-images.githubusercontent.com/1873745/133429759-1fc7ee77-a5f3-4f17-b131-4f0ca10e75af.png)
![image](https://user-images.githubusercontent.com/1873745/133429742-62273298-905f-4f0d-ab4b-9aa5cd25f83e.png)


```
curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/products?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
--header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8'
```
**Expected result:**
Only one test product should be returned.

**Actual result:**
Returned all products available in Magento
![image](https://user-images.githubusercontent.com/1873745/133429484-bf021908-5cf7-4fce-a479-4b3e7107c405.png)


Notes:

1. The same request with the filter applied using search criteria works fine (**THIS IS WORKING WORKAROUND**):
```
curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/products?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=sv2&searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
--header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8' 
```
![image](https://user-images.githubusercontent.com/1873745/133430305-900ee816-88b3-42d1-b5ed-4d9614fd76e1.png)

**Comment by Vossie1975** [comment]
wowww after only 3 1/2 years already a response.....
but never mind, fortunately within 1 and 2 months finally got rid of magento and to completely different software!

**Comment by ihor-sviziev** [comment]
@Vossie1975,
Sorry, I completely understand that your issue wasn't noticed for a huge amount of time.
I prefer re-opening this issue as it's still not fixed yet.

**Comment by tuyennn** [comment]
Is anyone working on this?

**Comment by invertedfjord** [comment]
> I can confirm that the issue still reproducing on 2.4-develop branch.
> 
> 1. created website, store and store view:
>    ![image](https://user-images.githubusercontent.com/1873745/133429682-5d769adc-a807-4edf-91b7-8aacc4dc023a.png)
> 2. created new root category and sub-category for 2nd store
>    ![image](https://user-images.githubusercontent.com/1873745/133429899-7e13d95d-bb41-4d0b-966f-996ad535aaf0.png)
> 3. created simple product, assigned to 2nd website:
>    ![image](https://user-images.githubusercontent.com/1873745/133429759-1fc7ee77-a5f3-4f17-b131-4f0ca10e75af.png)
>    ![image](https://user-images.githubusercontent.com/1873745/133429742-62273298-905f-4f0d-ab4b-9aa5cd25f83e.png)
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/products?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8'
> ```
> 
> **Expected result:** Only one test product should be returned.
> 
> **Actual result:** ❌ Returned all products available in Magento ![image](https://user-images.githubusercontent.com/1873745/133429484-bf021908-5cf7-4fce-a479-4b3e7107c405.png)
> 
> ### Other notes:
> 1. The same request with the filter applied using search criteria works fine (**THIS IS WORKING WORKAROUND**):
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/products?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=sv2&searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8' 
> ```
> 
> ✔Only one test product is returned ![image](https://user-images.githubusercontent.com/1873745/133430305-900ee816-88b3-42d1-b5ed-4d9614fd76e1.png)
> 
> 2. Fetching categories works fine w/o applying filter using search criteria:
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/categories?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8' \
> --header 'Cookie: PHPSESSID=dbov1elserndboromibgi6sl0l'
> ```
> 
> ✔ The only categories returned for 2nd store ![image](https://user-images.githubusercontent.com/1873745/133430859-f155f949-0d02-4878-8770-1586b0912152.png)
> 
> 2. Fetching categories works fine with applying filter using search criteria:
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/categories?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=sv2&searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8'
> ```
> 
> ✔ The only categories returned for 2nd store ![image](https://user-images.githubusercontent.com/1873745/133430900-7758b19e-11b6-4692-b282-53000973b452.png)



> I can confirm that the issue still reproducing on 2.4-develop branch.
> 
> 1. created website, store and store view:
>    ![image](https://user-images.githubusercontent.com/1873745/133429682-5d769adc-a807-4edf-91b7-8aacc4dc023a.png)
> 2. created new root category and sub-category for 2nd store
>    ![image](https://user-images.githubusercontent.com/1873745/133429899-7e13d95d-bb41-4d0b-966f-996ad535aaf0.png)
> 3. created simple product, assigned to 2nd website:
>    ![image](https://user-images.githubusercontent.com/1873745/133429759-1fc7ee77-a5f3-4f17-b131-4f0ca10e75af.png)
>    ![image](https://user-images.githubusercontent.com/1873745/133429742-62273298-905f-4f0d-ab4b-9aa5cd25f83e.png)
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/products?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8'
> ```
> 
> **Expected result:** Only one test product should be returned.
> 
> **Actual result:** ❌ Returned all products available in Magento ![image](https://user-images.githubusercontent.com/1873745/133429484-bf021908-5cf7-4fce-a479-4b3e7107c405.png)
> 
> ### Other notes:
> 1. The same request with the filter applied using search criteria works fine (**THIS IS WORKING WORKAROUND**):
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/products?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=sv2&searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8' 
> ```
> 
> ✔Only one test product is returned ![image](https://user-images.githubusercontent.com/1873745/133430305-900ee816-88b3-42d1-b5ed-4d9614fd76e1.png)
> 
> 2. Fetching categories works fine w/o applying filter using search criteria:
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/categories?searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8' \
> --header 'Cookie: PHPSESSID=dbov1elserndboromibgi6sl0l'
> ```
> 
> ✔ The only categories returned for 2nd store ![image](https://user-images.githubusercontent.com/1873745/133430859-f155f949-0d02-4878-8770-1586b0912152.png)
> 
> 2. Fetching categories works fine with applying filter using search criteria:
> 
> ```
> curl --location -g --request GET 'https://a157f32be171e2a736d57b2a1dece736-2-4-develop.instances.magento-community.engineering/index.php/rest/sv2/V1/categories?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=sv2&searchCriteria[pageSize]=50&searchCriteria[currentPage]=1' \
> --header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNjMxNzA2ODQyLCJleHAiOjE2MzE3MTA0NDJ9.y38aigVekrNE5KkogtWAUf3jtLRzj0H_aRfViJcWKp8'
> ```
> 
> ✔ The only categories returned for 2nd store ![image](https://user-images.githubusercontent.com/1873745/133430900-7758b19e-11b6-4692-b282-53000973b452.png)

@ihor-sviziev Does this workaround that you mentioned query the DB in the same way?

**Comment by invertedfjord** [comment]
> For those reading and following this issue, there's a workaround:
> 
> ```
> https://<DOMAIN>/rest/<STORE_CODE>/V1/products?
> searchCriteria=&
> searchCriteria[filterGroups][0][filters][0][field]=store_id&
> searchCriteria[filterGroups][0][filters][0][value]=<STORE_CODE> 
> ```
> 
> Essentially you can scope products by a store if you pass the store code as a custom search criteria.

We did extensive testing and passing the store code as a search param does not work reliably. If you pass the store ID for products it does work most of the time.

Testing on many Magento 2 accounts on various versions came to the following results.

1. Store code in the URL is essentially useless.
2. Store ID passed as a search param does work for 80% of accounts. Some accounts return 500 or 400 errors and sometimes it's still not store scoped. (Not sure why maybe from some customizations on the store front)

**Comment by nidhigupta13-ey** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @Vossie1975,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance and the issue is still reproducible.Kindly refer the screenshots.


<img width="908" height="714" alt="Image" src="https://github.com/user-attachments/assets/36d2b511-d81f-4c12-8843-4ecc61863723" />\

All products in the Magento instance are returned.


Hence Confirming the issue.

Thanks.

**Comment by markwallman** [comment]
Any update on this? Appears to still be an issue

**Comment by lbajsarowicz** [comment]
Confirmed on current 2.4-develop. `Magento\Catalog\Model\ProductRepository::getList()` (app/code/Magento/Catalog/Model/ProductRepository.php) builds the product collection and runs it through `collectionProcessor->process($searchCriteria, $collection)` without ever applying a store/website scope derived from the REST request's store code — unlike category retrieval, which does scope correctly. The only working mitigation remains passing an explicit `store_id` filter in `searchCriteria`. This still looks like a real, unaddressed gap rather than something already fixed.
