### ISSUE TITLE
New order notification is not sent to the admin

### ISSUE THREAD

**Issue by bnymn** [magento/magento2#16203]
When a customer places an order, (s)he receives an order confirmation email but admin does not receive any notification.

I have traced back the error to this file (**vendor/magento/module-sales/Model/Order/Email/Sender.php:84**)

![screenshot from 2018-06-17 16-24-56](https://user-images.githubusercontent.com/3506402/41511324-070b3c3c-724b-11e8-9e03-a151806aa053.png)

It throws an exception with the following message "**From Header set twice**".

### Preconditions
1. PHP 7.1.18
2. MySQL 5.7.22
3. Magento 2.2.4

### Steps to reproduce

1. Login as admin.
2. Go to Stores -> Configuration -> Sales -> Sales Emails.
3. Go to Order section.
4. Make sure it is **enabled**.
5. Add your email into the field **Send Order Email Copy To**.
6. "Send Order Email Copy Method" to "Separate Email".
7. Go to your Magento store.
8. Login as a customer.
9. Make a new order.

### Expected result

1. The customer should receive the order confirmation email.
2. The email address in the Magento admin which we have just added should also receive a copy.

### Actual result

1. The customer receives order confirmatio email.
2. But admin is not notified, nor the copies are sent.

**Comment by bnymn** [comment]
I think the following issue is related with this one. #16165

**Comment by gwharton** [comment]
This is where the issue was first created. https://github.com/magento/magento2/issues/11740

**Comment by ghost** [comment]
@bnymn, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gwharton** [comment]
PR #16461 is awaiting review and will fix this issue.

**Comment by rishabhrkrai** [comment]
I also have the same issue on Magento 2.2.5

**Comment by Mart-ASE** [comment]
I also encountered this. how can i fix it? im using Magento ver. 1.7.0.2

**Comment by tanolalano** [comment]
Same issue on magento 2.2.6 
php 7.1.22
MySQL 5.7.22

Order mail was sent but marked as (The order confirmation email is not sent) in admin detail order.
No  mail was sent to Addresses set on "Send Order Email Copy To" with "Separate Email" settings.
This issue is present on all payments method.
No error on log nor in Apache error_log

**Comment by gwharton** [comment]
PR #18472 is the fix. Just waiting to be merged.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @bnymn The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by gwharton** [comment]
I really don't agree with this new process to be honest. The decision to not fix any bugs on 2.2 unless they are also present in 2.3 seems a strange one!

**Comment by ghost** [comment]
@gwharton I'm tested it now on 2.2-develop, i'm not able to reproduce this on 2.2-develop.

**Comment by gwharton** [comment]
It only fails if you also have the amazon payment modules installed. These don't get deployed in git installs, only composer installs.

**Comment by gwharton** [comment]
Looks like it may have been fixed in MAGETWO-91477

https://github.com/magento/magento2/commit/9a7c9e553b1c9814907105388bffc2e8a91353a5#diff-dfb3ee5a7f863458afea75f5524cd2e5

**Comment by ankurverma5540** [comment]
I am facing the same issue. What need to done to fix this issue? I am using Magento 2.2.5 and i don't have Magento folder in lib/internal. I created that folder place files according this commit
[9a7c9e5#diff-dfb3ee5a7f863458afea75f5524cd2e5](https://github.com/magento/magento2/commit/9a7c9e553b1c9814907105388bffc2e8a91353a5#diff-dfb3ee5a7f863458afea75f5524cd2e5)
But still not working.

**Comment by donovandb** [comment]
Magento 2.2.1
Just adding that I did not have this problem until enabling authorize.net. 
We had "bluepay" up until Nov.  "Send Order Email Copy To" emails were working fine. We switched to Authorize.net and now they are no longer working. Hope that helps.

**Comment by magento-engcom-team** [comment]
Hi @bnymn. Thank you for your report. 
The issue has been fixed in magento/magento2#18471 by @gwharton in 2.3-develop branch
Related commit(s):
 - [ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3](https://github.com/magento/magento2/commit/ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3)
 - [e16ff74e4f5f24a4a2530b6aced6ef50032515e0](https://github.com/magento/magento2/commit/e16ff74e4f5f24a4a2530b6aced6ef50032515e0)
 - [621d2cfeaf8e0a15e592cdc001c856385b3cbd83](https://github.com/magento/magento2/commit/621d2cfeaf8e0a15e592cdc001c856385b3cbd83)
 - [b6f9e48289119117df230b6578ac9ff3d69e4996](https://github.com/magento/magento2/commit/b6f9e48289119117df230b6578ac9ff3d69e4996)
 - [0dc85785e522e2be8c72dfeaee7e9f5054195034](https://github.com/magento/magento2/commit/0dc85785e522e2be8c72dfeaee7e9f5054195034)
 - [122019c953037df74ef97245a42b274eae2e6639](https://github.com/magento/magento2/commit/122019c953037df74ef97245a42b274eae2e6639)
 - [193c6c2f6facf7276c1c8858d29ea3b847062ef5](https://github.com/magento/magento2/commit/193c6c2f6facf7276c1c8858d29ea3b847062ef5)
 - [bd0aa57cc837918335015d051f08cf380dc186d0](https://github.com/magento/magento2/commit/bd0aa57cc837918335015d051f08cf380dc186d0)
 - [523b0464966f81f1f01aa13073092bfddf363219](https://github.com/magento/magento2/commit/523b0464966f81f1f01aa13073092bfddf363219)
 - [424929fe9aee1005601cc2c9c7ad0090741be723](https://github.com/magento/magento2/commit/424929fe9aee1005601cc2c9c7ad0090741be723)
 - [c32ca7a0d58cbc57276349b26eb5ecd38451fd2d](https://github.com/magento/magento2/commit/c32ca7a0d58cbc57276349b26eb5ecd38451fd2d)
 - [e39ce7a3f2a7e6ee134cff9a097b7321756c32cf](https://github.com/magento/magento2/commit/e39ce7a3f2a7e6ee134cff9a097b7321756c32cf)
 - [99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31](https://github.com/magento/magento2/commit/99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31)
 - [f171c9d6ab035439ffb6374ec14dd8d51123dcd2](https://github.com/magento/magento2/commit/f171c9d6ab035439ffb6374ec14dd8d51123dcd2)

The fix will be available with the upcoming 2.3.1 release.

**Comment by coatesjonathan** [comment]
Hi, how do I get this merged into 2.2.5? I need this fixed

**Comment by LiamKarlMitchell** [comment]
How to backport to 2.2.5 please, has someone got an extension plugin for this, it's kind of an important functionality to let orders email know of orders...

**Comment by helefa** [comment]
I'm having this issue in 2.2.4 and cannot upgrade to 2.3. Is there a fix for my version?

**Comment by helefa** [comment]
How can I fix in 2.2.4?
