### ISSUE TITLE
Table rate shipment is taken from wrong website ID when creating an order through the admin

### ISSUE THREAD

**Issue by digikeijs** [magento/magento2#16604]
**Summary of the issue**

When I create an order through the admin panel and select my shipping method table rate it takes the shipping rate table from the wrong website ID. 

### Preconditions
magento 2.2.4, Linux, non sample data

### Steps to reproduce

1.  Setup multistore
2.  Setup different table rates per website
3.  Then through the admin create a new order for the second website/store
4.  Select your shipping method and the price will be taken from the first website / store (id1)

### Expected result
Table rate prices are taken from the correct website id

### Actual result
Shipment price is always taken from the table rate website id 1

<!---
    Thank you for contributing to Magento.
    To help us process this issue we recommend that you add the following information:
     - Summary of the issue,
     - Information on your environment,
     - Steps to reproduce,
     - Expected and actual results,

**Comment by magento-engcom-team** [comment]
Hi @digikeijs. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@digikeijs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by digikeijs** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @digikeijs. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @digikeijs, here is your [Magento instance](https://i-16604-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16604-2-2-4.engcom.dev.magento.com/admin](https://i-16604-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-backlog-nickolas** [comment]
Hello @digikeijs, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by digikeijs** [comment]
Thanks a lot, if you have time can you please also look at below issue. Almost the same issue but then related to update qty but also using the wrong website id / store.

https://github.com/magento/magento2/issues/15846

**Comment by CliftonWLS** [comment]
We are having the same issue. Tracked it down to the requestShippingRates() method in \Quote\Model\Quote\Address.php:

$request->setStoreId($this->storeManager->getStore()->getId());
$request->setWebsiteId($this->storeManager->getWebsite()->getId());

Where storeManager is not set with the store that was selected when creating the order. I have tried to override this method but have run into endless issues doing so. Is there anyone that can provide some insight into overriding this method?

**Comment by callumstar** [comment]
Hi @digikeijs,

Did you ever resolve this at all?

**Comment by callumstar** [comment]
Hi @CliftonWLS,

Did you ever manage to succeed in overriding the method at all?

**Comment by SvanZui** [comment]
@callumstar nope still waiting on the magento team to fix it. Do have a workaround but it sucks

**Comment by callumstar** [comment]
Hi @SAPontwerp,

Are you able to share the workaround at all with me please? If it's something then I'd be happy to use it!

**Comment by callumstar** [comment]
Hi @SAPontwerp, did you have a workaround at all? I'm happy to use it no matter how hacky it is.

**Comment by SvanZui** [comment]
@callumstar we do not have that much orders from the admin so we just enable a fixed shipping price when we add an order and turn it off again when done.

**Comment by Rickertje** [comment]
@magento-engcom-team hi guys any idea when this gets fixed (along with maybe https://github.com/magento/magento2/issues/18059 and https://github.com/magento/magento2/issues/12889 and https://github.com/magento/magento2/issues/16604 which are possible duplicates) ?

**Comment by Rickertje** [comment]
Hi guys it has been another month. Can someone give an update?

**Comment by oleksii-lisovyi** [comment]
Hi guys.

Looks like the issue has been fixed in the 2.2-develop branch.
Related commit: 
https://github.com/magento/magento2/commit/9c066ca1cc2f2db9e66575da25992ca9bb74f65a

**Comment by Rickertje** [comment]
@oleksii-lisovyi does this mean that this fix will also (by default) be incorporated in 2.3 (and or 2.2.7) ? I'm not a developer so I dont know exactly how this works.

**Comment by oleksii-lisovyi** [comment]
@Rickertje, yes. Having any fix in the develop branch means, that it will be available in one of the next 2.2.x releases and could be ported into 2.3.

**Comment by oleksii-lisovyi** [comment]
I tested the fix I've mentioned previously - it works great. I'm closing the issue.

**Comment by Rickertje** [comment]
@oleksii-lisovyi I have tried this in 2.2.7 but the problem is still there. Please reopen the issue.

**Comment by oleksii-lisovyi** [comment]
@Rickertje, the issue was not fixed in 2.2.7 (probably it will be fixed in the 2.2.8). 

But you can apply the fix right now by applying patch via [vaimo/composer-patches](https://github.com/vaimo/composer-patches).

How to apply specific commit/PR from terminal:
0. Install composer by following steps from https://getcomposer.org/download/. After make composer global:
```Shell
mv composer.phar /usr/local/bin/composer
```

1. Install package vaimo/composer-patches:
```Shell
cd path/to/magento2 && composer require vaimo/composer-patches:4.7.0
```

2. Add following section into path/to/magento2/composer.json file:
```json
...
"extra": {
        "magento-force": "override",
        "patches": {
           "magento/module-quote": {
                "Fix issue getting rates while placing order from Admin panel": {
                    "source": "https://github.com/magento/magento2/commit/9c066ca1cc2f2db9e66575da25992ca9bb74f65a.patch",
                    "level": 5
                }
            }
        }
    },
...
```

3. Apply patches:
```Shell
composer install
```

**Comment by digikeijs** [comment]
Anybody got this working on 2.3? When I want to install this patch I get 

```
 - Applying patches for magento/module-quote (1)
    ~ digikeijs/magento2: https://github.com/magento/magento2/commit/9c066ca1cc2f2db9e66575da25992ca9bb74f65a.patch [NEW]
      Fix issue getting rates while placing order from Admin panel
  [Vaimo\ComposerPatches\Exceptions\PatchFailureException]
  Cannot apply patch /tmp/composer-patches-e54b6815eedfac36ce8b5e9e0554cb6b.patch

```

**Comment by oleksii-lisovyi** [comment]
Hi, @digikeijs.

The issue is fixed in the 2.3-develop in the commit https://github.com/magento/magento2/commit/cc00197d13d6244e32201e4c6bf00287e54747c5. 
You can try to apply this commit instead of that one, that is related to 2.2.x.

**Comment by digikeijs** [comment]
Well it's not fixed in 2.3 but found a solution already but will also check your info thanks

**Comment by oleksii-lisovyi** [comment]
@digikeijs, 2.3 is a stable version, but 2.3-develop is a development branch, than usually contains more fixes and improvements comparing to the branch of stable version.
Just try to apply that patch - the fix looks the same as on 2.2.

**Comment by digikeijs** [comment]
Sorry you are right, misread that :-)

**Comment by digikeijs** [comment]
Same problem :-(  Processing patches configuration

  ```
- Applying patches for magento/module-quote (1)
    ~ digikeijs/magento2: https://github.com/magento/magento2/commit/cc00197d13d6244e32201e4c6bf00287e54747c5.diff [NEW]
      Fix issue getting rates while placing order from Admin panel


  [Vaimo\ComposerPatches\Exceptions\PatchFailureException]
  Cannot apply patch /tmp/composer-patches-09ece90d8e75d0f6997d6a89f04100b4.patch


```

**Comment by oleksii-lisovyi** [comment]
There is one more additional commit, that was done before that change.
Please add a patch for the commit https://github.com/magento/magento2/commit/b35b68130265163f2ed151ff94e0d9f7fc63d44c as well.
This should help.

**Comment by digikeijs** [comment]
Sorry for all the questions, can you help me running multiple patches? Like this it does not work

```
"extra": {
        "magento-force": "override",
		"patches": {
           "magento/module-quote": {
                "Fix issue getting rates while placing order from Admin panel": {
				    "source": "https://github.com/magento/magento2/commit/b35b68130265163f2ed151ff94e0d9f7fc63d44c.patch",
                    "source": "https://github.com/magento/magento2/commit/cc00197d13d6244e32201e4c6bf00287e54747c5.patch"
                }
```

**Comment by oleksii-lisovyi** [comment]
No problem. Each patch must contain 1 source. So adding 2 patches for 1 module requires to have following structure:

```json
"extra": {
        "magento-force": "override",
		"patches": {
           "magento/module-quote": {
                "Fix issue getting rates while placing order from Admin panel - part 1": {
				    "source": "https://github.com/magento/magento2/commit/b35b68130265163f2ed151ff94e0d9f7fc63d44c.patch"
                },
"Fix issue getting rates while placing order from Admin panel - part 2": {
				    "source": "https://github.com/magento/magento2/commit/cc00197d13d6244e32201e4c6bf00287e54747c5.patch"
                }
}
```

Please check on typos, because I'm writing from phone.

**Comment by oleksii-lisovyi** [comment]
Hi, @digikeijs.

Did it help? Do you need a help?

**Comment by digikeijs** [comment]
Thanks for the follow up. No already the first commit gives issues, most likely the content of the file is a bit different. But I like my workaround more, no more patch files, I just replace the files I want to have replaced during composer install. Saves a lot of hassel

```
		"scripts": {
		"post-install-cmd": [
				"cp -Rfp vendor-patches/. ."
```
