### ISSUE TITLE
Product Export fails

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#17320]
### Preconditions

1. Magento 2.2.3

### Steps to reproduce

1. Generate 20,000+ products by performance toolkit.
2. Go to System -> Data Transfer -> Export
3. Select Products for Entity Type and CSV for Export File Format.
4. Click Continue

### Expected result

1. CSV file is exported.

### Actual result

1. Export fails.

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@BezV8 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by BezV8** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @BezV8, here is your [Magento instance](https://i-17320-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17320-2-2-3.engcom.dev.magento.com/admin](https://i-17320-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@BezV8, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by BezV8** [comment]
@magento-engcom-team Can not reproduce issue on vanilla instance. Issue seems to being caused by the Entity Attributes grid never loading and thus not passing options to product export.

**Vanilla Instance:** 
![screenshot_2018-08-02 export import export data transfer system magento admin](https://user-images.githubusercontent.com/33320744/43574847-1d79e930-963d-11e8-8e9c-0386b71179fe.png)

**Live site:**
![screenshot_2018-08-02 export import export data transfer system magento admin 1](https://user-images.githubusercontent.com/33320744/43574870-29fe9372-963d-11e8-8636-c7a2921689e3.png)

**Comment by p-bystritsky** [comment]
Seems like the issue is caused by some kind of memory leak:
`Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes)`

**Comment by gfxguru** [comment]
I'm having the same issue. 2.2.7

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by p-bystritsky** [comment]
Fixed in https://github.com/magento/magento2ce/pull/3287 (2.3) and https://github.com/magento/magento2ce/pull/3303 (2.2)

**Comment by swatts7777777** [comment]
The links to the fix above do not work.  Can anybody help me with the correct URL please?

**Comment by Ctucker9233** [comment]
@p-bystritsky ditto on what @swatts7777777 said.

**Comment by jigar48** [comment]
@p-bystritsky  Please provide the correct fixes link, I am still getting this issue.

**Comment by vtransy** [comment]
In my case, I did remove all log file in var (or you can backup it) then re-run export function. After that go to var/log and found an exception.

Open log and see that function

    set_time_limit



I go to php.ini and found that the function in list disable function config. I remove it from list then it works.

You can visit here for more detail: https://community.magento.com/t5/forums/replypage/board-id/magento-2-technical-issues/message-id/1575
