### ISSUE TITLE
2.3.0 Watermark not showing on images

### ISSUE THREAD

**Issue by travis5491811** [magento/magento2#21154]
### Preconditions (*)

1. v2.3.0
2. Fresh installation, no third party modules

### Steps to reproduce (*)

1. Create categories
2. Create products
3. Modify [buggy image uploader ](https://magento.stackexchange.com/questions/252256/magento-2-3-favicon-and-logo-upload-does-not-take-hold)to work around bug so you actually can upload a watermark.
4. Upload a watermark (use [watermark in this issue ](https://github.com/magento/magento2/pull/17623) as a watermark example)
5. set image opacity to 10, image size to 40x50, image position to tile, and saved configuration. 
6. tap the Cache Management link in the system message. Then, refresh the invalid cache.

### Expected result (*)

1. Expect to see watermark on product images.

### Actual result (*)

1. No watermark

**Comment by magento-engcom-team** [comment]
Hi @travis5491811. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@travis5491811 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by travis5491811** [comment]
> Hi @travis5491811. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @travis5491811 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @travis5491811. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @travis5491811, here is your [Magento instance](https://i-21154-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21154-2-3-develop.instances.magento-community.engineering/admin](https://i-21154-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by travis5491811** [comment]
@magento-engcom-team same problem in your instance. Thumbnails show in the admin area Catalog > products list. But don't show on front-end.


![magenotbug_screenshot from 2019-02-12 10-23-23](https://user-images.githubusercontent.com/41482601/52646641-194bd500-2eb1-11e9-983c-f446a8bc61e9.png)
![magentobug_screenshot from 2019-02-12 10-23-48](https://user-images.githubusercontent.com/41482601/52646643-194bd500-2eb1-11e9-8610-74c00833257b.png)
![magentobug_screenshot from 2019-02-12 10-24-29](https://user-images.githubusercontent.com/41482601/52646645-194bd500-2eb1-11e9-967e-aa2a7bb8f5a8.png)
![magentobug_screenshot from 2019-02-12 10-26-49](https://user-images.githubusercontent.com/41482601/52646646-19e46b80-2eb1-11e9-8387-0f50011263c8.png)
![magentobug_screenshot from 2019-02-12 10-27-22](https://user-images.githubusercontent.com/41482601/52646647-19e46b80-2eb1-11e9-8da0-929a82ec5b51.png)




Try flushing magento cache and catalog images cache, still same results.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @travis5491811. Thank you for your report. 
The issue has been fixed in magento/magento2#21338 by @progreg in 2.3-develop branch
Related commit(s):
 - [c7930eb37b29c3bc14735d048845278092fca053](https://github.com/magento/magento2/commit/c7930eb37b29c3bc14735d048845278092fca053)
 - [7190983a7aa4c4c09d997871a4d71d863e3872f0](https://github.com/magento/magento2/commit/7190983a7aa4c4c09d997871a4d71d863e3872f0)

The fix will be available with the upcoming 2.3.2 release.

**Comment by maartenwolfsen** [comment]
I created a patch file for this:
https://gist.github.com/maartenatmarissen/14b48e1de6629dcccae10d75fbde6a19

Which can be installed using [cweagans/composer-patches](https://github.com/cweagans/composer-patches)

**Comment by onepack** [comment]
I wrote that it was not working but I just discovered that the default value from the global theme settings under Content design config is not automatically copied to the website level.
I had to manually set "use default" under website.

**Comment by ashvinimarwal** [comment]
This issue is still coming on Magento CE 2.3.1 even after applying fixes.
