### ISSUE TITLE
Unable to unset attribute values for store view scope

### ISSUE THREAD

**Issue by gavinlimely** [magento/magento2#21386]
### Preconditions (*)

1. Magento 2.3
2. Multiple websites / stores configured.

### Steps to reproduce (*)

1. Create a product, save it under the default scope. Save with a special price for the purpose of this example.
2. Switch scope to another store view.
3. Try and set the special price to empty (this store doesn't have a special price).
4. Hit save

### Expected result (*)

1. I'd expect to be able to save the product without a special price. 
2. The "Use Default" checkbox next to the special price should remain unticked, with the special price containing an empty value.

### Actual result (*)

1. The "Use Default" checkbox reverts back to ticked, with the original value being grayed out.
2. You are unable to unset the special price value.

Please note, this appears to be the same for all free type attribute values (name, description etc).

**Comment by magento-engcom-team** [comment]
Hi @gavinlimely. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gavinlimely do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by gavinlimely** [comment]
Yes this can be reproduced on a Vanilla instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98384` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mohith-ecommerce** [comment]
before saving the product or any attributes of the product setCurrentStore to '0' (zero) you can do this by following these steps

use Magento\Store\Model\StoreManagerInterface;
class YourClassName
{
/**
* @var StoreManagerInterface
*/
protected $_storeManager;
public function __construct(
StoreManagerInterface $storeManager
)
{
$this->_storeManager = $storeManager;
}
public function yourFunctionName()
{
$this->_storeManager->setCurrentStore('0');
//do your work and save
}
It work for me let me know if any issues
by this the Use Default" checkbox will be get checked

**Comment by koenner01** [comment]
I have stumbled into this issue and I have found this will be the case for every attribute on an EAV model object.

The origin of the problem can be traced to \Magento\Eav\Model\Entity\AbstractEntity::_collectSaveData function where you can find 

```
/**
* Check comparability for attribute value
*/
if ($this->_canUpdateAttribute($attribute, $v, $origData)) {
    if ($this->_isAttributeValueEmpty($attribute, $v)) {
        $this->_aggregateDeleteData($delete, $attribute, $newObject);
    } elseif (!is_numeric($v) && $v !== $origData[$k] || is_numeric($v) && $v != $origData[$k]) {
        $update[$attrId] = [
            'value_id' => $attribute->getBackend()->getEntityValueId($newObject),
            'value' => is_array($v) ? array_shift($v) : $v,//@TODO: MAGETWO-44182,
        ];
    }
} elseif (!$this->_isAttributeValueEmpty($attribute, $v)) {
    $insert[$attrId] = is_array($v) ? array_shift($v) : $v;//@TODO: MAGETWO-44182
}
```

The _isAttributeValueEmpty check being done is adding the empty values to be deleted (instead of updated)

**Comment by koenner01** [comment]
> before saving the product or any attributes of the product setCurrentStore to '0' (zero) you can do this by following these steps
> 
> ...
>   
>   It work for me let me know if any issues
>   by this the Use Default" checkbox will be get checked

I think you misread the original post; We are not asking for the "Use default" checkbox to be checked. We want to be able to save "empty" values on storeview scope.

**Comment by duckchip** [comment]
what is the status of this ticket?

**Comment by swapnilT2jcommerce** [comment]
I got the same issue in 2.3.2 version but after the upgraded the magento  from 2.3.2 to 2.3.5 -p2 version. Now, attribute values are cleared in website and store scope. This issue has been resolved in magento version 2.3.5-p2

**Comment by zakdma** [comment]
@magento i am working on it

**Comment by zakdma** [comment]
Cannot reproduce it on latest Magento version.
Also reporter didn't specify in description that price scope should be switched to website. Because for **Global scope** there are no **Use default** checkboxes
I'm closing this ticket. @gavinlimely please reopen it if you still can reproduce.

**Comment by magento-engcom-team** [comment]
Hi @gavinlimely, @zakdma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24160` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by evs-xsarus** [comment]
Sadly, this is still failing; if there is a null value, the logic in getAffectedFields() , see :

magento/vendor/magento/module-eav/Model/Entity/Attribute/Backend/AbstractBackend.php

can't find the value_id.
