### ISSUE TITLE
Magento 2.3 catalogsearch_fulltext no dropdown attribute labels but numbers

### ISSUE THREAD

**Issue by onepack** [magento/magento2#21678]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.2
3. Demo content

### Steps to reproduce (*)

1. Use a standard of Create a custom dropdown attribute and make it available in the search.
2. Assign the attribute to an attribute group
3. Set the value of the attribute in a product
4. Reindex all indexes via cli command

### Expected result (*)

1. Expected is that the product can than be searched via the dropdown value set in the product.
2. So search on a manufacturer and all products where that manufacturer is set will be shown in the result.

### Actual result (*)

1. No results on any search with this value.
2. I found that in the catalogsearch_fulltext table in the database that value was not saved with the dropdown option label but with the option value number.
This is the case for all dropdown attribute values that were set.
3. Searching with the actual stored dropdown option number returns the product in Magento.

![fulltext](https://user-images.githubusercontent.com/475598/54093070-db4cae80-4393-11e9-8c96-7451e0f6e632.png)

**Comment by magento-engcom-team** [comment]
Hi @onepack. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@onepack do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by onepack** [comment]
Hi @magento-engcom-team 
I can confirm that the first steps are made.

I have an other fresh install with demo content for an other project and there the same issue is present.

Not the selected option value label is stored in the fulltext table but the option value number.

No need to mention this has a high impact on the search functionality for the magento shops.
Manufacturer, color or any other dorpdown attribute values cannot be used in the search.

![fulltext_store2](https://user-images.githubusercontent.com/475598/54114843-948aa300-43eb-11e9-9df3-ad5e1d6739b9.png)

**Comment by onepack** [comment]
Searching on the frontend with pictures.
I should get the joust duffle bag but I get suggestions.
![Joust Duffle Bag](https://user-images.githubusercontent.com/475598/54118952-7bd2bb00-43f4-11e9-8a92-0bef5e36ac08.png)

Searching with the number 213 that stands for BrandA in the Manufacturer attribute dropdown options gives me the product.
![Joust Duffle Bag2](https://user-images.githubusercontent.com/475598/54119018-a4f34b80-43f4-11e9-9dc6-c093fb15dcb5.png)

This is currently an issue in at least 3 projects that I run with magento2.3

**Comment by onepack** [comment]
It seems to be a bigger problem. Today I worked with the REST for customers to see if custom attributes were also available.
They are but here the dropdown values also show up as the corresponding numbers instead of the label values. 

   "custom_attributes":    [
            {
         "attribute_code": "debtor_number",
         "value": "115245"
      },
            {
         "attribute_code": "segment",
         "value": "239" (dropdown value)
      },
            {
         "attribute_code": "segment_alt",
         "value": "Different"
      },
            {
         "attribute_code": "customer_erp",
         "value": "245" (dropdown value)
      },
            {
         "attribute_code": "erp_alt",
         "value": "Different"
      },
            {
         "attribute_code": "howdidyoufind",
         "value": "260" (dropdown value)
      }
]

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by onepack** [comment]
@engcom-backlog-nazar Do you need more information from my side?

**Comment by ghost** [comment]
HI @onepack thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release.
![DeepinScreenshot_select-area_20190315111847](https://user-images.githubusercontent.com/40756439/54421075-560b2600-4714-11e9-825c-ef4104ef2437.png)
![DeepinScreenshot_select-area_20190315111922](https://user-images.githubusercontent.com/40756439/54421077-56a3bc80-4714-11e9-9b47-ad16bf0b0a50.png)

**Comment by onepack** [comment]
@engcom-backlog-nazar 
Sorry to ask but do you have a related issue in Github or any information on the fix so I can apply the fix in my current installations that are almost going live?

**Comment by onepack** [comment]
Any info on the release date?
Files included for the fix?
Issue Id?

**Comment by liltbrockie** [comment]
Hello .. we are on 2.3.3 and this issue is not fixed.. should it be?
