### ISSUE TITLE
Normal price Display Issue for Configurable Product

### ISSUE THREAD

**Issue by ArpitGupta-shoptimize** [magento/magento2#22241]
### Preconditions (*)

1. Magento 2.3.0

### Steps to reproduce (*)
1. Create a Configurable product with at least 2 different swatch attributes (say Color and Size).
2. Give the Configurable product a price, say x.
3. For one of the simple products (except for the one with lowest product ID), change the Price to y and special price to z such that y,z>x.

### Expected result (*)
On frontend, when swatches are selected, both old price and normal price should show.

### Actual result (*)\
Only Normal Price is Shown and not the Old Price

**Comment by ArpitGupta-shoptimize** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @ArpitGupta-shoptimize. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ArpitGupta-shoptimize, here is your [Magento instance](https://i-22241-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-22241-2-3-0.instances.magento-community.engineering/admin](https://i-22241-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ArpitGupta-shoptimize** [comment]
> Hi @ArpitGupta-shoptimize. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @ArpitGupta-shoptimize do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ * ]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @ArpitGupta-shoptimize. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-22241-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22241-2-3-develop.instances.magento-community.engineering/admin](https://i-22241-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @ArpitGupta-shoptimize i'm not able to reproduce following steps you described. 
![DeepinScreenshot_select-area_20190409131234](https://user-images.githubusercontent.com/40756439/55792403-383da080-5ac9-11e9-9cf7-9a6661090462.png)

**Comment by ArpitGupta-shoptimize** [comment]
@engcom-backlog-nazar  Please make 2 attributes which are of type swatch, as mentioned in the steps

**Comment by ghost** [comment]
@ArpitGupta-shoptimize this issue has already fixed in 2.3-develop branch and available on 2.3.1 release.
![DeepinScreenshot_select-area_20190409135647](https://user-images.githubusercontent.com/40756439/55794981-67571080-5acf-11e9-95d8-82a17ef177b9.png)

**Comment by ArpitGupta-shoptimize** [comment]
@engcom-backlog-nazar According to the description I provided the normal price and special price of the simple product has to be greater than the normal price of the configurable product. I checked the issue on the develop instance provided and the issue still exists.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-22241-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22241-2-3-develop.instances.magento-community.engineering/admin](https://i-22241-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ArpitGupta-shoptimize** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ArpitGupta-shoptimize. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ArpitGupta-shoptimize, here is your [Magento instance](https://i-22241-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22241-2-3-develop.instances.magento-community.engineering/admin](https://i-22241-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
