### ISSUE TITLE
Frontend cookies are not set with secure flag on https

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#22272]
### Preconditions (*)

1. Every Magento 2 version
2.

### Steps to reproduce (*)

1. Open a page on a Magento 2 shop
2.

### Expected result (*)

1. Secure cookies to show up in the Cookie panel

### Actual result (*)

1. Only one cookie is set to secure;

![image](https://user-images.githubusercontent.com/431360/55889184-f851e880-5bb0-11e9-83d2-fe2a4fc54694.png)

This is because Magento uses the (deprecated - see https://github.com/magento/magento2/issues/22271) [jQuery-Storage-API](https://github.com/julien-maurel/jQuery-Storage-API) jQuery plugin and does not set secure cookies.

For example;

```
$.cookieStorage.set('mage-cache-sessid', true);
```

Should be;

```
$.cookieStorage.set('mage-cache-sessid', true, { secure: true });
```

There should be a check whether the current protocol is HTTPS or else the cookie won't set, so pseudo-code;

```
var cookieConfig = {};
if (document.location.protocol === 'https:') {
    cookieConfig = {secure:true};
}
$.cookieStorage.set('mage-cache-sessid', true, cookieConfig);
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99160`, `MAGETWO-99161` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment]
I'll investigate and try to fix this issue, right now I can see that there are multiple places where cookies are set so the first step is to find them.

**Comment by twoatechguy** [comment]
Is this still active development to be incorporated into Magento 2.2x/2.3.x?

**Comment by DrewML** [comment]
@twoatechguy we've got @bubasuma working on a fix for this now

**Comment by magento-engcom-team** [comment]
Hi @peterjaap, @diwipl. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [2d1f8ca5d13c626000b34002704de9e0a99d3d99](https://github.com/magento/magento2/commit/2d1f8ca5d13c626000b34002704de9e0a99d3d99)

The fix will be available with the upcoming `2.3.4` release.

**Comment by pefferen** [comment]
Is this issue going to be backported to 2.2.x?

**Comment by krzksz** [comment]
@pefferen no, according to [this document](https://magento.com/sites/default/files/magento-open-source-software-maintenance-policy.pdf) Magento 2.2.x reached its EOL both in terms of features and security fixes. You need to migrate to 2.3.x if you want to have this feature or backport it yourself.

**Comment by diazwatson** [comment]
@bubasuma @krzksz Guys one question:

I can see 
```
$cookieMetadata->setSecure($this->sessionConfig->getCookieSecure());
```
in
https://github.com/magento/magento2/commit/2d1f8ca5d13c626000b34002704de9e0a99d3d99#diff-d04b5bf70889e73e0e8dca947c6a5521R98
is used to set `secure` for the cookie but,  how you enable this in the frontend to prevent errors with Google recaptcha?
![528856980-image](https://user-images.githubusercontent.com/1080386/79115735-8c373100-7d7e-11ea-9b5a-55c3b6b7ceb4.png)

**Comment by tope316** [comment]
Hi, we are using version 2.3.5-p1 and the PCI compliance checking found this issue on our site: "Insecure configuration of Cookie attributes". The Base URL and Secure Base URL are already using https. Why is the cookie secure flag is still not being set on https?

**Comment by dribblecastle** [comment]
@tope316 I'm in the same situation.  We had the problem with 2.3.4 and also now 2.3.6.   Have you found any solutions since posting?

**Comment by tuyennn** [comment]
@krzksz please reopen the ticket since the bugs still exit on Magento 2.3.5-p1

**Comment by tomisavolainen** [comment]
We have this issue in Magento 2.3.6-p1
