### ISSUE TITLE
Top menu cache issue - 2.3.1

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#22407]
### Preconditions (*)

1.Magento 2.3.1 with all cache types enabled

### Steps to reproduce (*)

1. Create 2-3 categories, set include in menu = Yes
2. On frontend click on any category page in top menu
3. Flush magento cache
4. Open the same category page
5. Open any other category page

### Expected result (*)

Just opened category is marked as active in top menu

### Actual result (*)

Both categories in top menu are marked as active
![test](https://user-images.githubusercontent.com/8502721/56359465-5488be00-61ea-11e9-9794-3df7b3015aa3.png)

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22407-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22407-2-3-develop.instances.magento-community.engineering/admin](https://i-22407-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22407-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22407-2-2-develop.instances.magento-community.engineering/admin](https://i-22407-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99263`, `MAGETWO-99264` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lyusya-nnn** [comment]
If somebody needs the fix for this issue you can create a plugin for Magento\Theme\Block\Html\Topmenu, so in di.xml you will have something like this:

```
<type name="Magento\Theme\Block\Html\Topmenu">
<plugin name="catalogTopmenuCache" type="MagentoOverwrite\Catalog\Plugin\Block\Topmenu" />
</type>
```

And your plugin will look like this:

```
<?php
namespace MagentoOverwrite\Catalog\Plugin\Block;

use Magento\Catalog\Model\Category;
use Magento\Catalog\Model\Layer\Resolver;

/**
 * Class Topmenu
 *
 */
class Topmenu
{
    /**
     * @var Resolver
     */
    private $layerResolver;

    /**
     * Topmenu constructor.
     * @param Resolver $layerResolver
     */
    public function __construct(
        Resolver $layerResolver
    ) {
        $this->layerResolver = $layerResolver;
    }

    /**
     * Get current Category from catalog layer
     *
     * @return \Magento\Catalog\Model\Category
     */
    private function getCurrentCategory()
    {
        $catalogLayer = $this->layerResolver->get();

        if (!$catalogLayer) {
            return null;
        }

        return $catalogLayer->getCurrentCategory();
    }

    /**
     * Add category id to cache tag
     *
     * @param \Magento\Theme\Block\Html\Topmenu $subject
     * @param array $result
     * @return array
     */
    public function afterGetCacheKeyInfo(\Magento\Theme\Block\Html\Topmenu $subject, $result)
    {
        $category = $this->getCurrentCategory();

        if (!$category || !$category->getId()) {
            return $result;
        }

        $result[] = Category::CACHE_TAG . '_' . $category->getId();

        return $result;
    }
}

```

**Comment by ghost** [comment]
It is coming because \Magento\Theme\Block\Html\Topmenu has a cache life time. If we return 0 in `getCacheLifetime()` it works fine. But is it best possible solution?

**Comment by ghost** [comment]
Also when clicking on any Footer link one category is marked as active. 
![Screenshot (1)](https://user-images.githubusercontent.com/42089978/56914245-3ddb4480-6ad1-11e9-8229-ce0d49209ef4.png)

**Comment by mega667** [comment]
It can be a temporary solution. 
Set `cache_lifetime` as `1` for the `catalog.topnav` block.

`{YOUR_THEME_DIR}/Magento_Theme/layout/default.xml`

```
<referenceContainer name="page.top">
    <referenceBlock name="catalog.topnav">
        <arguments>
            <argument name="cache_lifetime" xsi:type="number">1</argument>
        </arguments>
    </referenceBlock>
</referenceContainer>
```

**Comment by gaurav-473** [comment]
I am working on this #dmcdindia1

**Comment by lvampa** [comment]
Looks like setting `cache_lifetime` to `0` for this particular block, as mentioned above, doesn't actually work because of the override of the `getCacheLifetime` method in the Topmenu block. `"0"` is a falsy value and the parent `getCacheLifetime` returns either `null | int` which allows a 0 return value. The Null Coalesce Operator should probably be used over the ternary shorthand.

```
# parent::getCacheLifetime() = "0";
return parent::getCacheLifetime() ?: 3600;
# returns 3600;
```
VS
```
# parent::getCacheLifetime() = "0";
return parent::getCacheLifetime() ?? 3600;
# returns 0;
```

The short term fix until the PR gets attention is to probably use the suggested solution above of setting `cache_lifetime` to 1 via layout unless you wanna composer patch.

Reference - 
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Theme/Block/Html/Topmenu.php#L71

**Comment by jkeller92** [comment]
The main problem is not the cache lifetime - the cached content is the problem:
In some cases a menu with active elements is cached just because of 'deprecated' block functions.

Have a look at:
```zsh
 Magento\Theme\Block\Html\Topmenu::_getMenuItemClasses(\Magento\Framework\Data\Tree\Node $item)
{
...
}
```
This function provides item's css classes.
Just remove these lines with the help of a plugin or something like that. There is no need to add these markup classes via php since it's done via js.

```zsh
if ($item->getIsActive()) {
      $classes[] = 'active';
} elseif ($item->getHasActive()) {
      $classes[] = 'has-active';
}
```

**Comment by NetStorm84** [comment]
> The main problem is not the cache lifetime - the cached content is the problem:
> In some cases a menu with active elements is cached just because of 'deprecated' block functions.
> 
> Have a look at:
> 
> ```shell
>  Magento\Theme\Block\Html\Topmenu::_getMenuItemClasses(\Magento\Framework\Data\Tree\Node $item)
> {
> ...
> }
> ```
> 
> This function provides item's css classes.
> Just remove these lines with the help of a plugin or something like that. There is no need to add these markup classes via php since it's done via js.
> 
> ```shell
> if ($item->getIsActive()) {
>       $classes[] = 'active';
> } elseif ($item->getHasActive()) {
>       $classes[] = 'has-active';
> }
> ```

The problem with doing it this way is that it's down to the javascript to mark as active, so there is a slight, sometimes visible delay, from when the page loads to when the menu is marked active. making the site appear slow.

**Comment by jkeller92** [comment]
> The problem with doing it this way is that it's down to the javascript to mark as active, so there is a slight, sometimes visible delay, from when the page loads to when the menu is marked active. making the site appear slow.

Is this really a problem?

**Comment by NetStorm84** [comment]
> > The problem with doing it this way is that it's down to the javascript to mark as active, so there is a slight, sometimes visible delay, from when the page loads to when the menu is marked active. making the site appear slow.
> 
> Is this really a problem?

It was for me, the solution from mega667, by setting the `cache_lifetime` to 1, is a cleaner and more effective solution.

**Comment by JeroenGerth** [comment]
So any updates on this one? This issue is couple of months old now. Is this fixed in 2.3.2?

**Comment by maaarghk** [comment]
looks like it was fixed here before this issue was even opened, lol - https://github.com/magento/magento2/commit/bf8af1e7d3781db0921ed530e4f51e6d54ae56e1

but unfortunately there appears to have been a great deal of bikeshedding over test descriptions (until 2 days before this issue was opened!) so it was only merged 6 days ago: https://github.com/magento/magento2/commit/bc0b41245c5e55ecf27496e9ce1204ac6cf02a81

so i suppose you will have to stick with @lyusya-nnn solution until, i dunno... presumably november or something

:roll_eyes: embarrassing

**Comment by ihor-sviziev** [comment]
Hi @rammohan-krish,
Could you double check if this issue was already fixed?
Thx

**Comment by ktpl-rammohan** [comment]
@ihor-sviziev sure

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22407-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22407-2-3-develop.instances.magento-community.engineering/admin](https://i-22407-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue not reproduced on the 2.3-develop instance

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22407-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22407-2-2-develop.instances.magento-community.engineering/admin](https://i-22407-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue reproduced on the 2.2-develop instance
please refer to the following screenshot:
![Magento-menuissue](https://user-images.githubusercontent.com/46926270/60566538-d2d61480-9d84-11e9-953b-b10cc599d79d.png)

**Comment by ktpl-rammohan** [comment]
Hello, @ihor-sviziev  issue reproducing on the 2.2-develop instance.

**Comment by mallafreDG** [comment]
Hello, I just reproduced this issue in a new project based in Magento 2.3.2 and me and a teammate saw that disabling the vertex cache, does the menu works as intended (for anyone who gets this issue).

**Comment by pioneerathletics** [comment]
I am seeing this issue in both 2.2 and 2.3 is this going to be fixed in the next releases?

**Comment by ihor-sviziev** [comment]
Hi @rammohan-krish,

`2.2-develop` branch already closed - we should not wait for fixing this issue in 2.2 release line.

Looks like fix for this issue was reverted in https://github.com/magento/magento2/commit/5a997fdc2e987c1371c66014be89734798deddd1.

Could you check if this issue is reproducing on 2.3-develop? If it's not reproducing - let's close it.

**Comment by pioneerathletics** [comment]
Hi @ihor-sviziev,

I know this isn't exactly what you asked for in terms of 2.3 develop, but I can confirm the issue is still present in 2.3.2 (see screenshot).

![screenshot-8 15 19](https://user-images.githubusercontent.com/19981272/63104155-6e45d200-bf4c-11e9-93ec-7a12d65ec06d.png)

**Comment by maaarghk** [comment]
https://github.com/magento/magento2/issues/22407#issuecomment-507742424

**Comment by ihor-sviziev** [comment]
Yes, I saw your comment, but after 10 days after your comment there
appeared commit that reverted these changes, that is strange

That’s why I asked to recheck it again

**Comment by Ambertvu** [comment]
An update would still be great for this. Currently encountering this on a live site (even with default template), but it's quite random for me sadly

**Comment by ihor-sviziev** [comment]
Looks like it was finally fixed in https://github.com/magento/magento2/commit/bd5b7c584de95da97200be47d6f63fd9eda372f7

All related changes you can find here: https://github.com/magento/magento2/commit/84b7d391bed8874fb818b9fef0106bf7ff246249

@engcom-Alfa could you confirm that this issue is not reproducing anymore?

**Comment by engcom-Alfa** [comment]
@ihor-sviziev Ok, I will check

**Comment by engcom-Alfa** [comment]
@ihor-sviziev We are not able to reproduce this issue on fresh 2.3-develop instance. The problem has been resolved in [bd5b7c5](https://github.com/magento/magento2/commit/bd5b7c584de95da97200be47d6f63fd9eda372f7).
Thanks!

**Comment by orozcodiaz** [comment]
For those who are not able to update Magento to the latest version at this moment and need a quick fix: https://github.com/oroskodias/m2-fix-cache-topmenu
Thank you @lyusya-nnn !

**Comment by pratikhmehta** [comment]
You need to add a cache key that is unique per search query.

Create a plugin for the topmenu block in `di.xml`:

    <type name="Magento\Theme\Block\Html\Topmenu">
        <plugin name="topmenu_searchbar" type="Vendor\Package\Plugin\Block\Topmenu" />
    </type>

Then use the `getAfterCacheKeyInfo()` method:

    <?php
    
    namespace Vendor\Package\Plugin\Block;
    
    class Topmenu
    {
        /**
         * @var \Magento\Search\Helper\Data
         */
        private $searchHelper;

        public function __construct(
            \Magento\Search\Helper\Data $searchHelper
    	) {
            $this->searchHelper = $searchHelper;
    	}
    
        /**
         * Since the search bar was moved into the topnav, we need to add a key for the search term
         * so it doesn't get cached.
         */
         public function afterGetCacheKeyInfo(\Magento\Theme\Block\Html\Topmenu $subject, $result)
         {
             $result[] = $subject->getUrl('*/*/*', ['_current' => true, 'q' => $this->searchHelper->getEscapedQueryText()]);
             return $result;
         }
    }

**Comment by operator888** [comment]
So, when is it planned, the solution to be merged and released? I'm still getting this double active category bug.

**Comment by pioneerathletics** [comment]
Same here, upgraded to 2.3.3 thinking this issue would be fixed. It is not.

**Comment by UgoTurner** [comment]
Actually this issue was fixed in the [2.3.4 Commerce release](https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-4-commerce.html) : 

> Magento now highlights only the most recently selected category as expected on storefront pages that contain multiple categories. Previously, all selected category menus remained highlighted.

**Comment by joinso** [comment]
Hi, @oroskodias !
 
Your plugin (https://github.com/oroskodias/m2-fix-cache-topmenu) works perfect for menu items on category, but not for menu items added by other extensions.

For example:
https://marketplace.magento.com/mageplaza-magento-2-blog-extension.html

Regards,
JOINSO

**Comment by maaarghk** [comment]
that would be a mageplaza_blog bug, it should also plugin afterGetCacheKeyInfo and add its own thing
