### ISSUE TITLE
Pricing Index runs without ever completing - Magento 2.3.1

### ISSUE THREAD

**Issue by batmike** [magento/magento2#22516]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2
3. MySQL 5.7

### Steps to reproduce (*)

1. Heavily configurable product based catalog - about 375,000 total products of which about 15,000 are configurable products and the remaining 350,000 are simple products links to the configurables.
2. Upon upgrading to version 2.3.1 from version 2.3.0, the pricing index (catalog_product_price) would not complete indexing and would run without ending (in my environment, I let it run out to about 50 hours before giving up)
3. After reverting the changes made in the following commits, pricing index was able to be rebuilt again:
- https://github.com/magento/magento2/commit/47675cc328a0dab8a80cd53b257d3c3e779a7bab
- https://github.com/magento/magento2/commit/364ebfe5c1092b2c29b6eb5d5f36d2b8edec56a7
- https://github.com/magento/magento2/commit/4350a2e5a7ba4ddda00d50c6f55906a3d9f44e25

### Expected result (*)

1. Pricing index should be able to be fully rebuilt and moved into the active price database table in a reasonable amount of time

### Actual result (*)

1. Pricing index does not rebuild after our maximum test time of 45 hours.
2. With a 32 core, 120 GB RAM server, the pricing index was able to be rebuilt in approximately 3 minutes on the above catalog size configuration after the rollback of the noted commits to version 2.3.1.

**Comment by batmike** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @batmike. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @batmike, here is your [Magento instance](https://i-22516-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22516-2-3-1.instances.magento-community.engineering/admin](https://i-22516-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by batmike** [comment]
@magento-engcom-team 

I have the instance but cannot confirm as I would need to run some kind of sample data loader to build out a similar configurable/simple product catalog like we have in production. I also have to way to run the indexer from the CLI.

If these are available to run in a test vanilla environment, I'd be happy to test and see if it still does a similar thing to what we experienced.

**Comment by orlangur** [comment]
@batmike this is just a bot :) Simply wow, thanks for such a fruitful investigation.

@kandy you should like this.

**Comment by batmike** [comment]
@orlangur - of course it is! Just trying to get used to talking more with the machines than people ahead of time.

**Comment by royandre** [comment]
We are experiencing the same issue in 2.3.1 (multi-site, +80k SKUs (around 15k configurable, with simples attached), with the price index taking like forever (7+ hours), though we actually managed to finish it, and thus have the product appear in the store.

We are trying to tune the batch size (https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexer-batch.html), which seems to might affect this, so recommend others experiencing this issue to also check the batching as mentioned in the above link.

**Comment by acampos1916** [comment]
@royandre we're in a similar situation and get a very slow price reindexing. We adjusted the batch size for configurable and default down to 1000 and the improvement is not great. What batching setup did you end up using?

Investigating the catalog_product_index_price_temp temporal table I can see that it gets populated by a query that is exponentially slower as more products are enabled in more store views or at least that's what I think.

2.3.1 EE, 60k SKUs, 7k configurables

**Comment by enl** [comment]
It looks like this guy ignores product's type when it creates batches and therefore each indexer walks through all the products: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Indexer/Product/Price/Action/Full.php#L275

**Comment by andimov** [comment]
@batmike, @royandre, @acampos1916 do you have Magento Inventory (MSI) enabled in your Magento installation?

**Comment by batmike** [comment]
@andimov - we do not have any of the MSI modules enabled in our install.

**Comment by omniprolatam** [comment]
@andimov we do have MSI enabled.

**Comment by acampos1916** [comment]
@andimov we do have MSI enabled.

**Comment by alex-79** [comment]
Trigger is not working correctly:

vendor/magento/framework/Mview/View/Subscription.php

Magento 2.2.5:
```
foreach ($columnNames as $columnName) {
    $columns[] = sprintf(
        'NEW.%1$s != OLD.%1$s',
        $this->connection->quoteIdentifier($columnName)
    );
}
```
Magento 2.3.1:
```
foreach ($columnNames as $columnName) {
    $columns[] = sprintf(
        'NEW.%1$s <=> OLD.%1$s',
        $this->connection->quoteIdentifier($columnName)
    );
}
```
**!=** is not **<=>**

See https://github.com/magento/magento2/issues/23077 and https://github.com/magento/magento2/pull/23294

**Comment by andimov** [comment]
@batmike, @acampos1916, thank you for your answers.

There are several reasons why price indexation takes a long time for large data profiles:
- As @enl mentioned, there are missed type check in [getBatchesForIndexer() method](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Indexer/Product/Price/Action/Full.php#L282) so adding a new line with
        `$select->where('type_id = ?', $typeId);`
fixed that issue. This fix will be delivered to 2.3-develop soon with the tests coverage.
- MSI introduced an additional dependency for stock index in price indexer and it caused the performance degradation for price indexation with the big profiles. This issue described here https://github.com/magento/inventory/issues/2210 and already fixed in 2.3-develop by https://github.com/magento/inventory/pull/2336 so in case of using MSI you can take the [patch from PR](https://patch-diff.githubusercontent.com/raw/magento/inventory/pull/2336.diff)
- Batch size in 1000 shows slightly better performance results for the price indexer with large profiles, so it can be decreased from 5000 to 1000.

**Comment by batmike** [comment]
@andimov - I made the change to the getBatchesForIndexer() method but it didn't seem to improve the indexing time, with or without the batch modification. However, I enabled the MSI modules and then applied the PR 2336 and the rebuild now completes in just a couple minutes.

Is there any reason that the processing should still be degraded so much with MSI disabled though?

**Comment by andimov** [comment]
@batmike thank you for updates!
Yeah, it's weird. Please, try to disable MSI with patch and run indexation one more time to recheck degradation.
Fix from https://github.com/magento/inventory/pull/2336 shouldn't affect your price indexation performance until you install MSI itself, but without MSI you should have at least the same indexation time as you receive with the fix.

I performed tests with data profile 10 times less as you described with fresh Magento Open Source installation from 2.3-develop and I received such results:
 - changes in getBatchesForIndexer give 10-12 times improvement
 - changes in batch-size ~10% improvement

I also performed tests with Magento Commerce along with MSI with a large profile (10m eSKU) and I wasn't able to receive successful indexation for 50+ hours. With hotfix similar to https://github.com/magento/inventory/pull/2336 it was completed in 5 hours.

**Comment by batmike** [comment]
@andimov - Yes, you are right and your numbers look similar to what I'm seeing. When I let it run longer to test out the full benefit of the fix, the price indexing on our store completed in about 1.5 hours, which was much better than not finishing at all.

1.5 hours still isn't great compared to 5-6 minutes as we got prior in version 2.3.0 but ideally we would be able to use more of the incremental indexing rather than full reindexes which should reduce processing as well.

**Comment by seyuf** [comment]
@batmike your issue (without msi enabled) could be related to https://github.com/magento/magento2/pull/23294. You should try the fix. 
Also, to improve re-indexation time you can try multithread/multi-dimension feature available since 2.2.6 i believe ([MAGE_INDEXER_THREADS_COUNT=3 php -f bin/magento indexer:reindex](https://community.magento.com/t5/Magento-DevBlog/Indexers-parallelization-and-optimization/ba-p/104922)), it's working like a charm for me as a temp solution on a 300K+ catalog.

**Comment by batmike** [comment]
@seyuf - thanks for the ideas! I made the change in #23294 but it didn't result in much improvement. I've had it running in our staging environment and it's consistently reindexing pricing in about 50 minutes so the 1.5 hour mark I mentioned earlier wasn't exactly right.

I did also give the multi-threading a try but from looking into that, it seems that it would really only be helpful if we had multiple types of pricing - i.e. store views, customer types, and so on - and it would index those various breakouts in parallel. We have a simple setup though with just one store view and no pricing tiers or anything so there's unfortunately not much to parallel process.

**Comment by seyuf** [comment]
@batmike if you're sure you've correctly applied the fix...
Because, if i remember correctly, you have to at least make a setup upgrade to update the triggers in the db.

**Comment by batmike** [comment]
@seyuf - I didn't originally confirm that so I ran setup:upgrade and confirmed that the triggers are updated in the database with NOT NEW. They are correct now but the price reindexing for us is still taking 50 minutes. I'm not against blaming our environment or even the ratio we have of configurable to simple products, which is about 1 configurable for every 40 simple products on average but in reality it's probably a much wider range with many being 1:5 but a number of them much higher around 1:100 or so.

**Comment by seyuf** [comment]
Yeah, there should be no increase in full reindexing performance due to the fix. But it will allow you to avoid full reindexing in favor of incremental one. Also on 2.3.1, to avoid indexing issues i set the index cron group (from the BO admin section) *Use Separate Process* to no. To avoid conflicts during incremental indexing.

**Comment by batmike** [comment]
@seyuf - that sounds very good. I'll be testing that out and update here with the results. Thanks!

Update ... changing to the incremental updating could potentially work but we have a process that imports stock quantity updates from our inventory system and that's pretty much constant as we have physical stores that sell and transfrer items throughout the day so updated quantities are constantly coming into our site to be processed. With that, using the incremental indexing even just on pricing hangs up the database as each of those stock updates triggers some reindex processes that make it take much longer and drag the site down.

In the end, this has resulted in a good compromise as we've been able to enable incremental indexing on some of the indexes and then keep full indexing enabled for the bigger ones that take too long for the Magento crontab jobs to deal with. The fixes above noted by @andimov did definitely resolve the major issue with the index taking 10s or 100s of hours, which was my main thing.

**Comment by andimov** [comment]
Thanks all, PR with changes were [delivered](https://github.com/magento/magento2/commit/d7b928af7737ea660d668bb60195351bd00070cb) 
The issue covered by Performance Acceptance Test which required for each PR.

**Comment by andimov** [comment]
The issue has been fixed in 2.3-develop branch
The fix will be available with the upcoming 2.3.3 release.
I have to close this issue.
Thanks for the report!
