### ISSUE TITLE
M2.3.1: Unable to place order for bundle when child quantity > 1

### ISSUE THREAD

**Issue by mystix** [magento/magento2#22743]
When placing an order for a bundle product with child product quantity set to a value greater than 1, the following error message is thrown:
`We found an invalid quantity to invoice item "%1".`

This happens for any payment method where invoices are automatically created during order creation e.g.
- PayPal Express Checkout + Payment Action = **Sale**
- Zero Subtotal Checkout + Automatically Invoice All Items = **Yes**

### Preconditions (*)
1. Magento 2.3.1
2. **Test** bundle product:
  --  **_General configuration_**
  ![Screenshot 2019-05-06 at 12 10 39 PM](https://user-images.githubusercontent.com/174070/57206400-ff291b00-6ff7-11e9-9a48-ad085a950235.png)
  --  **_Child product_ (ensure Ship Bundle Items is set to "Together")**
  ![Screenshot 2019-05-05 at 2 31 25 PM](https://user-images.githubusercontent.com/174070/57189577-f4f91500-6f42-11e9-97c4-753c456336e8.png)

3. **Admin > Stores > Configuration > Sales > Payment Methods** configuration:
  --  **_PayPal Express Checkout (note: a sandbox account will work as well)_**
    Enable this solution: **Yes**
    Payment Action: **Sale**
  --  **_Zero Subtotal Checkout_**
    Enabled: **Yes**
    New Order Status: **Processing**
    Automatically Invoice All Items: **Yes**

4. **Admin > Stores > Configuration > Sales > Shipping Methods** configuration:
  -- **_Free Shipping_**
    Enabled: **Yes**

---

### Steps to reproduce (as customer) (*)
1. Add **Test** bundle to the shopping cart, making sure to set the child quantity to a value > 1:
  ![Screenshot 2019-05-06 at 12 26 32 PM](https://user-images.githubusercontent.com/174070/57206662-3698c700-6ffa-11e9-9a93-e83c4ca6d940.png)
2. Proceed to Checkout
3. Select PayPal Express Checkout as the payment method
4. Click Continue to PayPal
5. Make payment on PayPal

### Expected result (*)
1. Customer is redirected back to Magento's Order Success page
  ![Screenshot 2019-05-06 at 12 39 03 PM](https://user-images.githubusercontent.com/174070/57206906-f5a1b200-6ffb-11e9-83dc-ab161f536421.png)

### Actual result (*)
1.  Error message `We found an invalid quantity to invoice item "%1".` is displayed:
  ![Screenshot 2019-05-06 at 12 41 58 PM](https://user-images.githubusercontent.com/174070/57206953-5c26d000-6ffc-11e9-89bf-233da0ab7f66.png)

---

### Steps to reproduce (as admin) (*)
1. Create a new order from **Admin > Sales > Orders** 
2. Add the **Test** bundle to the order, making sure the **child quantity** is set to a value greater than 1:
  ![Screenshot 2019-05-06 at 12 46 11 PM](https://user-images.githubusercontent.com/174070/57207028-f38c2300-6ffc-11e9-92bf-4daa926200ad.png)
3. Set a custom price of 0 for the **Test** bundle
  ![Screenshot 2019-05-06 at 12 47 42 PM](https://user-images.githubusercontent.com/174070/57207162-0b17db80-6ffe-11e9-927f-94687eb3a99c.png)
4. Under **Shipping Method**, select **Free Shipping**
5. **Payment Method** section should now display "No Payment Information Required", and the order total should be 0:
  ![Screenshot 2019-05-06 at 12 56 14 PM](https://user-images.githubusercontent.com/174070/57207204-59c57580-6ffe-11e9-8363-33ea8c0e0c3e.png)
6. Click Submit Order

### Expected result (*)
1. New zero subtotal order is successfully created
2. Invoice is automatically created for this zero subtotal order

### Actual result (*)
1. Error message `We found an invalid quantity to invoice item "Test".` is displayed:
  ![Screenshot 2019-05-06 at 1 06 53 PM](https://user-images.githubusercontent.com/174070/57207382-dc026980-6fff-11e9-92d0-43ac1932e73e.png)

**Comment by mystix** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mystix. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mystix, here is your [Magento instance](https://i-22743-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22743-2-3-develop.instances.magento-community.engineering/admin](https://i-22743-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mystix** [comment]
> @mystix do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
* [x]  yes
* [ ]  no

**Comment by mystix** [comment]
This bug was introduced in commit 2fb6b3b81ada22e1a172272a7eb5454a50a71a2d in the following 2 private methods from [app/code/Magento/Sales/Model/Service/InvoiceService.php](https://github.com/magento/magento2/blob/2fb6b3b81ada22e1a172272a7eb5454a50a71a2d/app/code/Magento/Sales/Model/Service/InvoiceService.php]app/code/Magento/Sales/Model/Service/InvoiceService.php):

```
    /**
     * Prepare qty to invoice for parent and child products if theirs qty is not specified in initial request.
     *
     * @param Order $order
     * @param array $qtys
     * @return array
     */
    private function prepareItemsQty(Order $order, array $qtys = [])
    {
        foreach ($order->getAllItems() as $orderItem) {
            if (empty($qtys[$orderItem->getId()])) {
                if ($orderItem->getProductType() == Type::TYPE_BUNDLE && !$orderItem->isShipSeparately()) { // herein lies the problem -- order item id is assumed to be > 0
                    $qtys[$orderItem->getId()] = $orderItem->getQtyOrdered() - $orderItem->getQtyInvoiced();
                } else {
                    continue;
                }
            }
            $this->prepareItemQty($orderItem, $qtys);
        }
        return $qtys;
    }

    /**
     * Prepare qty to invoice for bundle products
     *
     * @param \Magento\Sales\Api\Data\OrderItemInterface $orderItem
     * @param array $qtys
     */
    private function prepareBundleQty(\Magento\Sales\Api\Data\OrderItemInterface $orderItem, &$qtys)
    {
        if ($orderItem->getProductType() == Type::TYPE_BUNDLE && !$orderItem->isShipSeparately()) { // herein lies the problem -- order item id is assumed to be > 0
            foreach ($orderItem->getChildrenItems() as $childItem) {
                $bundleSelectionAttributes = $this->serializer->unserialize(
                    $childItem->getProductOptionByCode('bundle_selection_attributes')
                );
                $qtys[$childItem->getId()] = $qtys[$orderItem->getId()] * $bundleSelectionAttributes['qty'];
            }
        }
    }
```

The bug is triggered when the private method `prepareItemsQty()` is called by the public method `prepareInvoice()`.

ALL existing test cases which call the `prepareInvoice()` method assume an order has already been successfully created (and hence, all order items belonging to the order have an item id > 0). This assumption is invalid when invoices are created _together_ with orders, as is the case with
- PayPal Express Checkout + payment action = "Sale"
- Zero Subtotal Checkout + automatically invoice all items = "Yes"

To resolve this, the 2 private methods above should also check for a non-zero bundle item id:
```
    /**
     * Prepare qty to invoice for parent and child products if theirs qty is not specified in initial request.
     *
     * @param Order $order
     * @param array $qtys
     * @return array
     */
    private function prepareItemsQty(Order $order, array $qtys = [])
    {
        foreach ($order->getAllItems() as $orderItem) {
            if (empty($qtys[$orderItem->getId()])) {
                if ($orderItem->getId() && $orderItem->getProductType() == Type::TYPE_BUNDLE && !$orderItem->isShipSeparately()) { // bugfix
                    $qtys[$orderItem->getId()] = $orderItem->getQtyOrdered() - $orderItem->getQtyInvoiced();
                } else {
                    continue;
                }
            }
            $this->prepareItemQty($orderItem, $qtys);
        }
        return $qtys;
    }

    /**
     * Prepare qty to invoice for bundle products
     *
     * @param \Magento\Sales\Api\Data\OrderItemInterface $orderItem
     * @param array $qtys
     */
    private function prepareBundleQty(\Magento\Sales\Api\Data\OrderItemInterface $orderItem, &$qtys)
    {
        if ($orderItem->getId() && $orderItem->getProductType() == Type::TYPE_BUNDLE && !$orderItem->isShipSeparately()) { // bugfix
            foreach ($orderItem->getChildrenItems() as $childItem) {
                $bundleSelectionAttributes = $this->serializer->unserialize(
                    $childItem->getProductOptionByCode('bundle_selection_attributes')
                );
                $qtys[$childItem->getId()] = $qtys[$orderItem->getId()] * $bundleSelectionAttributes['qty'];
            }
        }
    }
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99568` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by davidwindell** [comment]
@mystix just wanted to say thank you for the detailed report and suggested fix - we've hit this exact issue on a live site (recently upgraded to 2.3.1) with Stripe also.

**Comment by lmstephenson** [comment]
I encountered this same issue using **Braintree gateway** with "_Enable PayPal through Braintree_" which I believe is a PayPal Flow transaction, slightly different than Express Checkout but still broken without @mystix fix.

@mystix thank you for posting the fix. I implemented on and M2.3.1 instance this morning. The InvoiceService.php source code was a bit different than what you posted, however, adding **`$orderItem->getId() &&`** to the beginning of the if statements worked the same.

I encountered this same issue with "Enable PayPal through Braintree" which I believe is a PayPal Flow transaction, slightly different that Express Checkout but still broken without @mystix fix.

`@file : vendor/magento/module-sales/Model/Service/InvoiceService.php`
`@lines: 179-206`
`@code : code added @line 190` **`$orderItem->getId() &&`**

```
   /**
     * Prepare qty to invoice for parent and child products if theirs qty is not specified in initial request.
     *
     * @param Order $order
     * @param array $qtys
     * @return array
     */
    private function prepareItemsQty(Order $order, array $qtys = [])
    {
        foreach ($order->getAllItems() as $orderItem) {
            if (empty($qtys[$orderItem->getId()])) {
                if ($orderItem->getId() && $orderItem->getProductType() == Type::TYPE_BUNDLE && !$orderItem->isShipSeparately()) {
                    $qtys[$orderItem->getId()] = $orderItem->getQtyOrdered() - $orderItem->getQtyInvoiced();
                } else {
                    $parentItem = $orderItem->getParentItem();
                    $parentItemId = $parentItem ? $parentItem->getId() : null;
                    if ($parentItemId && isset($qtys[$parentItemId])) {
                        $qtys[$orderItem->getId()] = $qtys[$parentItemId];
                    }
                    continue;
                }
            }

            $this->prepareItemQty($orderItem, $qtys);
        }

        return $qtys;
    }
```

`@file : vendor/magento/module-sales/Model/Service/InvoiceService.php`
`@lines: 240-258`
`@code : code added @line 249` **`$orderItem->getId() &&`**

```	
    /**
     * Prepare qty to invoice for bundle products
     *
     * @param \Magento\Sales\Api\Data\OrderItemInterface $orderItem
     * @param array $qtys
     */
    private function prepareBundleQty(\Magento\Sales\Api\Data\OrderItemInterface $orderItem, &$qtys)
    {
        if ($orderItem->getId() && $orderItem->getProductType() == Type::TYPE_BUNDLE && !$orderItem->isShipSeparately()) {
            foreach ($orderItem->getChildrenItems() as $childItem) {
                $bundleSelectionAttributes = $childItem->getProductOptionByCode('bundle_selection_attributes');
                if (is_string($bundleSelectionAttributes)) {
                    $bundleSelectionAttributes = $this->serializer->unserialize($bundleSelectionAttributes);
                }

                $qtys[$childItem->getId()] = $qtys[$orderItem->getId()] * $bundleSelectionAttributes['qty'];
            }
        }
    }
```

**Comment by DanielRiezebos** [comment]
I would like to thank @mystix for providing the fix I needed to solve this issue! Hopefully Magento can come out with a patch or update soon to properly resolve this problem.

**Comment by magento-engcom-team** [comment]
Hi @mystix, @GovindaSharma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-99568` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by bscbodyscience** [comment]
I am getting this issue in magento 2.3.2. I assume magento still didn't fix this

**Comment by mystix** [comment]
> I am getting this issue in magento 2.3.2. I assume magento still didn't fix this

I ran both my test cases, and double-checked my existing codebase just to make sure I'm running the code from M2.3.2 -- I can confirm I no longer see this problem in M2.3.2.

Try monkey-patching your codebase with the fix I suggested to see if it helps resolve your issue?
https://github.com/magento/magento2/issues/22743#issuecomment-489509956

**Comment by bscbodyscience** [comment]
@mystix Thanks for the reply mate. I am getting a lot of complaints from customers so, definitely, I am getting the error :(
I will try to add the fix you have mentioned mate.

**Comment by cscd98** [comment]
We are also having this problem on a live site, when will it be fixed? Magento 2.3.2

**Comment by bscbodyscience** [comment]
@mystix I have added your fix and it seems working now :) . thanks for the fix mate. you are a lifesaver.

@craigcarnell Try @mystix fix. it worked for me.

**Comment by develth** [comment]
Fixed it for me, too & does not seems to be fixed in 2.3.3

**Comment by cits74** [comment]
same issue here, magento 2.3.2 (cannot upgrade right now because it is production env). patched as @mystix suggested, now works. I hope it will be fixed in future versions, I don't want to keep custom patches in the code.
