### ISSUE TITLE
Can't update totals for credit note

### ISSUE THREAD

**Issue by vseager** [magento/magento2#22774]
### Preconditions (*)
1. Magento Open Source 2.3.x & 2.3-develop(after 2.3.3 code was merged)

### Steps to reproduce (*)
1. Select an invoice
2. Click "Credit Memo"
3. Add value to `Refund Shipping `, `Adjustment Refund` or `Adjustment Fee` field

### Expected result
1. Should be able to update totals using the "Update Totals" button

![M2 2 8](https://user-images.githubusercontent.com/2035088/57310996-ba2de300-70e2-11e9-938f-8dcf8c2174e9.png)

### Actual result
1. There is no way to update the total (without changing the quantity and then changing it back again)

![M2 3 1](https://user-images.githubusercontent.com/2035088/57311003-bef29700-70e2-11e9-8848-5ed613305810.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @vseager
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by deepakk-webkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-22774-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22774-2-3-develop.instances.magento-community.engineering/admin](https://i-22774-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @webkul-deepakkumar
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99601` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gaurav-473** [comment]
I am working on it. #imagine2019

**Comment by magento-engcom-team** [comment]
Hi @vseager, @Valant13, @gauravagarwal1001. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-18859` was closed as `non-reproducible` in `2.2-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @vseager, @Valant13, @gauravagarwal1001. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-18858` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by dverkade** [comment]
I'm reopening this issue. It still an issue in Magento 2.3.2. Steps to reproduce are clear and show the button is not present in Magento 2.3.1 and I can confirm it's not present in Magento 2.3.2 as well.

**Comment by engcom-Charlie** [comment]
Hello @dverkade 
I can't reproduce this issue on a fresh Magento 2.3-develop.
**GIF:**
![Peek 2019-09-27 09-57](https://user-images.githubusercontent.com/51680850/65748918-ac1e4480-e10d-11e9-995d-61ddf9af15c9.gif)
So i have to close this issue.

**Comment by coderimus** [comment]
@engcom-Charlie I think that the issue is still present and I have to reopen it. Please, check my description below. 

The current Magento 2.3.3 version does not contain the Update total button. I checked this not only on the 2.3.3 instance but also in the codebase.

For example, here, at the block class, the lastest commit has the next description: ["MC-19061: Revert ticket MC-17003"](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Create/Items.php) Which completely revert previously returned Update totals button This happened before your test at  Aug 12

Currently, there is no Update totals button. Is it the correct behaviour or this is a bug?

Looking forward to your reply,
Alex

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22200` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by danielrussob** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by danielrussob** [comment]
@magento give me 2.3-develop instance

**Comment by danielrussob** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by danielrussob** [comment]
It seems that Magento 2.3.x has missed a commit (451f7b9f317db5a27d3d9c541cc3c1678cc169f5), i don't know why


As a temporary fix you can create a patch from https://github.com/magento/magento2/commit/451f7b9f317db5a27d3d9c541cc3c1678cc169f5 to solve problem

**Comment by magento-engcom-team** [comment]
Hi @danielrussob. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @danielrussob. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @danielrussob. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
The Issue should be re-verified on the latest Magento code and re-Confirmed if its still actual

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
> The Issue should be re-verified on the latest Magento code and re-Confirmed if its still actual

@magento-engcom-team 

I have reproduced issue on Magento 2.3 but not on Magento 2.4 vanilla

**Comment by liquidia** [comment]
Any update if this issue is still persist  in 2.3.3 ? is there any patch available?

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @vseager,

Thanks for your reporting and collaboration.

We have verified the issue in the Magento 2.4-develop instance and the issue is no more reproducible.

<img width="887" alt="Screenshot 2024-04-29 at 13 41 07" src="https://github.com/magento/magento2/assets/51680745/22ba1c13-b330-4de0-8386-b3ad6de20b2b">


Hence We are closing this issue.

Thanks.
