### ISSUE TITLE
Delegated account creation fails with custom attributes present in customer address

### ISSUE THREAD

**Issue by a-t-s** [magento/magento2#22952]
### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1.Create a customer address custom attribute either programmatically (CE) or more convenient via backend in Magento Commerce.
![blocking_test_attr](https://user-images.githubusercontent.com/10349826/58025351-8a380400-7b14-11e9-9784-8837348b5910.png)
2. Checkout without being logged-in / as guest
3. On the success page choose to "create an account"
4. Wait for redirect
5. Choose password and submit form.
6. Get fatal error

### Expected result (*)
1. Account should be created with success message.

### Actual result (*)
1. Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Framework\Reflection\CustomAttributesProcessor::convertCustomAttribute() must be an instance of Magento\Framework\Api\AttributeInterface, null given, called in /vendor/magento/framework/Reflection/CustomAttributesProcessor.php on line 53 and defined in /vendor/magento/framework/Reflection/CustomAttributesProcessor.php:65

Deserialization of custom attributes in addresses retrieved from delegatedStorage in vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php:181
is incomplete and does not match the required at Magento\Framework\Api\AttributeInterface in vendor/magento/framework/Reflection/CustomAttributesProcessor.php:65 called via vendor/magento/framework/Reflection/CustomAttributesProcessor.php:53 when saving in  vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php:253

Changes were introduced with commit:
https://github.com/magento/magento2/commit/283a799a1b90419b029b2e26d8f5931086a2c735

**Comment by a-t-s** [comment]
Is there a way to get a commerce instance too? This would be the only way to confirm it on your instances via the backend.

**Comment by AlexWorking** [comment]
Hello @a-t-s. Thanks for reporting. We've got an incorrect behaviour following the steps You provided but somewhat another. When we choose password and submit form we are simply getting a blank page. Customer is not created. But we don't see fatal errors anywhere nether in the logs nor on that blank page providing the developer mode is enabled. Could You please guide us to where You get it? Thank You.

**Comment by magento-engcom-team** [comment]
@AlexWorking Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17200`, `MC-17201` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sjb9774** [comment]
Is there any update on this issue? I'm seeing this problem as well.

**Comment by ghost** [comment]
I am working on this issue. Let you know soon.

**Comment by gabs77** [comment]
Same issue for magento 2.2.8

**Comment by Sherbieny** [comment]
Issue happening in commerce 2.3.1
A temporary workaround that worked for me was the following:

1. preference for Magento\Framework\Reflection\CustomAttributesProcessor in your module
2. extend Magento\Framework\Reflection\CustomAttributesProcessor with your own class
3. copy the whole class (its a small one) into your custom once
3. add a null handler in the loop of buildOutputDataArray method
foreach ($customAttributes as $customAttribute) {
            if ($customAttribute) {
                $result[] = $this->convertCustomAttribute($customAttribute, $dataObjectType);
            }
        }
4. preference for Magento\Customer\Model\Address in your module
5. extend Magento\Customer\Model\Address with your own class
6. copy only the updateData method into your class along with used classes at the top of the original
use Magento\Customer\Api\AddressMetadataInterface;
use Magento\Customer\Api\Data\AddressInterface;
7. add a hanlder for null attributes in the loop
foreach ($customAttributes as $attribute) {
                if (isset($attribute)) {
                    $this->setData($attribute->getAttributeCode(), $attribute->getValue());
                }
            }

the second preference I made as I faced another error when saving the customer address having custom attributes

hope this help until an official fix is made

**Comment by magento-engcom-team** [comment]
Hi @a-t-s. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.2-develop` branch(es).
Related commit(s):
 - [2e81e2d3389acd572c98ed72513b7be1b91bc3ec](https://github.com/magento/magento2/commit/2e81e2d3389acd572c98ed72513b7be1b91bc3ec)
 - [25224302ef687737ce41cf86fd6e21a104f9ead3](https://github.com/magento/magento2/commit/25224302ef687737ce41cf86fd6e21a104f9ead3)

The fix will be available with the upcoming `2.2.10` release.

**Comment by magento-engcom-team** [comment]
Hi @a-t-s. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.

**Comment by siergiej-zarkiewicz** [comment]
Hi @magento-engcom-team 
Can I get fix for this issue?
Links to commit(s) not working.

**Comment by sjb9774** [comment]
@magento-engcom-team  I am seeing this issue on another environment again. Can you please provide a patch or working links to the commits that are supposed to fix this? I checked the DelegateAccount and CustomAttributesProcessor files on 2.3 develop and they do not appear to have been changed for a while. 

From what I can tell this is not fixed since the linked commits don't exist so I'm going to re-open until we can show it's fixed.

**Comment by sdzhepa** [comment]
Hello @sjb9774 

I have checked in the internal Jira:

1. The fix was delivered into `2.3-develop` branch in the scope of internal ticket `MC-17201`. 
Related commits:
- https://github.com/magento/magento2/commit/5223ed0226c2f176e6ffe81f039e94ef54910390
- https://github.com/magento/magento2/commit/52d678676ad85c09584e913cb90362b10707905f
Based on Jira, will be available with 2.3.4 release

2.  Commits mentioned in https://github.com/magento/magento2/issues/22952#issuecomment-515024784  related to `2.2-develop` branch. This branch was closed and not available anymore

>  _Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
>  See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details


Commits related to Magento Commerce(EE) were not listed because of this repository is intended for Magento Open Source users to report on issues related to Open Source only. To resolve any Commerce(EE) related issues you can use  one of two ways:
- use the Support portal associated with your account
- If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by sjb9774** [comment]
@sdzhepa Thank you for the update, I appreciate it. I applied the following patch using `cweagans/composer-patches` and it seems to have resolved the issue. Closing as this has the appropriate commit links now and appears to be fixed.

```
Index: vendor/magento/module-customer/Model/Delegation/Storage.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Model/Delegation/Storage.php	(date 1564699128000)
+++ Model/Delegation/Storage.php	(date 1564699128000)
@@ -104,11 +104,13 @@
             }
         }
         $this->session->setCustomerFormData($customerData);
-        $this->session->setDelegatedNewCustomerData([
-            'customer' => $customerData,
-            'addresses' => $addressesData,
-            'delegated_data' => $delegatedData
-        ]);
+        $this->session->setDelegatedNewCustomerData(
+            [
+                'customer' => $customerData,
+                'addresses' => $addressesData,
+                'delegated_data' => $delegatedData,
+            ]
+        );
     }

     /**
@@ -138,18 +140,28 @@
                 );
                 $addressData['region'] = $region;
             }
-            $addresses[] = $this->addressFactory->create(
+            $customAttributes = [];
+            if (!empty($addressData[CustomAttributesDataInterface::CUSTOM_ATTRIBUTES])) {
+                $customAttributes = $addressData[CustomAttributesDataInterface::CUSTOM_ATTRIBUTES];
+                unset($addressData[CustomAttributesDataInterface::CUSTOM_ATTRIBUTES]);
+            }
+            $address = $this->addressFactory->create(
                 ['data' => $addressData]
             );
+
+            foreach ($customAttributes as $attributeCode => $attributeValue) {
+                $address->setCustomAttribute($attributeCode, $attributeValue);
+            }
+            $addresses[] = $address;
         }
         $customerData = $serialized['customer'];
         $customerData['addresses'] = $addresses;

-        return $this->newFactory->create([
-            'customer' => $this->customerFactory->create(
-                ['data' => $customerData]
-            ),
-            'additionalData' => $serialized['delegated_data']
-        ]);
+        return $this->newFactory->create(
+            [
+                'customer' => $this->customerFactory->create(['data' => $customerData]),
+                'additionalData' => $serialized['delegated_data'],
+            ]
+        );
     }
 }

```

**Comment by pradeep18th** [comment]
@sjb9774 Thank you for the update, I have applied this code in vendor/magento/module-customer/Model/Delegation/Storage.php but it get an error :
atal error: Uncaught Error: Class 'Magento\Customer\Model\Delegation\CustomAttributesDataInterface' not found in /home/project/public_html/vendor/magento/module-customer/Model/Delegation/Storage.php:138

**Comment by ThakurPradeep** [comment]
Hi @sdzhepa after implement your code "5223ed0"
https://github.com/magento/magento2/commit/5223ed0226c2f176e6ffe81f039e94ef54910390

previous error is not show but  this error is get **we can't save the customer** and other think is when we refresh the page or resubmit account is create but on order is assign under this acoount.
Magento version => 2.3.1(B2B) 
please help me .
Thanks

**Comment by ThakurPradeep** [comment]
Thanks @sdzhepa your code is working fine.address variable is missing in our code at the time of implement of our code

**Comment by tprocter-ldg** [comment]
> Thanks @sdzhepa your code is working fine.address variable is missing in our code at the time of implement of our code

Hi @ThakurPradeep 

I am getting the same issue, however $address is populated by the time the new factory is returned. How did you resolve this? 

Thank you
