### ISSUE TITLE
Magento 2.3 URL keys regenerate on import

### ISSUE THREAD

**Issue by James-Hall195** [magento/magento2#22975]
### Preconditions (*)
1. Magento 2.3.0
2. Import Functionality

### Steps to reproduce (*)
1. Mass update products with no "url_key" header present (only "sku","description") using the import feature. (I have tested this on other builds of Magento, and cannot reproduce it)

### Expected result (*)
1. The import should only update the fields in the CSV files. In this case, "description"
2. URL keys should stay the same

### Actual result (*)
1. The import removes the URL keys from Magento of every sku listed. 
2. URL keys regenerate from the name if; 
- The product is saved with no URL key
- The import includes "name" and (empty) "url_key"

**Comment by James-Hall195** [comment]
@James-Hall195 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

  **yes**

**Comment by nfourteen** [comment]
I can also confirm this issue.

### Preconditions
1. Magento 2.3.1

### Steps to reproduce
1. Create a configurable product on a new Magento instance
2. Navigate to `System > Data Transfer > Export` and export the **Products** entity
3. Open the CSV file and update prices
4. Navigate to `System > Data Transfer > Import` and import the updated CSV file using the **Import Behavior** Add/Update.

### Expected result
1. The product prices should be updated to the new values.

### Actual result
1. On import, `Duplicates found in column names:` error is thrown. 
    - After some digging, this error is thrown because the `url_key` column exists within the CSV data.
2. Delete the `url_key` column and retry **Import**.
3. Another error is thrown, stating `1. Url key: 'test.html' was already generated for an item with the SKU: '0001'. You need to specify the unique URL key manually in row(s): 19`. 
    - Digging further, the `url_key` is generated using the value from the `name` column if the `url_key` column doesn't exist. 
4. Delete the `name` column and retry **Import**.
5. Another error is thrown, stating `Please make sure attribute "name" is not empty. in row(s): 19`.

The note under the **Import Behavior** field states: `New product data is added to the existing product data for the existing entries in the database. All fields except sku can be updated.`, but that can't be done due to the `url_key` validation and auto-generation logic.

**Comment by hostep** [comment]
@James-Hall195: can you try upgrading to Magento 2.3.1? I believe it is fixed over there.

It was fixed in Magento 2.2.8 by https://github.com/magento/magento2/pull/17882 but the forward port to 2.3.x was denied: https://github.com/magento/magento2/pull/18783 and then Magento fixed it themselves in https://github.com/magento/magento2/commit/468d2ac3810c5bead6693346e1d0b995d22eeeb1 which was released in Magento 2.3.1

@nfourteen: I believe what you are experiencing is a different issue, it might be best if you open a new issue for this.

**Comment by nfourteen** [comment]
@hostep I will open a new issue, thanks!

**Comment by James-Hall195** [comment]
@hostep I think that's what we're going to aim to do. I wasn't sure if this was somehow intended functionality in the new Magento, but it seems like a fairly big issue to miss. 

Thank you for the help. Glad this is fixed in the next version.

**Comment by hostep** [comment]
Ok, closing issue for now. If it turns out not to be fixed don't hesitate to come back :)

**Comment by ebgreen** [comment]
not fixed on 2.3.1

**Comment by hostep** [comment]
@ebgreen: can you give exact steps of how to reproduce in your case? (And maybe open a new issue around it). Thanks!

**Comment by jefflenz** [comment]
Still happening on 2.3.3-p1.  Not sure why url keys are being touched when you don't include it in your import file, very odd
