### ISSUE TITLE
Admin Page 404 After Install Magento2 RC

### ISSUE THREAD

**Issue by turgayozgur** [magento/magento2#2309]
I changed admn url from "admin_310mps" to "admin" at the installation step.

Magento2 admin page "http://127.0.0.1:8080/mage2/admin/" showing 404 error page after install magento2-rc.

How can i fix this issue?

**Comment by mazhalai** [comment]
@turgayozgur can you please try on the `develop` branch?

**Comment by mazhalai** [comment]
@turgayozgur Please try again, this has been fixed in RC2.

**Comment by sukool88** [comment]
I have just installed it successfully from the master branch and it still gives me 404 on admin panel. http://localhost:80/admin/.The fronted is not getting the styles and img. I am using windows10, php5.6, IIS with phpmanager.

![capture](https://cloud.githubusercontent.com/assets/4284233/11217755/e9fa3232-8d1f-11e5-91cd-9702027d2144.PNG)

**Comment by bh-ref** [comment]
I am facing the same problem (404 if I want to access /admin). I am using Windows 8.1, PHP 5.6.2 and apache 2.2.

The styles were not showing on the home page, too. But after running `php bin\magento setup:static-content:deploy`, I could at least see the lumia theme.

**Comment by balex13** [comment]
During the installation you entered unique admin URI (it generates automatically for you) eg. /admin_cr8w74  To get info about your URI use CLI command:
```bash
/var/www/html/magento2$ php bin/magento info:adminuri
```
Just after the installation cache with static content is empty. So you can see page without styles and images.
You have to generate static content to the cache (stored in pub/static/) using:
```bash
/var/www/html/magento2$ php bin/magento setup:static-content:deploy
```
Or you can enable `developer` mode by uncommenting following line in the .htaccess file:
```bash
#   SetEnv MAGE_MODE developer
```

**Comment by bh-ref** [comment]
Thank you for your answer. I am using the URI I get from CLI command `php bin/magento info:adminuri`, but unfortunately I still get a 404 error.

**Comment by bh-ref** [comment]
When I use the magento2 codebase from https://www.magentocommerce.com/download with the original .htaccess files, everything is working as expected (the styles are loaded and the admin URI is working, too). It seems like it was an issue with the .htaccess files I worked with before (I once edited them and then always used these edited ones thereafter). 

@sukool88 maybe you encounter this problem because IIS cannot work with the .htaccess files?

**Comment by theskillwithin** [comment]
Ya I have the same issue,  I could see the luma theme after setting up static-content deploy,  however on apache php 5.6 I did not have to do this and everything worked perfectly.  I am experiencing this with php7 and nginx. 

every page other than index.php returns a 404

**Comment by mazhalai** [comment]
@theskillwithin please do not comment on closed issues.
