### ISSUE TITLE
Elasticsearch category page issues when 1 column layout is used

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#24619]
### Preconditions (*)

1. Magento 2.3.2 CE and 2.3-develop
2. Installed & configured Elasticsearch 6.5 

### Steps to reproduce (*)
1. Choose category with products and set 1 column design to it (Catalog -> Categories -> Edit Category -> Design -> Layout -> "1 column"
2. Save category
3. Flush cache
4. Open this category on website and change sort order to "Price"
5. Go to page 2

### Expected result (*)
1. Products will be sorted by price

### Actual result (*)
**On 2.3.2:**
1. Products is sorted the same way they was sorted before

**On 2.3-develop** (with https://github.com/magento/magento2/commit/23b0061e057e482b1b0347b763b35125a6ed0c37):
1. Products is showing correctly on page 1 (right sort order used) but there is no products at page 2:

![image](
https://user-images.githubusercontent.com/1873745/65044546-bdc15880-d965-11e9-9078-074414e8ba99.png)

**Comment by ihor-sviziev** [comment]
Similar issue we had with MySQL search long time ago in https://github.com/magento/magento2/issues/12860.

@engcom-Alfa could you verify this issue?

**Comment by engcom-Charlie** [comment]
Hello @alexeya-ven .
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**

1. Enable Elasticsearch 6
2. Choose category with products and set 1 column design to it (Catalog -> Categories -> Edit Category -> Design -> Layout -> "1 column"
3. Save category
4. Flush cache
5. Open this category on website and change sort order to "Price"

**Actual result:**
Sort by price works fine:
![image](https://user-images.githubusercontent.com/51680850/65020840-a1f28e00-d936-11e9-9ea0-3171834adbee.png)

Could you reproduce this issue on Magento 2.3-develop?

**Comment by arendarenko** [comment]
Hi @engcom-Charlie,
You're right! Looks like this issue was fixed in https://github.com/magento/magento2/commit/23b0061e057e482b1b0347b763b35125a6ed0c37
BUT it introduced another issue - on 2nd page and higher - no products.
Just checked on 2.3-deveop + sample data.
![image](
https://user-images.githubusercontent.com/1873745/65044546-bdc15880-d965-11e9-9078-074414e8ba99.png)

I've updated issue description.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20203` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jorgb90** [comment]
I got this same problem but with all layouts, so not only 1 column layout.. Only first page show products with Elasticsearch!

@arendarenko I am using Magento 2.3.3 have any way to fix it?

Edit: Fixed my problem with the available Magento 2.3.3 patch. Should have looked for one first..

**Comment by ArthurSCD** [comment]
On Magento 2.3.2, encountered this issue and more - pagination was missing completely. 

On Magento 2.3.3, issue remains, even after the patch has been applied. Not only that, category sorting does not work at all, both with the sort and the category ordering set in the backend.

**Comment by ArthurSCD** [comment]
I can confirm that even with the patch in #25107 on Vanilla sample data 2.3.3, issue remains on ONE COLUMN layout. Note that it seems to work fine if the category is accessed through Layered Navigation. 


![ss (2019-10-22 at 03 36 20)](https://user-images.githubusercontent.com/13160340/67330892-a9cbc200-f4e2-11e9-8d2c-d36abf5ee8c3.png)

Surprisingly sorting does seem to work 1 column, Elasticsearch, 2.3.3 Vanilla instance, although it certainly does not for the site I encountered the issues. Should note that changing to MYSQL from Elastic immediately resolves all issues. 2.3.1 is also fine, but I had just checked the elasticsearch module to see quite a bit was reworked in 2.3.2. Completely new files etc.

**Comment by engcom-Kilo** [comment]
Hello @arendarenko 
I'm not able to reproduce this issue on latest 2.4-develop
![OneCulumnLayoutUpdate](https://user-images.githubusercontent.com/60192090/101168313-f0776f80-3643-11eb-8c9f-654172214c9e.gif)
Could you please add more details, or correct steps I did?

**Comment by magento-engcom-team** [comment]
Hi @arendarenko. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24209` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.

**Comment by magento-engcom-team** [comment]
Hi @arendarenko. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24209` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.
