### ISSUE TITLE
Store Switcher not working when customer is logged in - Magento 2.3.3

### ISSUE THREAD

**Issue by joris-ati4** [magento/magento2#24942]
### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Create at least 2 store views in Magento. 
2. Create a customer account
3. Go to a page on your shop and change the store with the store switcher while being logged in with the customer account.

### Expected result (*)

1. You a redirected to the same page of the other storeview

### Actual result (*)

1. The user is redirected to a 404 page because only the store code is changed in the URL. 

### Solution
I did some digging and found out that the bug is coming from the way the StoreSwitcher is currently implemented. For the moment the code is the following: 

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/code/Magento/Store/Model/StoreSwitcher.php#L48-L57

The elements and their position in the `$this->storeSwitchers` array is the following: 
* cleanTargetUrl
* manageStoreCookie
* managePrivateContent
* hashGenerator
* rewriteUrl

The problem is that the rewriteUrl Switcher has to receive the target url with the changed store code in order to find the equivalent url for the page on the other store. The problem is that when a customer is connected, the hashGenerator generates a url for the switchRequest and this url is then passed onto the rewriteUrl switcher. Because of that, the rewriteUrl switcher cannot find the equivalent Url and the user is redirected to a non existing url.

Their are 2 solutions for this problem: 

1. Change the position of the elements in the `$this->storeSwitchers` array in order to assure that the hashGenerator always is the last switcher to be applied.
2. Rewrite the switch method of the rewriteUrl switcher in order to be able to change the encoded url in the switchRequest. 

I think the first one would be the easiest to apply but I am wondering if this could add other bugs to the storeSwitcher.

Let me know which solution would be more appropriate and I will open a PR for this issue.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24942-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24942-2-3-develop.instances.magento-community.engineering/admin](https://i-24942-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @jojotjebaby 
thank you for reporting this issue .. I tried reproducing the issue on magento 2.3-develop instance but It seems that works fine .. can you please specify from which page you are changing store or store view ? also please share url and screenshot if you are able to reproduce it on 2.3-develop instance

**Comment by joris-ati4** [comment]
Hello @shikhamis11 , 

Thank you for testing out on the 2.3-develop instance. I am switching between 2 category pages on the store.

I also did some tests on the 2.3-develop instance but for the moment it seems to be working fine. This is because there is a difference between 2.3-develop and 2.3.3 for the di.xml file of the store module. 

2.3.3: 

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/code/Magento/Store/etc/di.xml#L433-L442

2.3-develop: 

https://github.com/magento/magento2/blob/68c48d55231de6849195e090e2b3ce750db61825/app/code/Magento/Store/etc/di.xml#L433-L441

It seems that the hash generator has been deleted from the arguments. Do you know the PR that is responsible for this change ? 

Thank you !

**Comment by joris-ati4** [comment]
Here is the commit that added this code to the 2.3.3 tag: https://github.com/magento/magento2/commit/fe7fbce272c0c0fdd06b7eaadede0bd18cfe8212

In order to prevent this bug on 2.3.3, you need to revert the `magento2/app/code/Magento/Store/etc/di.xml`  back to this: 

https://github.com/magento/magento2/blob/68c48d55231de6849195e090e2b3ce750db61825/app/code/Magento/Store/etc/di.xml#L433-L441

Once the following line is deleted, the store swticher works for logged in customers.
```
<item name="hashGenerator" xsi:type="object">Magento\Store\Model\StoreSwitcher\HashGenerator</item> 
```

**Comment by shikhamis11** [comment]
hello @jojotjebaby 
I checked on 2.3.3 there this issue was able to reproduced .. but it seems it is already fixed in magento 2.3-develop instance

**Comment by p-bystritsky** [comment]
@shikhamis11 this bug was introduced in 2.3.3 and will appear in 2.3-dev after merging 2.3.3 with 2.3-dev.

**Comment by joris-ati4** [comment]
> hello @jojotjebaby
> I checked on 2.3.3 there this issue was able to reproduced .. but it seems it is already fixed in magento 2.3-develop instance

I opened another issue but it seems that 2.3.3 hasn't been merged into 2.3-dev yet. So we have to wait for this merge before I can provide a PR ....

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21767` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by joris-ati4** [comment]
@shikhamis11 , are you currently working on this issue ? I would be okay to work on this issue but I would like to know which solution to do: 

1. Change the position of the elements in the $this->storeSwitchers array in order to assure that the hashGenerator always is the last switcher to be applied.

2. Rewrite the switch method of the rewriteUrl switcher in order to be able to change the encoded url in the switchRequest.

Please let me know and I will submit a PR

**Comment by tr46** [comment]
Store switching never works when you have multiple domain.tld store views.

**Comment by gtlt** [comment]
> Store switching never works when you have multiple domain.tld store views.

In magento 2.3.2, for views in subdomains I was able to circumvent the issue by adding domain to cookies : https://github.com/magento/magento2/issues/22966#issuecomment-494948104, maybe it can works in multiple domain.tld ?
Magento store switch is awfully crap, each update gives another issue... with 2.3.3 I can't have a proper working switch. It's like nothing is tested when they release a new version.

**Comment by magento-engcom-team** [comment]
Hi @jhart-efaktory. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-21767` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by hostep** [comment]
What's the status of this ticket? We're also seeing this after upgrading a shop from Magento 2.1.16 to 2.3.3.
If it was fixed on `2.3-develop`/`2.4-develop`, does somebody have a commit which points to the fix? Thanks!

**Comment by TimQSO** [comment]
I can confirm we are having this issue too on 2.3.3 (we upgraded from 2.2.7). This ticket should be reopened.

**Comment by TheLaughingThird** [comment]
updated 2.3.2 to 2.3.3. and sadly we are experiencing this issue on 2.3.3 too

**Comment by TimQSO** [comment]
@magento-engcom-team this ticket should be reopened.

**Comment by hostep** [comment]
@GuiltyNL: we should first test if this is still an issue on the `2.4-develop` branch. It [was reported](https://github.com/magento/magento2/issues/24942#issuecomment-561359666) as not being reproducible on `2.3-develop` (which became `2.4-develop` some days ago). It might mean that a fix is already there.
If a fix is already there, it would be nice if somebody could try to figure out where it is (by reading git logs or doing some git bisect testing for example).
Only if the issue still exists on `2.4-develop`, we should re-open the ticket.

**Comment by hostep** [comment]
Alrighty, for the people searching after the fix, I took a couple of hours today to go searching for it and after a bunch of bisecting attempts I finally found the fix over here: https://github.com/magento/magento2/commit/f19c780fb7e31db89bfd9965e177d52ad03dacd7

Adding the `sortOrder="1000"` to that `hashGenerator` item fixes the problem in Magento 2.3.3!

**Comment by mattijv** [comment]
Just a heads up for future readers, this problem also affects the 2.3.2-p2 version.

**Comment by TheLaughingThird** [comment]
I have applied changes that hostep brings to our attention, we are running on 2.3.3 and experienced this problem after update from 2.2.2 and now these two files replaced and we deployed it... It seems solved so big thanks !

Have to say that you will need to flush your internet history cache + cookies to see it working.
Thank you @hostep

**Comment by palviggi-flagbit** [comment]
Applying the sortOrder fixed it for other stores (we have 5), but it fails when going back to the first store (where i logged in), so something else must be missing

**Comment by dyuk1987** [comment]
I'm having the same problems when I upgraded the Magento from 2.2.7 to 2.2.10

**Comment by palviggi-flagbit** [comment]
We updated our store to 2.3.4, the problem persists when changing back to the store where the user is logged in

**Comment by GuiltyNL** [comment]
But did you apply the fix?

**Comment by palviggi-flagbit** [comment]
I started debugging the problem, since it's still happening on 2.3.4. 
The proposed patch only removes the processor from the request flow, but that's only working on the symptoms.
After StoreSwitcher/HashGenerator adds some parameters to validate the redirection, and send the redirect, magento process the redirect request and creates a new redirect (still don't know why). But this second redirect is processed by the plugin \Magento\Store\App\FrontController\Plugin\RequestPreprocessor, that removes all query parameters. So when the new request gets to the hash validator, it doesn't have any query parameter to check.

I created a small plugin that adds back the missing parameters (but only in case the signature parameter is set) and now everything works fine. Of course it would be better to fix the existing plugin instead of adding yet another on the critical path.

**Comment by bharat1811** [comment]
> I started debugging the problem, since it's still happening on 2.3.4.
> The proposed patch only removes the processor from the request flow, but that's only working on the symptoms.
> After StoreSwitcher/HashGenerator adds some parameters to validate the redirection, and send the redirect, magento process the redirect request and creates a new redirect (still don't know why). But this second redirect is processed by the plugin \Magento\Store\App\FrontController\Plugin\RequestPreprocessor, that removes all query parameters. So when the new request gets to the hash validator, it doesn't have any query parameter to check.
> 
> I created a small plugin that adds back the missing parameters (but only in case the signature parameter is set) and now everything works fine. Of course it would be better to fix the existing plugin instead of adding yet another on the critical path.

I am also facing issue after upgrade such after login store switcher action goes to 404. So, can you please share that changes you made or guide me.

**Comment by palviggi-flagbit** [comment]
@bharat1811 in the end it didn't made much difference, so I just left in the patch that removes the HashGenerator class from module-store/etc/di.xml at the end.

When I have time this week I'll create a patch with my debug changes in case someone wants to test it further

**Comment by behrang1981** [comment]
since this is not a small bug invisible but affects customers any hint for fixing temporarily on 2.3.4 would be appreciated. removing the entry in the di.xml is obviously not one working for at least 2.3.4

**Comment by exdiogene** [comment]
I had the same exact issue with my recent plain installation of Magento 2.3.4, after any login you received a 404 page because the URL was wrong.

Magento is installed in the directory "magento2" over my root domain, I temporarily corrected the issue with a redirection in root .htaccess to the proper directory because it previously was redirecting to the root.

Previous behavior after changing store view "disconnected" :
https://MyRootDomain.ca/magento2/stores/store/redirect/___store/english/___from_store/francais/uenc/aHR0cHM6Ly9lbnRyZXIuY2EvbWFnZW50bzIvP19fX3N0b3JlPWVuZ2xpc2g%2C/

Previous behavior after changing store view "connected" :
https://MyRootDomain.ca/stores/store/switchrequest?customer_id=1&time_stamp=1588353257&signature=3d79e953ea42942fd4c9b200fa36eb93659a2fc3fb0b83ec9c73c2e3b685f871&___from_store=english&uenc=aHR0cHM6Ly9lbnRyZXIuY2EvbWFnZW50bzIv

.htaccess file modification in root directory :
`RewriteRule ^stores/(.*)$ /magento2/stores/$1 [R=302,NC,L]`

Now anyone can change the language store view even logged!

Meantime I am waiting for the proper corrections to the code...

**Comment by Axel29** [comment]
HI,

I'm having the same issue on a Magento 2.3.4 website with the following process:

* Multi store instance
* Enable Varnish full page cache
* Create a category and translate it's URL key in the second store
* Go to a category page in store A
* Use the store switcher to go to the store B => redirection is okay
* Use the store switcher to go back to the store A again => redirection triggers a 404 because the store is switched but the URL key remains as store B's URL Key.

Anyone found a fix that can be applied?

Thank you.

**Comment by AndresSB2018** [comment]
how can I override the di.xml file in my presonalized module to comment out the line that is generating the error ?

**Comment by erikhansen** [comment]
@AndresSB2018 I'd recommend using `composer-patches` to apply patches. Details here: https://gist.github.com/erikhansen/1b18980b39464dc94b9f09282a43ea31

**Comment by erikhansen** [comment]
Has anyone found a solution to this issue for Magento 2.3.5-p2? We just launched a Spanish version of xchair.com and are running into this. Steps to reproduce:

1. Go to xchair.com and use the top-left dropdown to switch to "Spanish"
2. Go to https://www.xchair.com/es/x3build.html
3. In the dropdown, switch back to "English" and you'll be redirected to https://www.xchair.com/, as expected
4. Now, use the dropdown to try to switch to "Spanish"

You will not get redirected to https://www.xchair.com/es/, but will instead stay on https://www.xchair.com/

I tried adding `sortOrder="1000"` to this line:

```
<item name="hashGenerator" xsi:type="object">Magento\Store\Model\StoreSwitcher\HashGenerator</item>
```

I also tried deleting that line entirely. Neither of those things seemed to have fixed the problem. Any other suggestions for me?
