### ISSUE TITLE
Wrong price indexed for configurable/composite products

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#24953]
### Preconditions (*)
magento 2.3

1.
2.

### Steps to reproduce (*)

1. Edit `price` or `special_price` on configurable product from mass action grid or saving attribute via resource model `$this->productResource->saveAttribute($product, 'price');`  or 
`$this->productResource->saveAttribute($product, 'special_price');` 
2. Run reindex from cron (mb. CLI reindex as well)
3. See the price from attributes appeared on product grid 
4. See the price from attributes in columns `price` and `final_price` in the table `catalog_product_index_price`
5. Then save configurable product from admin edit page
6. See `null`  value saved for price attribute in `catalog_product_entity_decimal`
7. Wait for price reindex from cron (mb. CLI reindex as well)
8. Repeat step 4 and see `0` saved in columns `price` and `final_price` for edited configurable product

to find prices saved for configurable product use this SQL

```
SELECT decimal2.*
FROM catalog_product_entity
       inner join catalog_product_entity_decimal decimal2 on catalog_product_entity.entity_id = decimal2.entity_id and
                                                             attribute_id in (SELECT attribute_id
                                                                              from eav_attribute
                                                                              where attribute_code in
                                                                                    ('price', 'special_price'))
where type_id = 'configurable';
```

### Expected result (*)

1. Price never saved for a configurable product in `catalog_product_entity_decimal` table from any save point e.g. `resource model`, `repository`
2. Price indexed correctly in `catalog_product_index_price` (data for composite products should be calculated based on child products) e.g. final_price = min_price, price = max_price attribute values from `catalog_product_entity_decimal` should be ignored

### Actual result (*)

1. Still possible to save `price` and `special_price` for configurable/composite product in `catalog_product_entity_decimal` table
2. Wrong calculation of columns `price` and `final_price` in the `catalog_product_index_price` table

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22859` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ravi-chandra3197** [comment]
I have found a similar issue for configurable product price indexing witch fixed by this PR  #24962

**Comment by vishal-7037** [comment]
@ilnytskyi Hi,

I've faced the same issue after data migration. After data migration performed successfully, I've run `php bin/magento indexer:reindex` command. I've noticed that `min_price` saved as a negative value in `catalog_product_index_price` table and not indexed properly.

During the tracing process, I noticed that in `catalog_product_entity_decimal` table, price exists for a **configurable product** which occurs this issue during indexing.

I've applied below solution, and the issue has been fixed for me.

### Quick Fix:
**Please run below query:** (**Please update attribute_id = 75 with your price attribute's attribute_id**)

```UPDATE catalog_product_entity e INNER JOIN catalog_product_entity_decimal d ON (e.entity_id = d.entity_id AND e.type_id = 'configurable' AND d.attribute_id = 75 AND d.value IS NOT NULL) SET d.value = NULL```

And then, run indexer command again `php bin/magento indexer:reindex`.

Hopefully, Issue has solved by this solution.

**Comment by ihor-sviziev** [comment]
Seems like it's the same issue as described in #24535 #15609 and #14443.

**Comment by igor518** [comment]
This issue is still actual for Magento 2.4.8. It is also possible to create a simple product with the "Special Price" and than by adding  a new configurations to the product the product will be converted to the configurable product and you can't see the special price in the admin panel anymore but the price is present for the configurable product and it take part in an indexation process. I believe that the "Special Price" should not be present for the configurable product. Why just not to add an observer to the catalog_product_save_before event for example and not check the product type and presents of the "Special Price" and if it exist just remove it ? Correct me if I am wrong.

**Comment by engcom-Hotel** [comment]
Hello @igor518,

We have tried to reproduce this issue in the latest development branch i.e. 2.4-develop but the issue is not reproducible for us. We request you kindly create a screencast to demonstrate the issue, it will help us in issue reproduction.

Thanks

**Comment by IbrahimS2** [comment]
@engcom-Hotel The steps to reproduce are straightforward:

1. Create a simple product and give it a special price.
3. Convert that product into a configurable product by adding customizable options.
5. Assign separate special prices to each variant.

When an item is added to the cart, Magento uses the special price of the configurable parent instead of the variant-specific special price.

I created this ad-hoc script to remove configurable products' special prices, as it caused great damage to some store owners, who lost tens of thousands of dollars in less than a day.

[`https://gist.github.com/IbrahimS2/c58f4140ea496970f2dcf42ce5333473`](https://gist.github.com/IbrahimS2/c58f4140ea496970f2dcf42ce5333473)

**Comment by igor518** [comment]
Thanks @IbrahimS2  this what I was saying above. The use case is reproducible by the steps.
