### ISSUE TITLE
Marketing Email preview doesn't work with enabled js minification

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#25068]
### Preconditions (*)
1. Magento 2.3.2-p2, Magento 2.3.3, Magento 2.3-devlop
2. Enable JS minification in Admin >> Stores >> Configuration >> JavaScript Settings >> "Minify JavaScript Files" set to "Yes"
3. Switch magento to production mode

### Steps to reproduce (*)
1. Go to Admin >> Marketing >> Communications >> Email Templates
2. Click "Add New Template"
3. Select "New Order" template
4. Click "load template" button
5. Fill up "Template Name" with "New Order"
6. Click "Save  Template" button
7. In the email templates grid click on "Preview" link in "Actions" column

### Expected result (*)
1. You should see email template preview in opened popup
2. There should not be any JS errors

### Actual result (*)
1. Email Preview popup is empty
![image](https://user-images.githubusercontent.com/1873745/67681304-bd20d680-f995-11e9-8caf-f00b72287d9a.png)
2. We have JS error
![image](https://user-images.githubusercontent.com/1873745/67681891-e1c97e00-f996-11e9-815a-46fad6e3de4d.png)

> Failed to load resource: the server responded with a status of 404 ()
> Uncaught Error: Script error for: jquery

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25068-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25068-2-3-develop.instances.magento-community.engineering/admin](https://i-25068-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hello @ihor-sviziev 
thank you for reporting this issue , I checked it on 2.3-develop instance email template preview works fine  , there are some errors on console but those are related to CORS . 
Can you Please take a look ?

**Comment by ihor-sviziev** [comment]
@shikhamis11,
I see that changed from 2.3.3 and 2.3.2-p2 wasn't merged to 2.3-develop branch, so it will appear once it will be merged. As for now - you could try to reproduce it in 2.3.3.

Just check files contents:
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Email/view/adminhtml/templates/preview/iframeswitcher.phtml
- https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Email/view/adminhtml/templates/preview/iframeswitcher.phtml
- https://github.com/magento/magento2/blob/2.3.2-p2/app/code/Magento/Email/view/adminhtml/templates/preview/iframeswitcher.phtml

**Comment by ihor-sviziev** [comment]
Hi @shikhamis11,
Now 2.3.3 release was merged, could you double check it again?

**Comment by ihor-sviziev** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ihor-sviziev** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-25068-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25068-2-3-develop.instances.magento-community.engineering/admin](https://i-25068-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
@shikhamis11 just updated steps to reproduce, we have to have production mode, while on test instance we don't have production mode :(

**Comment by shikhamis11** [comment]
Hello @ihor-sviziev you can have production mode in test instance 
Just add pub/testing in instance url

**Comment by ihor-sviziev** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ihor-sviziev** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-25068-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25068-2-3-develop.instances.magento-community.engineering/admin](https://i-25068-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
I was able to reproduce this issue on test instance.

Just updated issue description with exact steps to reproduce and screenshots of actual result.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22163` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by LucasCalazans** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans, here is your [Magento instance](https://i-25068-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25068-2-3-develop.instances.magento-community.engineering/admin](https://i-25068-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by arnobsh** [comment]
Internal Magento team is working on this issue right now

**Comment by arnoudhgz** [comment]
The issue is, that somehow `jquery.js` is requested while `jquery.min.js` should be loaded. A **workaround** until the actual solution is found is to create a symlink named `jquery.js` that points to `jquery.min.js` in `pub/static/versionxxx/adminhtml/Magento/backend/en_US`. 

Of course replace **versionxxx** and **en_US** to your appropriate paths, versionxxx is only needed when static signing enabled.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, @arnobsh. 

Thank you for your report and collaboration!

The issue was fixed by Magento team.

**Comment by arnoudhgz** [comment]
@magento-engcom-team where is the fix?

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, @arnobsh. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [30cdbd21cc368263de5cb6259c158c6a60bc63a6](https://github.com/magento/magento2/commit/30cdbd21cc368263de5cb6259c158c6a60bc63a6)

The fix will be available with the upcoming `2.3.5` release.

**Comment by AlexanderSk** [comment]
hello guys, i just faced this issue one 2.3.3 and searched for this ticket and that it hopefully will be fine on 2.3.5.

i would only like to note that i did try to copy paste the jsuery.min.js to jquery.js and i get an error: Uncaught SyntaxError: Unexpected end of input for jquery.js

the actual file is this one if you would like to have a look.
https://tyanabelle.com/pub/static/version1576220203/adminhtml/Magento/backend/en_US/jquery.js

Thank you for your time and effort.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, @arnobsh. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [e8eb43a84cb861cedda424aaf8be83aa1c6c1c29](https://github.com/magento/magento2/commit/e8eb43a84cb861cedda424aaf8be83aa1c6c1c29)

The fix will be available with the upcoming `2.4.0` release.

**Comment by linardskrumins** [comment]
Hey @magento-engcom-team 

Were these commits deleted? The commit page for both commits is not found

**Comment by ihor-sviziev** [comment]
@linardskrumins now this link available https://github.com/magento/magento2/commit/e8eb43a84cb861cedda424aaf8be83aa1c6c1c29

**Comment by adarshkhatri** [comment]
Still happening in 2.3.3-p1. The system is looking for `jquery.js` instead of `jquery.min.js`.

**Comment by Eddcapone** [comment]
Does not work in 2.4.2 Enterprise. I get "Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set."

![image](https://user-images.githubusercontent.com/16349349/112817610-ebbb4900-9082-11eb-9e1f-4dd107ac4894.png)

**Comment by ihor-sviziev** [comment]
@Eddcapone, it looks like a bit different issue. Could you report it separately?
Thank you!
