### ISSUE TITLE
Unable to place a guest order with PayPal Express when Enable Automatic Assignment to Customer Group is enabled

### ISSUE THREAD

**Issue by xylodev** [magento/magento2#25399]
### Preconditions (*)

1. Magento 2.4-develop
2. PayPal Express payment method is enabled and configured
3. Option "Enable Automatic Assignment to Customer Group" is set to "Yes" in the Customers > Customer configuration settings section

### Steps to reproduce (*)
1. Make sure you are logged off from your Magento customer account
2. Put anything to the cart
3. Go to the cart and click "Checkout with PayPal" button
4. Login to your PayPal account, choose the payment instrument and other options if applicable
5. After being redirected back to the order review page, choose shipping method and click "Place order" button

### Expected result (*)
The payment is processed on PayPal gateway, the order is created in Magento, customer sees order thank-you page

### Actual result (*)
The payment is processed succesfully on PayPal gateway, but the order is not created in Magento because of "Failed address validation: %1" error, which is shown to the customer on the order review page, which the buyer is redirected to instead of the thank-you page

![paypal_place_order_error](https://user-images.githubusercontent.com/6035963/67939241-6acbf980-fbd1-11e9-97bb-c71f41803287.png)

**Comment by xylodev** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @xylodev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @xylodev, here is your [Magento instance](https://i-25399-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25399-2-3-develop.instances.magento-community.engineering/admin](https://i-25399-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by xylodev** [comment]
Reproduced on 2.3.x

<img width="1266" alt="paypal_error_on_magento_test_instance" src="https://user-images.githubusercontent.com/6035963/67940241-96e87a00-fbd3-11e9-84fd-b4929a631af0.png">

**Comment by webkul-ratnesh** [comment]
Not able to replicate this issue, I think the issue you are facing is with the address saved in your paypal account.

**Comment by xylodev** [comment]
@webkul-ratnesh thanks for your insights, but I cannot agree that it's related to the Paypal account address. It's actually a huge issue for one of our shops, it's not possible to place a guest order with PayPal, I was also able to reproduce it on vanilla Magento 2.3-develop instance with different PayPal accounts.

Did you follow all the steps carefully? Especially, were you logged off from your Magento customer account, did you use the PayPal button in the cart (please note, this issue is not valid when choosing PayPal Express in the checkout's payment methods step), did you enable "Automatic Assignment to Customer Group"? I'd love to see how you're completing the checkout following all the steps described.

Please check it once again, because I identified the root cause and have even a solution ready. The e-mail address is wiped out during the automatic group assignment, so it doesn't pass the final validation and the order creation fails.

**Comment by askmikeyd** [comment]
I was having the same issue and I don't think the proposed solution is the way to go. This only solves it for Paypal but this issue exists when using other payment methods as a guest. A better solution needs to be done in the Magento Core. My fix for it was to set "Enable Automatic Assignment to Customer Group" to "Yes" at the website level as that is where my customer is created and set it to "No" at the store level which is what is checked when placing a guest order.

**Comment by TonyRutherford1** [comment]
Any update here?

**Comment by ryanpalmerweb** [comment]
Just to confirm we have had the same issue, manifesting as the following error appearing in the checkout

>  Failed address validation: Email has a wrong format 

This was triggered by clicking the payment button in the checkout, which caused a 400 API response from the following endpoint

> rest/default/V1/guest-carts/{{cartId}}/payment-information

The $address object in vendor/magento/module-sales/Model/Order/Address/Validator.php in the validate function was the type "shipping" and appears to contain all of the address info except for the email, which triggers the above.

**Comment by franconicolasocchi** [comment]
Same here, disabling Assignment to Customer Group solve the issue.
Is someone working with that? @magento-engcom-team it have assigned enough priority?

**Comment by magento-engcom-team** [comment]
Hi @xylodev. Thank you for your report. 
The issue has been fixed in magento/magento2#25405 by @xylodev in 2.4-develop branch
Related commit(s):
 - [594fc93cdc92ca5648564718ce7a079d6afabdd8](https://github.com/magento/magento2/commit/594fc93cdc92ca5648564718ce7a079d6afabdd8)
 - [fb299a0beeab3d3949b83f86495e88b52898a90c](https://github.com/magento/magento2/commit/fb299a0beeab3d3949b83f86495e88b52898a90c)
 - [f898245488e4f199caae7e23f5b05433d0ff346e](https://github.com/magento/magento2/commit/f898245488e4f199caae7e23f5b05433d0ff346e)
 - [7f280cd1421318fe0e18a55f324a8c029d3178c4](https://github.com/magento/magento2/commit/7f280cd1421318fe0e18a55f324a8c029d3178c4)

The fix will be available with the upcoming 2.4.2 release.

**Comment by shoaibgits** [comment]
I am Having the same issue with Magento 2.3.6, when the Automatic Customer Group Assignment is Set to YES and trying checkout with the Paypal Express Checkout.

I cant disable the Customer Group Assignment because i need this for the Some VAT validation process, So how to resolve this with the current setup.

**Comment by shoaibgits** [comment]
For the Older Version I have created a patch to fix this issue please refer to this [Repository](https://github.com/shoaibgits/paypaexpress-patch ):

**Comment by kamzata** [comment]
Still present for **downloadable products** on Magento 2.4.7-p1.
