### ISSUE TITLE
i18n:collect-phrases -m can't find many important magento phrases

### ISSUE THREAD

**Issue by kkkonrad** [magento/magento2#2630]
looks like it can't find:

Order Summary
Review & Payments
Go to Wish List
View and edit cart
You can create an account after checkout

and other checkout phrases so frontend translation is imposible

**Comment by scholtz** [comment]
the same here.. we have translated everything from collected phrases to slovak language (https://connect20.aveo-trade.cz/cat:BuyPackage/details=1/extension=atconnect%2Fmagento2-language-sk_sk ) live preview is here: http://mag2-test.aveo-trade.cz/ and quite many phrases are not translated..

**Comment by scholtz** [comment]
Hi, i did not look it up yet properly, but it seems that also some of the translated texts are not put to the production.. 

For example "PDF Invoices" translated as "PDF Faktúry" (module,Magento_Sales) is shown in the administration as "PDF Invoices".

But many texts does not even collect.. for example from \vendor\magento\module-ui\view\base\web\templates\grid\actions.html it does not collect text "Select Items"

**Comment by jvanderbiest** [comment]
any update on this issue?

**Comment by scholtz** [comment]
i suggest someone should set this issue the highest priority because if M2 is not translated correctly to any language it is completly useless in every language beside English.. I dont understand how this could be released as official! :(

**Comment by mazhalai** [comment]
We are working on a fix. Ticket: MAGETWO-47439

**Comment by piotrekkaminski** [comment]
Related issue - please use MAGETWO-43958 to test. cc @mazhalai

**Comment by wanpower** [comment]
It could be a hard-to-fix issue, currently i18n:collect-phrases only extract phrases from given token with the i18n format __('phrase') for php/phtml files, and translate="true" for xml files.
This works well for the most cases, but when the target phrase was not listed in any file with the specific syntax, it will be missed by the command.
A workaround is to maintain an appendix dictionary and execute i18n:pack again in merge mode. Thanks for the fallback mechanism it won't require you to put the phrase in a proper module, so just use any module you like to keep the syntax acceptable. I just use "module,Magento_Backend" since it is coincidence the first one I started.
PS: Override the __ function to output all possible phrases and then do a full test you will get all phrases; subtract the existing ones you get with i18n:collect-phrases, then you will get all missing text quickly.

**Comment by thomvanderboon** [comment]
@scholtz 

After installing the language pack did you run the following commands?

 php bin/magento setup:static-content:deploy
 php bin/magento setup:static-content:deploy nl_NL <-- change to your own locale
 php bin/magento indexer:reindex
 php bin/magento cache:clean
 php bin/magento cache:flush

I also run the above commands in a nightly cron

here is my "how to" so far: http://www.vanderboon.net/wiki/Install_Test_Magento_2_Translation 

I am running into a new problem.... Static text are show in the correct language, by dynamic are not. Will open new issue for this.

**Comment by okorshenko** [comment]
@kkkonrad , in the scope of https://github.com/magento/magento2/commit/352bd0c90cc74a7f30649cba9724ce9b0c633b79 we have added processing of Javascript template files that fixes your initial case. Please, checkout latest version from develop branch

**Comment by kkkonrad** [comment]
looks like it works but i can't translate now header step names in checkout:
-Shipping 
-Review & Payments  
in backend there are problem with grid phrases:
-search by keyword
-select items
-records found
-filtes
-columns 
itp

can yo check this?

**Comment by thomvanderboon** [comment]
Is there a way to get in what module a certain string should be located?

I located for instance the "Review & Payments" text in the source code, but I can't get it translated. 

I tried the following codes in my csv... but nothing is working

"Review & Payments","Controle en betalen",module,Magento_Payment
"Review & Payments","Bekijk en betalen",module,Magento_CheckOut
"Review & Payments","Bekijk en betalen",module,Magento_Sales
"Review & Payments","Bekijk en betalen",module,Magento_Customer

Any idea's?

**Comment by scholtz** [comment]
Hi, we have translated whole magento2 already to three languages: [DE](https://connect20.aveo-trade.cz/cat:BuyPackage/details=1/extension=atconnect%2Fmagento2-language-de_de), [TR](https://connect20.aveo-trade.cz/cat:BuyPackage/details=1/extension=atconnect%2Fmagento2-language-tr_tr), [SK](https://connect20.aveo-trade.cz/cat:BuyPackage/details=1/extension=atconnect%2Fmagento2-language-sk_sk)

we release it as composer package, and i believe there should be no special need for this code to run: 
```
php bin/magento setup:static-content:deploy
php bin/magento setup:static-content:deploy nl_NL <-- change to your own locale
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```
Our packages are the zip file with for example this content:
magento-two-language-de-de\composer.json
```json
{
    "name": "atconnect/magento-two-language-de-de",
    "description": "Magento 2.0.0: de_DE",
	"version": "2.0.0.2-stable",
    "license": [
        "proprietary"
    ],
    "type": "magento2-language",
	"autoload": {
        "files": [
            "registration.php"
        ]
    }
}
```
magento-two-language-de-de\language.xml
```xml
<?xml version="1.0"?>
<!--
/**
 * @copyright Copyright (c) AveoTrade
 Licence: https://connect20.aveo-trade.cz/cat:Agreement
 */
-->
<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/Language/package.xsd">
    <code>de_DE</code>
    <vendor>atconnect</vendor>
    <package>magento-two-language-de-de</package>
</language>
```

magento-two-language-de-de\registration.php
```php
<?php
/**
 * Copyright © 2015 AveoTrade
 */
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::LANGUAGE,
    'atconnect_magento-two-language-de-de',
    __DIR__
);
```
magento-two-language-de-de\de_DE.csv
```csv
"1 Hour","1 Stunde",module,Magento_AdminNotification
"12 Hours","12 Stunden",module,Magento_AdminNotification
"2 Hours","2 Stunden",module,Magento_AdminNotification
"24 Hours","24 Stunden",module,Magento_AdminNotification
"6 Hours","6 Stunden",module,Magento_AdminNotification
```

You can see demo here: 

http://mag2-test3.aveo-trade.cz

In Slovak language we have already ported to version 2.0.1, but still many things are missing..

![not-translated-01](https://cloud.githubusercontent.com/assets/1223439/12481202/d11a72da-c047-11e5-9503-0c31b62c1b67.png)
![not-translated-02](https://cloud.githubusercontent.com/assets/1223439/12481204/d11b4520-c047-11e5-9f5b-7b3d5170ba3e.png)
![not-translated-03](https://cloud.githubusercontent.com/assets/1223439/12481203/d11a904e-c047-11e5-9d5b-58da26b78570.png)
![not-translated-04](https://cloud.githubusercontent.com/assets/1223439/12481205/d11f3144-c047-11e5-81f5-a8f413c97f71.png)

**Comment by scholtz** [comment]
Also it would be cool if there was some tool to export the product names, descriptions, cms pages and so on for the translation. We would like to provide for example translation services for eshops, so that they have localised content, but right now i dont know how to export these texts, and import them using composer...

**Comment by okorshenko** [comment]
@kkkonrad, thank you for reporting the issue. We have added support of javascript translations  and improved coverage for menu and ACL configuration. (please, see related commits)

Please, let us know if we resolved your initial use-case and we can close this issue.
Thank you!

**Comment by thomvanderboon** [comment]
I am currently testing the development branche concerning this issue. It looks like >99% of the problems have been solved.

I only found one problem so far:

the following strings are not dumped to the file to be translated from app\code\Magento\Catalog\view\frontend\web\js\catalog-add-to-cart.js 

```
        addToCartButtonTextWhileAdding: $t('Adding...'),
        addToCartButtonTextAdded: $t('Added'),
        addToCartButtonTextDefault: $t('Add to Cart')
```

**Comment by thomvanderboon** [comment]
Further testing: Step 2 of the Checkout proces still displays "Review & Payments". 

The bin/magento i18n:collect-phrases command does not dump this text to the source file. If the translation is present, text is not translated

**Comment by thomvanderboon** [comment]
Updated the development branche moments ago and the "Review & Payments" text is correctly translated now

**Comment by Krapulat** [comment]
The problem appears in Magento 2.0.4. When this fixes will be included?

**Comment by jrm93** [comment]
We are working on the Dutch translation. This problem is still existing and a sample can be found in /vendor/magento/module-customer/etc/adminhtml/menu.xml . In this file you can find the following line:

```
<add id="Magento_Customer::customer_manage" title="All Customers" module="Magento_Customer" sortOrder="10" parent="Magento_Customer::customer" action="customer/index/" resource="Magento_Customer::manage"/>
<add id="Magento_Customer::customer_online" title="Now Online" module="Magento_Customer" sortOrder="30" parent="Magento_Customer::customer" action="customer/online/" resource="Magento_Customer::online"/>
<add id="Magento_Customer::customer_group" title="Customer Groups" module="Magento_Customer" sortOrder="50" parent="Magento_Backend::other_settings" action="customer/group" resource="Magento_Customer::group"/>
```

These lines seems to miss the `translate="true"` attribute. This causes the collect-phrases not to include these labels.

**Comment by thomvanderboon** [comment]
@JRM93 Which version are you using? 

It is still broken in 2.0.4, Almost all issues have been resolved in latest developent version.
![magento backend](https://cloud.githubusercontent.com/assets/16068454/14934036/09c802f0-0ea4-11e6-95cf-c32a0b77d475.png)

**Comment by jrm93** [comment]
@thomvanderboon These is at least 1 phrase (maybe more) that still not gets written to the .csv.

One example is "All Customers" in the Customers menu as shown in my example. I generate the file with the following command:

```
./magento i18n:collect-phrases -o lines.csv -m /home/rozenkel/public_html/
```

When i then user grep like this All Customers string is not found.

```
grep -n "All Customers" lines.csv
```

Did i do something wrong or is it just a bug in the system.

**Comment by thomvanderboon** [comment]
@JRM93 What version of Magento 2 are you running?

**Comment by jrm93** [comment]
@thomvanderboon i am using version 2.0.4.

**Comment by thomvanderboon** [comment]
@JRM93 This issue **has not** been fixed in the 2.0.4 and will be fixed in one of the upcoming releases.

The issue **has been** fixed in the development branch, which has less stable code than the latest official release.

**Comment by jrm93** [comment]
@thomvanderboon thanks for the information. Will clone development branch tomorrow to finish the rest of the translations.

**Comment by Krapulat** [comment]
@thomvanderboon Do you know when this fixes will be included in 2.0 branch? In 2.0.6 there are still strings that can't be translated.

**Comment by thomvanderboon** [comment]
@Krapulat No, I don't know....Send e-mail to magento? ;)

**Comment by teokolo** [comment]
2.0.6 does not contain these fixes yet :(

**Comment by micheese** [comment]
Does anyone has an update on this please?

**Comment by paliarush** [comment]
@michiz05000 @teokolo could you please provide a list of phrases which are still not translatable? Please check them on [2.1 branch](https://github.com/magento/magento2/tree/2.1) before reporting.

**Comment by KrystynaKabannyk** [comment]
Hello @kkkonrad, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by Krapulat** [comment]
@KrystynaKabannyk I've upgraded to 2.1.0 and some strings in the checkout page can't be translated.

**Comment by Krapulat** [comment]
For example, the strings in Checkout like "Shipping", "Review & Payments", "Order Summary", "You can create an account after checkout." and many others can't be translated.

Thanks.

**Comment by gesell** [comment]
Still not translatable in Magento 2.1. 

"Shipping" works.
"Review & Payments" not. 

Has it to do with the "&"?

**Comment by jibrandlr** [comment]
@gesell "Review and Payments" IS translatable in my Magento 2.1 store

**Comment by gesell** [comment]
Hi @Igarridoj 

Thanks for your reply. How did you manage it? In my case it simply ignores this part of my CSV file (/app/design/frontend/Magento/luma/i18n/de_DE.csv)

**Comment by jibrandlr** [comment]
@gesell The row in my .csv file contains:
Review & Payments, My transalted phrase, module, Magento_Checkout

**Comment by razvanbalosin** [comment]
I think this has to be reopened as the checkout page is still not translatable (version 2.1.1)

**Comment by gewaechshaus** [comment]
I can't get "Review & Payments" to be translated by using de_DE.csv in a custom themes i18n folder... Think so 2

**Comment by jeanpham** [comment]
Unbelievable that this is possible...

https://snag.gy/2C8j6f.jpg

I'm desperately looking for a solution...anybody?

**Comment by andidhouse** [comment]
This should be escalated to the magento2 top management team now in my perspective. It looks like the m2 developers and m2 GitHub team are not handling bugreports properly since 1.5 years now.

There are hundreds of open bugs here never fixed. This one is also present in 2.1.7.

If you read on GitHub more and more people/developer/user are getting really more and more angry because the @magento-team does not fix important bugs for moths and years.

I think the only way is to escalate this to the top management team as no promises from magento2 team made here are kept.

**Comment by BenGlassAtlas** [comment]
It's embarrassing that this is still an issue.

**Comment by paliarush** [comment]
Hi @BenSpace48, I see that @magento-engcom-team has closed this issue about a year ago. Could you please clarify the scenario in which you still experience a bug?

**Comment by BenGlassAtlas** [comment]
There are issues currently open for this problem so despite it being closed it still isn't fixed fully, I'm referring to the fact that these issues have been around since 2015 and are still causing problems. 

It feels like Translations have always been broken when it comes to html and JS translations.

See https://github.com/magento/magento2/issues/8508#issuecomment-305417154 and https://github.com/magento/magento2/issues/11175 

I find UI Components easier to work with than translations 😱

**Comment by paliarush** [comment]
@BenSpace48 I understand that this is frustrating, unfortunately the only way to get these issues fixed is to report specific cases when translation does not work. 

As far as I can see, the tickets you referred in previous comment have been triaged by @magento-engcom-team and will be fixed according to their priorities.

**Comment by zmaster94** [comment]
@paliarush 
### Specific case
- Magento version:
  `2.3.4 Community edition`
- Php version:
  `7.2`
- Phrase:
  `Item in Cart`
- Location:
  `vendor/magento/module-checkout/view/frontend/web/template/minicart/content.html`
```html
33                <!-- ko if: (getCartLineItemsCount() === 1) -->
34                    <span translate="'Item in Cart'"/>
35                <!--/ko-->
```
Using _i18n:collect-phrases -m_, the phrase does not appear in results (while being present in its original translation file: _vendor/magento/module-checkout/i18n/en_US.csv_).
