### ISSUE TITLE
Switching billing address causes Javascript function text to render in front-end checkout payment section

### ISSUE THREAD

**Issue by chris-pook** [magento/magento2#26375]
With the Braintree payment method enabled, when switching billing address using the dropdown of the customer's saved addresses a ton of javascript gets rendered to the page (looks like PrototypeJS source code). This is really nasty and looks quite scary right in the payment step alongside the customer's payment card details..

### Preconditions (*)
1. Magento 2.3.3 installed
2. Braintree payment method enabled

### Steps to reproduce (*)
1. Enable and configure Braintree module
2. Register a customer account
3. Add at least one address to the customer account
4. Add a product to cart
5. Go to checkout
6. Proceed to payment step
7. Untick "My billing and shipping address are the same"
8. Select an address from dropdown
9. Click "update"

### Expected result (*)
1. The address section should update to reflect the selected address

### Actual result (*)
1. The address section updates but includes a lot of javascript code text
![image](https://user-images.githubusercontent.com/4628660/72266250-e3115b00-3615-11ea-8d7d-c6f8ba067a67.png)

**Comment by chris-pook** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @chris-pook. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by chris-pook** [comment]
The above instance request did not work, tryinga 2.4 one...

@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @chris-pook. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @chris-pook, here is your [Magento instance](https://i-26375-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26375-2-4-develop.instances.magento-community.engineering/admin](https://i-26375-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by chris-pook** [comment]
Can confirm this is still an issue on 2.4-develop, tested on instance above.

![image](https://user-images.githubusercontent.com/4628660/72328785-7d6fae00-36ab-11ea-98d5-4a0d8ac988ad.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30410` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @chris-pook. Thank you for your report. 
The issue has been fixed in magento/magento2#26378 by @chris-pook in 2.4-develop branch
Related commit(s):
 - [4ea41d058503bb8d9671224c87fc0d022f2873f3](https://github.com/magento/magento2/commit/4ea41d058503bb8d9671224c87fc0d022f2873f3)
 - [ee3f8e345a34b463bd8a9f305166157cf68ed323](https://github.com/magento/magento2/commit/ee3f8e345a34b463bd8a9f305166157cf68ed323)
 - [54270993b4dd2301113144441a27adb6ac80309b](https://github.com/magento/magento2/commit/54270993b4dd2301113144441a27adb6ac80309b)

The fix will be available with the upcoming 2.4.0 release.

**Comment by advocat** [comment]
I found one more case that caused the same issue

**Preconditions (*)**
- Magento 2.4.1 installed
- Google Tag Manager is enabled
- Cash Money Order payment is enabled

**Steps to reproduce (*)**
- Enable and configure Google Tag Manager
- Add a product to cart
- Go to checkout
- Proceed to payment step

**Expected result (*)**
The address has correct street

**Actual result (*)**
The address section includes a lot of javascript code text

**Root Cause**
Load legacy Prototype in Magento_GoogleTagManager/web/js/google-analytics-universal.js

**Comment by alwinj1989** [comment]
yes, I am able to reproduce the above issue .. Can I know whether above issue been resolved?

**Comment by jglassmaker** [comment]
This is still an issue in Magento 2.4.2.
For a quick fix remove 'prototype' from the define includes inside google-analytics-universal.js

**Comment by davemyb** [comment]
Same issue is occurring with Stripe as the payment provider. The fix proposed above by jglassmaker works to solve it.

**Comment by jlenzstaysafe** [comment]
Why is this closed?  Still happening on 2.4.2 EE.

**Comment by chirag-taraviya** [comment]
Issue is still in Magento 2.4.2 EE.

**Comment by DevAwesomeK** [comment]
This issue is still exists in Magento 2.4.2 EE.

**Comment by aboritskiy** [comment]
seems like there is an official patch for this problem: https://support.magento.com/hc/en-us/articles/360058863531-MDVA-33289-Magento-patch-Javascript-in-address-at-checkout
