### ISSUE TITLE
Queue consumer handler can't be virtual type

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#26866]
### Preconditions (*)

1. Magento 2.3.3
2. Rabbit MQ 3.7.8

### Steps to reproduce (*)

1. In custom module add consumer in `queue_consumer.xml` for any queue
2. Consumer should be virtual type
3. Start consumer from console

### Expected result (*)

1. Consumer handles message

### Actual result (*)

1. Consumer is not started
2. There is error in console: "Service method specified as handler for of consumer "<name>" is not available. Given "<class>::<method>"

The problem sems to be in here vendor/magento/framework-message-queue/Consumer/Config/Validator/Handlers.php. `MethodsMap` tries to load class with reflection (`vendor/magento/framework/Reflection/MethodsMap.php:130`) and fails because virtual type in fact doesn't exists.

**Comment by bartoszkubicki** [comment]
This issue is still a bug, but needs reviewing from @magento-engcom-team, before any fixing.

**Comment by bartoszkubicki** [comment]
Still an issue.

**Comment by engcom-Hotel** [comment]
Hi @bartoszkubicki 

The issue is not reproducible in version 2.4-develop. Please tell us how you created a consumer with type virtual.

**Comment by engcom-Hotel** [comment]
Hi @bartoszkubicki,

I hope that your issue is resolved because we did not get any update on this since 14 days. Hence closing the ticket.

Please feel free to raise the new ticket if you have any other issue. We will be happy to work for you.

**Comment by bartoszkubicki** [comment]
@engcom-Hotel I didn't  have time recently to check it again. I was waiting for your response for over one year, so I don't think this should be closed just like this. I am going to examine that in two next week, so you can reopen this one.

**Comment by Dren7755** [comment]
It's still possible to reproduce this issue on Magento 2.4.0

How to reproduce
1. Create some service class like this
```
namespace Vendor\Module\Model;

class Consumer implements CustomConsumerInterface
{
    private CustomValidatorInterface $validator;

    public function __construct(
        CustomValidatorInterface $validator
    ) {
        $this->validator = $validator;
    }

    public function consume(SomeCustomInterface $foo): void
    {
        $this->validator->validate($foo);
    }
}

```
2. Create virtual type based on created class
```
<virtualType name="Vendor\Module\Model\ConcreteConsumer" type="Vendor\Module\Model\Consumer">
        <arguments>
            <argument name="validator" xsi:type="object">Vendor\Module\Model\ConcreteValidator</argument>
    </virtualType>
```
3. Use virtual consumer in queue_consumer.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/consumer.xsd">
    <consumer name="testConsumer"
              queue="test.queu"
              connection="amqp"
              maxMessages="1"
              handler="Vendor\Module\Model\ConcreteConsumer::consume" />
</config>

```
4. Make sure `setup:di:compile` finished successfully
5. Run `bin/magento queue:consumers:start testConsumer` and see the error
```
In Handlers.php line 74:
                                                                                                                                                                              
  Service method specified as handler for of consumer "testConsumer" is not available. Given "Vendor\Module\Model\ConcreteConsumer::consume"
```

**Comment by novikor** [comment]
⬆️ Looks like the issue is not resolved, is being reproduced, and still requires an attention

**Comment by engcom-Echo** [comment]
Hello @bartoszkubicki,

Thanks for contribution and collaboration.
We have tried to reproduce this issue on magento 2.4-develop branch and it is not able to reproduce.
Steps followed to reproduce issue:
Module Zip file :- 
[Hidro.zip](https://github.com/magento/magento2/files/9198499/Hidro.zip)

1. Install the fresh magento instance.
2. Create Custom Module.
3. Create some service class
4. Create virtual type based on created class
5. Use virtual consumer in queue_consumer.xml
6. Make sure setup:di:compile finished successfully

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/181245198-18002277-bb64-4770-9688-d5b216250bc6.png">

8. Run bin/magento queue:consumers:start updateproduct.consumer

And not found any error on console.
Please check if i missed anything and kindly check on magento 2.4-develop branch and provide more information so that we can reproduce this issue.

Thanks

**Comment by engcom-Echo** [comment]
Hello @bartoszkubicki,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
