### ISSUE TITLE
2.3.4 Email Template New Pickup Order or add New Template order items are missing in Mail

### ISSUE THREAD

**Issue by stradd** [magento/magento2#26882]
**Preconditions (*)**
magento 2.3.4 

I installed magento 2.3.4 with sample data.
In the customer order mail order items are missing

**Steps to reproduce(*)**

Stores> Configuration> Sales > Sales Emails> New Order Confirmation select Template: New Pickup Order
Sales > Order: Select a order, goto Information, Send Mail

In the mail that Magento sends, the section with the order items is not transferred.
The same applies if you create a new template and select a template New Order or New Order (Magento Luma).

Only if you select
Stores> Configuration> Sales Emails> New Order Confirmation Template: New Order (default)
the order items will be transferred

**Actual result (*)**
In the customer order mail order items are missing

**Expected result (*)**
In the customer order mail order items should be there

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31544` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ramesh-durairajaram** [comment]
Hi @shikhamis11 , I don't get this new pickup template in `new order confirmation` option. How do we get this new pickup template

**Comment by fongd** [comment]
I believe this issue also affects 2.3.3-p1 as well.

**Comment by verheesj** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @verheesj. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @verheesj, here is your [Magento instance](https://i-26882-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26882-2-4-develop.instances.magento-community.engineering/admin_8d71](https://i-26882-2-4-develop.instances.magento-community.engineering/admin_8d71)
Login: `9254450c` Password: `9cc5942a15ef`
Instance will be terminated in up to 3 hours.

**Comment by achleitner** [comment]
How can this be solved? All my order emails are empty. Anyone has a fix? Thanks

**Comment by singhvivek64** [comment]
$magento give me 2.4-develop instance

**Comment by puntable** [comment]
I can confirm. It seems every 2.3.4 are missing order_items_grid in emails, if they are not using default.

**Comment by marinagociu** [comment]
In case it helps anyone.
If you're using a custom template for your order emails, I found that a temporary fix until the issue is solved by Magento is to update `is_legacy` to 1 in the `email_template` table for your order templates. This way Magento should correctly process `{{layout handle="sales_email_order_items" order=$order area="frontend"}}`. If `is_legacy` is 0 (this is the default value for a newly added template created after the upgrade), then the `order` passed to the blocks created by the `sales_email_order_items` handle is `null`, so no data will be displayed in the email.
Curious enough, if you're using the default template and not one saved in the DB, the `order` object is correctly passed into the order items grid blocks.

**Comment by galahadl** [comment]
I have also had a problem with this. Even if you make no changes, just creating an email template in the admin by loading and saving the default template, then assigning it, causes the items grid to be lost. 

We have tested and confirmed this issue exists on both 2.3.3-p1 and 2.3.4

**Comment by gwharton** [comment]
Note, this also affects invoice, shipment and credit memo emails.

**Comment by magento-engcom-team** [comment]
Hi @stradd, @BrentRobert. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [1f4166bc94bc3143e30e1f66243391ccd8434f1f](https://github.com/magento/magento2/commit/1f4166bc94bc3143e30e1f66243391ccd8434f1f)
 - [c5837830a4802b8822160ebe4fdbff0a8179090b](https://github.com/magento/magento2/commit/c5837830a4802b8822160ebe4fdbff0a8179090b)

The fix will be available with the upcoming `2.4.0` release.

**Comment by hryvinskyi** [comment]
I create patch for maegnto 2.3.4 https://gist.github.com/hryvinskyi/5313b25c30839edd82e7f3d295f00666

**Comment by jajajaime** [comment]
@hryvinskyi Thanks for the patch, but it seems to be failing in a few places to apply on 2.3.4. I am getting this in response

```
error: patch failed: vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php:17
error: vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php: patch does not apply
error: app/design/frontend/Magento/luma/Magento_Sales/email/creditmemo_new.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/creditmemo_new_guest.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/invoice_new.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/invoice_new_guest.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/order_new.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/order_new_guest.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/shipment_new.html: No such file or directory
error: app/design/frontend/Magento/luma/Magento_Sales/email/shipment_new_guest.html: No such file or directory
```

Most are just template location, as they should be on the vendor folder and easy to update, but I'm not sure about the Model classes.

**Comment by jajajaime** [comment]
> @hryvinskyi Thanks for the patch, but it seems to be failing in a few places to apply on 2.3.4. I am getting this in response
> 
> ```
> error: patch failed: vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php:17
> error: vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php: patch does not apply
> error: app/design/frontend/Magento/luma/Magento_Sales/email/creditmemo_new.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/creditmemo_new_guest.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/invoice_new.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/invoice_new_guest.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/order_new.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/order_new_guest.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/shipment_new.html: No such file or directory
> error: app/design/frontend/Magento/luma/Magento_Sales/email/shipment_new_guest.html: No such file or directory
> ```
> 
> Most are just template location, as they should be on the vendor folder and easy to update, but I'm not sure about the Model classes.

I actually adapted it for my `ShipmentSender` class, but it still doesn't fix the issue for me.
This was my change anyway
```
diff --git a/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php b/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
index 4dbc103..090c6aa 100644
--- a/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
+++ b/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
@@ -108,7 +108,9 @@ class ShipmentSender extends Sender
 
             $transport = [
                 'order' => $order,
+                'order_id' => $$order->getId(),
                 'shipment' => $shipment,
+                'shipment_id' => $shipment->getId(),
                 'comment' => $shipment->getCustomerNoteNotify() ? $shipment->getCustomerNote() : '',
                 'billing' => $order->getBillingAddress(),
                 'payment_html' => $this->getPaymentHtml($order),
```

**Comment by Jamiebullock87** [comment]
> In case it helps anyone.
> If you're using a custom template for your order emails, I found that a temporary fix until the issue is solved by Magento is to update `is_legacy` to 1 in the `email_template` table for your order templates. This way Magento should correctly process `{{layout handle="sales_email_order_items" order=$order area="frontend"}}`. If `is_legacy` is 0 (this is the default value for a newly added template created after the upgrade), then the `order` passed to the blocks created by the `sales_email_order_items` handle is `null`, so no data will be displayed in the email.
> Curious enough, if you're using the default template and not one saved in the DB, the `order` object is correctly passed into the order items grid blocks.

This worked on magento 2.3.5 with the default magento email templates for anyone else waiting on 2.4 release

**Comment by Josko73** [comment]
Hello There
I have the same isseu with the magento 2.3.4.
Can someone please give me instructions how I can update is_legacy to 1 in the email_template table?

Thanks for your support.
Best Wishes
Josko

**Comment by puntable** [comment]
> Hello There
> I have the same isseu with the magento 2.3.4.
> Can someone please give me instructions how I can update is_legacy to 1 in the email_template table?
> 
> Thanks for your support.
> Best Wishes
> Josko

First you need to connect to the database. Use either phpMyAdmin or other SQL workbench.
Then you need to edit the column called `is_legacy` in the table `email_template`. Change the value from `0` to `1` for the templates, you are experimenting problems with.
If there are no rows in this table, you need to create new template from Magento backend first.

**Comment by Josko73** [comment]
> 
> 
> > Hello There
> > I have the same isseu with the magento 2.3.4.
> > Can someone please give me instructions how I can update is_legacy to 1 in the email_template table?
> > Thanks for your support.
> > Best Wishes
> > Josko
> 
> First you need to connect to the database. Use either phpMyAdmin or other SQL workbench.
> Then you need to edit the column called `is_legacy` in the table `email_template`. Change the value from `0` to `1` for the templates, you are experimenting problems with.
> If there are no rows in this table, you need to create new template from Magento backend first.

Thank you! It works!

**Comment by KZNcode** [comment]
This bug are ridiculous and a huge waste of time. Even IDENTICAL templates to the magento "XXX (default)" don't show the product list... only direct database manipulation of "is_legacy" works. Come on now... This don't make any sense.

**Comment by chrisastley** [comment]
Changing "is_legacy" doesn't work for me on 2.3.5-p2. Does anyone know of a patch to get this working as I'm not in a position to upgrade to 2.4 yet?

**Comment by jordanvector** [comment]
@chrisastley have you seen this https://github.com/magento/magento2/pull/28331. Some guy made a backport to 2.3 for those fixes.  Looks like magento never rolled in his commit because his PR was on the wrong branch 🙄

**Comment by chrisastley** [comment]
> @chrisastley have you seen this #28331. Some guy made a backport to 2.3 for those fixes. Looks like magento never rolled in his commit because his PR was on the wrong branch 🙄

I had to modify the patch file in the end, it appears that the changes in magento 2.3.5-p2 included the changes to the luma theme email template files so I had to remove those from the patch and it then worked.

**Comment by jordanvector** [comment]
Ok I will post this here for others on 2.3 struggling with this. I rolled these fixes against 2.3.5-p2 (removing the template changes bc they are already there). 

https://gist.github.com/jordanvector/ead76e777afb3fe71b4e7716496619a6#file-mc-31544-2-3-5-p2-patch

Then I can add it as a composer patch like so

```
            "magento/module-sales": {
                "MC-31544: Email Template New Pickup Order or add New Template order items are missing in Mail #28331": "patches/composer/MC-31544-2.3.5-p2.patch"
            }
```

**Comment by mischabraam** [comment]
The `is_legacy` set to `1` work around and patch from @jordanvector doesn't seem to fix the issue with the shipment (and tracking) email. Any ideas how to fix these?

```
PHP Fatal error:  Uncaught Error: Call to a member function getUrl() on null in ./vendor/magento/module-sales/view/frontend/templates/email/shipment/track.phtml:28
```

**Comment by miteshdhaduk** [comment]
> In case it helps anyone.
> If you're using a custom template for your order emails, I found that a temporary fix until the issue is solved by Magento is to update `is_legacy` to 1 in the `email_template` table for your order templates. This way Magento should correctly process `{{layout handle="sales_email_order_items" order=$order area="frontend"}}`. If `is_legacy` is 0 (this is the default value for a newly added template created after the upgrade), then the `order` passed to the blocks created by the `sales_email_order_items` handle is `null`, so no data will be displayed in the email.
> Curious enough, if you're using the default template and not one saved in the DB, the `order` object is correctly passed into the order items grid blocks.

This worked on Magento 2.3.5 with the default Magento email templates. The perfect fix for the issue.

**Comment by mpchadwick** [comment]
For those on 2.3.X, I haven't personally tested at this point, but looks like there's a fix in 2.3.6

- https://github.com/magento/magento2/blame/2.3.6/app/code/Magento/Sales/view/frontend/email/order_new.html#L94
- https://github.com/magento/magento2/commit/bc1155b5838af7c4b818d37e1dbb1d5a88460398

**Comment by harrigo** [comment]
I have not had any difficulty like this until 2.4.3-p2 and only just noticed it on a secondary store. Strange thing is that these templates look correct (using order_id) and legacy=0 in DB. Have used the same template for both stores however one store fails with order_id is null and cannot then pull the order. Same for the shipment_id however all other variables look ok. 

Am gonna try legacy mode see if that works for the broken store but left scratching me head again on this one.
