### ISSUE TITLE
Performance issue and scalability of popular search term cache

### ISSUE THREAD

**Issue by mflott** [magento/magento2#27559]
Upon upgrading our site to 2.3, we saw a sudden increase in database CPU load. By looking at the processlist we saw a frequent query that took a lot of time:

`SELECT DISTINCT  COUNT(*) FROM `search_query` AS `main_table` WHERE (main_table.store_id = 1) AND (num_results > 0)`

We found that this is part of the 2.3.0 update where they added Popular Search Term Cache ([This pull request](https://github.com/magento/magento2/commit/fc3c42960ed10ef8124d5c54ce76d6e31f0ffda8)) The larger the _search_query_ table is, the longer the query takes to complete.

### Preconditions (*)
1. Magento Commerce 2.3.4
2. ElasticSearch 6.7.0

### Steps to reproduce (*)
1. Make a query in the main search bar.

### Expected result (*)
1. The query is expected to finish within a reasonable amount of time.

### Actual result (*)
1. The query takes a long time to finish, depending on the size of the _search_query_ table.

On our live site we have about 2,7 million search terms, so when doing queries this puts a lot of strain on the database and the queries are very slow. The main part that takes time is the _num_results > 0_ part - when we tested without this in our local testing environment we got a query duration of 0,7 sec., while if we included it it takes approx. 23 sec.

**Comment by igorwulff** [comment]
Hi @mflott do you know what the impact is of removing the `AND (num_results > 0)` part? Or do you have any other suggestion to improve this? We are seeing the same issues here with larger datasets.

**Comment by mflott** [comment]
Hi @igorwulff . I'm not sure if removing the num_results will have any impact, would have to check that part a bit deeper. 

Instead of a patch for reverting the PR, we decided to override the execute function in Magento_CatalogSearch/Controller/Result/Index instead and changed it to only use the getNotCacheableResult part, and removed code for the getCacheableResult part. This pretty much changes it back to how it performed before the PR.

**Comment by convenient** [comment]
Seeing this issue also

**Comment by mattijv** [comment]
Just got hit by this too on 2.3.5-p1 when a campaign caused a surge in traffic. Hotfixed by doing what @mflott suggested and forcing the controller code take the `getNotCacheableResult` path.

**Comment by mattijv** [comment]
Initial testing suggests that adding this index on the `search_query` table may resolve the issue. I did not observe much increase in write loads, but this is yet to be tested in production.

```xml
<index referenceId="SEARCH_QUERY_STORE_ID_NUM_RESULTS" indexType="btree">
    <column name="store_id"/>
    <column name="num_results"/>
</index>
```

**Comment by igorwulff** [comment]
This issue is still relevant....  a suggestion to fix this was added by @mattijv and should be checked by Magento.

**Comment by tuyennn** [comment]
Have same this issue even not using Elastic Search and lower magento 2  version

**Comment by leonhelmus** [comment]
This issue is still relevant on a 2.4.1-p1 magento website with PHP 7.4 & mysql 8.0.

**Comment by engcom-Bravo** [comment]
#### We have tested it from code side on 2.4-develop branch and confirming this issue.

Even on disabling search suggestions from admin panel and enabling elastic search as per https://devdocs.magento.com/guides/v2.3/release-notes/open-source-2-3-6.html#search  , main search bar still hits the MYSQL 'search_query' table. 

Due to this search_query table grows and cause performance issue. We need to either index this or use elastic-search for all search related operations.

#### Admin panel configurations:
![image](https://user-images.githubusercontent.com/51680745/122581954-3a222780-d075-11eb-9c1c-6ed0015f7844.png)


#### db.log file after above configurations and search:
![image](https://user-images.githubusercontent.com/51680745/122582075-5920b980-d075-11eb-90df-c399d889f28f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42673` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment]
@mflott The issue has been resolved on **2.4-develop** branch. 

Thank you!

**Comment by hostep** [comment]
@multipasko, it's probably this one: https://github.com/magento/magento2/commit/c90edaa7fbfb8bcd0098de1981e4e022a79a8c13 (the commit has the same ticket number as [referenced above](https://github.com/magento/magento2/issues/27559#issuecomment-905302374))

**Comment by davidandersson1** [comment]
Hello,

We have below query which is continuous recorded as slow query with magento version 2.4.1 

SELECT COUNT(*) FROM (SELECT DISTINCT `main_table`.`query_text` FROM `search_query` AS `main_table` WHERE (main_table.store_id IN (1)) AND (num_results > 0) ORDER BY `popularity` desc
LIMIT 100) AS `result` WHERE (result.query_text = 'test')

so we have to apply https://github.com/magento/magento2/commit/c90edaa7fbfb8bcd0098de1981e4e022a79a8c13 this one as patch?

Can you please confirm!

Thanks,
David Andersson

**Comment by sdouma** [comment]
Still having this issue in 2.4.4-p2. This doesn't seem to be fixable with the way it is currently structured. The reason why is it uses select distinct on a table that is going to have millions of records.
Why even cache it?

**Comment by cdcrothers** [comment]
I fail to see how [c90edaa](https://github.com/magento/magento2/commit/c90edaa7fbfb8bcd0098de1981e4e022a79a8c13) could possibly fix the performance issue. All it does is add columns to the select query, which would only add MORE lift for mysql to need to compute distinctness. It is not difficult for this table (in my case) to reach 700k entries. Many likely reach far more. Search requests also have a much higher chance for page cache misses. It's no surprise that mysql performance is a concern in production when `isTopSearchResult` takes 700ms for a single mysql query on a server that isn't under any other load.

Removing the `DISTINCT` operator from the query reduces it from 700ms down to 2ms and produces the same results. The results are always going to be the same too, because the search_query table already has as unique constraint on `query_text` and `store_id`, and in all cases, the `store_id` is being filtered and `query_text` is being used as a column in the select.

The solution here should be to simply remove the the `DISTINCT` operator from queries within `\Magento\Search\Model\ResourceModel\Query\Collection`, because those `DISTINCT` operators are effectively not doing anything, and only hurting your query performance.

However, if your performance is caused by a a high search term cardinality (lots of unique terms), it's possible that the mysql inserts are too expensive for your project. The solution in THAT case is a bit more involved. You could instead:
- asynchronously insert search terms into the table in batches to prevent it from slowing down search request times.
- only insert a fraction of the search terms
- stop tracking search terms entirely (this will cause you to lose visibility to user search term behaviors on your site)

**Comment by nilesh-dhumal-fexle** [comment]
My magento 2 admin panel is not working at all 
when I run "show full processlist;" in MySQL,
it shows this query running multiple times "SELECT DISTINCT  COUNT(*) FROM `search_query` AS `main_table` WHERE (main_table.store_id = 1) AND (num_results > 0)"
I am using magento 2.3.4 community version.

**Comment by jmonrove** [comment]
2.4.5-p4 still having issues with this useless feature.

**Comment by hemendrametawolf** [comment]
I also facing suddenly high CPU usages on Magento 2.4.4-p1.
any quick solution for this.

**Comment by sixng** [comment]
i am using 2.4.6 commerce version. I have 1.4M rows in search_query table, which is bottle neck of keyword search. Now, keyword search takes around 10 seconds to complete one search, which is ridiculous. Finally, I got the solution and shorten the keywords to 2-3 seconds. However, I am not sure is it a right approach.

in /vendor/magento/module-search/Model/ResourceModel/Query/Collection.php
public function isTopSearchResult(string $term, int $storeId, int $maxCountCacheableSearchTerms):bool
change $select->distinct(false);

**Comment by qlhu** [comment]
The issue happens to mine 2.4.5-p5 community and MySQL 8.0. It's worse than @sixng case because we have over 40M rows in search_query table. MySQL [Bug #99717 Peformance regression of parallel count](https://bugs.mysql.com/bug.php?id=99717) explains the performance issue to the "Select COUNT(*)". 
Besides optimizing the query, I would like to recommend Magento to prevent the spam search text as much as possible. That's because I figured out 99% of the rows of search_query is spam search like below.
![image](https://github.com/magento/magento2/assets/29137910/3cef05b4-8ac6-4d73-9b7e-126be71da39c)

**Comment by tuyennn** [comment]
Any update on this issue? Apparently no one is working on this.

**Comment by jmonrove** [comment]
2.4.6-p4 problem still present, I don't think anyone cares... I'm just going to set up a cron to empty the table every certain amount of time.

**Comment by sixng** [comment]
in /vendor/magento/module-search/Model/ResourceModel/Query/Collection.php
public function isTopSearchResult(string $term, int $storeId, int $maxCountCacheableSearchTerms):bool
change $select->distinct(false);

I revised the code for few months, I did not see any negative impact here. Thanks.

**Comment by scadox** [comment]
Hi all, after opening Support ticket in experienceleague.adobe.com for same problem, we have received patch `ACSD-61957 / ACSD-61957_2.4.7-p2`,  and fix this slow problem.

More details here : https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-34/acsd-51857-slow-cron-job-of-aggregate-sales-report-bestsellers-data-affects-performance 

Cordialement,

**Comment by tuyennn** [comment]
@scadox Doesn't seem ACSD-61957 exist on https://github.com/magento/quality-patches repository, could you paste or attach it here for us/

**Comment by scadox** [comment]
@tuyennn , here attach file, i have received this patch from AC Support Business.

[ACSD-61957_2.4.7-p2.patch](https://github.com/user-attachments/files/17574498/ACSD-61957_2.4.7-p2.patch)

Cordialement,

**Comment by herobk** [comment]
> > [@tuyennn](https://github.com/tuyennn) , here attach file, i have received this patch from AC Support Business.
> > [ACSD-61957_2.4.7-p2.patch](https://github.com/user-attachments/files/17574498/ACSD-61957_2.4.7-p2.patch)
> > Cordialement,
> 
> Have you or anyone else confirmed that this solved the issue?

Hi @addmitt , I confirm this patch is working well.
I got the same issue with magento 2.4.7-p6.
Updates of this patch is match with latest code in magento 2.4.8-p1
