### ISSUE TITLE
AUTO_INCREMENT grows on every INSERT ... ON DUPLICATE on InnoDB tables

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#28387]
### Preconditions (*)

1. any magento version, mysql or mariaDB database
2. Magento 2.4-develop
3. InnoDB tables
4. Magento uses queries like this to save new values or update existing in tables
see method `\Magento\Eav\Model\Entity\AbstractEntity::_processAttributeValues`
```
INSERT INTO `catalog_product_entity_int` (`attribute_id`, `store_id`, `entity_id`, `value`)
VALUES (97, 1, 123, 1)
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
```

The problem causes that the table reaches max autoincrement value too fast that leads to errors.
Changing column type to **bigint** just temporalny resolves the problem but  autoincrement still grows to infinity
Problem is noticeable when products or some attributes are updated often and new products/attribute values (e.g. in store) added. New attributes have bigger autoincrement than expected.
Moreover, the method `\Magento\Eav\Model\Entity\AbstractEntity::_processAttributeValues` always uses statements `INSERT INTO ... ON DUPLICATE KEY UPDATE` to insert new value or update existing. So updating existing values this way when **innodb_autoinc_lock_mode** > 0 causes the issue. 

### Steps to reproduce (*)

1. Take **auto_increment** value from table **catalog_product_entity_int**
2. Remember that value (e.g. **1000**)
3. Save one new product attribute (e.g. int type).  
```
$this->productResourceModel->saveAttribute($product, 'status');
```
it generates query like above. INSERT INTO ... ON DUPLICATE KEY UPDATE
4. New value inserted and **auto_increment** is _1001_
5. Run the same query, or save the same attribute 4 more times
6. Save the same attribute under store (important that value not exist before insertion)
7. Check the **auto_increment** value of the table or **MAX(value_id)** 

### Expected result (*)

1. The  **auto_increment** value or **MAX(value_id)** is 1002
2. Only one new record inserted that increased auto_increment by 1

### Actual result (*)

1. The  **auto_increment** value or **MAX(value_id)** is 1006
2. Only one new record inserted but auto_increment increased by 5

### Workaround: (*)
Set parametr in **my.cnf** 
```
innodb_autoinc_lock_mode=0
```
or recreate column
```
ALTER TABLE catalog_product_entity_int
drop column value_id;

ALTER TABLE catalog_product_entity_int
ADD value_id BIGINT(11) AUTO_INCREMENT NOT NULL FIRST,
ADD PRIMARY KEY (value_id);
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ilnytskyi** [comment]
At first growing auto_increment will cause the issue 

> SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'value_id' at row 1, query was: INSERT INTO `catalog_product_entity_int`

Then devs might consider changing the column type to allocate bigger ints
> ALTER TABLE catalog_product_entity_int MODIFY value_id bigint(20) unsigned NOT NULL auto_increment COMMENT 'Value ID';

but the value will be growing

It seems to be DB issue or db configuration issue, however It is not mentioned or documented by  Magento. 

Additionally, magento does not chose between INSERT or UPDATE when add or modify values so the issue happens.

https://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html

**Comment by hostep** [comment]
Hmm, let's remove the stale issue label, this sounds pretty important.

@sidolov: can somebody verify this and if verified add some priorities?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40808` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by NateSwanson7** [comment]
Any progress on this? This seems like an issue that could potentially start affecting many instances since M2 has been around for a few years now.

**Comment by JelleGe** [comment]
Any update on this? We face this issue also and now reached the max of int on catalog_product_entity_varchar

**Comment by ilnytskyi** [comment]
@JelleGe try to recreate a column and change autoincrement lock mode to 0 as I described in workaround.

**Comment by JelleGe** [comment]
@ilnytskyi Thanks! I tried to recreate a column using your workaround, but we get a query error; Query 1 ERROR: Duplicate column name 'value_id'

**Comment by JelleGe** [comment]
It's a fine temporary solution that works, but it's a matter of time before it returns. So will there become a solution in a future Magento core update?

**Comment by JesKingDev** [comment]
@JelleGe I created a gist for getting the database table back in shape if you've maxed out the auto_increment.
https://gist.github.com/JesKingDev/af70e92740215009ab1bebe5a2cdc17f
It's very thorough and has a lot of checkpoints to ensure you know what's being done.

This isn't a long-term solution, but should definitely buy you back some time while the root cause is fixed.

**Comment by hostep** [comment]
@engcom-Delta, @sdzhepa: why did this issue got closed without any sort of extra information?

**Comment by pmonosolo** [comment]
Looks like this is related to this issue posted all the way in 2019:
https://github.com/magento/magento2/issues/21890

I'm hitting the same limit on 2.4.3

**Comment by pmonosolo** [comment]
> @JelleGe I created a gist for getting the database table back in shape if you've maxed out the auto_increment. https://gist.github.com/JesKingDev/af70e92740215009ab1bebe5a2cdc17f It's very thorough and has a lot of checkpoints to ensure you know what's being done.
> 
> This isn't a long-term solution, but should definitely buy you back some time while the root cause is fixed.

Step 8 (truncate / reset auto_increment) did not work for me in my testing environment. 

For some reason the auto_increment stays the same even after ALTER TABLE catalog_product_entity_varchar AUTO_INCREMENT = 1;

**Comment by convenient** [comment]
Oh yeah @pmonosolo that does indeed look to be the same symptoms as my issue from #21890 

In that case it was fixed in 2.2, but it seems like some kind of regression since then.

Thanks for flagging this to me! This puts one of our sites who's looking into having new stores added dangerously close to running out of auto increment ids again 😱

**Comment by JelleGe** [comment]
Is there any update on this issue?

**Comment by szagabesz** [comment]
Any update on this issue? Just have run into it with a high-traffic Magento instance.

**Comment by engcom-Hotel** [comment]
Hello @ilnytskyi,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento's latest development branch ie 2.4-develop and the issue is still reproducible. We have followed the exact steps and refer to this PR https://github.com/magento/magento2/pull/34339 to reproduce the issue.

Hence confirming the issue.

Thanks

**Comment by pmonosolo** [comment]
> Just hit this on a staging instance (thankfully)

@convenient What version of M2 are you running?

**Comment by convenient** [comment]
@pmonosolo It was a 2.4.2 instance

**Comment by pmonosolo** [comment]
@convenient hmm. Since 2021, I've been using lock_mode = 0 and its been holding up.  Its not perfect - I'm having issues with DB locking - possibly because of having to use lock_mode = 0.

**Comment by convenient** [comment]
Thanks @pmonosolo 

We're just building a module that will fire an alert when we are over 90% capacity on auto increment IDs, to allow us to do maintenance.

It's only every few years we've encountered it

**Comment by pmonosolo** [comment]
> Thanks @pmonosolo
> 
> We're just building a module that will fire an alert when we are over 90% capacity on auto increment IDs, to allow us to do maintenance.
> 
> It's only every few years we've encountered it

Whats the plan when you do hit the limit? 

Change to differen field type or there is some way of purging the table?

**Comment by convenient** [comment]
@pmonosolo https://github.com/magento/magento2/issues/21890

The "workaround" section on that is largely valid

Due to declarative schema we need to drop the constraints on the existing table, and add properly named constraints on the new table before swapping the table names around.

But this way we end up back at auto_increment=1 with the original Magento schema intact

**Comment by TomJ1588** [comment]
Any update on this issue? Just ran into this in production. Any timeframe on a fix?

**Comment by tuey30716** [comment]
> Any update on this issue? Just ran into this in production. Any timeframe on a fix?

change column type on value_id to bigint(20) 
or 
following this step https://gist.github.com/JesKingDev/af70e92740215009ab1bebe5a2cdc17f#2-get-the-current-max-value_id-used-in-the-table

**Comment by mahesh-singh-pinja** [comment]
This issues doesn't looks fixed as changes reverted here: https://github.com/magento/magento2/commit/2eb09dbee39fcc98a1d270cb2ad3b9fd2247f021 

So when attributes update via action: https://github.com/magento/magento2/blob/2.4.7-p1/app/code/Magento/Catalog/Model/ResourceModel/Product/Action.php#L138

It will still use `insertOnDuplicate` and the same issue happens again.

@StanislavVoytenko

**Comment by VladyslavSikailo** [comment]
changing column type to `bigint` significatly increased DB load on our instance, so the more accurate fix for this is to change type to `int(11) unsigned` which increases max autoincrement value twice
