### ISSUE TITLE
Royalmail Click & Drop Integrations Magento 2

### ISSUE THREAD

**Issue by deepakwsofi** [magento/magento2#28996]
The attempt to post data to consumer failed due to an unexpected error. Please try again later.

### Preconditions (*)

1. Magento 2.4-develop
2. 

### Steps to reproduce (*)

1. ![image](https://user-images.githubusercontent.com/11625124/87167140-24937200-c2ea-11ea-84d5-40ee617513f8.png)
2. ![image](https://user-images.githubusercontent.com/11625124/87167222-455bc780-c2ea-11ea-8c03-be5ea88ba102.png)
3. ![image](https://user-images.githubusercontent.com/11625124/87167265-54db1080-c2ea-11ea-9c94-bb50a11e86f7.png)
4. ![image](https://user-images.githubusercontent.com/11625124/87167290-5c9ab500-c2ea-11ea-9122-b6cf1f9c459f.png)

### Expected result (*)

1. No errors during integration

### Actual result (*)

1. Error when try to activate integration
![image](https://user-images.githubusercontent.com/51681379/104010065-a179a880-51b4-11eb-804d-e5194df5fe8a.png)
![image](https://user-images.githubusercontent.com/51681379/104009884-5f506700-51b4-11eb-9b38-75196ffb50f2.png)

### Additional information
Issue is reproducible on 2.4-develop locally according scenario from https://jira.corp.magento.com/browse/MAGETWO-79809

**Comment by krishprakash** [comment]
Hi @deepakwsofi.
Kindly update all required information to reproduce the issue
Precondition
Steps to reproduce
Expected and actual result

**Comment by gwharton** [comment]
RM C&D working fine for me on 2.3.5-p1

**Comment by deepakwsofi** [comment]
Hi @m2-assistant @krishprakash 
![image](https://user-images.githubusercontent.com/11625124/87167046-09c0fd80-c2ea-11ea-9993-1b538ecea5f9.png)
![image](https://user-images.githubusercontent.com/11625124/87167140-24937200-c2ea-11ea-84d5-40ee617513f8.png)
![image](https://user-images.githubusercontent.com/11625124/87167222-455bc780-c2ea-11ea-8c03-be5ea88ba102.png)
![image](https://user-images.githubusercontent.com/11625124/87167265-54db1080-c2ea-11ea-9c94-bb50a11e86f7.png)
![image](https://user-images.githubusercontent.com/11625124/87167290-5c9ab500-c2ea-11ea-9122-b6cf1f9c459f.png)

The problem is integrating Royal Mail click and drop to Magneto 2.3 
We tried now many times 
It won’t allow us to activate integration 
Error The attempt to post data to consumer failed due to an unexpected error. Please try again later.

**Comment by spiyda** [comment]
Same problem on 2.3.6, it worked perfectly on 2.2.2  exactly the same steps as above, slightly different error message
Royal Mail report "Magento Invalid Magento Identity Confirmation, Request for uri: https://xxxxx.com/oauth/token/request failed.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40346` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @deepakwsofi. Thank you for your report. 
The issue has been fixed in magento/magento2#32095 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [68d20230ca9d6198fa3093eb174e24aff47b1646](https://github.com/magento/magento2/commit/68d20230ca9d6198fa3093eb174e24aff47b1646)

The fix will be available with the upcoming 2.4.3 release.

**Comment by gwharton** [comment]
Confirmed working on 2.4.2 with PR patch applied.

**Comment by saxenapritesh** [comment]
@gwharton Please confirm If is it working on Magento ver. 2.4.2-p1 because i have done all changes in same file as provided in here  https://github.com/magento/magento2/commit/68d20230ca9d6198fa3093eb174e24aff47b1646?branch=68d20230ca9d6198fa3093eb174e24aff47b1646&diff=unified but still the issue is not resolved.

**Comment by insaurabh** [comment]
Not working on Magento ver `2.4.2-p1`

**Comment by deepakwsofi** [comment]
> Not working on Magento ver `2.4.2-p1`

Hello insaurabh
i have done thi Job Magento ver 2.4.2 so please share your login Detail info@webgodam.com i will check.

**Comment by deepakwsofi** [comment]
> @gwharton Please confirm If is it working on Magento ver. 2.4.2-p1 because i have done all changes in same file as provided in here [68d2023?branch=68d20230ca9d6198fa3093eb174e24aff47b1646&diff=unified](https://github.com/magento/magento2/commit/68d20230ca9d6198fa3093eb174e24aff47b1646?branch=68d20230ca9d6198fa3093eb174e24aff47b1646&diff=unified) but still the issue is not resolved.

yes working
