### ISSUE TITLE
Can't Create URLs Shorter than Three Characters

### ISSUE THREAD

**Issue by astorm** [magento/magento2#2910]
If I attempt to create a new route for a module, and that module's front name is less than three characters

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/App/etc/routes.xsd">
    <router id="standard">
        <route id="hello-world" frontName="hw">
            <module name="Pulsestorm_HelloPestle"/>
        </route>
    </router>
</config>
```

Magento's XML validator complains

```
Element 'route', attribute 'frontName': [facet 'pattern'] The value 'hw' is not accepted by the pattern '[A-Za-z0-9_\-]{3,}'.
```

It looks like the regular expressions for validating this element (`[A-Za-z0-9_]{3,}`) demands a `frontName` be at least three characters.

Based on the behavior of other PHP frameworks (which allow segments shorter than three characters), this is a bug and should be fixed.

**Comment by namluu** [comment]
It's not a URL's problem. The route id doesn't allow dashes but frontName does, you can set: 
`<route id="helloworld" frontName="hello-world">`

**Comment by astorm** [comment]
@Namluu You are correct!  You **can** have dashes in the `frontName`.  Useful, thanks!  Updated the bug the reflect my annoyance on the limits of three character URLs instead :)

**Comment by ghost** [comment]
@astorm Thanks for pointing this out. I updated the [routing topic](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/routing.html) with character restrictions.

BTW, in your example XML, you're using a path to the XSD instead of a [URN](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/XSD-XML-validation.html).

**Comment by shiftedreality** [comment]
Hi @astorm 

Is it still an issue for you?

**Comment by antonkril** [comment]
Route Front Name has this limitation by mistake. It should be fixed.

**Comment by shiftedreality** [comment]
Internal ticket MAGETWO-48333 was created to fix this issue.

**Comment by astorm** [comment]
Any update on this issues?

/cc @piotrekkaminski

**Comment by piotrekkaminski** [comment]
This is not yet fixed. Increased priority but I don't expect the fix in nearest release.

**Comment by cspruiell** [comment]
This was fixed in the scope of another ticket (MAGETWO-48495) and is in the latest develop branch. It will be included in the next release.
