### ISSUE TITLE
Cannot Insert and Upload Images to text editor 2.3.5-p2

### ISSUE THREAD

**Issue by joemstar** [magento/magento2#29383]
Preconditions (*)
1. Magento Open Source 2.3.5-p2
2. Insert/Edit Image

Steps to reproduce (*)
1. Click the Insert/Edit Image button in the text editor.
![image](https://user-images.githubusercontent.com/40399102/89315694-27fbee00-d649-11ea-8e01-fb813664c0aa.png)
2. Select the option to browse for image source.
![image](https://user-images.githubusercontent.com/40399102/89315798-47931680-d649-11ea-824b-a30d7382c190.png)

Expected result (*)
1. I should be able to browse to select a file to upload.

Actual result (*)
1. I see a white screen and magento stays on that screen and hangs.
![image](https://user-images.githubusercontent.com/40399102/89315975-7e692c80-d649-11ea-8bb7-c60716424f5d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29383-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-29383-2-3-5-p2.instances.magento-community.engineering/admin_a302](https://i-29383-2-3-5-p2.instances.magento-community.engineering/admin_a302)
Login: `739e00eb` Password: `b2db4c50de43`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @joemstar,
In Which module, You have to face the issue. Can you please update here?
Thanks.

**Comment by joemstar** [comment]
If I go to Contect>Pages>Edit and then try to insert an image I face this issue. I also have the same issue in blocks or other areas of admin with the same texted editor. I logged into your clean install of 2.3.5-p2 briefly and tried it there and noticed the problem doesn't exist there. Are there any suggestions as to what may cause this to be happening in my environment?

**Comment by ajijshekh123** [comment]
Hi @joemstar,
I have verified this issue on "Content >> Elements >> Pages" and "Content >> Elements >> Block"
Not able to reproduce this issue.
**PFA:**

![Block](https://user-images.githubusercontent.com/24711761/89326104-6c1ddb80-d6a7-11ea-9e32-8140d0078897.png)

![Pages](https://user-images.githubusercontent.com/24711761/89326111-6de79f00-d6a7-11ea-8863-086f930981b9.png)

Thanks.

**Comment by minhluan259** [comment]
@ajijshekh123 
The new media gallery can not load old images and images which uploaded via file transfer (FTP, SSH) to media folder.

Steps to produce:

Issue 1:
1. Upload images to folder pub/media/wysiwyg/ by FTP (SSH)
2. Go to text editor and insert image (by new media gallery) - folder wysiwyg is blank

Issue 2:
1. Go to text editor and upload image to folder wysiwyg/new/ (by new media gallery)
2. Delete images from pub/media/wysiwyg/new/ by FTP (SSH)
3. Go to text editor and insert image, all thumbnail images in wysiwyg/new/ still exist

Both issues exist in Magento 2.3.5-p2 and 2.4.0

**Comment by BassemN** [comment]
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @BassemN. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @BassemN, here is your [Magento instance](https://i-29383-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-29383-2-3-5-p2.instances.magento-community.engineering/admin_c83d](https://i-29383-2-3-5-p2.instances.magento-community.engineering/admin_c83d)
Login: `4594bd4c` Password: `49cb748d9b74`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
> @ajijshekh123
> The new media gallery can not load old images and images which uploaded via file transfer (FTP, SSH) to media folder.
> 
> Steps to produce:
> 
> Issue 1:
> 
> 1. Upload images to folder pub/media/wysiwyg/ by FTP (SSH)
> 2. Go to text editor and insert image (by new media gallery) - folder wysiwyg is blank
> 
> Issue 2:
> 
> 1. Go to text editor and upload image to folder wysiwyg/new/ (by new media gallery)
> 2. Delete images from pub/media/wysiwyg/new/ by FTP (SSH)
> 3. Go to text editor and insert image, all thumbnail images in wysiwyg/new/ still exist
> 
> Both issues exist in Magento 2.3.5-p2 and 2.4.0

@minhluan259 - Magento Provide the Instance so I can't able to verify this issue in my local system.

**Comment by joemstar** [comment]
I thought of one more detail that may have led to this problem. I attempted to upgrade from 2.3.5-p1 to 2.4.0. However, the upgrade failed because my hosting provider was only running ElasticSearch 6 instead of 7. Therefore, I downgraded to 2.3.5-p2. I generally try not to perform downgrades and I'm not sure if this is related to the issue I'm having with image uploads. But I thought it could be helpful information

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-29383-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29383-2-4-develop.instances.magento-community.engineering/admin_8882](https://i-29383-2-4-develop.instances.magento-community.engineering/admin_8882)
Login: `d607f106` Password: `4ce3cd53c46b`
Instance will be terminated in up to 3 hours.

**Comment by joemstar** [comment]
@ajijshekh123 Have you had any luck reproducing this issue? Is there anything additional I can do to help?

**Comment by engcom-Oscar** [comment]
Hi @joemstar 

Thank you for your report and collaboration!

I closing this issue, because I was unable to reproduce it using provided Steps to Reproduce from the Description section on clean 2.4-develop and 2.3.5-p2 version of Magento. Perhaps the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the Description section and reopen this issue.

**Comment by joemstar** [comment]
I have been unable to resolve this issue. I still cannot open the image uploader. What additional information can I provide to help get a resolution to this?
