### ISSUE TITLE
Subtotal Cart Price Rule excludes product tax for fixed amount

### ISSUE THREAD

**Issue by bckpff** [magento/magento2#29740]
### Preconditions (*)
Reproducing on 2.4-develop
Magento ver. 2.3.5-p2 - upgraded from 2.3.5-p1 using composer

- Product price includes product tax. Product tax is 5%. Shipping table rate is 10,- €.
- Create subtotal cart price rule to apply 10 € fixed discount if subtotal is greater or equal than 50,- €

### Steps to reproduce (*)

- As customer, add two products to cart (f.e. 2x "Gwyn Endurance Tee" from sample data, 24,- € each)
- Go to checkout
- Look at the shipping costs displayed as part of the cart price
- The shipping costs are 10 €
- Cart subtotal incl. tax is  50,40 € 
- Tax is 2,40
- Cart subtotal excl. tax is 48,- €

### Expected result (*)

- At checkout, the subtotal cart rule should evaluate the product price including tax, being 50,40 €
- The subtotal cart rule applies the 10,- € amount
- The order total is cart subtotal incl. tax (50,40 €) + shipping costs (10,- €) - discount (10,- €) => 50,40 €

### Actual result (*)

- At checkout, the subtotal cart rule should evaluate the product price including tax, being 50,40 €
- The subtotal cart rule does not apply the fixed discount amount of 10,- € 
- The order total remains as cart subtotal incl. tax (50,40 €) + shipping costs (10,- €) => 60,40 €

This pobably relates to: https://github.com/magento/magento2/issues/28472
The related PR did not fix my issue. 

Edit: I could reproduce this behaviour on a fresh 2.4-develop instance.

**Comment by madhippieqq** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @madhippieqq. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @madhippieqq, here is your [Magento instance](https://i-29740-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29740-2-4-develop.instances.magento-community.engineering/admin_75c5](https://i-29740-2-4-develop.instances.magento-community.engineering/admin_75c5)
Login: `a749cc0b` Password: `070b466cba2a`
Instance will be terminated in up to 3 hours.

**Comment by madhippieqq** [comment]
Could reproduce this issue on 2.4-develop

**Comment by albsa** [comment]
We commited patch https://github.com/pixelhed/magento2/commit/25ea6caf9f64c9ad55e951c54bbb633b84f3dcc2 thanks to @pixelhed 

This fixed the issue for us temporarily untill core fix is released.

**Comment by madhippieqq** [comment]
I applied the same patch. This didn't work for me.

**Comment by albsa** [comment]
@madhippieqq how did you apply the patch? we had to make some addjustments to the patch file.
Did you follow the instructions how to apply a patch in Magento 2?
Then you would have to edit the patch file because the original file contains path of local core code. You have to adjust to composer vendor modules file path.

Note: this is a .diff file

`diff --git a/Model/Sales/Total/Quote/CommonTaxCollector.php b/Model/Sales/Total/Quote/CommonTaxCollector.php
index c7cc4ded1bf0..cc37cba69ffe 100644
--- a/Model/Sales/Total/Quote/CommonTaxCollector.php
+++ b/Model/Sales/Total/Quote/CommonTaxCollector.php
@@ -596,8 +596,8 @@ protected function processProductItems(
         $address = $shippingAssignment->getShipping()->getAddress();
         $address->setBaseTaxAmount($baseTax);
         $address->setBaseSubtotalTotalInclTax($baseSubtotalInclTax);
-        $address->setSubtotal($total->getSubtotal());
-        $address->setBaseSubtotal($total->getBaseSubtotal());
+        //$address->setSubtotal($total->getSubtotal());
+        //$address->setBaseSubtotal($total->getBaseSubtotal());

         return $this;
     }
`

https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html

**Comment by madhippieqq** [comment]
@albsa Since it were only two changed lines , I just applied the changes to Model/Sales/Total/Quote/CommonTaxCollector.php on my local machine manually, cleared cache and generation folder and retried. The error still occurs on magento 2.3.5-p2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37729` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by voleye** [comment]
@magento I am working on this

**Comment by voleye** [comment]
@magento add to contributors team

**Comment by voleye** [comment]
@magento I am working on this

**Comment by voleye** [comment]
@magento-engcom-team seems it is not a bug. Magento has an appropriate setting sin Store->Configuration->Sales->Tax->Calculation Settings
Apply Discount On Prices (Excluding Tax|Including Tax) and description: 
"
Warning: To apply the discount on prices including tax and apply the tax after discount, set Catalog Prices to “Including Tax”.
"
So, if you would like to apply discount on a price value including tax then you have to make appropriate configuration in particular set Catalog Prices to “Including Tax”

**Comment by bernieu2** [comment]
@voleye but this issue is relating to a cart price rule for a fixed amount on order. Not related to specific product prices? I definitely think this is a bug. A few issues have raised now. https://github.com/magento/magento2/issues/28472 perhaps this one is related too? https://github.com/magento/magento2/issues/13392
I think it is difficult to evaluate the issue as tax has many variables dependent on user country. This is especially true when a merchant sells taxable and non-taxable goods in the same transaction; we cannot apply a simple 'workaround' by changing the discount gate amount to exclusive of tax.

For example - I have the following settings in Tax Configuration. My tax rate is 10%. 
![Screenshot from 2020-10-27 11-55-32](https://user-images.githubusercontent.com/65838389/97244333-7ede2180-184c-11eb-9366-0b7a121446dd.png)
![Screenshot from 2020-10-27 11-55-45](https://user-images.githubusercontent.com/65838389/97244337-830a3f00-184c-11eb-9afd-e6c0c6366f25.png)

Now, I have created a cart price rule that gives $15.95 discount (the relevant shipping cost) to the cart when a customers cart totals $199 or more.
![Screenshot from 2020-10-27 11-57-16](https://user-images.githubusercontent.com/65838389/97244656-61f61e00-184d-11eb-8163-52fda552ea31.png)
![Screenshot from 2020-10-27 11-57-34](https://user-images.githubusercontent.com/65838389/97244664-64587800-184d-11eb-8e01-de5b48b254ef.png)

I think its important to note here that there is option for Subtotal Excl Tax or Subtotal. One would assume the latter is inclusive of tax.
![Screenshot from 2020-10-27 12-07-33](https://user-images.githubusercontent.com/65838389/97244703-805c1980-184d-11eb-85a8-9f6508626878.png)

Now, for simplicity sake I have added a taxable item to cart worth $10 (which is actually $9.09 excl tax + $0.91 tax). With a quantity of 20 of this item so the cart total is now $200. I then select the relevant shipping method as per cart price rule. 
NO DISCOUNT APPLIED:
![Screenshot from 2020-10-27 11-53-15](https://user-images.githubusercontent.com/65838389/97245084-5b1bdb00-184e-11eb-9d25-f31b46de4fed.png)
Now, I add two more of this product to the cart. Now my total is $220 (which includes $20.02 tax; $199.98 exclusive of tax). DISCOUNT IS APPLIED:
![Screenshot from 2020-10-27 11-55-08](https://user-images.githubusercontent.com/65838389/97245216-a635ee00-184e-11eb-9ea1-86985865862d.png)

It seems Magento is using the price exclusive of tax to calculate whether the sales price rule applies. This is not consistent with the tax settings or the cart price rule settings. To the customer, it seems like we are lying or duping them with our cart price offer.

After applying the patch linked above:
https://github.com/pixelhed/magento2/commit/25ea6caf9f64c9ad55e951c54bbb633b84f3dcc2

Now, I re-add the same product, quantity and select the relevant shipping method and the discount is applied correctly:
![Screenshot from 2020-10-27 11-59-43](https://user-images.githubusercontent.com/65838389/97245417-1ba1be80-184f-11eb-9932-0a9eeb09e574.png)

Perhaps this patch causes other issues for other users who don't include tax in catalog prices etc... I don't know. But for merchants that do, it is a problem. Thoughts?

**Comment by voleye** [comment]
@bernieu2 thank you for so detailed description, I will try to reproduce the issue again making all these settings!
