### ISSUE TITLE
Elastic Search issue with Synonyms

### ISSUE THREAD

**Issue by soumiktuban** [magento/magento2#30104]
### Preconditions (*)

1. Magento 2.3.*. 
2. Elasticsearch 6+

Also reproducible on 2.4-develop with Elasticsearch7

### Steps to reproduce (*)

1. Enable Elasticsearch 6+
2. Add a product with a long name with a slash / in it.
Example: LSS 3/8"X3/4"X25' EZ-PULL 1/2" INS SWEAT LINESET W/90 END BEND SUCTION LINE INSULATED
3. Add Search Synonyms with a word belongs to the product name.
Example: center end boot,torpedo boot,horn boot,register boot center end,register boot torpedo
4. Search in the frontend for that exact product.

### Expected result (*)
1. Find that particular product without errors.

### Actual result (*)
1. Error report: {"0":"Warning: preg_match(): Unknown modifier '8' in \/vendor\/magento\/module-search\/Model\/SynonymAnalyzer.php on line 96","1":"#1 preg_match() called at [vendor\/magento\/module-search\/Model\/SynonymAnalyzer.php:96]\n#2 Magento\\Search\\Model\\SynonymAnalyzer->findInArray() called at [vendor\/magento\/module-search\/Model\/SynonymAnalyzer.php:71]

### Additional info
1. Create a product with below product name as mentioned earlier:
![image](https://user-images.githubusercontent.com/10050358/95423336-8ce00700-095e-11eb-8735-71dc67a30b29.png)

2. Create a Search Synonyms (Marketing -> Search Synonyms) and clear the cache as mentioned earlier:
![image](https://user-images.githubusercontent.com/10050358/95423622-01b34100-095f-11eb-846c-404645a90938.png)

3. Copy the entire product name and search in frontend.
![image](https://user-images.githubusercontent.com/10050358/95423746-3921ed80-095f-11eb-9bc7-7bb271c453c6.png)

4. Hit enter
![image](https://user-images.githubusercontent.com/10050358/95423965-8aca7800-095f-11eb-9d63-32c8a7d5aac4.png)

5. Here is the message from the report:
![image](https://user-images.githubusercontent.com/10050358/95424072-bea59d80-095f-11eb-9cfc-122d51355985.png)

6. Here is my configuration:
![image](https://user-images.githubusercontent.com/10050358/95424225-f4e31d00-095f-11eb-9185-352dfe9b4f9f.png)

**Comment by engcom-Oscar** [comment]
Hello @soumiktuban  

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck it on clean Magento 2.4 installation and confirm?

**Comment by soumiktuban** [comment]
I don't have a system ready for Magento 2.4 right now. Kindly keep it open till I get a system to confirm. 
Please let me know if this issue can be fixed by using a patch on Magento 2.3.*.

Thanks :)

**Comment by engcom-Oscar** [comment]
Sorry, but  we are able to process, collaborate, fix, and deliver pull requests ONLY for Issues that can be reproduced on the latest [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop) public branch.
- [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)  <details><summary>Quote</summary>
**v2.4 Contribution Notice:** Magento is focusing development efforts on v2.4, so we are no longer accepting pull requests to the v2.3, v2.2, v2.1, and v2.0 release lines.

**Comment by soumiktuban** [comment]
Hello @engcom-Oscar 

This issue is still reproducible on Magento 2.4
Below snaps are the steps to reproduce the issue:

1. Create a product with below product name as mentioned earlier:
![image](https://user-images.githubusercontent.com/10050358/95423336-8ce00700-095e-11eb-8735-71dc67a30b29.png)

2. Create a Search Synonyms (Marketing -> Search Synonyms) and clear the cache as mentioned earlier:
![image](https://user-images.githubusercontent.com/10050358/95423622-01b34100-095f-11eb-846c-404645a90938.png)

3. Copy the entire product name and search in frontend.
![image](https://user-images.githubusercontent.com/10050358/95423746-3921ed80-095f-11eb-9bc7-7bb271c453c6.png)

4. Hit enter
![image](https://user-images.githubusercontent.com/10050358/95423965-8aca7800-095f-11eb-9d63-32c8a7d5aac4.png)

5. Here is the message from the report:
![image](https://user-images.githubusercontent.com/10050358/95424072-bea59d80-095f-11eb-9cfc-122d51355985.png)

6. Here is my configuration:
![image](https://user-images.githubusercontent.com/10050358/95424225-f4e31d00-095f-11eb-9185-352dfe9b4f9f.png)

Hope this will help you to reproduce the issue.

Thanks,
Soumik

**Comment by soumiktuban** [comment]
@engcom-Oscar @magento-engcom-team  
Any update? 
Are you able to reproduce this issue?

**Comment by soumiktuban** [comment]
@magento-engcom-team  @engcom-Oscar  - Any update?

**Comment by engcom-Bravo** [comment]
Hello @soumiktuban 

Thank you for your report and detailed description

We are able to reproduce the issue on the latest 2.4-develop with Elasticsearch7
We Confirm the issue and move it further to Ready for Development

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38560` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by soumiktuban** [comment]
> Hello @soumiktuban
> 
> Thank you for your report and detailed description
> 
> We are able to reproduce the issue on the latest 2.4-develop with Elasticsearch7
> We Confirm the issue and move it further to Ready for Development

Hi @engcom-Bravo 

Good to know that you are able to reproduce the issue. Once the issue got fixed please let me know if we can have a patch on it for Magento 2.3.x.

Thanks,
Soumik

**Comment by denchev** [comment]
@magento give me 2.4-develop instance

**Comment by denchev** [comment]
I can reproduce the issue so @magento I am working on this

**Comment by denchev** [comment]
@magento add to contributors team

**Comment by denchev** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @soumiktuban. Thank you for your report. 
The issue has been fixed in magento/magento2#30614 by @denchev in 2.4-develop branch
Related commit(s):
 - [b21693a04f4d92fc3afb4c530363d9304beb7b2e](https://github.com/magento/magento2/commit/b21693a04f4d92fc3afb4c530363d9304beb7b2e)
 - [c36f29b1c66720217c52b63b6a79801ff29c5f1e](https://github.com/magento/magento2/commit/c36f29b1c66720217c52b63b6a79801ff29c5f1e)
 - [b75440eea2c6d2bda4ec588c29cf2876a5d6c9ce](https://github.com/magento/magento2/commit/b75440eea2c6d2bda4ec588c29cf2876a5d6c9ce)
 - [64cb4937defb8fdb7dbb8cb98456098b64bb2b8b](https://github.com/magento/magento2/commit/64cb4937defb8fdb7dbb8cb98456098b64bb2b8b)

The fix will be available with the upcoming 2.4.2 release.
