### ISSUE TITLE
Varnish cache is cleared for the product and categories after an order is placed

### ISSUE THREAD

**Issue by bmitchell-ldg** [magento/magento2#30128]
### Preconditions (*)
1. Magento 2.3.5 
2. Varnish-6.0.6
3. Elasticsearch 6
4. PHP 7.2.30

### Steps to reproduce (*)
1. Go to a category page and inspect the page and refresh until you see a x-cache HIT confirming that the page is being cached 
2. Pick a simple product on that category page and on the product page inpect the page and refresh until you see the x-cache HIT confirming that the page is being cached 
3. purchase that product
4. within the next couple of minutes you will see a purge request sent to varnish for that product i assume because the stock level changed (product saved)
-   ReqMethod      PURGE
-   ReqURL         /
-   ReqHeader      X-Magento-Tags-Pattern: ((^|,)cat_p_43(,|$))
5. refresh the category and product pages and see the x-cache MISS for both the category and product pages related to that specific product

The more categories the product is related to the more of an issue it causes for the website as all of the categories related to the product are being purged.

### Expected result (*)
1. Since the actual stock level is not something that is displayed on the frontend as default, then i can't think of a reason why it should need to purge the cache everytime the quantity changes. I would have thought it would only carry out the cache purge if the stock status had changed because it would need to show the new instock/out of stock status on the product/category pages. Any website with fast selling products is never going to be able to keep the cache warm. 

### Actual result (*)
1. Placing an order causes all cache tags related to that product to be cleared.

Severity: **S2**

**Comment by bmitchell-ldg** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by bmitchell-ldg** [comment]
Hello, 
I am unable to use varnish on the 2.4 testing instance to be able to fully replicate the issue we are seeing, but i have been able to see the same behaviour using the built in cache on product pages. 

**Product Page Cache Tests*
I have added screenshots below
- Screenshot shows the page load on a cached page
- I have then placed an order for the product
- a couple of minutes after the order is placed, you can see the cache has been purged for that product, you can see it by the page load time increase when inspecting the network tab. 
<img width="1384" alt="Screenshot 2020-09-21 at 14 22 49" src="https://user-images.githubusercontent.com/3041320/93772116-5abc6e80-fc16-11ea-8d43-9e2496ff58f7.png">
<img width="1076" alt="Screenshot 2020-09-21 at 14 20 53" src="https://user-images.githubusercontent.com/3041320/93772130-5e4ff580-fc16-11ea-999d-054094ce8324.png">
<img width="1334" alt="Screenshot 2020-09-21 at 14 20 43" src="https://user-images.githubusercontent.com/3041320/93772136-6019b900-fc16-11ea-918d-0bbd94901fbd.png">
<img width="1234" alt="Screenshot 2020-09-21 at 14 19 36" src="https://user-images.githubusercontent.com/3041320/93772142-61e37c80-fc16-11ea-952f-f8fca119d53f.png">

**Comment by bmitchell-ldg** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by gwharton** [comment]
Could be because of "only X left" functionality. If so it should only clear cache if qty is less than threshold I guess.

**Comment by bmitchell-ldg** [comment]
@gwharton thank you for your suggestion, i set "only X left" functionality to 0 for all sites in case it was that and it's unfortunately still an issue for us.
When we place an order, a purge request is sent to varnish for the products in the order, which i think isn't expected behaviour. 
**Example** 
1 order containing 8 products, 1 purge request sent to varnish containing the cache tags for those 8 products causing them to go to a cache MISS. 
![image (76)](https://user-images.githubusercontent.com/3041320/103882396-a3b80600-50d3-11eb-8ec4-7239c7eac9f7.png)
![Screenshot 2021-01-06 at 12 12 34](https://user-images.githubusercontent.com/3041320/103882402-a61a6000-50d3-11eb-8cca-c08ff3913f44.png)
I'm currently debugging this now, so will hopefully have some more information soon.

**Comment by bmitchell-ldg** [comment]
I disabled all of our custom modules and any 3rd party ones and it was still happening, it seems to be down to a plugin called afterUpdateMview in vendor/magento/module-indexer/Model/Processor/CleanCache.php 

`/**
     * Update indexer views
     *
     * @param \Magento\Indexer\Model\Processor $subject
     * @return void
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function afterUpdateMview(\Magento\Indexer\Model\Processor $subject)
    {
        $this->eventManager->dispatch('clean_cache_after_reindex', ['object' => $this->context]);
        if (!empty($this->context->getIdentities())) {
            $this->getCache()->clean($this->context->getIdentities());
        }
    }`

I have added some logging to our dev enviroment and i can see that when the order is placed it uses a function called clean in vendor/magento/module-catalog-inventory/Model/Indexer/Stock/CacheCleaner.php which has the logic in to see if the stock status has changed and this only purges the caches if the status is changed and not the stock level which works perfectly.

`/**
     * Clean cache by product ids.
     *
     * @param array $productIds
     * @param callable $reindex
     * @return void
     */
    public function clean(array $productIds, callable $reindex)
    {
        $productStatusesBefore = $this->getProductStockStatuses($productIds);
        $reindex();
        $productStatusesAfter = $this->getProductStockStatuses($productIds);
        $productIds = $this->getProductIdsForCacheClean($productStatusesBefore, $productStatusesAfter);
        if ($productIds) {
            $this->cacheContext->registerEntities(Product::CACHE_TAG, array_unique($productIds));
            $this->eventManager->dispatch('clean_cache_by_tags', ['object' => $this->cacheContext]);
        }
    }`

but then later on afterUpdateMview is actioned and purges the caches anyway

[2021-01-29 13:25:08] report.INFO: After update mview [["cat_p_837","cat_p_837"]] []
[2021-01-29 13:25:08] report.INFO: Bare Tags  [["cat_p_837","cat_p_837"]] []
[2021-01-29 13:25:08] report.INFO: Sending purge request for Tags  [["((^|,)cat_p_837(,|$))","((^|,)cat_p_837(,|$))"]] []
[2021-01-29 13:25:08] report.INFO: Cron Job indexer_update_all_views is successfully finished.

Varnish output
<< Request  >> 2064457   
-   ReqMethod      PURGE
-   ReqHeader      X-Magento-Tags-Pattern: ((^|,)cat_p_837(,|$))
- -   RespReason     Purged
-   RespHeader     Date: Fri, 29 Jan 2021 13:25:08 GMT
-   RespHeader     Server: Varnish

**Comment by bmitchell-ldg** [comment]
I disabled all of our custom modules and any 3rd party ones and it was still happening, i think it might be down to a plugin called afterUpdateMview in vendor/magento/module-indexer/Model/Processor/CleanCache.php which i can see being called after the reindex has completed

![Screenshot 2021-01-29 at 16 47 08](https://user-images.githubusercontent.com/3041320/107345464-7dfb9380-6abb-11eb-824e-d98ebc71a8e1.png)

I added some logging to our dev enviroment and i can see that when the order is placed it actions a function called clean in vendor/magento/module-catalog-inventory/Model/Indexer/Stock/CacheCleaner.php which has the logic in to see if the stock status has changed and this only purges the caches if the status is changed and not the stock level which works perfectly.

![Screenshot 2021-01-29 at 16 47 17](https://user-images.githubusercontent.com/3041320/107345535-94a1ea80-6abb-11eb-87db-96e298f4d413.png)

but then afterUpdateMview is actioned and sends the purge

[2021-01-29 13:25:08] report.INFO: After update mview [["cat_p_837","cat_p_837"]] []
[2021-01-29 13:25:08] report.INFO: Bare Tags  [["cat_p_837","cat_p_837"]] []
[2021-01-29 13:25:08] report.INFO: Sending purge request for Tags  [["((^|,)cat_p_837(,|$))","((^|,)cat_p_837(,|$))"]] []
[2021-01-29 13:25:08] report.INFO: Cron Job indexer_update_all_views is successfully finished.

Varnish output
<< Request  >> 2064457   
-   ReqMethod      PURGE
-   ReqHeader      X-Magento-Tags-Pattern: ((^|,)cat_p_837(,|$))
-   RespReason     Purged
-   RespHeader     Date: Fri, 29 Jan 2021 13:25:08 GMT
-   RespHeader     Server: Varnish

Will continue debugging and update when i find anything else

**Comment by bmitchell-ldg** [comment]
Spent a little more time looking into this and found the following;
When an order is placed depending on if the stock status is changed it either sends 2 or 3 purges to varnish.

Place an order with a product that has plenty of stock and the purges are sent from
- Magento\Indexer\Model\Processor\CleanCache function called afterUpdateMview
- Magento\Indexer\Model\Indexer\CacheCleaner function called afterExecuteList

Place an order but make the product out of stock (the stock status changes) and the purges are sent from 
- Magento\Indexer\Model\Processor\CleanCache function called afterUpdateMview
- Magento\Indexer\Model\Indexer\CacheCleaner function called afterExecuteList
- Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner function called clean

The correct logic to only purge the cache if the stock status changes is in Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner so i'm trying to figure out why a purge is also sent from the other two (afterUpdateMview, afterExecuteList) if i remove those after plugins everything still flushes as expected when it's supposed to (regarding actions to stock, pricing, product data, categories etc).

**Comment by bmitchell-ldg** [comment]
In our instance we removed both after plugins
Magento\Indexer\Model\Processor\CleanCache function called afterUpdateMview
Magento\Indexer\Model\Indexer\CacheCleaner function called afterExecuteList

The only issue we found when removing those two plugins was the purge not being sent for the $stockThresholdQty logic in Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner when it needed to flush the cache to change the X amount qty display on the frontend (everything else regarding stock, products, categories and attributes purged as expected). 

$stockThresholdQty = $this->stockConfiguration->getStockThresholdQty(); 
returns 
$this->scopeConfig->getValue(self::XML_PATH_STOCK_THRESHOLD_QTY,ScopeInterface::SCOPE_STORE,$store);

But i realised the storeId is not passed in at this point so it was just taking the value from the default store, in our instance we have 12 stores so it wasn't purging the cache for the products that fell into the check to see if $statusAfter['qty'] <= $stockThresholdQty because we had the value set to 0 at default store.

Another thing we noticed is if you have $stockThresholdQty set to 0 at default store it makes the configurable product cache be purged on every order placed because $statusAfter['qty'] is always 0.
Example of the output for $statusAfter after buying a child product
"36786":{"product_id":"36786","stock_status":"1","qty":"0.0000","parent_id":null}}

As a quick work around we;

- created patches to remove the two after plugins

- changed the default value for Only X left Threshold (cataloginventory/options/stock_threshold_qty) to a value we would be happy to use for all stores

- Added a preference for Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner and changed the logic for getProductIdsForCacheClean to

    /**
     * Return list of product ids that need to be flushed from cache
     *
     * @param array $productStatusesBefore
     * @param array $productStatusesAfter
     * @return array
     */
    private function getProductIdsForCacheClean(array $productStatusesBefore, array $productStatusesAfter)
    {
        $disabledProductsIds = array_diff(array_keys($productStatusesBefore), array_keys($productStatusesAfter));
        $enabledProductsIds = array_diff(array_keys($productStatusesAfter), array_keys($productStatusesBefore));
        $commonProductsIds = array_intersect(array_keys($productStatusesBefore), array_keys($productStatusesAfter));
        $productIds = array_merge($disabledProductsIds, $enabledProductsIds);

        $stockThresholdQty = $this->stockConfiguration->getStockThresholdQty();

        foreach ($commonProductsIds as $productId) {
            $statusBefore = $productStatusesBefore[$productId];
            $statusAfter = $productStatusesAfter[$productId];

            if ($statusBefore['stock_status'] !== $statusAfter['stock_status']) {
                $productIds[] = $productId;
                if (isset($statusAfter['parent_id'])) {
                    $productIds[] = $statusAfter['parent_id'];
                }
            }

            if($statusAfter['qty'] > 0) {
                if ($stockThresholdQty && $statusAfter['qty'] <= $stockThresholdQty) {
                    $productIds[] = $productId;
                }
            }
        }

        return $productIds;
    }

This is only a workaround until a full solution can be looked at, but saves the caches from being unnecessarily flushed.

**Comment by gregorybesson** [comment]
Hello @bmitchell-ldg  and thanks for your detailed study.

I'm working on a 2.4.1 EE version and had the same problem. You're detailed explanation has been invaluable to me.

Your solution was almost ok, but I've added another fix to take care of the stock/source reindex which produces a cache clear on the items also. 

The total fix is something like that:

`di.xml`

```
<!-- These AOP after methods from the Magento 2 core clear the cache (when stock/source is in SYNC mode) after an order -->
<!-- has been placed even when the status of the products has not changed (but the qty has changed) -->
<!-- this bug : https://github.com/magento/magento2/issues/30128 -->
<!-- does show the problem + part of the solution -->
<!-- The impact is huge on perf. See the documentation for details -->
<type name="Magento\Indexer\Model\Processor">
    <plugin name="page-cache-indexer-reindex-clean-cache" disabled="true"/>
</type>
<type name="Magento\Framework\Indexer\ActionInterface">
    <plugin name="cache_cleaner_after_reindex" disabled="true"/>
</type>
<type name="Magento\InventoryIndexer\Indexer\SourceItem\Strategy\Sync">
    <plugin name="invalidate_products_cache" disabled="true"/>
    <plugin name="lc_invalidate_products_cache" type="LivingColor\Api\Plugin\InventoryIndexer\Indexer\SourceItem\Strategy\Sync\CacheFlush"/>
</type>
<type name="LivingColor\Api\Model\ResourceModel\GetProductIdsBySourceItemIds">
    <arguments>
        <argument name="productTableName" xsi:type="string">catalog_product_entity</argument>
    </arguments>
</type>
```

`LivingColor\Api\Plugin\InventoryIndexer\Indexer\SourceItem\Strategy\Sync\CacheFlush`: (the only change is the usage of `use LivingColor\Api\Model\ResourceModel\GetProductIdsBySourceItemIds` to select only products changing status
```
<?php
declare(strict_types=1);

namespace LivingColor\Api\Plugin\InventoryIndexer\Indexer\SourceItem\Strategy\Sync;

use Magento\InventoryCache\Model\FlushCacheByProductIds;
use Magento\InventoryIndexer\Indexer\SourceItem\Strategy\Sync;
use LivingColor\Api\Model\ResourceModel\GetProductIdsBySourceItemIds;

/**
 * Clean cache for corresponding products after source item reindex.
 */
class CacheFlush
{
    /**
     * @var FlushCacheByProductIds
     */
    private $flushCacheByIds;

    /**
     * @var GetProductIdsBySourceItemIds
     */
    private $getProductIdsBySourceItemIds;

    /**
     * @param FlushCacheByProductIds $flushCacheByIds
     * @param GetProductIdsBySourceItemIds $getProductIdsBySourceItemIds
     */
    public function __construct(
        FlushCacheByProductIds $flushCacheByIds,
        GetProductIdsBySourceItemIds $getProductIdsBySourceItemIds
    ) {
        $this->flushCacheByIds = $flushCacheByIds;
        $this->getProductIdsBySourceItemIds = $getProductIdsBySourceItemIds;
    }

    /**
     * Clean cache for specific products after source items reindex.
     *
     * @param Sync $subject
     * @param void $result
     * @param array $sourceItemIds
     * @throws \Exception in case catalog product entity type hasn't been initialized.
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function afterExecuteList(Sync $subject, $result, array $sourceItemIds)
    {
        $productIds = $this->getProductIdsBySourceItemIds->execute($sourceItemIds);
        $this->flushCacheByIds->execute($productIds);
    }
}
```

Last but not least

`LivingColor\Api\Model\ResourceModel\GetProductIdsBySourceItemIds`

```
<?php
declare(strict_types=1);

namespace LivingColor\Api\Model\ResourceModel;

use Magento\Framework\App\ResourceConnection;
use Magento\Inventory\Model\ResourceModel\SourceItem;
use Magento\InventoryApi\Api\Data\SourceItemInterface;

/**
 * Provides product ids related to specified source items ids.
 */
class GetProductIdsBySourceItemIds
{
    /**
     * @var ResourceConnection
     */
    private $resource;

    /**
     * @var string
     */
    private $productTableName;

    /**
     * @param ResourceConnection $resource
     * @param string $productTableName
     */
    public function __construct(
        ResourceConnection $resource,
        string $productTableName
    ) {
        $this->resource = $resource;
        $this->productTableName = $productTableName;
    }

    /**
     * Get product ids related to specified source items.
     * We've added the filter on stock status. The calculation is not definitely good
     * as it could fail if multiple sources are used (the sum of the quantity of a SKU has to be done)
     * or all the sources have to declare the SKU as out of stock to be good.
     *
     * But for now it's enough : We have only one source.
     * This way, we clear the cache ONLY when the product is out of stock.
     *
     * @param array $sourceItemIds
     * @return array
     */
    public function execute(array $sourceItemIds): array
    {
        $connection = $this->resource->getConnection();
        $outOfStockStmt = new \Zend_Db_Expr(
            'source_item.' . SourceItemInterface::QUANTITY . ' = 0 OR source_item.' . SourceItemInterface::STATUS . ' = ' . SourceItemInterface::STATUS_OUT_OF_STOCK
        );
        $select = $connection->select()
            ->from(
                ['source_item' => $this->resource->getTableName(SourceItem::TABLE_NAME_SOURCE_ITEM)],
                []
            )->where(
                'source_item.' . SourceItem::ID_FIELD_NAME . ' IN (?)',
                $sourceItemIds
            )->where(
                $outOfStockStmt
            )->join(
                ['product' => $this->resource->getTableName($this->productTableName)],
                'source_item.' . SourceItemInterface::SKU . ' = product.sku',
                ['product.entity_id']
            )->distinct();

        return $connection->fetchCol($select);
    }
}
```

Hope it will help Magento team to fix / improve it.

Greg

**Comment by bartoszkubicki** [comment]
doesnt seem to be resolved

**Comment by jitheesh-lumi** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by mrtuvn** [comment]
@bmitchell-ldg have you recheck this problem at latest code ?

**Comment by nemanjamm** [comment]
> In our instance we removed both after plugins
> Magento\Indexer\Model\Processor\CleanCache function called afterUpdateMview
> Magento\Indexer\Model\Indexer\CacheCleaner function called afterExecuteList
> 
> The only issue we found when removing those two plugins was the purge not being sent for the $stockThresholdQty logic in Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner when it needed to flush the cache to change the X amount qty display on the frontend (everything else regarding stock, products, categories and attributes purged as expected).
> 
> $stockThresholdQty = $this->stockConfiguration->getStockThresholdQty();
> returns
> $this->scopeConfig->getValue(self::XML_PATH_STOCK_THRESHOLD_QTY,ScopeInterface::SCOPE_STORE,$store);
> 
> But i realised the storeId is not passed in at this point so it was just taking the value from the default store, in our instance we have 12 stores so it wasn't purging the cache for the products that fell into the check to see if $statusAfter['qty'] <= $stockThresholdQty because we had the value set to 0 at default store.
> 
> Another thing we noticed is if you have $stockThresholdQty set to 0 at default store it makes the configurable product cache be purged on every order placed because $statusAfter['qty'] is always 0.
> Example of the output for $statusAfter after buying a child product
> 
> Product status before
> [{"837":{"product_id":"837","stock_status":"1","qty":"124.0000","parent_id":"21176"},
> "20326":{"product_id":"20326","stock_status":"1","qty":"0.0000","parent_id":null},
> "21176":{"product_id":"21176","stock_status":"1","qty":"0.0000","parent_id":null}}] []
> 
> Product status after
> [{"837":{"product_id":"837","stock_status":"1","qty":"123.0000","parent_id":"21176"},
> "20326":{"product_id":"20326","stock_status":"1","qty":"0.0000","parent_id":null},
> "21176":{"product_id":"21176","stock_status":"1","qty":"0.0000","parent_id":null}}] []
> 
> As a quick work around we;
> 
> * created patches to remove the two after plugins
> * changed the default value for Only X left Threshold (cataloginventory/options/stock_threshold_qty) to a value we would be happy to use for all stores
> * Added a preference for Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner and changed the logic for getProductIdsForCacheClean to
> 
> ![Screenshot 2021-03-01 at 10 48 04](https://user-images.githubusercontent.com/3041320/109487058-9ee05480-7a7b-11eb-8b28-71a16c6ce662.png)
> 
> and changed the clean function to
> ![Screenshot 2021-06-08 at 15 56 12](https://user-images.githubusercontent.com/3041320/121208612-19d2bb80-c872-11eb-940e-999451c1081c.png)
> to take care of cache flushes for configurable products with swatches
> 
> This is only a workaround until a full solution can be looked at, but saves the caches from being unnecessarily flushed.
> We will extensively test this in both dev and live environments.

@bmitchell-ldg can you share repo with patches or patches here? Thank you

**Comment by mrtuvn** [comment]
Lol

**Comment by mrtuvn** [comment]
Right now a lot of code changed but i don't see author response any new updates. Feel free to recheck problem with 2.4.3 or 2.4-develop

**Comment by mrtuvn** [comment]
@bmitchell-ldg can you have time for check in 2.4 develop code

**Comment by multipasko** [comment]
The problem is still there on Magento 2.4.3

**Comment by multipasko** [comment]
@gregorybesson thanks for your code. How is it going to work if product out of stock wants to get back to be "in stock".
It seems your code would clear the cache only when getting to out of stock and not do it again when the inventory gets back positive.

**Comment by gregorybesson** [comment]
> @gregorybesson thanks for your code. How is it going to work if product out of stock wants to get back to be "in stock". It seems your code would clear the cache only when getting to out of stock and not do it again when the inventory gets back positive.

Hello @multipasko you're fully right, this use case should be taken into account. It's not the case in the fix I've proposed

**Comment by kestraly** [comment]
+1 with this issue - FPC is included in the tags 

Tags: cat_p_3368,FPC

Followed by 

Tags: cat_p_3368

**Comment by korostii** [comment]
FYI anyone whom this may concern: this issue is supposedly being fixed in 2.4.4, at least according to [the beta's releases notes](https://devdocs-beta.magento.com/guides/v2.4/release-notes/commerce-2-4-4.html#cache).

**Comment by hostep** [comment]
@onlinebizsoft: they link to https://github.com/magento/magento2/pull/33468 from the release notes.

You can find this by viewing the source code of the release notes, every issue is being prepended by some reference to a ticket number or something else and searching github for this can often show you want they reference there, example:
<img width="1086" alt="Screenshot 2022-02-07 at 13 51 51" src="https://user-images.githubusercontent.com/85479/152791620-5e2d1d67-fba6-42ed-9ff4-9d492a2393f6.png">

**Comment by onlinebizsoft** [comment]
@hostep I'm not very clear about the git flow of Magento product, not sure when this git repository (2.4-develop branch) merged into release,.....if there is any easy way or some points where we can see all issues or pull requests will be included in 2.4.4 release then it would be great.

**Comment by hostep** [comment]
@onlinebizsoft: most details can be found in the [release notes](https://devdocs-beta.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html) (there is a chance these aren't finalised yet, because it's on the "beta" devdocs environment). At the bottom of the release notes, there is a big amount of links to github issues and pull requests.

Hope this helps a bit 🙂

**Comment by Legeakademiet** [comment]
@

> Right now a lot of code changed but i don't see author response any new updates. Feel free to recheck problem with 2.4.3 https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogInventory/Model/Indexer/Stock/CacheCleaner.php#L83

Did you manage to fix it? We have the problem at with version 2.4.3.

**Comment by websecureNL** [comment]
We are experiencing a related problem when stock updates are done through the API. We use an order picking system that updates stock through API. When stock is updated, cache of the product and associated categories are purged. We are on 2.4.5. For us this means that cache is kept for less than half an hour on average. If it's true stock is also cleared on checkout it might even be worse (we are testing our new site on staging, so no orders yet).

**Comment by kestraly** [comment]
@websecureNL - That one is the most annoying at present. If you’re doing mass stock updates for all products, the indexing triggers the FPC to be cleared. So a mass action for all products does exactly the same. What’s annoying is, it’s not an FPC update at the end of the cycle, it’s an FPC one after the other. So 25,000 products updated and it clears FPC 25,000 times in all the logs that I’ve checked so far. A real drain

**Comment by jakegore** [comment]
@websecureNL Did anyone find a fix/workaround for this? We appear to be having this issue on a store that we just recently updated to 2.4.5-p1.

**Comment by JelleGe** [comment]
Is this issue solved in 2.4.6? What files are exactly changed to solve the issue?

**Comment by bmitchell-ldg** [comment]
Noticed this mentioned in the release notes for 2.4.4 
"Placing an order no longer results in the removal of all cache tags that are related to the ordered products from the Varnish cache. GitHub-30128"
I can confirm this is still an issue in 2.4.5, we placed an order for a product that has hundreds in stock, and the varnish cache was purged for the product and all related categories.

**Comment by hostep** [comment]
@bmitchell-ldg, just guessing here, but maybe this thread helps: https://github.com/magento/magento2/issues/36813
This is supposed to be fixed in the MSI modules version 1.2.6 (which gets included in Magento 2.4.6)

From [MSI release notes](https://experienceleague.adobe.com/docs/commerce-admin/inventory/release-notes.html?lang=en#v1.2.6):
> - Fixed issue Category page caches are no longer invalidated when stock quantity changes and the product is still in stock. Adobe Commerce now loads pages from the cache instead of regenerating them when product quantity (and nothing else) on the storefront category page changes.
>
> ...
>
> - Fixed issue Updating product inventory in scheduled mode no longer clears all caches. Previously, the Inventory indexer cleared all configuration caches.

**Comment by alexryall** [comment]
This does appear to be fixed in 2.4.6 but not because of https://github.com/magento/magento2/issues/36813 as this is a different issue where everything gets flushed and this issue is when particular products that are ordered are flushed.

vendor/magento/module-indexer/Model/Indexer/DeferredCacheCleaner.php
```
public function flush(): void
    {
        $this->deferredCacheContext->commit();
        $this->eventManager->dispatch('clean_cache_by_tags', ['object' => $this->cacheContext]);
        $identities = $this->cacheContext->getIdentities();
        if (!empty($identities)) {
            $this->appCache->clean($identities);
            $this->cacheContext->flush();
        }
    }
```
In 2.4.5 $identities contains the tags for the unchanged products and flushes the cache. In 2.4.6 $identities is empty so the if check fails and is passed over. I haven't been able to find the change that has fixed this so will likely be looking to upgrade to 2.4.6 rather than patching our current version.

**Comment by alexryall** [comment]
This is the change in 2.4.6 that fixes this issue once and for all.
https://github.com/magento/magento2/commit/b3969936251e1a03427cd24c209abb6af3a0ce1b

**Comment by farrukhk** [comment]
This is working for simple products but for configurable products cache is still being flushed. Is there a way to fix that too?
