### ISSUE TITLE
Admin tinymce iframe should not be referenced by base static url

### ISSUE THREAD

**Issue by keithbentrup** [magento/magento2#3041]
The iframe created by tinymce used frequently in the admin should not be referenced by the base static url. Doing so, so will cause a same origin policy security error.
<img width="1761" alt="sop-violation" src="https://cloud.githubusercontent.com/assets/253579/12431672/b9f71b96-bec4-11e5-8d3e-f6bec2d486b8.png">

**Comment by i-daszkowski** [comment]
Internal issue id: APPSEC-1316

**Comment by wert2all** [comment]
Fixed

**Comment by tigerx7** [comment]
I'm curious, how was this fixed? After implementing a CDN (cdn.ourdomain.com), I'm running into the same issue and even after setting "document.domain=ourdomain.com" in tiny_mce-popup,js, we're still receiving a same-origin violation. Currently using Magento v.2.0.10.
