### ISSUE TITLE
setup:upgrade not possible in after installing Sample Data Magento 2.4.1 

### ISSUE THREAD

**Issue by NielsVroman** [magento/magento2#30685]
## Preconditions (*)
1. Magento version 2.4.1
2. PHP 7.4.11
3. MYSQL 8.0.22
4. ES 7.6.2

### Steps to reproduce (*)
1. Setup basic magento installation.
2. Set Magento into **Production Mode** bin/magento deploy:mode:set production
3. Install Magento Sample data using command: sampledata:deploy
4. Use command setup:upgrade.

### Expected result (*)
1. setup upgrade activates modules and installs the sample data in the database.

### Actual result (*)
Error thrown:
![image](https://user-images.githubusercontent.com/29861710/97428907-f4162900-1916-11eb-9133-234c3eb0fb06.png)

unable to apply data patch magento\catalogrulesampledata\setup\patch\data\installcatalogrulesampledata for module magento_catalogrulesampledata. original exception message: rolled back transaction has not been completed correctly.

In the system log:
[2020-10-28 11:12:45] main.ERROR: Sample Data error: Unable to unserialize value. Error: Syntax error [] []

Returning the string that causes the error is:
string(352) "{"type":"Magento\\CatalogRule\\Model\\Rule\\Condition\\Combine","attribute":null,"operator":null,"value":"1","is_value_processed":null,"aggregator":"all","conditions":[{"type":"Magento\\CatalogRule\\Model\\Rule\\Condition\\Product","attribute":"category_ids","operator":"()","value":%url_key=pants-women,url_key=pants-men%,"is_value_processed":false}]}"

When returning an empty array instead of throwing the error it continues into the next error:

Module 'Magento_ConfigurableSampleData':
Running data recurring...{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}

### Additional info from Engcom
Precondition **MySQL 8**

Steps to reproduce 
1. Install Magento 2.4.1 using composer `create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.1 .`
2. Deploy Sampledata `bin/magento sampledata:deploy`
3. Perform Upgrade `bin/magento setup:upgrade`

Actual Result

Setup upgrade is aborted with an error 
:x: _Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly._
![rolled_back](https://user-images.githubusercontent.com/51680745/97563910-715f9d80-19ec-11eb-8e50-ac96888931a2.png)

**Comment by engcom-Bravo** [comment]
Hello @NielsVroman 

Thank you for your report

We have rechecked the reported issue on Magento 2.4.1 and did not face any error

We have successfully deployed Sample Data using the command `bin/magento sampledata:deploy` And successfully Upgraded the instance using `bin/magento setup:upgrade` 

Can you please provide more information about your store and settings?

Thank you in advance

**Comment by NielsVroman** [comment]
@engcom-Bravo I'll try to give some more info, this is al i've got:

server is setup with 
PHP 7.4.11
MYSQL 8.0.22
ES 7.6.2

The commands we used to set magento up are as followed:
composer create-project --repository-url=https://repo.magento.com/ "$MagentoEdition" "$INSTALL_DIR" "$MagentoVersion"
Where the magento version is 2.4.1, and edition is magento/project-community-edition

"$INSTALL_DIR/bin/magento" setup:install --base-url="$MAGENTO_BASE_URL" 
--backend-frontname="$MAGENTO_BACKEND_FRONTNAME" \
--db-host="$MAGENTO_DB_HOST" 
--db-name="$MAGENTO_DB_NAME" 
--db-user="$MAGENTO_DB_USER" 
--db-password="$MAGENTO_DB_PASSWORD" \
--admin-firstname="$MAGENTO_ADMIN_FIRSTNAME" 
--admin-lastname="$MAGENTO_ADMIN_LASTNAME" 
--admin-email="$MAGENTO_ADMIN_EMAIL" \
--admin-user="$MAGENTO_ADMIN_USER" 
--admin-password="$MAGENTO_ADMIN_PASSWORD" 
--language=nl_BE 
--currency=EUR \
--timezone=Europe/Brussels 
--use-rewrites=1 
--use-secure=1 
--use-secure-admin=1 
--admin-use-security-key=1 \
--session-save=redis --key="$MAGENTO_ENCRYPTKEY" 
--cleanup-database 
--consumers-wait-for-messages=0

after this, we set the permissions.

"$RUN_DIR/bin/magento" cron:install
"$RUN_DIR/bin/magento" deploy:mode:set production
"$RUN_DIR/bin/magento" setup:config:set --cache-backend=redis --cache-backend-redis-server="$MAGENTO_REDIS_SERVER" --cache-backend-redis-db=3
"$RUN_DIR/bin/magento" setup:config:set --page-cache=redis --page-cache-redis-server="$MAGENTO_REDIS_SERVER" --page-cache-redis-db=4

after this some configurations.
	#General admin stuff
	"$RUN_DIR/bin/magento" config:set -e web/cookie/cookie_lifetime 86400;
	"$RUN_DIR/bin/magento" config:set -c web/secure/enable_upgrade_insecure 1

	#Elastic search
	"$RUN_DIR/bin/magento" config:set -e catalog/search/engine elasticsearch7
	"$RUN_DIR/bin/magento" config:set -e catalog/search/elasticsearch7_server_hostname localhost
	"$RUN_DIR/bin/magento" config:set -e catalog/search/elasticsearch7_server_port 9200
	"$RUN_DIR/bin/magento" config:set -e catalog/search/elasticsearch7_index_prefix magento2
	"$RUN_DIR/bin/magento" config:set -e catalog/search/elasticsearch7_enable_auth 0
	"$RUN_DIR/bin/magento" config:set -e catalog/search/elasticsearch7_server_timeout 15

	#Europe/Belgium stuff
	"$RUN_DIR/bin/magento" config:set -c general/locale/firstday 1
	"$RUN_DIR/bin/magento" config:set -c general/locale/weight_unit "kgs"
	"$RUN_DIR/bin/magento" config:set -c general/country/default BE

After this completes magento is running.
We install the sample data using the command.
And do setup:upgrade here it fails.

This is about everything i can give regarding the setup of magento.
These are also the only settings that are set.
No other settings were touched.

**Comment by engcom-Bravo** [comment]
Hello @NielsVroman 

Thank you for the quick response

We are able to reproduce the issue. We have discovered that the main cause of the issue is the **Production Mode**

Additional info from Engcom is added to the description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38788` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
Further investigation discovered that according to [Install Sample Data using Composer](https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-after-composer.html) article on Developer Documentation, _Installing sample data in production mode fails._ Please use Developer mode`bin/magento deploy:mode:set developer` to install Sample Data and Upgrade

**Comment by gibkigonzo** [comment]
@engcom-Bravo Hey, thanks for your investigation. I use latest docker image from https://github.com/bitnami/bitnami-docker-magento and it still fails (also in dev mode)

**Comment by martingregoire** [comment]
We had the same issue as described by @NielsVroman, deploying the sample data after installing Magento resulted in the `Unable to apply data patch` error message.

Explicitly setting Magento to Developer Mode before deploying the sample data did not help, we had the same error message.

We were able to resolve it by deploying the sample data *before* installing Magento however. Our workflow now is this:

```shell
composer create-project ...
bin/magento deploy:mode:set developer
bin/magento sampledata:deploy
bin/magento setup:install ...
bin/magento setup:upgrade
bin/magento cache:clean
```

**Comment by engcom-Bravo** [comment]
I'm reopening this issue for further investigation

**Comment by engcom-Bravo** [comment]
Seems like the cause of the issue is MySQL 8. We confirm

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38788` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by smanav7** [comment]
Hello, I am still facing this issue!

**Comment by karlgama** [comment]
I am also still have this issue!

**Comment by rfay** [comment]
Yes, this same exact failure happens as originally reported, magento 2.4.1, attempting to install sample data, in Developer mode.

**Comment by ajmalbuffy** [comment]
Am also facing the same issue, may I know what is the fix or solution for this. I am in much needed.

**Comment by NielsVroman** [comment]
I got it to work after applying the merge request.
https://github.com/magento/magento2/pull/30928/files

I applied this directly on the server as this was just a temp demo site we created.
But if you want this to work properly you should create a patch from these and add them.

**Comment by ankarpy** [comment]
How can I fix this issue?

**Comment by max3w** [comment]
I have the same problem. I'm in `bin/magento deploy:mode:set developer`, install demo data `bin/magento sampledata:deploy` then update `bin/magento setup:upgrade` And I get an error: Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly.

**Comment by PascalBrouwers** [comment]
Have the same issue with 2.4.3-p1 with includes the PR. Nothing is fixed.

**Comment by kirill533** [comment]
Same on 2.4.4:

bin/magento setup:upgrade: 
`Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly.`

System.log: `Sample Data error: Unable to unserialize value. Error: Syntax error`

**Comment by Werew1942** [comment]
Same on 2.3.5

**Comment by devphoenix2404** [comment]
I'm getting the same issue for 2.4.0, 2.4.1, 2.4.2, 2.4.3 and i've tried with all mode (default, developer)
Can anyone help here 🙏🏻

**Comment by bptsd** [comment]
Still happening in 2.4.5 for me in developer mode.  Has anyone got a solution?

**Comment by miwrona2** [comment]
I think, it is fixed in Magento ver. 2.4.3-p1. I had the same issue while trying to execute php bin/magento setup:install (I had sample data related packages in my composer.json), so I checked var/log/system.log and found this

```bash
[2022-09-29 12:25:04] main.ERROR: Sample Data error: {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [magento2_product_1_v1] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"index [magento2_product_1_v1] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403} [] []
[2022-09-29 12:25:05] main.ERROR: Sample Data error: Unable to unserialize value. Error: Syntax error [] []
[2022-09-29 12:25:05] main.ERROR: Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly.
```

After searching the web I realized, there is not much space on a disk Elasticsearch can use (inside docker container in my case). **I freed up some space** in location the container was assigned to and **it fixed issue**. There is another solution, when you don’t want to free up disk space:

[https://www.naguel.com/blocked-by-forbidden-12-index-read-only-allow-delete-api/](https://www.naguel.com/blocked-by-forbidden-12-index-read-only-allow-delete-api/)

but I haven’t tested that yet.
