### ISSUE TITLE
Translation collect-phrase command giving Parse error with PHP 7

### ISSUE THREAD

**Issue by ashishnai** [magento/magento2#3115]
Using below mentioned command 

**bin/magento i18n:collect-phrases -o "translation.csv" MAGENTO_ROOT_PATH**

gives 

**PHP Parse error:  syntax error, unexpected 'The' (T_STRING), expecting ';' in /var/www/html/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php(274) : eval()'d code on line 1**

I have tried the command on environment with PHP 5.5 and it works well. Possible reason for this error might be that **as of PHP 7, if there is a parse error in the evaluated code, eval() throws a ParseError exception. Before PHP 7, in this case eval() returned FALSE and execution of the following code continued normally.**

http://php.net/manual/en/function.eval.php

**Comment by mazhalai** [comment]
@ashishnai this issue has been fixed in the develop branch and also  in 2.0.1, can you please check using that branch/ tag?

**Comment by ashishnai** [comment]
I have taken updated code of v1.0.2. I see changes made to getCompiledString() function to handle the senario. Still geting below mentioned error.

PHP Parse error:  syntax error, unexpected ''label'' (T_CONSTANT_ENCAPSED_STRING), expecting ';' in /var/www/html/setup/src/Magento/Setup/Module/I18n/Dictionary/Phrase.php(278) : eval()'d code on line 1

**Comment by mazhalai** [comment]
@ashishnai is this still an issue?

**Comment by mazhalai** [comment]
@ashishnai closing as non-responsive.

**Comment by shireenn2587** [comment]
@mazhalai.. We are still facing this issue.. We have 2.0.2 version.
