### ISSUE TITLE
Magento 2 CLI Installation fails

### ISSUE THREAD

**Issue by AngelsDustz** [magento/magento2#31286]
### Preconditions (*)

1. Have GiT installed
2. Have docker installed
3. Clone the magento2 project with branch (2.4-develop, commit: ad2945209811dc9fb5cd531af8f2a2bace8647f3)
4. Have PHP CLI version 7.4.10 installed
5. Have MariaDB Percona Server 5.7.32-35 installed

### Steps to reproduce (*)

1. Create an mariadb and php docker image
2. Configure Magento to use proper credentials/hosts
3. Run `composer install`
4. Run `bin/magento setup:install` (or follow command(s) in https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-install.html or https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands.html)

### Expected result (*)

1. Magento 2 installs or fails on missing parameters.

### Actual result (*)

1. The installation fails on step 4 with "The default website isn't defined. Set the website and try again."
![Screenshot from 2020-12-15 09-29-27](https://user-images.githubusercontent.com/4640484/102190342-34763a00-3eb8-11eb-9143-62a49f45d34c.png)

What I have done so far:
- Clear all cache
- Try a different setup command (see links step 3 reproduce)
- Re-create database
- Composer install without dev packages

It appears to be related to https://github.com/magento/magento2/issues/27864 and https://github.com/magento/magento2/issues/15196 and maybe https://github.com/justbetter/magento2-sentry/issues/23

It is also important to note that when the install fails the database is still empty and no tables have been created yet.

**Comment by MagicLegend** [comment]
I just ran into almost the same; with a little different setup. I'm using the containers found [here](https://devdocs.magento.com/cloud/docker/docker-mode-developer.html), but the error was identical. It appears to have fixed itself after I ran `bin/magento setup:db-schema:upgrade`, _which will fail_, but then the `setup:install` command will suddenly work...

**Comment by AngelsDustz** [comment]
That does indeed work as a quick fix, thank you for that. I still believe it should have some investigation because why does the setup try to access database values before the database is set-up?

**Comment by engcom-Delta** [comment]
Hi @AngelsDustz thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Clone magento 2.4-develop: `git clone https://github.com/magento/magento2.git --branch 2.4-develop .`
- Run `composer install`
- Run `bin/magento setup:install`

**Result:**
:heavy_check_mark: Error `Parameter validation failed` is shown as no parameters for database were set
![image](https://user-images.githubusercontent.com/51681379/103210643-f133b680-490e-11eb-866b-5d1fb2f49bc8.png)

**Note:** With preconfigured `env.php` file, command `bin/magento setup:install` is finished without errors and magento is successfully installed

It was known issue in Magento 2.4.0 but for 2.4.1 and 2.4-develop it is fixed
https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-1.html#installation-upgrade-deployment

Is there any steps that I missed during testing issue?

**Comment by AngelsDustz** [comment]
Hello thank you for checking it out. A configured `env.php` is needed for the database config (I should have added it, nice catch) and that is it. Once it reaches step 4 out of 841 it fails with the exact same error I just tested it with the latest 2.4-develop and the issue still exists.

Which version of php/db did you use? Maybe the issue is related to that? Or maybe it is a container specific issue.

**Comment by ikevinsolomon** [comment]
I'm facing this same issue using docker magento (https://github.com/markshust/docker-magento) the work around mentioned works but can someone please explain how to clone from a self hosted m2.4 repo with the module already lying inside the app/code folder and if some of the modules in that use magento core modules.

**Comment by engcom-Delta** [comment]
@AngelsDustz sorry for delay. I used php 7.4 and mysql 8.0.22:
![image](https://user-images.githubusercontent.com/51681379/106283391-8bf31e00-624a-11eb-9ba9-69d832cc70d8.png)
![image](https://user-images.githubusercontent.com/51681379/106283347-7e3d9880-624a-11eb-918c-6631c37cf343.png)

Also I install magento on Ubuntu locally and don't use docker
Seems like its specific issue connected with your environment

Are you able to check magento installation with one of recommended [database](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#database)? or it could be a container specific issue as you said

**Comment by MagicLegend** [comment]
> or it could be a container specific issue as you said

Could be, but I've had this issue consistently using the official magento cloud containers. I could post my full `Dockerfile` if you want.

**Comment by gabrieldagama** [comment]
Hi @AngelsDustz, can you check if there is any extra information on the logs? A backtrace would be good in this case to identify where exactly this exception is being thrown.

Thanks.

**Comment by manobi** [comment]
I'm using a pre-compiled docker image with Magento 2.4.2 and this error appeared, it have not happened before (Magento 2.4.0).

I'm going to try with the bin/magento setup:db-schema:upgrade before magento install.

**Comment by manobi** [comment]
The workaround suggested had no effect in my setup (setup:db-schema:upgrade).
To explain my context:

**PHP** 7.4.15 (cli) (built: Feb  9 2021 19:48:41) ( NTS )
**Composer** version 1.10.20 2021-01-27 15:41:06
**Magento** 2.4.2

Everything is in my CI/CD pipeline:
1. Magento is created with composer
2. Custom extensions that uses Magento\Framework\Console\CommandList is installed are installed using composer*
3. setup:di compile
4. magento install
5. Error in step 4 like everyone here

It seems that it have not being fixed after all:
https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-1.html#installation-upgrade-deployment
> Installation of Magento with third-party extensions that have dependencies on APIs for the Store module in CLI commands no longer fails. Previously, Magento displayed this error message: The default website isn't defined. Set the website and try again. This was a known issue in Magento 2.4.0.

**Comment by minhluan259** [comment]
@manobi I've same issue with PHP 7.4.15
run
`bin/magento setup:upgrade`

```
Module 'PayPal_Braintree':
Installing schema... Killed

```

I reverted to using PHP 7.3, all worked fine.

**Comment by manobi** [comment]
Thank you @minhluan259 but it did not fixed my problem.

Anyone knows where they have it fixed? It's definitely no working in magento 2.4.2.

**Comment by AngelsDustz** [comment]
> Hi @AngelsDustz, can you check if there is any extra information on the logs? A backtrace would be good in this case to identify where exactly this exception is being thrown.
> 
> Thanks.

Hello, I've read over this my bad! I do not have any logs that indicate what is wrong sadly. All I have is the exception message, no stack nothing.

**Comment by Morgy93** [comment]
Probably same error here as described before, using very similar setup:

```
The command "cd . && (/usr/local/bin/php ./bin/magento setup:static-content:deploy de_DE -f --exclude-theme=Magento/blank)" failed. 

Compilation from source /lib/web/moment.js failed

DomainException: The default website isn't defined. Set the website and try again. in vendor/magento/module-store/Model/WebsiteRepository.php:159 

Stack trace:
#0 vendor/magento/module-store/Model/StoreResolver/Website.php(49): Magento\Store\Model\WebsiteRepository->getDefault()
#1 vendor/magento/module-store/Model/StoresData.php(65): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds(NULL) 
#2 vendor/magento/module-store/Model/StoreResolver.php(138): Magento\Store\Model\StoresData->getStoresData('website', NULL)
#3 vendor/magento/module-store/Model/StoreResolver.php(97): Magento\Store\Model\StoreResolver->getStoresData() 
#4 vendor/magento/module-store/Model/StoreManager.php(160): Magento\Store\Model\StoreResolver->getCurrentStoreId() 
#5 generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL) 
#6 vendor/magento/module-store/Model/Resolver/Store.php(30): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL) 
#7 vendor/magento/framework/Url/ScopeResolver.php(41): Magento\Store\Model\Resolver\Store->getScope(NULL)
#8 vendor/magento/framework/Url.php(429): Magento\Framework\Url\ScopeResolver->getScope(NULL)
#9 vendor/magento/framework/Url.php(444): Magento\Framework\Url->setScope(NULL)
#10 vendor/magento/framework/Url.php(460): Magento\Framework\Url->_getScope()
#11 vendor/magento/framework/View/Asset/Repository.php(284): Magento\Framework\Url->getBaseUrl(Array)
#12 vendor/magento/framework/View/Asset/Repository.php(233): Magento\Framework\View\Asset\Repository->getFallbackContext('static', NULL, 'frontend', 'Magento/blank', 'de_DE')
#13 vendor/magento/module-deploy/Service/DeployStaticFile.php(87): Magento\Framework\View\Asset\Repository->createAsset('extjs/resources...', Array)
#14 vendor/magento/module-deploy/Service/DeployPackage.php(189): Magento\Deploy\Service\DeployStaticFile->deployFile('extjs/resources...', Array) 
#15 vendor/magento/module-deploy/Service/DeployPackage.php(133): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#16 vendor/magento/module-deploy/Service/DeployPackage.php(102): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false) 
#17 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}() 
#18 vendor/magento/framework/App/State.php(187): call_user_func_array(Object(Closure), Array)
#19 vendor/magento/module-deploy/Service/DeployPackage.php(103): Magento\Framework\App\State->emulateAreaCode('frontend', Object(Closure))
#20 vendor/magento/module-deploy/Process/Queue.php(358): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#21 vendor/magento/module-deploy/Process/Queue.php(267): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package)) 
#22 vendor/magento/module-deploy/Process/Queue.php(248): Magento\Deploy\Process\Queue->executePackage(Object(Magento\Deploy\Package\Package), 'frontend/Magent...', Array, false) 
#23 vendor/magento/module-deploy/Process/Queue.php(176): Magento\Deploy\Process\Queue->assertAndExecute('frontend/Magent...', Array, Array) 
#24 vendor/magento/module-deploy/Strategy/QuickDeploy.php(76): Magento\Deploy\Process\Queue->process() 
#25 vendor/magento/module-deploy/Service/DeployStaticContent.php(115): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#26 setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php(136): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#27 vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#29 vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 bin/magento(23): Symfony\Component\Console\Application->run()
#33 {main}
```

**Comment by BernardRobbins** [comment]
I'm also having this issue but with 2.3.6.

PHP 7.3.27-9+ubuntu20.04.1+deb.sury.org+1 (cli)
"magento/product-community-edition": "2.3.6",
Composer 1.10.1 2020-03-13 20:34:27

bin/magento setup:install --base-url='http://mydomain' --db-host=127.0.0.1 --db-name=myDb --db-user=myDbUser --db-password='myCoolPw' --admin-firstname=Bernard --admin-lastname=Robbins --admin-email=bernard@domain --admin-user=bernard --admin-password='MyPw' --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin

In WebsiteRepository.php line 159:                                                                     
  The default website isn't defined. Set the website and try again.  

bernard@magento:/var/www/html/staging$ cat var/log/system.log 
[2021-03-12 15:56:45] main.ERROR: The default website isn't defined. Set the website and try again.
#0 /var/www/html/staging/vendor/magento/module-store/Model/StoreResolver/Website.php(49): Magento\Store\Model\WebsiteRepository->getDefault()
#1 /var/www/html/staging/vendor/magento/module-store/Model/StoresData.php(65): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds(NULL)
...

**Comment by Gael101** [comment]
I'm having the same issue with magento 2.4.2, on a fresh install. The issue disappears in following situations :

- If I run the setup:install command with --cleanup-database **twice**  (first time it fails, then it's working)
- if I delete the custom modules under app/code and run the install command
- if I run the command against a full db.
here's my install command : 

$WEB_DIR/bin/magento setup:install \
--base-url=$URL --backend-frontname=$BACKEND_FRONTNAME \
--language=$LANGUAGE --timezone=$TIMEZONE \
--currency=$DEFAULT_CURRENCY --db-host=$MYSQL_HOST \
--db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER \
--db-password=$MYSQL_PASSWORD --use-secure=$USE_SECURE \
--use-secure-admin=$USE_SECURE_ADMIN --session-save-redis-host=$REDIS_HOST \
--cache-backend-redis-server=$REDIS_HOST --cache-backend=redis \
--admin-firstname=$ADMIN_FIRSTNAME \
--admin-lastname=$ADMIN_LASTNAME --admin-email=$ADMIN_EMAIL \
--admin-user=$ADMIN_USERNAME --admin-password=$ADMIN_PASSWORD \
--disable-modules=$DISABLE_MODULE --elasticsearch-host=$ES_HOST \
--session-save=redis --use-rewrites=1 --cleanup-database \
&& $WEB_DIR/bin/magento module:disable Magento_TwoFactorAuth

I'm running magento 2.4.2 community edition / PHP7.4/Elasticsearch-oss/mysql5.7(same issue with mysql 8)

**Comment by Gael101** [comment]
Found a way to make it work after all : 
disable custom modules at install time, then re-enable them , and finally update db schema and data : 
```bash
pimpmylog "running magento installation" $YELLOW
composer install -d $WEB_DIR && \
$WEB_DIR/bin/magento setup:install \
--base-url=$URL --backend-frontname=$BACKEND_FRONTNAME \
--language=$LANGUAGE --timezone=$TIMEZONE \
--currency=$DEFAULT_CURRENCY --db-host=$MYSQL_HOST \
--db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER \
--db-password=$MYSQL_PASSWORD --use-secure=$USE_SECURE \
--use-secure-admin=$USE_SECURE_ADMIN --session-save-redis-host=$REDIS_HOST \
--cache-backend-redis-server=$REDIS_HOST --cache-backend=redis \
--admin-firstname=$ADMIN_FIRSTNAME \
--admin-lastname=$ADMIN_LASTNAME --admin-email=$ADMIN_EMAIL \
--admin-user=$ADMIN_USERNAME --admin-password=$ADMIN_PASSWORD \
--disable-modules=$DISABLE_MODULE --elasticsearch-host=$ES_HOST \
--session-save=redis --use-rewrites=1 --cleanup-database 

pimpmylog "enabling modules back " $YELLOW
for module in $(echo $DISABLE_MODULE | sed "s/,/ /g");do
    if [[ $module != "Magento_TwoFactorAuth" ]];then
        $WEB_DIR/bin/magento module:enable $module 
    fi
done

pimpmylog "upgrade data & schema " $YELLOW
$WEB_DIR/bin/magento setup:db-data:upgrade 
$WEB_DIR/bin/magento setup:db-schema:upgrade 

pimpmylog "Magento installation done" $GREEN
```

**Comment by Gael101** [comment]
I've found a way to make it work : 
- disable custom modules during install with --disable-modules
- re enable modules afterwards 
- update db schema and data
```bash 
pimpmylog "running magento installation" $YELLOW
composer install -d $WEB_DIR && \
$WEB_DIR/bin/magento setup:install \
--base-url=$URL --backend-frontname=$BACKEND_FRONTNAME \
--language=$LANGUAGE --timezone=$TIMEZONE \
--currency=$DEFAULT_CURRENCY --db-host=$MYSQL_HOST \
--db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER \
--db-password=$MYSQL_PASSWORD --use-secure=$USE_SECURE \
--use-secure-admin=$USE_SECURE_ADMIN --session-save-redis-host=$REDIS_HOST \
--cache-backend-redis-server=$REDIS_HOST --cache-backend=redis \
--admin-firstname=$ADMIN_FIRSTNAME \
--admin-lastname=$ADMIN_LASTNAME --admin-email=$ADMIN_EMAIL \
--admin-user=$ADMIN_USERNAME --admin-password=$ADMIN_PASSWORD \
--disable-modules=$DISABLE_MODULE --elasticsearch-host=$ES_HOST \
--session-save=redis --use-rewrites=1 --cleanup-database 

pimpmylog "enabling modules back " $YELLOW
for module in $(echo $DISABLE_MODULE | sed "s/,/ /g");do
    if [[ $module != "Magento_TwoFactorAuth" ]];then
        $WEB_DIR/bin/magento module:enable $module 
    fi
done

pimpmylog "upgrade data & schema " $YELLOW
$WEB_DIR/bin/magento setup:db-data:upgrade 
$WEB_DIR/bin/magento setup:db-schema:upgrade 

pimpmylog "Magento installation done" $GREEN
```
(2factor auth is kept disabled for local developements purposes)
