### ISSUE TITLE
Moving multiple categories bug

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3171]
There exist an problem with moving categories. 

For example:
Categories A,B and C
When I move category A to B  --> Succes
When moving A from B to C (without refreshing) --> Categorie doesn't move
etc.

Backtrace: loader_old.js:

_onAjaxSend: function (e, jqxhr, settings) {
            if (settings && settings.showLoader) {
                var ctx = this._getJqueryObj(settings.loaderContext);
                ctx.trigger('processStart');

```
            // Check to make sure the loader is there on the page if not report it on the console.
            // NOTE that this check should be removed before going live. It is just an aid to help
            // in finding the uses of the loader that maybe broken.
            if (window.console && !ctx.parents('[data-role="loader"]').length) {
                console.warn('**Expected to start loader but did not find one in the dom'**);
            }
        }
    },
```

**Comment by ghost** [comment]
The bug still exist in magento 2.0.2

**Comment by ghost** [comment]
I'm just wondering if there are any new updates for this issue?

**Comment by kanduvisla** [comment]
It seems that this bug still exists in Magento 2.0.4. I can only move one category at the time. I have to refresh the page after every move

**Comment by lgt** [comment]
same issue on magento 2.0.4 production but on development side works

**Comment by grasdaggel** [comment]
I get the same error (Expected to start loader but did not find one in the dom) when trying to translate something, using Inline Translation.

**Comment by Skrypton** [comment]
I am getting the same error. The only way I can move categories is by saving the category after moving and sometimes I am getting an error that a category can't be moved.
I figured out that if an category can't be moved it is related to URL rewrites, because if I delete all rewrites that are related to that category, the category can be moved as described in the beginning.

**Comment by ajaymscit** [comment]
Hello Team,

I am getting error in moving category from sub-subcategory to sub-category.

I am using Magento 2.0

**Comment by Anshu-Mishra** [comment]
I am getting the same error as well on 2.1.3

**Comment by wardcapp** [comment]
Was having the same problem on a Magento 2.0.7, while debugging and attempting to resolve the issue, it became clear internal issue MAGETWO-46196 was created by the core team and the resolving commit is https://github.com/magento/magento2/commit/8d19e959bd14437143c92ccf1a652e1cf6048d2b.
The bug has been addressed within the develop branch, but is still to be published to 2.0.x.

Not really sure why the same also happened on 2.1.3 (see the comment made by @Anshu-Mishra), since it was already merged within release 2.1.3:
https://github.com/magento/magento2/blob/2.1.3/app/code/Magento/Catalog/view/adminhtml/templates/catalog/category/tree.phtml

**Comment by jimul** [comment]
I have compare this template file, but bug still exist in moving category version EE 2.1.5

**Comment by magento-engcom-team** [comment]
@ghost, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
