### ISSUE TITLE
Vimeo Product Video Not Found

### ISSUE THREAD

**Issue by gcampedelli** [magento/magento2#31753]
### Preconditions (*)

1. It was previoulys working, tested in Magento 2.4.0. 

### Steps to reproduce (*)
1. So upgrade to 2.4.1. Do not upgrade and remain in 2.4.0 in another cloned enviroment
2. Go to product page
3. Insert a product video in product page using the regular insert video button. It previously worked. 
4. Few days later try to do it again. Vimeo returns 404 
5. Try to upload to another Vimeo account to check if a setting may be blocking. No, it returns 404
6. curl -i https://vimeo.com/videoId. It returns 200 and a response with json and ajax call
7. Try to get in browser Vimeo dowload a file a does not print information on client
8. Try the same in postman, it returns Json
9. Try to debug Magento
10. Check if it is Cors. Vimeo Cors is declared in Csp policy

### Expected result (*)

1.Insert url in Product Video and it is found
2. Video displays in fotorama

### Actual result (*)

1. Video not found. Unable to display Vimeo on Fotorama

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
A colleague of mine just reported the same error today. I'm guessing something changed at Vimeo's side and Magento is no longer compatible with the change.

Somebody will need to debug and figure out what happens and how it can be corrected in Magento to make it work again.

Or maybe it's a problem at Vimeo itself and we should just wait a few hours until it gets resolved, that might be an option as well...

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40467` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by awaredigital** [comment]
This isn't just a 2.4 instance issue. It looks as though Vimeo has changed it's API.

**Comment by novikor** [comment]
Hi. It seems that ` https://vimeo.com/api/v2/video` should be used instead of `https://www.vimeo.com/api/v2/video/`

**Comment by awaredigital** [comment]
Just checked this by modifying the following file:

> vendor/magento/module-product-video/view/adminhtml/web/js/get-video-information.js

Just for sanity, removing the `www` from the URL doesn't make a difference.

`url: 'https://vimeo.com/api/v2/video/' + id + '.json',`

**Comment by novikor** [comment]
Applying the patch fixes the problem locally:

```
Index: app/code/Magento/ProductVideo/view/adminhtml/web/js/get-video-information.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/code/Magento/ProductVideo/view/adminhtml/web/js/get-video-information.js b/app/code/Magento/ProductVideo/view/adminhtml/web/js/get-video-information.js
--- a/app/code/Magento/ProductVideo/view/adminhtml/web/js/get-video-information.js	(revision 49d4a2fd48c750e97846140b68ea8e63827610b7)
+++ b/app/code/Magento/ProductVideo/view/adminhtml/web/js/get-video-information.js	(date 1611072804688)
@@ -539,7 +539,7 @@
                     );
                 } else if (type === 'vimeo') {
                     $.ajax({
-                        url: 'https://www.vimeo.com/api/v2/video/' + id + '.json',
+                        url: 'https://vimeo.com//api/v2/video/' + id + '.json',
                         dataType: 'jsonp',
                         data: {
                             format: 'json'
```

**Comment by omaxmo** [comment]
@magento I am working on this

**Comment by gcampedelli** [comment]
> Just checked this by modifying the following file:
> 
> > vendor/magento/module-product-video/view/adminhtml/web/js/get-video-information.js
> 
> Just for sanity, removing the `www` from the URL doesn't make a difference.
> 
> `url: 'https://vimeo.com/api/v2/video/' + id + '.json',`
> 
> The API request still fails and we still get the same error.

I did it and it just changed the 301 redirect to 200 redirect but still no video found

**Comment by gcampedelli** [comment]
Mine is exactly like proposed patch since step 9 on the issue opened

![image](https://user-images.githubusercontent.com/7084395/105105534-0675ae00-5a93-11eb-9cb7-9480c826fbf7.png)

**Comment by gcampedelli** [comment]
Hi
I've got it this way

`/**
                 * @private
                 */
                function logResults(json){
                    console.log(json);
                }
                function _onVimeoLoaded(data) {
                    var tmp,
                        respData;

                    if (data.length < 1) {
                        this._onRequestError($.mage.__('Video not found'));

                        return null;
                    }
                    tmp = data[0];
                    respData = {
                        duration: this._formatVimeoDuration(tmp.duration),
                        channel: tmp['user_name'],
                        channelId: tmp['user_url'],
                        uploaded: tmp['upload_date'],
                        title: tmp.title,
                        description: tmp.description.replace(/(&nbsp;|<([^>]+)>)/ig, ''),
                        thumbnail: tmp['thumbnail_large'],
                        videoId: videoInfo.id,
                        videoProvider: videoInfo.type
                    };
                    this._videoInformation = respData;
                    this.element.trigger(this._UPDATE_VIDEO_INFORMATION_TRIGGER, respData);
                    this.element.trigger(this._FINISH_UPDATE_INFORMATION_TRIGGER, true);
                }

                type = videoInfo.type;
                id = videoInfo.id;

                if (type === 'youtube') {
                    googleapisUrl = 'https://www.googleapis.com/youtube/v3/videos?id=' +
                        id +
                        '&part=snippet,contentDetails&key=' +
                        this.options.youtubeKey + '&alt=json&callback=?';
                    $.getJSON(googleapisUrl,
                        {
                            format: 'json'
                        },
                        $.proxy(_onYouTubeLoaded, self)
                    ).fail(
                        function () {
                            self._onRequestError('Video not found');
                        }
                    );
                } else if (type === 'vimeo') {
                    $.ajax({
                        url: 'https://vimeo.com/api/v2/video/' + id + '.json',
                        dataType: 'jsonp',
                        jsonpCallback: "logResults",
                        data: {
                            format: 'json'
                        },
                        timeout: 5000,
                        success:  $.proxy(_onVimeoLoaded, self),

                        /**
                         * @private
                         */`

Any better ideas?

**Comment by omaxmo** [comment]
@gcampedelli you can look at the pull request https://github.com/magento/magento2/pull/31767 https://github.com/magento/magento2/pull/31767/files

**Comment by gcampedelli** [comment]
> @gcampedelli you can look at the pull request #31767 https://github.com/magento/magento2/pull/31767/files

I did
I'm proposing another PR

**Comment by gcampedelli** [comment]
@magento I am working on this

**Comment by gcampedelli** [comment]
I have a PR

@magento add to contributors team

**Comment by gcampedelli** [comment]
> @gcampedelli you can look at the pull request #31767 https://github.com/magento/magento2/pull/31767/files

Hi @omaxmo. Your solution may work in my install, but I proposed another PR because of concerns with security regarding oembed urls. I don't know why Magento would, for example, not use https://youtube.com/oembed?url=http://www.youtube.com/watch?v=VideoId. In the same Vimeo fashion oembed it is possible to get You Tube Videos. I'm afraid it is because original developers where concerned about cookie capture associated with this method. So, I proposed a simple fix. You can check also. Thank you for your contribution.

**Comment by omaxmo** [comment]
@gcampedelli Vimeo recommends use oEmbed implementation. 

```
The Simple API was a basic way for users to get public metadata about their albums, channels, groups, users, videos. The URL structure for the Simple API looked like this:

http://vimeo.com/api/v2/album/album_id/request.json
http://vimeo.com/api/v2/channel/channel_name/request.json
http://vimeo.com/api/v2/group/group_name/request.json
http://vimeo.com/api/v2/username/request.json
http://vimeo.com/api/v2/video/video_id.json

**This API is no longer maintained or supported. We recommend developers utilize our oEmbed implementation to get that same metadata for embeddable videos.**
```
[https://vimeo.zendesk.com/hc/en-us/articles/360042975791-Deprecated-APIs-libraries-and-upload-methods](url)

**Comment by zakdma** [comment]
Bug was fixed ins scope of internal jira ticket MC-40463

**Comment by ihor-sviziev** [comment]
FYI here is a commit that fixes this issue https://github.com/magento/magento2/commit/f2231f8d953bb650c3462a824716fd8972c6bb6c

**Comment by orthener** [comment]
> FYI here is a commit that fixes this issue [f2231f8](https://github.com/magento/magento2/commit/f2231f8d953bb650c3462a824716fd8972c6bb6c)

Patch file (if it help someone) `MC-40463__Vimeo-simple-API-stop-working-as-expected.patch` (tested on M2.4.1)
```
From f2231f8d953bb650c3462a824716fd8972c6bb6c Mon Sep 17 00:00:00 2001
From: Myroslav Dobra <dmaraptor@gmail.com>
Date: Wed, 20 Jan 2021 11:27:26 +0200
Subject: [PATCH] MC-40463: Vimeo simple API stop working as expected

---
 .../module-product-video/etc/csp_whitelist.xml    |  6 ++++++
 .../adminhtml/web/js/get-video-information.js     | 15 ++++++++-------
 lib/web/fotorama/fotorama.js                      |  9 ++++++---
 3 files changed, 20 insertions(+), 10 deletions(-)

diff --git a/vendor/magento/module-product-video/etc/csp_whitelist.xml b/vendor/magento/module-product-video//etc/csp_whitelist.xml
index ca453605710..2e091440330 100644
--- a/vendor/magento/module-product-video/etc/csp_whitelist.xml
+++ b/vendor/magento/module-product-video/etc/csp_whitelist.xml
@@ -14,6 +14,7 @@
                 <value id="google_video" type="host">www.googleapis.com</value>
                 <value id="vimeo" type="host">vimeo.com</value>
                 <value id="www_vimeo" type="host">www.vimeo.com</value>
+                <value id="vimeo_cdn" type="host">*.vimeocdn.com</value>
             </values>
         </policy>
         <policy id="img-src">
@@ -21,5 +22,10 @@
                 <value id="vimeo_cdn" type="host">*.vimeocdn.com</value>
             </values>
         </policy>
+        <policy id="frame-src">
+            <values>
+                <value id="player_vimeo" type="host">player.vimeo.com</value>
+            </values>
+        </policy>
     </policies>
 </csp_whitelist>
diff --git a/vendor/magento/module-product-video/view/adminhtml/web/js/get-video-information.js b/vendor/magento/module-product-video/view/adminhtml/web/js/get-video-information.js
index cb56a085304..4b3c1b7f8ee 100644
--- a/vendor/magento/module-product-video/view/adminhtml/web/js/get-video-information.js
+++ b/vendor/magento/module-product-video/view/adminhtml/web/js/get-video-information.js
@@ -497,20 +497,20 @@ define([
                     var tmp,
                         respData;
 
-                    if (data.length < 1) {
+                    if (!data) {
                         this._onRequestError($.mage.__('Video not found'));
 
                         return null;
                     }
-                    tmp = data[0];
+                    tmp = data;
                     respData = {
                         duration: this._formatVimeoDuration(tmp.duration),
-                        channel: tmp['user_name'],
-                        channelId: tmp['user_url'],
+                        channel: tmp['author_name'],
+                        channelId: tmp['author_url'],
                         uploaded: tmp['upload_date'],
                         title: tmp.title,
                         description: tmp.description.replace(/(&nbsp;|<([^>]+)>)/ig, ''),
-                        thumbnail: tmp['thumbnail_large'],
+                        thumbnail: tmp['thumbnail_url'],
                         videoId: videoInfo.id,
                         videoProvider: videoInfo.type
                     };
@@ -539,10 +539,11 @@ define([
                     );
                 } else if (type === 'vimeo') {
                     $.ajax({
-                        url: 'https://www.vimeo.com/api/v2/video/' + id + '.json',
+                        url: 'https://vimeo.com/api/oembed.json',
                         dataType: 'jsonp',
                         data: {
-                            format: 'json'
+                            format: 'json',
+                            url: 'https://vimeo.com/' + id
                         },
                         timeout: 5000,
                         success:  $.proxy(_onVimeoLoaded, self),
diff --git a/lib/web/fotorama/fotorama.js b/lib/web/fotorama/fotorama.js
index 314949bd2f4..f268c9aa736 100644
--- a/lib/web/fotorama/fotorama.js
+++ b/lib/web/fotorama/fotorama.js
@@ -858,13 +858,16 @@ fotoramaVersion = '4.6.4';
             dataFrame.thumbsReady = true;
         } else if (video.type === 'vimeo') {
             $.ajax({
-                url: getProtocol() + 'vimeo.com/api/v2/video/' + video.id + '.json',
+                url: getProtocol() + 'vimeo.com/api/oembed.json',
+                data: {
+                    url: 'https://vimeo.com/' + video.id
+                },
                 dataType: 'jsonp',
                 success: function (json) {
                     dataFrame.thumbsReady = true;
                     updateData(data, {
-                        img: json[0].thumbnail_large,
-                        thumb: json[0].thumbnail_small
+                        img: json[0].thumbnail_url,
+                        thumb: json[0].thumbnail_url
                     }, dataFrame.i, fotorama);
                 }
             });
-- 
2.17.1

```

**Comment by MirkoHuf** [comment]
Hi, any help for Magento 2.3.6 available?
In 2.3.5-p2 I don't have a app/code/Magento/ProductVideo/Test/Mftf/ActionGroup/AssertProductVideoStorefrontProductPageActionGroup.xml file.
I changed all the rest - but it didn't work.
I have already cleared the cache and did a "php bin/magento setup:static-content:deploy --theme Magento/backend". But the problem still exist.
Thanks in advance.

**Comment by gcampedelli** [comment]
> Hi, any help for Magento 2.3.6 available?
> In 2.3.5-p2 I don't have a app/code/Magento/ProductVideo/Test/Mftf/ActionGroup/AssertProductVideoStorefrontProductPageActionGroup.xml file.
> I changed all the rest - but it didn't work.
> I have already cleared the cache and did a "php bin/magento setup:static-content:deploy --theme Magento/backend". But the problem still exist.
> Thanks in advance.

Hi, you can try my patch in this topic, or just manually change "get-video-information.js" accordingly.

**Comment by lewisje** [comment]
@MirkoHuff, I've tried [a later PR](https://github.com/magento/magento2/pull/31769/files) by gcampedelli, putting the patched file into `Magento_ProductVideo/web/js/` inside of a custom admin theme.
