### ISSUE TITLE
Cron jobs scheduled once time per day are not ran

### ISSUE THREAD

**Issue by mtwegrzycki** [magento/magento2#32444]
### Preconditions (*)
1. Magento 2.4.0

### Steps to reproduce (*)
1. Open cron_schedule table in database
2. Try to find job with job_code 'sales_clean_quotes'
3. There are no results for this job_code

### Expected result (*)
1. Cron job sales_clean_quotes is ran once time per day and expired carts are removed

### Actual result (*)
1. Cron job is not scheduled and is not ran.
2. I found, that all cron jobs with the following schedule: <schedule>0 0 * * *</schedule> (from default group) are not scheduled and are not ran.

I modified schedule in the following way: <schedule>0 * * * *</schedule> for sales_clean_quotes job and it fixed issue. sales_clean_quotes job is now scheduled and ran correctly.
However it is not valid solution, because 0 0 * * * means that it will be ran once time per hour, not per day.

I think, that issue is related with the this exact schedule value: 0 0 * * *. Maybe there are some conflict between this value and default group settings?
I do not know, how it works in others groups.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Hmm strange

Not sure about Magento version 2.4.0 but I can tell that on Magento 2.4.2 it works correctly.

Can you make sure that you've checked the `var/log/cron.log` file as well?
Because executed cronjobs that succeeded will be removed from the `cron_schedule` database table after 60 minutes (that's the default setting, but you can override it in Stores > Configuratoin > Advanced > System > Cron (Scheduled Tasks) > * > Success History Lifetime)

If you grep your `cron.log` file, you should see it being executed if everything is ok:
```
$ grep 'sales_clean_quotes' var/log/cron.log
[2021-03-07 23:00:03] main.INFO: Cron Job sales_clean_quotes is run [] []
[2021-03-07 23:00:04] main.INFO: Cron Job sales_clean_quotes is successfully finished. Statistics: ... [] []
[2021-03-08 23:00:03] main.INFO: Cron Job sales_clean_quotes is run [] []
[2021-03-08 23:00:04] main.INFO: Cron Job sales_clean_quotes is successfully finished. Statistics: ... [] []
[2021-03-09 23:00:03] main.INFO: Cron Job sales_clean_quotes is run [] []
[2021-03-09 23:00:03] main.INFO: Cron Job sales_clean_quotes is successfully finished. Statistics: ... [] []
[2021-03-10 23:00:03] main.INFO: Cron Job sales_clean_quotes is run [] []
[2021-03-10 23:00:03] main.INFO: Cron Job sales_clean_quotes is successfully finished. Statistics: ... [] []
```

**Comment by mtwegrzycki** [comment]
Thank you for your answer.
I ran this command for cron.log and I did not get any result for sales_clean_quotes
I found that other crons with this schedule 0 0 * * * also do not work but e.g. sales_clean_orders which is in the same crontab.xml file and has 0 * * * * schedule works properly.

I ran the following test:
I setup sales_clean_quotes with the following settings: e.g. 8 8 * * * and it does not work, but if I setup this cron with 8 * * * * - it works properly.
It really looks like issue with setting specified hour, when I set "every hour" - (*) - it works fine.
This issue occur on few Magento cloud environments and on local virtual machine.

**Comment by hostep** [comment]
Strange.

Could you maybe upgrade to Magento 2.4.2 and see if that solves it?
The only significant change I'm noticing in the Cron module between 2.4.0 and 2.4.2 is this PR: https://github.com/magento/magento2/pull/28930, that one got introduced in Magento 2.4.1

I don't think that PR should fix your issue, but I'm not sure, who knows ...

If it's not solved in Magento 2.4.2 in your case, I would start searching for any customisations done to your shop that have to do with the cron executions, maybe some customisation breaks it in your case.

**Comment by mtwegrzycki** [comment]
I tested this on Magento 2.4.2 instance without any customization and the same issue occurs.

**Comment by mtwegrzycki** [comment]
@magento give me 2.4-develop instance

**Comment by mtwegrzycki** [comment]
I can still reproduce this issue, even on clear Magento 2.4.2 installation.
Please, let me know, if someone has any idea.

**Comment by engcom-Bravo** [comment]
Hi @mtwegrzycki,

Could you please let us know the exact steps you are doing to set up the cron on clean Magento installation so that we can try to reproduce the issue?

**Comment by onlinebizsoft** [comment]
I think we have a similar issue, look like many jobs were marked as "missed", maybe some configuration or something make some jobs "easy to miss" from scheduled time

**Comment by engcom-Hotel** [comment]
Hello @mtwegrzycki,

This issue is reproducible in 2.4-develop. We have followed below steps in order to reproduce the issue:

1. Made changes in app/code/Magento/Sales/etc/crontab.xml to run this particular cron for every minute (For e.g. 0 * * * *). It works fine.
2. But when I set the schedule for 5 9 * * *, it should run at 09:05, but it is not running.

So we are confirming the issue.

Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42887` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
@engcom-Hotel: have you taken timezones into account?
Also the expression `0 * * * *`  does not run every single minute, but once per hour: [explanation](https://crontab.guru/#0_*_*_*_*)

I can confirm on Magento 2.4.2-p1 this problem does not happen if you take timezones into account.
For example, the `backend_clean_cache` job has cron expression: `30 2 * * *`, on a Magento installation with timezone set to `Europe/Brussels`. I can see it runs as expected in the `var/log/cron.log` file:
```
[2021-07-18 00:30:03] main.INFO: Cron Job backend_clean_cache is run [] []
[2021-07-18 00:30:03] main.INFO: Cron Job backend_clean_cache is successfully finished.
[2021-07-19 00:30:02] main.INFO: Cron Job backend_clean_cache is run [] []
[2021-07-19 00:30:02] main.INFO: Cron Job backend_clean_cache is successfully finished.
[2021-07-20 00:30:03] main.INFO: Cron Job backend_clean_cache is run [] []
[2021-07-20 00:30:03] main.INFO: Cron Job backend_clean_cache is successfully finished.
```
These timezones are in UTC timezone, which differ by 2 hours with `Europe/Brussels` at the moment with daylight saving active.

So everything is running correctly in my experience.

**Comment by engcom-Hotel** [comment]
Hello @hostep,

Thank you for the clarification. I have checked the issue after changing the timezone and found the cron is working fine. I am removing the "Issue: confirmed" label.


Hello @mtwegrzycki,

Please check this with changing the timezone, this might be a configuration-related issue. Please review it again and let us know if you still getting this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @hostep,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
