### ISSUE TITLE
 Public Hash Error  

### ISSUE THREAD

**Issue by CelinaNguyen114** [magento/magento2#32943]
Hi Magento Supporter, 

Currently, we have discovered the Public  Hash error when customers try to create a new order with a saved credit card, they get this error.  Also, we see this error when we try to place an order for an existing customer from the Admin panel. It has to do with the Vault where credit cards are saved.  

### Preconditions

1. Magento CE 2.3.6-p1
2. Linux (x86_64)
3. PHP 7.3.28
4. mysql  Ver 15.1 Distrib 10.3.28-MariaDB

### Steps to reproduce: 

Case 1:  When customers 
![Public Hash error](https://user-images.githubusercontent.com/83684394/117108425-5ca1ff00-adad-11eb-9cab-a9283d8298c2.png)
try to create a new order with a saved credit card, they will see the Public Hash error. 
Case 2 : we see this error when we try to place an order for an existing customer from the Admin panel. 
![Public Hash](https://user-images.githubusercontent.com/83684394/117108725-cc17ee80-adad-11eb-9c2e-ae8b5fa27c22.png)

### Actual result: Appear the public Hash error. 
![Public Hash error](https://user-images.githubusercontent.com/83684394/117108677-bd313c00-adad-11eb-9736-e6074eeabb62.png)

### Expected results: 

The Public Hash will no longer appear 
 
Case 1:  When customers try to create a new order with a saved credit card, they will not see the Public Hash error. 
Case 2: we see not this error when we try to place an order for an existing customer from the Admin panel. 

Could you please check this issue and let me know if you need further any information? 

Thanks!
Celina

**Comment by engcom-Alfa** [comment]
Hi @CelinaNguyen114

We followed the steps provided to reproduce the issue unfortunately we did not get any option to select payment method in admin while placing the order.

So, Can you please provide us more details regarding the payment method.

**Comment by CelinaNguyen114** [comment]
*Hi Manjunath, Thanks for your feedback,We are using payflow from PayPal
for our website. Please let me know if you need  further
information,Best,Celina*

**Comment by CelinaNguyen114** [comment]
*Hi Manjunath, I just wanted to update some information. The public hash
happens when we create an order for customers who used to save the credit
card at least once on the front end.  After debugging the issue, at the
time we choose a payment method, we see,  it will have a public hash
key.  However, when I choose the shipping method for the order,  the public
hash key will disappear.Then, when  saving  the order, we will see this
error. I guess, maybe this issue is related to the public hash key.  I hope
these information will helpful and let me know if you need anything
else,Thanks!Celina *

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42425` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Lima** [comment]
Hi @CelinaNguyen114 ,

I went through the magento document, There is no default component implementation for the Admin, so your component must implement all logic for validation and order placing. Please follow the documentation here.
https://devdocs.magento.com/guides/v2.4/payments-integrations/vault/admin-integration.html

So, here i have the question have you added vault component for the admin by your self or you trying without doing anything.

Please let me know if you have any query.

**Comment by engcom-Lima** [comment]
Dear @CelinaNguyen114,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by tcmax76** [comment]
We are also having this same issue on our sites.

**Comment by WebHostingAce** [comment]
Same issue. We cant place orders via Admin Panel with the Stored Credit Cards (Braintree)

Error - "Order saving error: Public hash should be defined"

This was working until we upgraded from 2.4.3-p1 to 2.4.3-p2

**Comment by mzenner1** [comment]
I can confirm this is still an issue in 2.4.3-p1

Error - "Order saving error: Public hash should be defined"

**Comment by elioermini** [comment]
We have this on 2.4.5-p1 with the bundled Braintree module @engcom-Lima

**Comment by amcguireweb** [comment]
Also have this error. Why is this still closed?

**Comment by marcin-dykas** [comment]
Same issue on 2.4.4

@CelinaNguyen114
@engcom-Lima

Could you please open it ?

**Comment by vipin12117** [comment]
Same issue exists in Magento 2.4.6.p3. So looks like this is never checked and fixed.
