### ISSUE TITLE
Magento 2.4.2 Category Pages Sort by Quantity not working properly

### ISSUE THREAD

**Issue by Chandresh22** [magento/magento2#33000]
### Preconditions (*)

1. magento version 2.4.2 
2. at least 5 products on category 
3. make 1 or 2 product(s) out of stock

### Steps to reproduce (*)

1. Go to Stores menu and select Configuration -> Catalog -> Inventory -> Display Out of Stock Products to yes
2. Go to Stores menu and Select  Attributes -> Product
3. Search quantity_and_stock_status and edit it
4. Open last tab Storefront Properties and Select yes from Used for Sorting in Product Listing
5. make cache flush or clean
6. Go to Store Frontend and open category and select sort by Quantity

### Expected result (*)

1. Store Frontend  open category and select sort by Quantity it will sort product by
   quantity not  work with ascending/descending arrow (order) always only out of stock product display first
2. 
![stockissue](https://user-images.githubusercontent.com/47473360/117984802-c5611c80-b355-11eb-90c6-d879be477ab9.jpg)

### Actual result (*)

1. Store Frontend  open category and select sort by Quantity it will sort product by
   quantity  work with ascending/descending arrow  and out of stock product display first in ascending order &
   out of stock product display last with descending order
2. 
![actual](https://user-images.githubusercontent.com/47473360/117985198-1e30b500-b356-11eb-9574-07966e2770c5.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hello @Chandresh22 ,
I have verified this issue as per your steps, actual result and expected result.
In default magento, Asc/Dsc functionality is not working on Sorting drop-down. In my end, Every time Out of stock product is showing on end of the list.

![Uploading image.png…]()

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42314` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Iamwade** [comment]
@magento I am working on this

**Comment by intheshallow** [comment]
Any update on this?

**Comment by rahulanand77** [comment]
Is this issue fixed in 2.4.3?

**Comment by intheshallow** [comment]
It is not. I tested it.

**Comment by vDeggial** [comment]
Hi there,
Any update on this? Or a workaround as our client needs this to work
We have version 2.4.4 of Magento and it is still broken

**Comment by engcom-Bravo** [comment]
Hi @Chandresh22,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1273" alt="Screenshot 2024-06-19 at 10 52 21" src="https://github.com/magento/magento2/assets/51680745/f6b6ebf6-11d1-45a8-b2d8-601f05e99808">


<img width="1273" alt="Screenshot 2024-06-19 at 10 52 29" src="https://github.com/magento/magento2/assets/51680745/ebe53ace-a053-494c-8883-25844e0f17ec">


Out of stock always showing first while sorting.

Hence We are closing this issue.

Thansk.

**Comment by kapilpandya2203** [comment]
Hi @engcom-Bravo @engcom-Hotel , 
I checked in Dev branch and the issue is still reproducible.
please check attached video for reference.
https://www.loom.com/share/165a9f41ed944d60b3e13707d6324c5e?sid=e6b3a8a9-9824-4d3e-bb54-fc66adda2ae9
