### ISSUE TITLE
grunt error.

### ISSUE THREAD

**Issue by shuaiZend** [magento/magento2#3300]
2.0.1
Error information:
`[root@localhost mybag.com]# grunt exec:shuai
Running "exec:shuai" (exec) task
Running "clean:shuai" (clean) task

> > 31 paths cleaned.

Done, without errors.

Execution Time (2016-02-05 13:22:32 UTC)
loading tasks                316ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 89%
loading grunt-contrib-clean    7ms  ▇ 2%
clean:shuai                   30ms  ▇▇▇ 8%
Total 354ms

Processed Area: frontend, Locale: en_US, Theme: Shuai/luma, File type: less.

> > [Magento\Framework\Exception\FileSystemException]  
> >   Cannot create a symlink for "/home/wwwroot/mybag.com/vendor/magento/theme-frontend-blank/web/css/source/_reset.less" and place it to "/home/wwwroot/mybag.com/pub/static/frontend/Shuai/luma/en_US/css/source/_reset.less" Warning!file_get_contents(/home/wwwroot/mybag.com/var/cache//mage-tags/mage---a2d_INTERCEPTION): failed to open stream: No such file or directory
> > dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
> > Exited with code: 1.
> > Warning: Task "exec:shuai" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2016-02-05 13:22:31 UTC)
loading tasks  337ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 8%
exec:shuai      3.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 91%
Total 4s`

**var/cache//mage-tags/mage---a2d_INTERCEPTION): failed to open stream: No such file or directory**

**Comment by shuaiZend** [comment]
I fixed.coz php cant use symlink .
Open php.ini
find disable_functions
remove symlink
restart webserver.
grunt is okay!

**Comment by ghost** [comment]
shuaiZend, please keep it easy to explaination.

m not getting what u saygin

**Comment by shuaiZend** [comment]
@seetpal-smartshore 
Open **php.ini**
find **disable_functions**
remove **symlink**

**Comment by anton-huz** [comment]
Hi @shuaiZend 
We are appreciate your contribution. It's a good catch. Thank you.

Is issue still actual for you? May we close it?

**Comment by seetpalsingh** [comment]
Thanks for asking, its a long time I was in this.

But, I think I solved that symlink issue with grunt 

with running cmd/terminal/git-bash with administrator-mode/sudo.

from my side, its ok . we can close this issue.

:)
