### ISSUE TITLE
Multi-Currency not working when setting Custom Prices on adding product to Cart. This occurs on version 2.4.2 and previous versions as well

### ISSUE THREAD

**Issue by ticaje** [magento/magento2#33134]
### Preconditions (*)

1. Magento version 2.4.2.
2. Clean instance of Magento.
3. Sample products has been imported.
4. Two currencies have been defined: dollar and euro.
5. Dollar is default currency.
6. One website has been defined with two stores: English(default one) and Spanish store.
7. A custom module that catches __checkout_cart_product_add_after__ event to set Custom Price according to some specific business logic: https://www.mageplaza.com/devdocs/add-product-to-cart-with-custom-price-magento-2.html

### Steps to reproduce (*)

1. Enter PDP in front-end.
2. Add product to Cart(__dollar currency__).
3. For this product prices has been set(in the code) to 100 dollars.
4. Product has been added to Cart.
5. @magento give me 2.4-develop instance - upcoming 2.4.x release

### Expected result (*)

1. Either in mini-cart section or Cart Page the price must be the calculated in the custom module.
2. For dollar currency the price should be 100 dollars.
3. For euro currency the price should be 87 euros.

### Actual result (*)

1. For dollar currency the price is 100 dollars.
2. For euro currency the price is 100 euros.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

> Hi @engcom-Alfa. Thank you for working on this issue.
> In order to make sure that issue has enough information and ready for development, please read and check the following instruction: point_down
> 
>     * [ ]  1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).DetailsIf the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.
> 
>     * [ ]  2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.
> 
>     * [ ]  3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
> 
>     * [ ]  4. Verify that the issue is reproducible on `2.4-develop` branchDetails- Add the comment `@magento give me 2.4-develop instance` to deploy test instance on Magento infrastructure.  - If the issue is reproducible on `2.4-develop` branch, please, add the label `Reproduced on 2.4.x`.- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
> 
>     * [ ]  5. Add label `Issue: Confirmed` once verification is complete.
> 
>     * [ ]  6. Make sure that automatic system confirms that report has been added to the backlog.

I'd really like to add the labels you require in previous answer but I cant' find a way to do that over here

**Comment by i95devdivya** [comment]
@ticahe: Try this once vendor/magento/module-tax/Model/Sales/Total/Quote/CommonTaxCollector.php:692

$quoteItem->setCustomPrice($baseItemTaxDetails->getPrice());

should be:

$quoteItem->setCustomPrice($itemTaxDetails->getPrice());

**Comment by ticaje** [comment]
@i95devdivya That's already what core class has defined.
![image](https://user-images.githubusercontent.com/1042962/120633269-3e8df400-c46a-11eb-8e2c-e3bba0614f7a.png)

**Comment by ticaje** [comment]
@i95devdivya That's already what core class has defined.
![image](https://user-images.githubusercontent.com/1042962/120633269-3e8df400-c46a-11eb-8e2c-e3bba0614f7a.png)


> Hi @ticaje. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * Summary of the issue
> 
>     * Information on your environment
> 
>     * Steps to reproduce
> 
>     * Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> Please, add a comment to [assign the issue](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#assigning-an-issue): `@magento I am working on this`
> 
>     * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.
> 
> 
> warning According to the Magento Contribution requirements, all issues must go through the Community Contributions Triage process. Community Contributions Triage is a public meeting.
> 
> clock10 You can find the schedule on the [Magento Community Calendar page](https://opensource.magento.com/community-calendar).
> 
> telephone_receiver The triage of issues happens in the queue order. If you want to speed up the delivery of your contribution, please join the Community Contributions Triage session to discuss the appropriate ticket.
> 
> movie_camera You can find the recording of the previous Community Contributions Triage on the [Magento Youtube Channel](https://www.youtube.com/playlist?list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj)
> 
> pencil2 Feel free to post questions/proposals/feedback related to the Community Contributions Triage process to the corresponding [Slack Channel](https://magentocommeng.slack.com/archives/C016SG16J03)

I'd really like to add the labels you require in previous answer but I cant' find a way to do that over here

**Comment by ticaje** [comment]
I have just reported the issue, I don't have the knowledge to solve it, that's why I'm heading to you so you can take care of it since the problems comes out of a pretty common use case that is Setting Custom prices when adding to cart.

**Comment by engcom-Alfa** [comment]
HI @ticaje 
Tried on Magento 2.4-develop Magento, we can see the price differences after changing the currency ( from Dollar to Euro).

**Comment by ticaje** [comment]
Hi @engcom-Alfa please provide link to such environment so I can see it in action online.

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance.

**Comment by ticaje** [comment]
I don't know exactly how this env can be useful to our current issue. The problem comes when setting custom prices, using an event/observer, specifically after adding a product to cart and after that switching to a different currency. On that specific moment the prices go wrong, they remain the same, no conversion. When adding a product to cart the prices come back in mini-cart to correct values. The custom prices settlement is done according to the explanation this [Post](https://www.mageplaza.com/devdocs/add-product-to-cart-with-custom-price-magento-2.html) provides

**Comment by engcom-Delta** [comment]
@magento give me 2.4.2 instance.

**Comment by engcom-Hotel** [comment]
Hello @ticaje,

We are able to reproduce the issue in Magento 2..4-develop branch, with the description provided. We are confirming the issue.

Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42857` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment]
Hello @ticaje,

I am proposing below the solution for this issue. You need to make changes in your CustomPrice.php's execute function as below:
`public function execute(Observer $observer)
    {
        $item = $observer->getEvent()->getData('quote_item');
        $item = ( $item->getParentItem() ? $item->getParentItem() : $item );

        $curentCurrencyCode =  $this->storeManager->getStore()
            ->getCurrentCurrency()
            ->getCode();
        $this->logger->debug("Current Currency Code: ".$curentCurrencyCode);
        $baseCurrencyCode =  $this->storeManager->getStore()
            ->getBaseCurrency()
            ->getCode();
        $this->logger->debug("Base Currency Code: ".$baseCurrencyCode);
        $rate = $this->currencyFactory->create()
            ->load($curentCurrencyCode)
            ->getAnyRate($baseCurrencyCode);
        $this->logger->debug("Rate: ".$rate);

        $price = 200; //set your price here
        $convertedPrice = $price * $rate;
        $item->setCustomPrice($convertedPrice);
        $item->setOriginalCustomPrice($convertedPrice);
        $item->getProduct()->setIsSuperMode(true);
    }`

Please let us know if this fixes your issue.

Thanks

**Comment by ticaje** [comment]
Hi @engcom-Hotel, before everything let me say thank you for your support.
Ye, actually this is pretty much what I'm doing. Technical details appart, I kind of calculate custom price based on current store currency. But I think is important to stand out here that basically, regardless the custom price your setting up corresponds to current store currency, that price does not change properly when switching currency on front-end immediately after adding a product to cart.
Best regards

**Comment by engcom-Hotel** [comment]
Hello @ticaje,

It seems the solution is working for you. Can we close this issue now?

Thanks

**Comment by ticaje** [comment]
Hello @engcom-Hotel, the answer is no, it is not solved at all, the solution that I did perform is exactly what you propose and what the post that I specify in preconditions explains, but it does not work when multiple currencies, please see what you recomend  in action in this link [Example](http://dev.booktocuba.com/en/royalton-hicacos-double-room-junior-suite-adults-only.html). If you add the product to basket and after that switch to another currency, the price in the cart remains the same. See it by your self. I can't close the ticket with this picture cause the problem is not solved.

**Comment by 19681217** [comment]
We are retailer company and we are also going through the same issues. We are in the midst of a platform migration from 1.9 to 2.3 and we have stumbled upon this issue where switching from currency immediately after adding product to basket, with calculated prices on the fly, the amounts are not calculated properly.
We also implemented the solution to set custom prices you provided here by the way.
This is really important to us, it is crucial to our business and can not go forward with migration because of this.

**Comment by rush4u** [comment]
Hi, im in the process of migrating a store from 1.7 to 2.4, almost ol of our requirements are done already, but this issue is happening to us and we cannot be on production without this being resolved, Please help fix this issue

**Comment by engcom-Lima** [comment]
Hi,

This issue was already Confirmed and JIRA ticket was generated before so putting appropriate labels and moving to confirmed state again.

**Comment by hatemdeeb** [comment]
I can't believe that his issue still exists in Magento v 2.4.6
if you set custom_price to quote item (programmatically) $quoteItem->setCustomPrice(X); then you switch currency, the price of quote item is not being converted, instead it remains X
solution would be adding base_custom_price field to quote_item model then do the necessary converting as per base_price/price conversion

**Comment by hatemdeeb** [comment]
This issue still exists on Magento v 2.4.6
easy to re-produce without coding - just by using admin panel, you just need clean Magento instance, 
1. Configure two currencies at least, add new customer and a new simple product
2. In admin panel, create new order, and add one product 
3. Set custom price = X for this product 
4. Switch currency on the order creation page
Expected result: the quote item price should be converted to match new currency

Actual result: quote item's price remains unchanged after changing currency

Solution would be adding base_custom_price field to quote_item model then do the necessary converting as per base_price/price conversion

**Comment by maheshmakwana-code** [comment]
**[Magento Version 2.4.6]**

I faced the same issue while using the above code to add a custom price. I found there is one file where the getCustomPrice() function is called but it is not implemented that's why we did not get the proper custom price.  

`Path: /vendor/magento/module-quote/Model/Quote/Item.php ` 

After I solved addtocart event issue there was one more problem because of the currency switcher. I checked the quote_item table and found a difference between normal and custom price values. I created a plugin for it and fixed that issue.

`Path: vendor/magento/module-directory/Controller/Currency/SwitchAction.php` 

**I added the whole solution here.**

**app/code/Msquare/ModuleName/etc/frontend**

**events.xml**

	<?xml version="1.0"?>
	
	<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
	    <event name="checkout_cart_product_add_after">
	        <observer name="custom_price_add" instance="Msquare\CustomPriceFix\Observer\CustomPrice" />
	    </event>
	</config>


**app/code/Msquare/ModuleName/Observer**

**CustomPrice.php**

	<?php
	/**
	 * @category Msquare
	 * @package Msquare_CustomPriceFix
	 * @author Mahesh Makwana <maheshmakwana588@gmail.com>
	 */
	namespace Msquare\CustomPriceFix\Observer;

	use Msquare\CustomPriceFix\Helper\Data as DataHelper;
	use Magento\Framework\Currency\Data\Currency as CurrencyData;
	use Magento\Framework\Event\Observer;
	use Magento\Framework\Event\ObserverInterface;

	class CustomPrice implements ObserverInterface
	{
	    /**
	     * @param DataHelper $dataHelper
	     */
	    public function __construct(
	        protected DataHelper $dataHelper
	    ) {}

	    public function execute(Observer $observer)
	    {
	        $item = $observer->getEvent()->getData('quote_item');
	        $item = ($item->getParentItem() ? $item->getParentItem() : $item);
	        $price = 100; //set your price here

	        $curentCurrency = $this->dataHelper->getCurrentCurrency();
	        $baseCurrency = $this->dataHelper->getBaseCurrency();
	        if ($curentCurrency != $baseCurrency) {
	            $currencyObj = $this->dataHelper->getCurrencyFactory();
	            $rate = $currencyObj->load($baseCurrency)->getAnyRate($curentCurrency);
	            $price *= $rate;
	            $price = (float) $currencyObj->format($price, ['display' => CurrencyData::NO_SYMBOL], false);
	        }

	        $item->setCustomPrice($price);
	        $item->setOriginalCustomPrice($price);
	        $item->getProduct()->setIsSuperMode(true);
	    }

	}


**app/code/Msquare/ModuleName/Helper**

**Data.php**

	<?php
	/**
	 * @category Msquare
	 * @package Msquare_CustomPriceFix
	 * @author Mahesh Makwana <maheshmakwana588@gmail.com>
	 */
	namespace Msquare\CustomPriceFix\Helper;

	use Magento\Checkout\Model\CartFactory;
	use Magento\Directory\Model\CurrencyFactory;
	use Magento\Store\Model\StoreManagerInterface;

	class Data
	{
	    public function __construct(
	        protected StoreManagerInterface $storeManager,
	        protected CurrencyFactory $currencyFactory,
	        protected CartFactory $cartFactory
	    ) {}

	    /**
	     * Get base currency code
	     *
	     * @return string
	     */
	    public function getBaseCurrency()
	    {
	        return $this->storeManager->getStore()->getBaseCurrency()->getCurrencyCode();
	    }

	    /**
	     * Get current currency code
	     *
	     * @return string
	     */
	    public function getCurrentCurrency()
	    {
	        return $this->storeManager->getStore()->getCurrentCurrency()->getCurrencyCode();
	    }

	    /**
	     * Get currency factory
	     *
	     * @return CurrencyFactory
	     */
	    public function getCurrencyFactory()
	    {
	        return $this->currencyFactory->create();
	    }

	    /**
	     * Get cart items
	     *
	     * @return CartFactory
	     */
	    public function getCartItems()
	    {
	        return $this->cartFactory->create()->getQuote()->getAllItems();
	    }

	}


**app/code/Msquare/ModuleName/etc/frontend**

**di.xml**

	<?xml version="1.0"?>
	
	<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
	    <type name="Magento\Directory\Controller\Currency\SwitchAction">
	        <plugin name="custom_price_fix"
	                type="Msquare\CustomPriceFix\Plugin\Direcotry\Controller\Currency\SwitchAction"
	                sortOrder="10"/>
	    </type>
	</config>


**app/code/Msquare/ModuleName/Plugin/Direcotry/Controller/Currency**

**SwitchAction.php**

	<?php
	/**
	 * @category Msquare
	 * @package Msquare_CustomPriceFix
	 * @author Mahesh Makwana <maheshmakwana588@gmail.com>
	 */
	namespace Msquare\CustomPriceFix\Plugin\Direcotry\Controller\Currency;

	use Msquare\CustomPriceFix\Helper\Data as DataHelper;
	use Magento\Directory\Controller\Currency\SwitchAction as SwitchActionParent;
	use Magento\Framework\Currency\Data\Currency as CurrencyData;

	class SwitchAction
	{
	    /**
	     * @param DataHelper $dataHelper
	     */
	    public function __construct(
	        protected DataHelper $dataHelper
	    ) {}

	    /**
	     * Currency switcher before plugin
	     *
	     * @param SwitchActionParent $subject
	     *
	     * @return void
	     */
	    public function beforeExecute(SwitchActionParent $subject)
	    {
	        $items = $this->dataHelper->getCartItems();
	        $currencyObj = $this->dataHelper->getCurrencyFactory();
	        $baseCurrency = $this->dataHelper->getBaseCurrency();
	        $newCurrency = (string) $subject->getRequest()->getParam('currency');
	        if ($newCurrency != $baseCurrency) {
	            /* Update Price for Other Currency */
	            $rate = $currencyObj->load($baseCurrency)->getAnyRate($newCurrency);
	            foreach ($items as $item) {
	                $customPrice = $item->getBasePrice();
	                $customPrice *= $rate;
	                $customPrice = (float) $currencyObj->format($customPrice, ['display' => CurrencyData::NO_SYMBOL], false);
	                $item->setCustomPrice($customPrice);
	                $item->setOriginalCustomPrice($customPrice);
	                $item->getProduct()->setIsSuperMode(true);
	                $item->save();
	            }

	        } else {
	            /* Update Price for Base Currency */
	            foreach ($items as $item) {
	                $item->setCustomPrice($item->getBasePrice());
	                $item->setOriginalCustomPrice($item->getBasePrice());
	                $item->getProduct()->setIsSuperMode(true);
	                $item->save();
	            }
	        }
	    }
	}

**Note: Here NO_SYMBOL constant value is 1. You can also add static value.**
`Path: vendor/magento/framework/Currency/Data/Currency.php`
