### ISSUE TITLE
The front-end date-picker in PT "short name" broken

### ISSUE THREAD

**Issue by tyago343** [magento/magento2#33280]
### Preconditions (*)

1. Install a fresh magento 2.4.2-p1 instance
2. Locale Portuguese(Portugal) in the store

### Steps to reproduce (*)

1. Add DOB field in customer create
2. Go to customer/account/create/

### Expected result (*)
![image](https://user-images.githubusercontent.com/33085448/122550298-c9a6e680-d033-11eb-92ad-b49cfda60c95.png)
But with days short names in portuguese.

### Actual result (*)

![image](https://user-images.githubusercontent.com/33085448/122550108-9401fd80-d033-11eb-97db-46e6d778c660.png)

**Comment by engcom-Delta** [comment]
Hi tygo343,

Followed below steps and found that issue is reproducible in Magento 2.4.2-p1

1. Login to backend admin portal
2. Go to Stores --> configuration
3. Select Customers --> Customer configuration 
4. Change the Locale to  Portuguese
5. Save it
6. Go to Create customer section--> Account 
7. Click on Add new Customer 
8. Enter the required details apart from DOB & save it
9. Reload the  page
10. Observe that error ![Uploading SignupError_2.4.2.-p1.png…]().

Hence marked this as issue confirmed

**Comment by magento-engcom-team** [comment]
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by tyago343** [comment]
@magento-engcom-team I need to do something more to confirm this issue?

**Comment by engcom-Delta** [comment]
Hi @tyago343,

As per comments provided , issue is already confirmed. it is still reproducible on Magento 2.4.2-p1. Hence adding the label 'Issue confirmed'.

Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42864` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment]
Hi @tyago343,

This issue has tested on Magento 2.4. Develop and found that it is not reproducible .Hence, it is look like resolved in this version.
Kindly request to test from your end and confirm.

added the label 'Needs update'

Thanks

**Comment by tyago343** [comment]
Hi @engcom-Delta 
This 2.4-develop branch it's a wip branch? This fix will be in the next release of magento? 

I'm working with 2.4.2-p1 in production enviroment, so i can't downgrade to 2.4. 
thanks for your help.

**Comment by engcom-Delta** [comment]
Thanks @tyago343. closing the issue ,kindly raise new issue if required or please re-open the existing issue.

**Comment by tyago343** [comment]
Hi @engcom-Delta This issue it's not solved, in Magento 2.4.2-p1 (latest version) it's reproducible.
