### ISSUE TITLE
Currency Symbol Disappear on Product View Page (After Fully Loaded)

### ISSUE THREAD

**Issue by WebHostingAce** [magento/magento2#33856]
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Visit any product page
2. Currency symbol appears eg - $1.00
3. Wait untill page fully load.
4. Currency symbol disappear eg - 1.00

### Expected result (*)

1. Currency Symbol to remain displayed.

### Actual result (*)

1. Currency symbol disappear

Tried with a freshly installed Magento 2.4.3. I can confirm this is a bug.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by yogicse** [comment]
@WebHostingAce 

I tried to replicate the issue on my local setup with Magento 2.4.3 Open Source. But Issue not replicate. it shows the price with currency symbol after fully page load as well.

**System Configuration** 
Ubuntu 18, PHP 7.4, Apache

**Tested In Both Mode of Application**
Magento 2.4.3 with Production mode
Magento 2.4.3 with Developer mode

**Step Followed**

Visit any product page
Currency symbol appears eg - $1.00
Wait untill page fully load.
Currency symbol disappear eg - 1.00

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by WebHostingAce** [comment]
@yogicse Thank you for your reply.

Ive installed on a fresh copy. The currency is A$.

Tried on Mozilla, Chrome and Edge. Same result.

https://www.fmbdev.xyz/test2.html

**Comment by WebHostingAce** [comment]
Cart page Cart Summary and Checkout page Order Summary also missing the currency symbol.

**Comment by engcom-Echo** [comment]
Hi @WebHostingAce 
We tried to reproduce the issue on **2.4-develop** branch & were unable to do so.
Here are the Steps we followed,
1. Create a fresh installation of magento (2.4-develop branch) with parameters **--language=en_AU --currency=AUD --timezone=Australia/Melbourne**
2. Created a New Product & Visited the product on frontend.
The Currency symbol is displayed properly on the product page & also on the cart & checkout pages.
<img width="1232" alt="Screenshot 2021-08-19 at 14 33 00" src="https://user-images.githubusercontent.com/51681435/130043098-5ec58efc-599d-4804-a483-a6b304dfde9f.png">

<img width="1308" alt="Screenshot 2021-08-19 at 14 34 18" src="https://user-images.githubusercontent.com/51681435/130043082-653549dd-b817-44bd-b936-845fe34a1b83.png">
<img width="633" alt="Screenshot 2021-08-19 at 14 35 37" src="https://user-images.githubusercontent.com/51681435/130043126-0fb473dc-68fc-4f96-af09-98219bff10c6.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

Thank you.

**Comment by ihor-sviziev** [comment]
@engcom-Echo, the 2.4.3 release still NOT merged to 2.4-develop. Could you double-check the issue on 2.4.3 release OR on 2.4-develop branch AFTER merging

**Comment by WebHostingAce** [comment]
@engcom-Echo  I can reproduce this issue on a upgrade from 2.3.5 to 2.4.3 as well

**Comment by WebHostingAce** [comment]
> 
> 
> @WebHostingAce
> 
> I tried to replicate the issue on my local setup with Magento 2.4.3 Open Source. But Issue not replicate. it shows the price with currency symbol after fully page load as well.
> 
> **System Configuration**
> Ubuntu 18, PHP 7.4, Apache
> 
> **Tested In Both Mode of Application**
> Magento 2.4.3 with Production mode
> Magento 2.4.3 with Developer mode
> 
> **Step Followed**
> 
> Visit any product page
> Currency symbol appears eg - $1.00
> Wait untill page fully load.
> Currency symbol disappear eg - 1.00

Could you please share the command line for the installation you followed?

**Comment by yogicse** [comment]
@WebHostingAce 

`/usr/local/bin/composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.3`

`php bin/magento setup:install --base-url=http://magentodev.com/ --db-host=localhost --db-name=magento --db-user=root --db-password=admin123 --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200 --backend-frontname=admin`

**Comment by zlep** [comment]
This issue is related to https://github.com/magento/magento2/issues/33798

**Comment by WebHostingAce** [comment]
@yogicse I tried with your command line.. same issue. https://www.fmbdev.xyz/test2.html

@zlep I get the price correctly. The issue is $ symbol disappear after the page fully load.

**Comment by zlep** [comment]
@WebHostingAce Set it to Euro and Local German and you will loose the actual price. When I set it to Dollar and anything else than Local English, I will loose the currency symbol as well.

**Comment by engcom-Echo** [comment]
> @engcom-Echo, the 2.4.3 release still NOT merged to 2.4-develop. Could you double-check the issue on 2.4.3 release OR on 2.4-develop branch AFTER merging?

Hi @ihor-sviziev 
Its recommended to verify the issues on Magento 2.4-develop branch only as the issues in 2.4.2-p1/ 2.4.3 are fixed in 2.4-develop branch. 
@WebHostingAce Sorry but I'm not able to reproduce this issue on Magento 2.4-develop branch with provided steps.
Kindly recheck the issue on 2.4-develop and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by WebHostingAce** [comment]
@zlep Thank you for the update. Now I know I'm not the only one who is facing this issue.

**Comment by ihor-sviziev** [comment]
@engcom-Echo, I've asked @sdzhepa to explain a bit more about releases and branches.

**Comment by onlinebizsoft** [comment]
Oh is this release 2.4.3 that bad? Quite few major issues.

**Comment by ihor-sviziev** [comment]
Hi @engcom-Echo, could you double check this issue on 2.4-develop branch again? The 2.4.3 is release just was merged to it

**Comment by reense** [comment]
Hi! I've been digging into this issue. So far, I've found the following:

The problem is caused by `Magento_Catalog/js/price-box.js` in the function `reloadPrice: function reDrawPrices()`, specifically this:
```
 $('[data-price-type="' + priceCode + '"]', this.element).html(priceTemplate({
                    data: price
                }));
```

This explains why it takes a couple of seconds.

the `price` variable in the snippet above is created by this line (price-box.js:153): 
```
price.formatted = utils.formatPrice(price.final, priceFormat);
```
It uses the `priceFormat` variable. `priceFormat` comes from the `priceConfig` variable passed in `Magento_Catalog/product/view/form.phtml`:

```
"[data-role=priceBox][data-price-box=product-id-<?= $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig":  <?= /* @noEscape */ $block->getJsonConfig() ?>
            }
        }
``` 

`getJsonConfig()` in `Magento\Catalog\Block\Product\View` calls `$this->_localeFormat->getPriceFormat()`, which resolves to `Magento\Framework\Locale\Format`. 

The `$result` of `Magento\Framework\Locale\Format` looks like this:
```
       $result = [
            //TODO: change interface
            'pattern' => $currency->getOutputFormat(),
            'precision' => $totalPrecision,
            'requiredPrecision' => $requiredPrecision,
            'decimalSymbol' => $decimalSymbol,
            'groupSymbol' => $groupSymbol,
            'groupLength' => $group,
            'integerRequired' => $totalPrecision == 0,
        ];
```

The `$currency->getOutputFormat()` is what causes the bug; in Magento  2.4.2 this method returns the following (for the euro currency);
```
€ %s
```

On Magento 2.4.3 this method returns the following:

```
%s
```

If we take a closer look at the implementation of `getOutputFormat()`, we see that two variables get computed, named `$formatted` and `$number`.
```
    public function getOutputFormat()
    {
        $formatted = $this->formatTxt(0);
        $number = $this->formatTxt(0, ['display' => \Magento\Framework\Currency::NO_SYMBOL]);
        return str_replace($this->trimUnicodeDirectionMark($number), '%s', $formatted);
    }
```

So far, I've conclused that the problem is in the `$number` declaration. It calls the `formatTxt()` method with the `NO_SYMBOL` option. However, the `$number` variable still contains the currency symbol. This causes the `str_replace` method to replace the currency symbol, causing it to return without the symbol.

I'm currently investigating why this option does not seem to apply. If I have any progress updates to share, I will do so here.

@ihor-sviziev  do you have any idea why no currency symbol is returned?

**Comment by reense** [comment]
Hello,

I've found the issue. It is caused by this commit: https://github.com/magento/magento2/commit/ba2ae68a55c6e571a58c749e2a96f366d6a05745#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927

More specifically, line 369 through 370 in `Magento\Directory\Model\Currency` causes this issue:
```
 if ($this->canUseNumberFormatter($options)) {
            return $this->formatCurrency($price, $options);
        }
```

canUseNumberFormatter results to true, causing the price to be improperly returned. This is new behaviour as of Magento 2.4.3, which, to me, looks like a definite bug.

removing the if statement causes the price to render properly and stay proper, because the priceFormat is correct.

**Comment by zlep** [comment]
@reense Could you please look into https://github.com/magento/magento2/issues/33798 because as I said, these two issues are related. But as fas as I tested with the develop-branch are fixed.

**Comment by ihor-sviziev** [comment]
Hi @reense,
Is the issue reproducing on the 2.4-develop branch?

**Comment by WebHostingAce** [comment]
Thanks to @reense I changed the formatTxt function with 2.4.2. It worked.
`    public function formatTxt($price, $options = [])
    {
        if (!is_numeric($price)) {
            $price = $this->_localeFormat->getNumber($price);
        }
        /**
         * Fix problem with 12 000 000, 1 200 000
         *
         * %f - the argument is treated as a float, and presented as a floating-point number (locale aware).
         * %F - the argument is treated as a float, and presented as a floating-point number (non-locale aware).
         */
        $price = sprintf("%F", $price);
        return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
    }`

**Comment by reense** [comment]
@ihor-sviziev  sorry, I do not have enough time to check if it's reproducable on a 'standard' Magento 2.4.3 instance. I have, however, selected 'Luma' as design theme and this issue was still occurring. I have no plugins installed that are interfering with the named classes (checked via `dev:di:info`). I also disabled the all the custom extensions. I have, however, disabled all Magento MSI modules but I do not think that that is the root cause of this issue.

@WebHostingAce sure, that works. However, it still does not explain why it's happening, and happening only on 2.4.3..

**Comment by engcom-Echo** [comment]
> Hi @engcom-Echo, could you double check this issue on 2.4-develop branch again? The 2.4.3 release just was merged to it

@ihor-sviziev 
I again tried to reproduce the issue with a fresh installation of magento (2.4-develop branch) with parameters 
**--language=en_AU --currency=AUD --timezone=Australia/Melbourne** but wasnt able to reproduce it. Currency Symbol was displayed properly on Product page, cart & checkout.

**Comment by reense** [comment]
@engcom-Echo This is happening for us on detail pages of configurable products with multiple configurations, in combination with product options.

**Comment by jtomaszewski** [comment]
To make it work on Magento 2.4.3 without having to switch to unstable develop branch, you can create a `patches/magento-disable-currency-number-formatter.patch` file with following content:

```patch
--- Model/Currency.php
+++ Model/Currency.php
@@ -365,10 +365,6 @@
          */
         $price = sprintf("%F", $price);
 
-        if ($this->canUseNumberFormatter($options)) {
-            return $this->formatCurrency($price, $options);
-        }
-
         return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
     }
 
```

And then add the following to your `composer.json`:

```json
{
    "extra": {
        "patches": {
            "magento/module-directory": {
                "Disable number formatter for Model/Currency ( https://github.com/magento/magento2/issues/33856 )": "patches/magento-disable-currency-number-formatter.patch"
            }
        }
    }
}
```

**Comment by ihor-sviziev** [comment]
Hi @jtomaszewski,
Could you provide some steps to reproduce the issue on clean magento installation? 
On which PHP version is it happening?
Could you provide the output of `php -i` where the issue reproducing?

**Comment by WebHostingAce** [comment]
@baoutch I'm on Plesk as well.

**Comment by ihor-sviziev** [comment]
Hi @baoutch,
It looks like you don't have the `intl` extension installed.

Could you run `composer check-platform-reqs` on your environment?

**Comment by ihor-sviziev** [comment]
@engcom-November, please check https://github.com/magento/magento2/issues/33910#issuecomment-908956529, feels like there is some diff on different OS, or library versions that causing these issues.

**Comment by LRotherfield** [comment]
@ihor-sviziev we are running into the same issue so I ran your snippet on 3 environments:
```
50.2
10,30 €
10,30 €

65.1
10,30 €
10,30

67.1
10,30 €
10,30
```
That all looks good regarding an upgrade to ICU, however, our issue is with the `GBP` currency symbol with the `en_US` locale, and if I change your script to use those values I get the following:

```
cat - <<'EOF' | php
<?php

try {
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
    $icuVersion = trim($matches[1]);
} catch (\ReflectionException $e) {
    $icuVersion = null;
}
echo $icuVersion . PHP_EOL;


$formatter = new NumberFormatter('en_US', NumberFormatter::CURRENCY);

echo $formatter->formatCurrency(10.3, "GBP") . PHP_EOL;

$formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
echo $formatter->formatCurrency(10.3, "GBP") . PHP_EOL;
EOF
```
```
50.2
£10.30
£10.30

65.1
£10.30
10.30

67.1
£10.30
£10.30
```
As you can see, there is unexpected behaviour in `67.1` and `50.2`.  We also get the unexpected behaviour in `69.1` for `GBP` and `en_US`. 

It seems the `en_US` locale is the cause of the issue for newer versions of ICU after 65.1.  If I use `en_GB` I get expected results for `67.1`:
```
67.1
£10.30
10.30
```

**Comment by ihor-sviziev** [comment]
@LRotherfield,
Now I'm not sure if that's related to the ICU library.
Could you send your `php -i` output from 3 different environments? Maybe there is a diff between other things?

**Comment by LRotherfield** [comment]
@ihor-sviziev 

Centos 7: [65.1-phpinfo-2.txt](https://github.com/magento/magento2/files/7091737/65.1-phpinfo-2.txt)
Centos 7: [65.1-phpinfo.txt](https://github.com/magento/magento2/files/7091738/65.1-phpinfo.txt)
Both the above give the following when using `GBP` and `en_US`:
```
65.1
£10.30
10.30
```

Mac OS 11.5.2: [67.1-phpinfo.txt](https://github.com/magento/magento2/files/7091739/67.1-phpinfo.txt)
The above gives the following when using `GBP` and `en_US`:
```
67.1
£10.30
£10.30
```

Centos 7: PHP 7.3.29 (cli) (built: Jul  2 2021 17:39:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.29, Copyright (c) 1999-2018, by Zend Technologies
The above gives the following when using `GBP` and `en_US`:
```
50.2
£10.30
£10.30
```

As you can see, the newer version of ICU is running on Mac OS so it is possible the issue is there for newer versions.  However all the others are running on Centos 7 with the issue happens on one of the PHP73 boxes but not the other, so I don't think the issue is OS or PHP version.

**Comment by ihor-sviziev** [comment]
@LRotherfield, thx for the input!
Could you check if the changes from https://github.com/magento/magento2/pull/33966 are fixing the issue?

**Comment by LRotherfield** [comment]
@ihor-sviziev I have tested the patch on one of two projects and it worked.  I will test the other project in the morning

**Comment by pmonosolo** [comment]
I have the same issue on production server with 2.4.3. The Currency sign disappears on product page after full load.(CA$100 then 2 seconds later 100)

On catalog page, the currency sign just shows up even though it's not set to CA in the configuration on backend. All prices have this sign. 

Also if you try to change the currency sign it has no effect.

**Comment by pmonosolo** [comment]
> @baoutch I'm on Plesk as well.

Are you running Apache as your backend?

I have this issue too - Production server = Apache (does not work), Local Machine = NGINX (works correctly)

**Comment by pmonosolo** [comment]
Looks like this might be the solution to the currency showing up on the Catalog page even though its disabled within configuration:
https://github.com/magento/magento2/pull/33966/commits/82c1a4d1137f747b9551e7d4d87106bf2c726b9e

**Comment by ihor-sviziev** [comment]
@pmonosolo, the solution from https://github.com/magento/magento2/pull/33966 still doesn't work fine on all installations. 
Here is workaround that you can use in the meanwhile https://github.com/magento/magento2/issues/33856#issuecomment-904606945

**Comment by pmonosolo** [comment]
> @pmonosolo, the solution from #33966 still doesn't work fine on all installations.
> Here is a workaround that you can use in the meanwhile [#33856 (comment)](https://github.com/magento/magento2/issues/33856#issuecomment-904606945)
> OR you can update the ICU library that is used in PHP to version >= 65

Yup, looks like that one is finally starting to work on Catalog pages. I think it was probably propagating through the redis cache or something like that because some products would get correct symbol and some would still have the broken one.

Thanks for letting me know! Easy patch then!

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by SoCix** [comment]
I am on 2.4.3-p and having same issue

**Comment by SoCix** [comment]
> ihor-sviziev

Thanks ihor, I've applied the patch, and it is working like a charm, thank You

**Comment by ihor-sviziev** [comment]
@bijeeshkg,
Please review the following comment https://github.com/magento/magento2/issues/33856#issuecomment-946761019

**Comment by bijeeshkg** [comment]
@ihor-sviziev thanks this patch works like a charm!

**Comment by calvinmuller** [comment]
how do I apply this patch when i've installed magento via composer? The code lives in the vendor directory?

**Comment by LRotherfield** [comment]
@calvinmuller you can install patches in the vendor directory with https://github.com/cweagans/composer-patches

**Comment by parthaccorin** [comment]
> Looks like the issue was fixed by internal team in the following commit Looks like this issue was fixed in [ae304d4](https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde). Could someone confirm that?

This is the solution, I am able to fix it with a patch of this commit. we have issues on PDP, Cart, and Checkout Summary all of them are fixed with it.
Thank you.

**Comment by ShapesGraphicStudio** [comment]
Hi,
Suddenly got the same issue updating from 2.4.3 to 2.4.5...

**Comment by ihor-sviziev** [comment]
@ShapesGraphicStudio, I see the changes from https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde were included to 2.4.4, 2.4.4-p1 and 2.4.5, so you shouldn't have it.
Could you please report a separate issue and express that you have it on 2.4.5, which contains the fix?
Thank you!

**Comment by ShapesGraphicStudio** [comment]
Well, I had a diffchecker on my vendor/magento/module-directory/Model/Currency.php file and ae304d4 patch and they were different. Uploading the patch seems to have done the trick nicely..

**Comment by stkrelax** [comment]
@ihor-sviziev 
upgraded today to 2.4.5 -p1 the currency problem still causes 0 prices on db quote items and on cart view
in our case it actually caused configurables not being visible in cart at all after adding, though it was added successfully.

i had a look at the suggested patch and than to the core code to be patched. 
Actually it seems the problem is something different:

you seem to have commited a special invisible char U+00a0 (no break space ) instead of a space (or may be it should be like this ?)

when i change 
            $formattedCurrency = preg_replace('/{{no-brak-space}}/u', '', $formattedCurrency, 1);
to
            $formattedCurrency = preg_replace('/{{space}}/u', '', $formattedCurrency, 1);

and 
            $formattedCurrency = preg_replace('{{no-brak-space}}', '', $formattedCurrency, 1);
to
            $formattedCurrency = preg_replace('{{space}}', '', $formattedCurrency, 1);

it works for me in EURO and PLN

Adjusting Unicode Highlighting options in vsc made it visible:


![Bildschirmfoto vom 2022-11-25 16-22-50](https://user-images.githubusercontent.com/48922246/204015451-fba0b48e-1562-47e9-9bf4-656eb5431999.png)

**Comment by n2diving-dgx** [comment]
Same problem reappears in 2.4.6... workaround patches to core mentioned above are not compatible with 2.4.6, need a new version of the fix for 2.46... wonder why M2 can't seem to fix this issue, it's been going on since 2.4.3

**Comment by ihor-sviziev** [comment]
Hi @stkrelax @n2diving-dgx @dphilipps,
If you see this issue on Magento 2.4.6 and 2.4-develop, please report a separate issue.
Thank you!

**Comment by n2diving-dgx** [comment]
I can confirm @dphilipps analysis is correct.  CentOS has the very dated libicu v50 core OS library.  Upon updating the server CentOS libicu to v71 and recompiling php 8.1 the issue with missing currency symbols on Magento front end was resolved for our instance of M2.4.6 (and also M2.4.5-p2).     

This issue is apparently a compatibility conflict between older versions of the International Components for Unicode and Magento.

**Comment by frostitution** [comment]
@dphilipps @n2diving-dgx 

I found this thread after desperately searching why our currency symbol on cart page was not appearing after updating from Magento 2.4.4 -> 2.4.5-p2 and it put me on the right track to learning that our ICU version was also 50.2

I verified the issue by copying over the file at `vendor/magento/module-directory/Model/Currency.php` on 2.4.5-p2 over to a 2.4.4 installation and could re-create the issue successfully.

After updating our ICU version the problem was resolved. Thank you!!! There should definitely be some sort of notice by Adobe about this, I thought this was due to some third party module we had installed and was ready to tear our entire store apart trying to figure this out.

**Comment by ihor-sviziev** [comment]
@frostitution if you have steps to reproduce of how can we reproduce it on clear Magento installation, please report a separate issue.
Thank you!

**Comment by dphilipps** [comment]
> @dphilipps @n2diving-dgx
> 
> I found this thread after desperately searching why our currency symbol on cart page was not appearing after updating from Magento 2.4.4 -> 2.4.5-p2 and it put me on the right track to learning that our ICU version was also 50.2
> 
> I verified the issue by copying over the file at `vendor/magento/module-directory/Model/Currency.php` on 2.4.5-p2 over to a 2.4.4 installation and could re-create the issue successfully.
> 
> After updating our ICU version the problem was resolved. Thank you!!! There should definitely be some sort of notice by Adobe about this, I thought this was due to some third party module we had installed and was ready to tear our entire store apart trying to figure this out.

You're welcome - glad you got it working!

**Comment by xtremevision** [comment]
Updating libicu using the remi repo fixed the problem, on Magento 2.4.6. No need for any patches.

**Comment by ligurukas** [comment]
> Updating libicu using the remi repo fixed the problem, on Magento 2.4.6. No need for any patches.

Hi, could you please give more information how you have updated it through remi repo? I have installed remi repo on Centos 7 and using the command "yum update libicu" I get a notice "No packages marked for update"
