### ISSUE TITLE
Can't add custom theme

### ISSUE THREAD

**Issue by serzhik** [magento/magento2#3409]
When I try to generate static content for my custom theme I get an error:

```
=== frontend -> Vendor/theme -> en_US ===
Unable to load theme by specified key: 'Vendor/theme'>

#0 C:\www\site.loc\www\vendor\magento\module-theme\Model\View\Design.php(147): Magento\Framework\View\Design\Theme\FlyweightFactory->create('Vendor/theme', 'frontend')
#1 C:\www\site.loc\www\vendor\magento\module-deploy\Model\Deployer.php(140): Magento\Theme\Model\View\Design->setDesignTheme('Vendor/theme', 'frontend')
#2 C:\www\site.loc\www\vendor\magento\module-deploy\Console\Command\DeployStaticContentCommand.php(120): Magento\Deploy\Model\Deployer->deploy(Object(Magento\Framework\App\ObjectManagerFactory), Array)
#3 C:\www\site.loc\www\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(257): Magento\Deploy\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\www\site.loc\www\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\www\site.loc\www\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Deploy\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\www\site.loc\www\vendor\magento\framework\Console\Cli.php(49): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\www\site.loc\www\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\www\site.loc\www\bin\magento(25): Symfony\Component\Console\Application->run()
#9 {main}
```

**Comment by serzhik** [comment]
After runing `composer update` problem was fixed.

**Comment by davidalger** [comment]
@Serzhik Your latest comment states the issue was fixed by running composer updated, but then you re-opened the issue. Are you still encountering errors. generating static content? If so, can you post details… steps to reproduce, php / mysql versions, etc?

**Comment by serzhik** [comment]
1. Install Magento 2.0.2.
2. Copy custom theme to `app/design/frontend/Vendor/theme`
3. Run `php bin/magento setup:upgrade`
4. Run `php bin/magento setup:static-content:deploy`
5. Get an error.

**Comment by serzhik** [comment]
I think it can be related to #2797

**Comment by serzhik** [comment]
I delete folder `vendor` and run `composer update`.
Problem was resolved.

**Comment by davidalger** [comment]
Good to know. If you run into this again, let us know!

**Comment by grasdaggel** [comment]
We have the same problem but no chance to use the composer over the Terminal. Any other ideas how to fix it?

**Comment by serzhik** [comment]
@kingalca 
1. To add new theme you need to turn in developer mode.
2. Sometimes new theme added to 'theme' table with param 'type'=1 (virtual theme). Try to set it to 0 (physical theme)

**Comment by Igloczek** [comment]
Problem still exist and fixing them by removing package from vendor is good only for local development / testing purposes.

It looks like somehow composer/magento ignore autoload of `registration.php`, because when we add manually record to `theme` table, everything works fine...

**Comment by ghost** [comment]
I faced same problem when I trying to redeploy static content.

![screen shot 2016-07-18 at 11 27 24](https://cloud.githubusercontent.com/assets/5654423/16912500/5c28e14c-4cdc-11e6-9d24-a71cb8733c14.png)

I realised that, "Vendor/theme => Magento/lumaClone" hasn't registered on my "theme" table. Then I added that entry manually. 

![screen shot 2016-07-18 at 11 30 30](https://cloud.githubusercontent.com/assets/5654423/16912522/8511b318-4cdc-11e6-8e6d-86628a762b6d.png)

Then I executed following commands from Magento root directory

php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:static-content:deploy

After that my problem was sorted.

![screen shot 2016-07-18 at 11 32 14](https://cloud.githubusercontent.com/assets/5654423/16912569/cc80830a-4cdc-11e6-9e1a-4ac8881838a1.png)

Hope this would help someone.

**Comment by workmi** [comment]
cdhalwatura - u need add u theme in table : theme

**Comment by tomnyson** [comment]
you can setting this theme to default theme and try again.
i have done it

**Comment by SyedMuneebb** [comment]
Please follow this simple step by step guide: [Create Custom Theme Magento 2](https://magenticians.com/create-custom-theme-magento-2/)
