### ISSUE TITLE
Unable to create credit note, "Please enter positive number in this field." validation error for adjustment fields

### ISSUE THREAD

**Issue by edward-simpson** [magento/magento2#34375]
### Preconditions (*)

1. M2.4.3
2. Order with online or offline payment, and invoice

### Steps to reproduce (*)

1. Navigate to invoice, create credit note
2. Refund Shipping, Adjustment refund, Adjustment fee all 0

### Expected result (*)

1. Credit memo gets created successfully

### Actual result (*)

1. Unable to submit credit note, each of the above fields gets a validation error "Please enter positive number in this field."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tuanpht** [comment]
Hi, as my research so far, this is related to PHP Intl NumberFormatter => https://stackoverflow.com/a/63108846/6595322.

But I haven't found what different between my local docker environment and server yet:

Test script:
```php
$a = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY); 
$a->setSymbol(NumberFormatter::CURRENCY_SYMBOL, ''); 
var_dump($a->formatCurrency(123, 'USD'));
```

Result on my local docker environment ([dockerfile](https://github.com/sun7pro/docker-library/blob/master/magento2-php-fpm/7.4-composer2.Dockerfile))

![image](https://user-images.githubusercontent.com/21072956/140018354-b57d2372-b04f-47bb-87df-831d3736885a.png)

Result on my server:
![image](https://user-images.githubusercontent.com/21072956/140018522-17f4f09d-4f54-4bcf-ae90-6dd94467ea6e.png)

**Comment by IanFiretoys** [comment]
this appears to have been related to the disappearing currency symbols etc, and was fixed with this patch for us: https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde

**Comment by tuanpht** [comment]
So this line https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R440-R443 fixed this issue by remove all special character
```diff
@@ -430,7 +439,7 @@ private function formatCurrency(string $price, array $options): string

        if ((array_key_exists(LocaleCurrency::CURRENCY_OPTION_DISPLAY, $options)
                && $options[LocaleCurrency::CURRENCY_OPTION_DISPLAY] === \Magento\Framework\Currency::NO_SYMBOL)) {
-            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
+            $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);
        }
```

But still don't know why there's difference in the results of PHP Intl NumberFormatter https://github.com/magento/magento2/issues/34375#issuecomment-958687958

**Comment by engcom-Delta** [comment]
Hi @edward-simpson,
As per commented provided patch is fixed the problem, Hence we are closing the ticket. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by edward-simpson** [comment]
@engcom-Delta is it going to be merged into core?  If not I wouldn't really count that as a permanent solution

**Comment by dchaykas** [comment]
> ```diff
> index 65b47d7535c..f9943daba24 100644
> --- a/vendor/magento/module-directory/Model/Currency.php
> +++ b/vendor/magento/module-directory/Model/Currency.php
> @@ -365,10 +365,6 @@ class Currency extends \Magento\Framework\Model\AbstractModel
>           */
>          $price = sprintf("%F", $price);
>  
> -        if ($this->canUseNumberFormatter($options)) {
> -            return $this->formatCurrency($price, $options);
> -        }
> -
>          return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
>      }
>  
> ```
> 
> This patch resolved the issue

This piece of code definitely caused the issue, removing it resolves the problem but why was it added there in the first place? If removing this IF statement might as well remove the private function within it, it's not used anywhere else.

`Index: vendor/magento/module-directory/Model/Currency.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-directory/Model/Currency.php b/vendor/magento/module-directory/Model/Currency.php
--- a/vendor/magento/module-directory/Model/Currency.php	
+++ b/vendor/magento/module-directory/Model/Currency.php	(date 1638491758615)
@@ -365,41 +365,9 @@
          */
         $price = sprintf("%F", $price);
 
-        if ($this->canUseNumberFormatter($options)) {
-            return $this->formatCurrency($price, $options);
-        }
-
         return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
     }
 
-    /**
-     * Check if to use Intl.NumberFormatter to format currency.
-     *
-     * @param array $options
-     * @return bool
-     */
-    private function canUseNumberFormatter(array $options): bool
-    {
-        $allowedOptions = [
-            'precision',
-            LocaleCurrency::CURRENCY_OPTION_DISPLAY,
-            LocaleCurrency::CURRENCY_OPTION_SYMBOL
-        ];
-
-        if (!empty(array_diff(array_keys($options), $allowedOptions))) {
-            return false;
-        }
-
-        if (array_key_exists('display', $options)
-            && $options['display'] !== \Magento\Framework\Currency::NO_SYMBOL
-            && $options['display'] !== \Magento\Framework\Currency::USE_SYMBOL
-        ) {
-            return false;
-        }
-
-        return true;
-    }
-
     /**
      * Format currency.
      *
`

**Comment by shaileshjangir** [comment]
> > ```diff
> > index 65b47d7535c..f9943daba24 100644
> > --- a/vendor/magento/module-directory/Model/Currency.php
> > +++ b/vendor/magento/module-directory/Model/Currency.php
> > @@ -365,10 +365,6 @@ class Currency extends \Magento\Framework\Model\AbstractModel
> >           */
> >          $price = sprintf("%F", $price);
> >  
> > -        if ($this->canUseNumberFormatter($options)) {
> > -            return $this->formatCurrency($price, $options);
> > -        }
> > -
> >          return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
> >      }
> >  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This patch resolved the issue
> 
> This piece of code definitely caused the issue, removing it resolves the problem but why was it added there in the first place? If removing this IF statement might as well remove the private function within it, it's not used anywhere else.
> 
> ```
> Index: vendor/magento/module-directory/Model/Currency.php
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/vendor/magento/module-directory/Model/Currency.php b/vendor/magento/module-directory/Model/Currency.php
> --- a/vendor/magento/module-directory/Model/Currency.php	
> +++ b/vendor/magento/module-directory/Model/Currency.php	(date 1638491758615)
> @@ -365,41 +365,9 @@
>           */
>          $price = sprintf("%F", $price);
>  
> -        if ($this->canUseNumberFormatter($options)) {
> -            return $this->formatCurrency($price, $options);
> -        }
> -
>          return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
>      }
>  
> -    /**
> -     * Check if to use Intl.NumberFormatter to format currency.
> -     *
> -     * @param array $options
> -     * @return bool
> -     */
> -    private function canUseNumberFormatter(array $options): bool
> -    {
> -        $allowedOptions = [
> -            'precision',
> -            LocaleCurrency::CURRENCY_OPTION_DISPLAY,
> -            LocaleCurrency::CURRENCY_OPTION_SYMBOL
> -        ];
> -
> -        if (!empty(array_diff(array_keys($options), $allowedOptions))) {
> -            return false;
> -        }
> -
> -        if (array_key_exists('display', $options)
> -            && $options['display'] !== \Magento\Framework\Currency::NO_SYMBOL
> -            && $options['display'] !== \Magento\Framework\Currency::USE_SYMBOL
> -        ) {
> -            return false;
> -        }
> -
> -        return true;
> -    }
> -
>      /**
>       * Format currency.
>       *
> ```

Thanks , its worked for me 👍

**Comment by gjportegies** [comment]
Also having this issue on a vanilla Magento 2.4.3 instance with sample data.

<img width="851" alt="Schermafbeelding 2022-01-12 om 17 07 04" src="https://user-images.githubusercontent.com/6707410/149177135-9b79f2de-a911-41bb-8f5d-b6c0cf166067.png">

**Comment by tschallacka** [comment]
@gjportegies use this fix as a patch https://github.com/magento/magento2/issues/34375#issuecomment-958722456

**Comment by DJB95** [comment]
this might be obvious to you guys, but in what directory can I apply this patch?
Our installation doesn't have the directory app/code/Magento/Directory/Model
I tried creating it myself and adding the Currency.php file there, but it doesn't work.

I'm on Magento 2.4.1 btw (soon updating to 2.4.3)
Our numbers are formatted like this: **0,-** (no currency symbol)

#NotARealProgrammer:D

**Comment by gjportegies** [comment]
@DJB95 I've added the patch via `composer.json`:

```
    "extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/module-directory": {
                "AC-1089: Fixed incorrect amount display for PLN currency in summary section": "patches/composer/github-issue-34375.diff"
            }
        }
    }
```

The patch file `patches/composer/github-issue-34375.diff` contains the following:

```
index 65b47d7535c..f9943daba24 100644
--- a/Model/Currency.php
+++ b/Model/Currency.php
@@ -365,10 +365,6 @@ class Currency extends \Magento\Framework\Model\AbstractModel
          */
         $price = sprintf("%F", $price);

-        if ($this->canUseNumberFormatter($options)) {
-            return $this->formatCurrency($price, $options);
-        }
-
         return $this->_localeCurrency->getCurrency($this->getCode())->toCurrency($price, $options);
     }

```

**Comment by IanFiretoys** [comment]
@DJB95 
the github repo for magento is an image of a non-composer based install. in an instance of magento installed through composer they would be in the vendor/magento folder (the rest of the path will usually be the same). but just replacing that file isn't recommended as it will be overwritten.

most recommend using composer patches: https://github.com/cweagans/composer-patches

with that you can use the patch provided by @gjportegies above

some more info here about making your own: https://magento.stackexchange.com/questions/256571/create-magento-2-patch

**Comment by DJB95** [comment]
@gjportegies & @IanFiretoys thanks guys! will give it a shot!

**Comment by DJB95** [comment]
@gjportegies @IanFiretoys just tried that, but it doesn't solve the issue. See the image below:
![image](https://user-images.githubusercontent.com/74458320/150327367-465b4e46-2225-49e0-8488-1bf746bf1ede.png)

the currency symbol is not there, but it adds the **.-**
Is it correct that this is not solved by this patch?

**Comment by jcconde** [comment]
After reviewing their comments I have applied the next on Magento Cloud 2.4.3-p1

```
        if ((array_key_exists(LocaleCurrency::CURRENCY_OPTION_DISPLAY, $options)
                 && $options[LocaleCurrency::CURRENCY_OPTION_DISPLAY] === \Magento\Framework\Currency::NO_SYMBOL)) {
             $formattedCurrency = str_replace(' ', '', $formattedCurrency);
+            $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);
         }
```

After that I did other changes on `magento/module-sales/view/adminhtml/templates/order/creditmemo/create/totals/adjustments.phtml` file
```
<td>
             <input type="text"
                    name="creditmemo[shipping_amount]"
-                   value="<?= /* @noEscape */ $block->formatValue($block->getShippingAmount()) ?>"
+                   value="<?= /* @noEscape */ $block->formatValue($block->getShippingAmount(), ['display' => \Zend_Currency::NO_SYMBOL]) ?>"
                    class="input-text admin__control-text not-negative-amount"
                    id="shipping_amount" />
         </td>
@@ -29,7 +29,7 @@
         <td>
             <input type="text"
                    name="creditmemo[adjustment_positive]"
-                   value="<?= /* @noEscape */ $block->formatValue($_source->getBaseAdjustmentPositive()) ?>"
+                   value="<?= /* @noEscape */ $block->formatValue($_source->getBaseAdjustmentPositive(), ['display' => \Zend_Currency::NO_SYMBOL]) ?>"
                    class="input-text admin__control-text not-negative-amount"
                    id="adjustment_positive" />
         </td>
@@ -42,7 +42,7 @@
         <td>
             <input type="text"
                    name="creditmemo[adjustment_negative]"
-                   value="<?= /* @noEscape */ $block->formatValue($_source->getBaseAdjustmentNegative()) ?>"
+                   value="<?= /* @noEscape */ $block->formatValue($_source->getBaseAdjustmentNegative(), ['display' => \Zend_Currency::NO_SYMBOL]) ?>"
                    class="input-text admin__control-text not-negative-amount"
                    id="adjustment_negative"/>
             <?php $scriptString = <<<script
```

**Comment by snez** [comment]
@engcom-Delta everyone in the thread is confirming the issue on the **Magento 2.4.3-p1** yet you are testing on the develop branch. Noone is using the develop branch of Magento on production sites. This should be tested on the **reported** version, planned for 2.4.3-p2 internally, update the community on internal plans and temporary workaround, and move on.

**Comment by lytesaber** [comment]
Experiencing reported issue on current Magento 2.4.3-p1 release.

Both currency symbol and prefix causing issues with processing / creating a credit memo on invoice.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/16328255/160327119-b7daac0a-cf78-42e2-8215-4b53a6eb17b0.png">

**Comment by Organizer21** [comment]
@engcom-Delta Just ran into this issue on Magento 2.4.3-p1 having it confirmed if a patch is being rolled into whatever the next version is would be helpful a already pointed out... this does not seem to be a "localized issue" but a general one. 

That aside, I am new your GITHUB work and M2, but are issues often closed without a fix being implemented into the next versions? This must be the third or fourth issue we have, where we end up on a bug thread here after extensive searching... some bug even created years ago and thread still being open. 

If a fix have been posted, it's also unclear to me how the bug can still exist in the latest M2 version (and where closed it's not clear if it's a confirmed bug that then will be fixed in the next version or not - so far my experience with M2 is rather negative as far as clear and concise communication goes on these type of threads).

**Comment by erfanimani** [comment]
@snez bugs should be reproduced on the develop branch. If you can't reproduce on develop, it must mean it's fixed, and the issue should be changed to become a backport. Hence, the core team uses `develop` to validate issues.

I'm running into this issue as well, and the above suggestion fixed it for me.

**Comment by snez** [comment]
@erfanimani we know it is fixed now that 2.4.4 has been released. But a response like "I tried to reproduce on a different version and I couldn't, so it must be fixed" is not the same as "I was able to reproduce it on the reported version, followed the exact same steps and was not able to reproduce it on develop, so it is definitely fixed and will be released in 2.4.4".

**Comment by erfanimani** [comment]
@snez you're right, but I suppose that responsibility lies with the developer that is reporting the issue.

**Comment by ctadlock** [comment]
I think this is related to the version of the PHP INTL ICU. Im using Amazon linux 2 on my prod server and Ubuntu 22.04 for dev, both are PHP 7.4.30. However if you run "php -i" on both you get different version of the ICU.

Ubuntu
```
Internationalization support => enabled
ICU version => 70.1
ICU Data version => 70.1
ICU TZData version => 2022a
ICU Unicode version => 14.0
```

aws
```

**Comment by dphilipps** [comment]
I also resolved this issue on 2.4.5-p1 by updating ICU libraries from 50.2 to 71.1.
