### ISSUE TITLE
2.3.5-p2 Elastic Search does not asc/desc position sort products on category page 

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#34583]
### Preconditions (*)

1. Magento 2.3.5-p2
2. Elastic Search installed and enabled
3. Sample data installed

### Steps to reproduce (*)

1. Go to Category page (Women's > Jackets)
2. Click descending sort

### Expected result (*)

1. Products are desc sorted by product id/created at

### Actual result (*)

1. No changes to product order

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nbennett25** [comment]
@magento give me 2.3.5-p2 instance

**Comment by nbennett25** [comment]
@magento give me 2.3.5-p2 instance

**Comment by nbennett25** [comment]
@magento give me 2.3.5-p2 instance

**Comment by engcom-Delta** [comment]
Hi @nbennett25 ,
We have verified on Magento 2.4 Develop latest branch(frontend).it works fine , we could see the changes to product order.
Hence added the label 'Needs update'.
Please find the attached snapshots for reference.
![Before DescendingSort](https://user-images.githubusercontent.com/51681379/140873123-223a5b75-33da-4471-ae1f-7e12574515d2.JPG)
![After DescendingSort](https://user-images.githubusercontent.com/51681379/140873142-21a4a5d3-537c-449d-b09f-929fddccc646.JPG)

**Comment by devchris79** [comment]
This issue appears in quite a few open issues for 2.4, it appears to now be fixed in the 2.4 develop code branch.

I posted a while back for 2.4.3 #32522 and came up with a change to the setCollection function to get my ordering to work. The current develop code doesn't implement the same change though, so I am guessing the root cause was fixed rather than my cover up.

**Comment by nbennett25** [comment]
Thx @engcom-Delta  - but as noted in the preconditions of the issue, the Magento version should have been 2.3.5-p2, not 2.4. Nice to hear that it's fixed in 2.4 though. 

@devchris79 I tried applying your patch to a clean 2.3.5-p2 install, and no luck - the asc/desc still does not change the product order. 

@magento give me 2.3.5-p2 instance

**Comment by nbennett25** [comment]
@magento give me 2.3.5-p2 instance

**Comment by engcom-Delta** [comment]
Hi @nbennett25 ,
As it works fine on Magento 2.4 develop with latest branch, we are closing the issue .Kindly request to re-open it if required or raise fresh ticket.

Thanks
