### ISSUE TITLE
\DateTime object should be usable in ExtensionAttributes or in relatd

### ISSUE THREAD

**Issue by MeCapron** [magento/magento2#34904]
### Preconditions (*)

1. Magento 2.4.2-p2

### Steps to reproduce (*)

1. Define DateTime extension attributes
2. 
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Customer\Api\Data\CustomerInterface">
        <attribute code="date" type="DateTime"/>
    </extension_attributes>
</config>
```
3. Error shows : `1 exception(s): Exception #0 (InvalidArgumentException): Each getter must have a doc block. See DateTime::format()`

### Expected result (*)

1. `DateTime` built-in must be ignored as `\Magento\Framework\Phrase` is

### Actual result (*)

1. Error shows : `1 exception(s): Exception #0 (InvalidArgumentException): Each getter must have a doc block. See DateTime::format()`

### Possible solution

https://github.com/magento/magento2/blob/2.4.2-p2/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php#L114 

we could replace this line by : 

```php
if (is_object($value) && (!($value instanceof Phrase) && !($value instanceof \DateTime))) {
```

and https://github.com/magento/magento2/blob/2.4.2-p2/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php#L120 

```php
if (is_object($singleValue) && (!($singleValue instanceof Phrase) && !($singleValue instanceof \DateTime))) {
```

We could also maybe add a di.xml field to allow such configuration or ignoring specific types. I can't measure the impact of the latest solution though.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @MeCapron,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-dev but the issue is not reproducible.

Steps followed to reproduce issue:
1. Installed the fresh Magento 2.4-dev instance.
2. Added the following code to the extension_attributes.xml file.
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Customer\Api\Data\CustomerInterface">
        <attribute code="date" type="DateTime"/>
    </extension_attributes>
</config>

Cleard cache and run di:compile to generate new files.
bin/magento c:c 
bin/magento setup:di:compile   

Following code generated after execution of di:compile under file “generated/code/Magento/Customer/Api/Data/CustomerExtensionInterface.php”

<?php
namespace Magento\Customer\Api\Data;

/**
 * ExtensionInterface class for @see \Magento\Customer\Api\Data\CustomerInterface
 */
interface CustomerExtensionInterface extends \Magento\Framework\Api\ExtensionAttributesInterface
{
    /**
     * @return DateTime|null
     */
    public function getDate();

    /**
     * @param DateTime $date
     * @return $this
     */
    public function setDate(\DateTime $date);
}
```
3. Tested the generated code by using the below mention code
```
$customerDataObject = $this->customerRepository->getById($customerId);
$extension = $customerDataObject->getExtensionAttributes();
$extension->setDate( \DateTime::createFromFormat( 'Y-m-d', date('Y-m-d') ) );
echo $extension->getDate()->getTimestamp();
```
4. The above code successfully, without any error. (See the attached output screenshot).

<img width="1289" alt="Screenshot 2022-01-13 at 7 56 16 PM" src="https://user-images.githubusercontent.com/51681435/149460851-5bb400a8-0b61-43fc-a059-f392e6a8db72.png">

If the issue still persists at your end then please provide some more details or provide the exact steps, accordingly, I’ll try to reproduce it again.

Thanks

**Comment by MeCapron** [comment]
> ```
> is_object($value) && (!($value instanceof Phrase)
> ```

Hello, thanks for watching out this issue. I retried and figured out that I shuffled two issues. Very sorry about this.

This issue still persists in this way : 

1. Add an extension_attribute that is an objet model 
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Customer\Api\Data\CustomerInterface">
        <attribute code="date" type="MyModule\MyObject\Model\DTOWDateTime"/>
    </extension_attributes>
</config>
```

```php
<?php

declare(strict_types=1);

namespace MyModule\MyObject\Model;

use Magento\Framework\DataObject;
use DateTime;

class DTOWDateTime extends DataObject
{
    /**
     * @return DateTime
     */
    public function getMyDateTime(): DateTime
    {
        return new DateTime();
    }
}
```

2. Generate the code `bin/magento c:c && bin/magento setup:di:compile`
3. Try to save the customer, you will pass in `vendor/magento/framework/Reflection/ExtensionAttributesProcessor.php` l118 that will break

Thanks

**Comment by engcom-Echo** [comment]
Hi @MeCapron,

I understood the issue now which you are getting but it seems it's not an actual issue, after debugging it some more I found that buildOutputDataArray($dataObject, $dataObjectType) needs an object and its type, and on the basis of object type it loads the interface. But in our case, we are using the standard PHP date time object for which Magento doesn’t have an interface available. To solve this issue we need to use Magento’s standard DateTime library.

Update your extension_attributes.xml with the following code:
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Customer\Api\Data\CustomerInterface">
        <attribute code="date" type="Magento\Framework\Stdlib\DateTime"/>
    </extension_attributes>
</config>
```
And while using, you have to use Stdlib\DateTime() instead the standard DateTime object.
$customerDataObject->getExtensionAttributes()->setDate(new Stdlib\DateTime());

Hope it helps. Let me know if you are still face this issue or provide more relevant details if you think it is Magento core issue ?

Thanks

**Comment by engcom-Hotel** [comment]
Dear @MeCapron,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by MeCapron** [comment]
> Hi @MeCapron,
> 
> I understood the issue now which you are getting but it seems it's not an actual issue, after debugging it some more I found that buildOutputDataArray($dataObject, $dataObjectType) needs an object and its type, and on the basis of object type it loads the interface. But in our case, we are using the standard PHP date time object for which Magento doesn’t have an interface available. To solve this issue we need to use Magento’s standard DateTime library.
> 
> Update your extension_attributes.xml with the following code:
> 
> ```
> <?xml version="1.0"?>
> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
>     <extension_attributes for="Magento\Customer\Api\Data\CustomerInterface">
>         <attribute code="date" type="Magento\Framework\Stdlib\DateTime"/>
>     </extension_attributes>
> </config>
> ```
> 
> And while using, you have to use Stdlib\DateTime() instead the standard DateTime object. $customerDataObject->getExtensionAttributes()->setDate(new Stdlib\DateTime());
> 
> Hope it helps. Let me know if you are still face this issue or provide more relevant details if you think it is Magento core issue ?
> 
> Thanks

Hi!

I do not really aggree about using Magento main DateTime. What about external objects that are using DateTime of any kind of PHP object? Would it mean that if the **core** function has no docblock, we will just skip it? Plus, you are blocking the use of external objects that are not part of Magento system (such as serialized DTOs from API calls)

I think that all of the native PHP objects should not be part of the reflection in this system, or should be handled without any doc block (which can not be done in some cases).

What do you think about this?

Melvin

**Comment by MeCapron** [comment]
Hello, can someone provide me an update on this?

Thanks you

**Comment by MeCapron** [comment]
> Dear @MeCapron,
> 
> We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
> 
> Regards

Hello,

Can you reopen this issue please? This is still an issue.

Thanks
