### ISSUE TITLE
Magento Graph QL : route query product and cms-page caching issue

### ISSUE THREAD

**Issue by mandarzope** [magento/magento2#34908]
### Preconditions (*)
1. Magento 2.4.3-p1
2. Sample Data is imported

### Steps to reproduce (*)
1. Query using route(url:"<<product-url>>") 

### Expected result (*)

1. Response header should contain X-Magento-Tags and Cache-Control to be public

### Actual result (*)

1. X-Magento-Tags header is missing and Cache-Control is no-cache

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

After debugging I have found that 
vendor/magento/module-cms-url-rewrite-graph-ql/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php:26
vendor/magento/module-catalog-url-rewrite-graph-ql/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php:36

expects a key 'id' to be present in $resolvedData
$ids = [$selectedCacheTag, sprintf('%s_%s', $selectedCacheTag, $resolvedData['id'])];

A workaround solution is to overwrite the files 
vendor/magento/module-catalog-url-rewrite-graph-ql/Model/DataProvider/UrlRewrite/ProductDataProvider.php:48
$product = $this->productRepository->getById($id, false, $storeId);
$result = $product->getData();
$result['id'] = $product->getId();

vendor/magento/module-cms-url-rewrite-graph-ql/Model/DataProvider/UrlRewrite/Page.php:49
$result = $this->pageDataProvider->getDataByPageId((int)$id);
$result['type_id'] = $entity_type;
$result['id'] = $result['page_id']

**Comment by mandarzope** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @mandarzope,

Thank you for reporting the issue.

I have tried to reproduce it on Magento 2.4-develop instance but getting proper response headers which contains x-magento-tags when I am running any query. Attached screenshot for your ref.

<img width="1191" alt="Screenshot 2022-01-03 at 1 13 45 PM" src="https://user-images.githubusercontent.com/51681435/147908532-a1235e39-9794-4445-958a-dfe5ddfe6fc3.png">

There was a similar query reported [here](https://magento.stackexchange.com/questions/212529/magento-2-x-magento-tags-missing-form-header/213964). You can check and see if it helps. If you still think it is Magento core issue, can you please provide more info or if I missed anything which will help me in reproducing it ?

Thanks

**Comment by aligent-lturner** [comment]
The issue here is very similar for both Products and CMS pages.

For products, data is provided by https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogUrlRewriteGraphQl/Model/DataProvider/UrlRewrite/ProductDataProvider.php

For CMS pages, data is provided by https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CmsUrlRewriteGraphQl/Model/DataProvider/UrlRewrite/Page.php

Both of these data providers return data using the relevant repositories, so for products, we end up with `entity_id` as part of the result array, while for CMS pages, we end up with `page_id`.

However, when it comes to determining if a query is cacheable, we need to look at https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php and https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CmsUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php

We can see in both cases, the code is looking specifically for the presence of `id` in the resolved data. Since this doesn't exist in either case, no cache tags get added to the array of identities. Subsequently, the query is considered to not be cacheable, and the no-cache headers are added.

https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php#L29-L40

https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CmsUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php#L26-L34


My suggestion would be for one of the following two things to happen:
1. Change `CatalogUrlResolverIdentity` to use `entity_id` instead of `id`. This class is also used for categories, but since they also have an entity id, this should still work. Similarly, change `CmsUrlResolverIdentity` to use `page_id` instead of `id`.
2. Change the two data providers to additionally set the `id` value based on `entity_id` (for products) or `page_id` (for CMS pages.

**Comment by aligent-lturner** [comment]
> The issue here is very similar for both Products and CMS pages.
> 
> For products, data is provided by https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogUrlRewriteGraphQl/Model/DataProvider/UrlRewrite/ProductDataProvider.php
> 
> For CMS pages, data is provided by https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CmsUrlRewriteGraphQl/Model/DataProvider/UrlRewrite/Page.php
> 
> Both of these data providers return data using the relevant repositories, so for products, we end up with `entity_id` as part of the result array, while for CMS pages, we end up with `page_id`.
> 
> However, when it comes to determining if a query is cacheable, we need to look at https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php and https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CmsUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php
> 
> We can see in both cases, the code is looking specifically for the presence of `id` in the resolved data. Since this doesn't exist in either case, no cache tags get added to the array of identities. Subsequently, the query is considered to not be cacheable, and the no-cache headers are added.
> 
> https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php#L29-L40
> 
> https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CmsUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php#L26-L34
> 
> My suggestion would be for one of the following two things to happen:
> 
> 1. Change `CatalogUrlResolverIdentity` to use `entity_id` instead of `id`. This class is also used for categories, but since they also have an entity id, this should still work. Similarly, change `CmsUrlResolverIdentity` to use `page_id` instead of `id`.
> 2. Change the two data providers to additionally set the `id` value based on `entity_id` (for products) or `page_id` (for CMS pages.

That will teach me to check an older version of the code - it appears this issue has already been fixed in `2.4-develop` (as can be seen in the code snippets above)

**Comment by aligent-lturner** [comment]
@engcom-Echo can you test this against the latest 2.4-develop code - I believe it should be fixed now.

**Comment by rostilos** [comment]
Apparently, the reason is that initially graphql requests are POST requests, so cache tags will not be assigned to them because of this condition
![2024-07-10_01-08](https://github.com/magento/magento2/assets/85498741/e2a5f0b5-ed1a-4507-a1e8-0097af008aec)

**Comment by mandarzope** [comment]
I had raised the PR in past (2 years back). However because I am not a contributor, these are not accepted.

https://github.com/magento/magento2/pull/34910

https://github.com/magento/magento2/pull/34909

**Comment by engcom-Bravo** [comment]
Hi @mandarzope,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance and the issue is still reproducible.Kindly refer the screenshots.

<img width="1407" alt="Image" src="https://github.com/user-attachments/assets/857d593f-4aec-4b47-8434-8d3567f112a4" />



X-Magento-Tags header is missing and Cache-Control is no-cache.Hence Confirming the issue.

Thanks.
