### ISSUE TITLE
Configurable Product still OOS In case the variants is In stock

### ISSUE THREAD

**Issue by johnybk08** [magento/magento2#35494]
**Preconditions (*)**
1. Magento EE 2.4.4

**Steps to reproduce (*)**
Step 1: Create new configurable with Color RED, Blue (for example)
Step 2: update stock for Variant RED to In Stock and qty > 0

Access to PDP
**Expected result (*)**
The configurable is in stock

**Actual result (*)**
Actual: The configurable product is still OOS

After a detail investigate I found that the 2.4.4 had updated the function getStatusExpression in Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\DefaultStock

**Comment by engcom-Delta** [comment]
Hi @johnybk08 ,
Thank you for raising an issue and We are happy to assist you . Kindly provide clear issue description, pre-condition, steps to reproduce, actual results and expected results .

Regards,

**Comment by maheshm-kensium** [comment]
Hi @engcom-Delta ,

We are also seeing the same issue in 2.4.4 version, once configurable parent product goes out of stock it is always stays in OOS because stock status is not updating in cataloginventory_stock_status table.

**Preconditions and environment**
Setup Vanilla 2.4.4 Magento instance either Open Source or Commerce Edition

**Steps to reproduce**
Scenario 1:
1. Create new configurable product with child variants with Quantities and set stock status to Is In Stock
2. Now update all child products to Out Of Stock then check cataloginventory_stock_status table and see that stock status setting correctly to 0 for both parent and child products.
3. Now again change Stock Status back to Is In Stock for all child products then check cataloginventory_stock_status table and see that only child product stock status updating to 1 correctly but parent still is in 0 stock status.

Scenario 2:
1. Create new configurable product with child variants with Quantities and set stock status to Is In Stock
2. Now update parent product stock status to Out Of Stock then check cataloginventory_stock_status table and see stock status setting correctly to 0 for the parent product.
3. Now again change Stock Status back to Is In Stock for parent product then check cataloginventory_stock_status table and see that stock status not updating and still is in 0 stock status value.

**Expected result**
In both scenarios Parent Product Stock Status should to update stock status value 1 in cataloginventory_stock_status table.

**Actual result**
In both scenarios Parent Product Stock Status value not changing from 0 to 1 in cataloginventory_stock_status table.

![Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/64009865/170519529-4bebe718-0877-4dcc-af87-cdff39117802.png)

![localhost-localhost-mage244os001-cataloginventory_stock_status-phpMyAdmin-4-6-6deb5ubuntu0-5](https://user-images.githubusercontent.com/64009865/170519602-286bbd2f-6a69-409e-9423-ccd194d4da2c.png)

![Products-Inventory-Catalog-Magento-Admin(1)](https://user-images.githubusercontent.com/64009865/170520047-0d273df0-7f1b-4f2e-8b71-a418cf8cf634.png)

![localhost-localhost-mage244os001-cataloginventory_stock_status-phpMyAdmin-4-6-6deb5ubuntu0-5(1)](https://user-images.githubusercontent.com/64009865/170520090-2835f880-7b47-4421-b0b1-95b1ab2f6561.png)

**Comment by engcom-Delta** [comment]
Hi @johnybk08 ,
Kindly confirm what was the configurable product (Parent ) quantity you have entered while creating please?
Thanks

**Comment by maheshm-kensium** [comment]
Hi @engcom-Delta ,

For Configurable Product we always keep zero, so no quantity.

**Comment by engcom-Delta** [comment]
We have verified the issue on Magento 2.4.develop EE , issue is not reproducible . 
Please find below steps and screenshots for reference.

Scenario 1:

1. Create new configurable product with child variants with Quantities and set stock status to Is In Stock

<img width="1440" alt="Screenshot 2022-05-30 at 8 13 52 PM" src="https://user-images.githubusercontent.com/51681379/171017973-7d8964e7-8a2a-4b5d-ad2f-5a346ffc8992.png">
<img width="1440" alt="Screenshot 2022-05-30 at 8 22 46 PM" src="https://user-images.githubusercontent.com/51681379/171018013-9862c22c-a86e-4303-a467-65943d2e4cce.png">

2. Now update all child products to Out Of Stock then check cataloginventory_stock_status table and see that stock status setting correctly to 0 for both parent and child products.

<img width="1440" alt="Screenshot 2022-05-30 at 8 37 01 PM" src="https://user-images.githubusercontent.com/51681379/171020102-eba4d2f8-cca5-4f07-a2df-15e77bdb3969.png">

3. Now again change Stock Status back to Is In Stock for all child products then check cataloginventory_stock_status table and see that only child product stock status updating to 1 correctly but parent still is in 0 stock status.

<img width="1440" alt="Screenshot 2022-05-30 at 8 41 56 PM" src="https://user-images.githubusercontent.com/51681379/171020864-62d132c1-bb11-4241-b132-74c8c73cc215.png">


Scenario 2:

1. Create new configurable product with child variants with Quantities and set stock status to Is In Stock
2. Now update parent product stock status to Out Of Stock then check cataloginventory_stock_status table and see stock status setting correctly to 0 for the parent product.

<img width="1440" alt="Screenshot 2022-05-30 at 8 44 19 PM" src="https://user-images.githubusercontent.com/51681379/171021360-7fe2041d-cf2e-407c-8752-97237a312c96.png">
<img width="1440" alt="Screenshot 2022-05-30 at 8 44 56 PM" src="https://user-images.githubusercontent.com/51681379/171021432-0ba1b023-c920-4b38-88d9-77eb8989eb24.png">

3. Now again change Stock Status back to Is In Stock for parent product then check cataloginventory_stock_status table and see that stock status not updating and still is in 0 stock status value.

<img width="1440" alt="Screenshot 2022-05-30 at 8 47 24 PM" src="https://user-images.githubusercontent.com/51681379/171021748-7ab9c660-03db-48a7-b6f0-2dcaea1c7673.png">


Actual result
In both scenarios Parent Product Stock Status value is changing from 0 to 1 in cataloginventory_stock_status table.

**Comment by maheshm-kensium** [comment]
Hi @engcom-Delta ,

I verified again with 2.4-develop branch the configurable stock status is working as expected. But when we installed the 2.4.4 CE or EE with composer, the below issue is still exist. 
https://github.com/magento/magento2/issues/35494#issuecomment-1138697607

So, after reviewing further I understood that issue is coming due to MSI Inventory Modules, when we disabled MSI modules then configurable status updating as expected and when we enabling back we are seeing the same stock status issues.

The expected behaviour of configurable parent stock status is:
1. If parent is in stock and all child product is in stock, then if we change all child stock status to OOS then parent should be OOS as well.
2. If parent is OOS and all child product is OOS, then if we change any once child stock status to Is In Stock then parent should be Is In Stock.
3. Irrespective of child, if we manually update parent from OOS to Is In stock or vice versa it should work the same.

Because of the MIS Inventory modules this functionality not working as expected, when we install Magento through composer MIS modules will be installed as well and this causing the issue.

**Comment by engcom-Delta** [comment]
Hi @maheshm-kensium ,

Thank you for confirming the issue once again , We will verify on 2.4.4 CE or EE with composer and update you .

Regards,

**Comment by engcom-Delta** [comment]
Hi @maheshm-kensium ,

Here are the test results:
1. If parent is in stock and all child product is in stock, then if we change all child stock status to OOS then parent should be OOS as well.

<img width="1440" alt="Screenshot 2022-06-03 at 5 27 18 PM" src="https://user-images.githubusercontent.com/51681379/171854866-f86a29f8-0747-4c60-b738-899094d278a3.png">
<img width="789" alt="Screenshot 2022-06-03 at 5 47 06 PM" src="https://user-images.githubusercontent.com/51681379/171860827-1fc995a8-9215-41c3-aa38-bd1792d83aa6.png">

**Before changing child stock to OOS**

<img width="789" alt="Screenshot 2022-06-03 at 5 47 06 PM" src="https://user-images.githubusercontent.com/51681379/171860988-f7746436-21b9-44e4-8c5c-337e44dee716.png">

**After changing child stock to OOS**

<img width="1043" alt="Screenshot 2022-06-03 at 5 58 02 PM" src="https://user-images.githubusercontent.com/51681379/171861071-e38a31e2-6bd7-4ed7-9ad7-1998483928e7.png">

on UI:
<img width="1440" alt="Screenshot 2022-06-03 at 6 44 04 PM" src="https://user-images.githubusercontent.com/51681379/171861398-f6a765d9-9586-4e0a-bf76-a3b90ef3389c.png">


If parent is OOS and all child product is OOS, then if we change any once child stock status to Is In Stock then parent should be Is In Stock.
Irrespective of child, if we manually update parent from OOS to Is In stock or vice versa it should work the same.

**Comment by maheshm-kensium** [comment]
Hi, can anyone please help me to make understand, whether this issue is fixed or still is in progress?

**Comment by engcom-Delta** [comment]
Hi @johnybk08 

The issue was already fixed and merged in Inventory develop branch [PR](https://github.com/magento-commerce/inventory/pull/247).

Thanks.

**Comment by saran2108** [comment]
Hi @engcom-Delta 

Please share patch for this fix, Shared develop branch [PR](https://github.com/magento-commerce/inventory/pull/247) not able to access showing 404

**Comment by danielrussob** [comment]
Hello @saran2108 ,
you must apply Quality Patch: MDVA-41061-V4 and ACSD-45488

https://devdocs.magento.com/quality-patches/tool.html#patch-grid

**Comment by engcom-November** [comment]
Hi,
As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-813 by the internal team 
Related commits: https://github.com/magento/magento2/search?q=ACP2E-813&type=commits
Based on Jira, target version is 2.4.6
Thank you.

**Comment by luancschmitz** [comment]
@engcom-November 

This problem continues to occur in version 2.4.4 of Magento after the application of MDVA-41061-V4 and ACSD-45488 Patches.

Steps to reproduce:

1. Create a configurable product with in stock status and its variations without stock and quantity 0 by API REST
2. Enter one of the variations, put the stock to: "in stock", and quantity 10.

Expected outcome:
The configurable product will return to appear in stock and can be purchased normally.

Current results:
Configurable product continues as "without stock".
If you look at the cataloginventory_stock_status table the stock_status column will have the value 0 for the configurable product.

To solve, you must go back to the configurable product, change stock status to "out of stock", save the product, change the status to "in stock" and save the product, the product is available for purchase.

**Comment by jcoszig** [comment]
> Hello @saran2108 , you must apply Quality Patch: MDVA-41061-V4 and ACSD-45488
> 
> https://devdocs.magento.com/quality-patches/tool.html#patch-grid

I can confirm that on M2.4.4-p1 these patches fix the cataloginventory_stock_status table when configurable variants are set to in stock/ out of stock in the admin panel as noted above. However if you run a qty + stock status update via product import then the issue remains. Presumably this might also be an issue with stock status updates via API although I haven't tested this.

**Comment by Winfle** [comment]
This still happens, we REALLY suffer from it.
I've checked magento-inventory module attached to the 2.4.4-p1, so it doesn't contain realted fixes.
How can we apply lates inventory modules with this fix?

**Comment by jcoszig** [comment]
> This still happens, we REALLY suffer from it. I've checked magento-inventory module attached to the 2.4.4-p1, so it doesn't contain realted fixes. I can't any pull request or commit attached to the issue. How can we apply latest inventory modules with this fix?

Please try the following:

quality patches: MDVA-41061-V4 and ACSD-45488
and additionally [this patch](https://github.com/magento/magento2/files/10769129/ACSD-47951_2.4.4-p1.patch)

**Comment by NicholasRoge** [comment]
We are experiencing this issue as well and the recommended patches have no effect on (Magento Commerce 2.4.4-p2).  As best as I can tell, this is being caused by a bad query in the cataloginventory_stock indexer.  When determining a product's status for any product which is not a bundle or grouped product, the Magento_InventoryCatalog module overrides the non-MSI Magento_CatalogInventory module's default handler for obtaining the stock status expression, updating it from `Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\StatusExpression\DefaultExpression` to `Magento\InventoryCatalog\Model\ResourceModel\StockStatusExpressionForDefaultStock`.  

The only thing that is changed about the MSI status expression is that, if the product is manage stock, instead of directly using the `cisi.is_in_stock` value as ultimate factor to decide whether the product is in stock, it adds a condition: 

```sql
IF(
    cisi.is_in_stock = 0,
    0,
    IF(
        css.stock_status IS NOT NULL,
        css.stock_status,
        cisi.is_in_stock
    )
)
```

That is, if the product is out of stock, set the product to out of stock; otherwise, use **the existing stock status value**.  I believe that this is the source of products not being updated to being back in stock.  In the case where the product is in stock according to the `cataloginventory_stock_item` table, if it was out of stock before, it will continue to be out of stock since the existing out of stock value will be used.  Please let me know if I am mistaken, but for the time being I am considering this a bug and will be patching it out.

**Comment by Winfle** [comment]
> Hello still have this issue on Magento 2.4.5-p1 someone has found a solution ?

We just activate products by cron, thats all we can do in this case.

**Comment by DzemalBecirevic** [comment]
> We are experiencing this issue as well and the recommended patches have no effect on (Magento Commerce 2.4.4-p2). As best as I can tell, this is being caused by a bad query in the cataloginventory_stock indexer. When determining a product's status for any product which is not a bundle or grouped product, the Magento_InventoryCatalog module overrides the non-MSI Magento_CatalogInventory module's default handler for obtaining the stock status expression, updating it from `Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\StatusExpression\DefaultExpression` to `Magento\InventoryCatalog\Model\ResourceModel\StockStatusExpressionForDefaultStock`.
> 
> The only thing that is changed about the MSI status expression is that, if the product is manage stock, instead of directly using the `cisi.is_in_stock` value as ultimate factor to decide whether the product is in stock, it adds a condition:
> 
> ```sql
> IF(
>     cisi.is_in_stock = 0,
>     0,
>     IF(
>         css.stock_status IS NOT NULL,
>         css.stock_status,
>         cisi.is_in_stock
>     )
> )
> ```
> 
> That is, if the product is out of stock, set the product to out of stock; otherwise, use **the existing stock status value**. I believe that this is the source of products not being updated to being back in stock. In the case where the product is in stock according to the `cataloginventory_stock_item` table, if it was out of stock before, it will continue to be out of stock since the existing out of stock value will be used. Please let me know if I am mistaken, but for the time being I am considering this a bug and will be patching it out.

@NicholasRoge Did you get a working patch for this and could you please share? I identified the same problem but was not sure how I should change it. We have the exact same issue.

**Comment by DzemalBecirevic** [comment]
> > We are experiencing this issue as well and the recommended patches have no effect on (Magento Commerce 2.4.4-p2). As best as I can tell, this is being caused by a bad query in the cataloginventory_stock indexer. When determining a product's status for any product which is not a bundle or grouped product, the Magento_InventoryCatalog module overrides the non-MSI Magento_CatalogInventory module's default handler for obtaining the stock status expression, updating it from `Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\StatusExpression\DefaultExpression` to `Magento\InventoryCatalog\Model\ResourceModel\StockStatusExpressionForDefaultStock`.
> > The only thing that is changed about the MSI status expression is that, if the product is manage stock, instead of directly using the `cisi.is_in_stock` value as ultimate factor to decide whether the product is in stock, it adds a condition:
> > ```sql
> > IF(
> >     cisi.is_in_stock = 0,
> >     0,
> >     IF(
> >         css.stock_status IS NOT NULL,
> >         css.stock_status,
> >         cisi.is_in_stock
> >     )
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That is, if the product is out of stock, set the product to out of stock; otherwise, use **the existing stock status value**. I believe that this is the source of products not being updated to being back in stock. In the case where the product is in stock according to the `cataloginventory_stock_item` table, if it was out of stock before, it will continue to be out of stock since the existing out of stock value will be used. Please let me know if I am mistaken, but for the time being I am considering this a bug and will be patching it out.
> 
> @NicholasRoge Did you get a working patch for this and could you please share? I identified the same problem but was not sure how I should change it. We have the exact same issue.

Answering my own question here:

We had two problems:

1. Our configurable products where set to use_config_manage_stock which was set to "Yes" meaning we should managed stock on configurable products as well, which is incorrect and we changed this on all our configurable products.
2. The stock status indexer `Magento\InventoryCatalog\Model\ResourceModel\StockStatusExpressionForDefaultStock` was patched with the following (Can not get the diff to format correctly).


-            $connection->getCheckSql('css.stock_status IS NOT NULL', 'css.stock_status', $stockItemInStockField)
+            $connection->getCheckSql('css.stock_status IS NOT NULL',
+                    $connection->getCheckSql('css.stock_status != cisi.is_in_stock',
+                                                                                  'cisi.is_in_stock',
+                                                                                  'css.stock_status'),
+                $stockItemInStockField)


These two changes solved our issues at least.

**Comment by xls2802** [comment]
Try this solution for MSI  [https://github.com/magento/magento2/issues/36154#issuecomment-2489979458](url)
