### ISSUE TITLE
Magnifier.js syntax error

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#36200]
### Preconditions and environment

- Mage 2.4.4

### Steps to reproduce

1. Open the console on the Product Detail page and define `const data={}` in the console.
2. Try to navigate the image gallery and get the below error:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/51681618/207542848-193d6fbb-94c2-4a9f-ba81-51d015f26b5b.png">
3. But if replace `;` to `,` from `lib/web/magnifier/magnifier.js`, then the issue is resolved.

./lib/web/magnifier/magnifier.js 26-30 is causing an error depending on contexts

```
           largeWrapper = options.largeWrapper || '.magnifier-preview',
            $magnifierPreview = $(largeWrapper);

        curThumb = null,
        magnifierOptions = {
```

It errors out later in the script, saying I cannot redefine `const data`. This is because the list of variables starting at `curThumb` doesn't have specified what kind of var it is, thus living in global space.

So a fix would either be

```
// Comma instead of ;
$magnifierPreview = $(largeWrapper),
curThumb = null,
```

Or properly initiate the variables

```
$magnifierPreview = $(largeWrapper);

var curThumb = null,
```

### Expected result

No JS errors

### Actual result

JS breaks, product detail page image gallery is not functional anymore.

### Additional information

I wouldn't know which solution is preferred which is why I just drop this as an issue with possible solutions provided. Additionally, it would be great to have proper JS linting set up, that doesn't allow global variable declaration like this.

As far as I can see, this has been an issue/unchanged for a few Magento version, it just got triggered by another module/js taking 'control' of the 'data' var-label.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vandijkstef** [comment]
Hi @engcom-Delta,

Sorry I missed your question for a bit. Basically I have another js-script running that is trying to set a variable `const data`. The variable initialisation of the magnifier script is interupted by the `;` on the line containing `$magnifierPreview = $(largeWrapper);` making every variable after it global, as it's not prefixed by `var|let|const` anymore.

[Here's an interesting thread](https://stackoverflow.com/questions/6888570/declaring-variables-without-var-keyword) about the subject

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @vandijkstef,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue on the above Magento instance and found that `curThumb` variable is in the `Global` scope, please refer the screenshot:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/51681618/207252975-bdb9d0d2-8699-4e41-a7df-4b07c84a13c1.png">

But still, the Image gallery is working fine for us. Can you please let us know any additional steps which we need to follow in order to reproduce the issue?

Thanks

**Comment by vandijkstef** [comment]
> Basically I have another js-script running that is trying to set a variable `const data`.

`curThumb` is just the start of this list of global variables. Having global variables is just asking for unintended side-effects and incompatibility issues. Please stop using global variables. Any module (accidently) using one of these variable names will have issues.

It's highly likely to me that `$magnifierPreview = $(largeWrapper);` used to end with nothing, and a linter added `;` to that line

**Comment by engcom-Hotel** [comment]
Hello @vandijkstef,

Thanks for the reply!

According to your comment, we have tried to reproduce the issue by following the below steps:

1. Open the console on the Product Detail page and define `const data={}` in the console.
2. Try to navigate the image gallery and get the below error:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/51681618/207542848-193d6fbb-94c2-4a9f-ba81-51d015f26b5b.png">
3. But if replace `;` to `,` from `lib/web/magnifier/magnifier.js`, then the issue is resolved.

But I think this is not the proper way to reproduce the issue. So can you please help us in the same?

Thanks

**Comment by vandijkstef** [comment]
This is the proper way to reproduce this issue. This is the proper solution. It's all about JS coding standards not being applied here. Any of the following variables will otherwise not be usable by any other module

```
curThumb
magnifierOptions
pos
gId
status
curIdx
curLens
curLarge
lensbg
gZoom
gZoomMin
gZoomMax
gMode
gEventTypemagnifierOptions.eventType,
data
inBounds
isOverThumb
rate
paddingX
paddingY
enabled
showWrapper
```

If I look the the [old version of the file](https://github.com/magento/magento2/blame/eacba1c4a402209a1a61ade5ab51449b134b1388/lib/web/magnifier/magnifier.js) (it's a few years back) you can see what was originally in there, and that a `;` was [inserted around here](https://github.com/magento/magento2/blame/de27216b0dc9ae392b29f462ada6094677abbf40/lib/web/magnifier/magnifier.js) likely without the intend to do so, but a linter accidently inserting the `;`

**Comment by engcom-Hotel** [comment]
Hello @vandijkstef,

Thanks for the update!

We are confirming this issue and updating the main description with the steps mentioned here https://github.com/magento/magento2/issues/36200#issuecomment-1350612745

Thanks

**Comment by vandijkstef** [comment]
This is still an issue in Mage 2.4.7 - We're talking about replacing a `;` with a `,` after faulty auto-formatted js code
