### ISSUE TITLE
Magento 2.4.5 Layer Navigation not working with Display Out of Stock Products = YES

### ISSUE THREAD

**Issue by rutvik-monpara** [magento/magento2#36312]
### Preconditions and environment

- Magento version 2.4.5
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Go to **Stores -> Configuration -> Catalog -> Inventory -> Display Out of Stock Products = YES**
Now Try to filter products on the category page.

### Expected result

Products with filter.

### Actual result

All products display.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** & **2.4.5** M2.

**Description:** Layered navigation is not working when Display out of stocks products set to yes.

**Pre-requisite:**
Fresh magento `2.4-develop` and `2.4.5` should be installed.
Products and categories should be created.

**Steps to reproduce:**
Go to Stores -> Configuration -> Catalog -> Inventory -> Display Out of Stock Products = YES
Now Try to filter products on the category page

**Expected result:** Products should be filetered out.

**Actual result:** All products displayed.
**Screenshots:**
<img width="1034" alt="Screenshot 2022-10-17 at 5 35 14 PM" src="https://user-images.githubusercontent.com/60198022/196173489-ce8cd370-4b22-4c5c-ae0f-45a889a3566d.png">

**Comment by alexwatever** [comment]
We're also seeing this after upgrading to 2.4.5-p1

**Comment by pimjansen** [comment]
Also experiencing this. Is there already a solid patch?

**Comment by melvinversluijs** [comment]
For anyone running into this issue, it seems to have been fixed on the `2.4-develop` branch. https://github.com/magento/magento2/commit/a9170022cce29993e586ffaa6f4c1cc357ee3b11

**Comment by engcom-Hotel** [comment]
Hello,

As the issue has already been fixed and merged in the below PR:

https://github.com/magento/magento2/pull/35986

You can use the below patch in order to fix this issue for your instance:

https://github.com/magento/magento2/commit/a9170022cce29993e586ffaa6f4c1cc357ee3b11

We are closing this issue.

Thanks

**Comment by rutvik-monpara** [comment]
Layer navigation working fine using [#35986](https://github.com/magento/magento2/pull/35986)
But, the product count is displayed wrong.
![image](https://user-images.githubusercontent.com/115232682/196667808-5436d4b3-92e3-408d-b606-deb62e13b4f8.png)

**Comment by rutvik-monpara** [comment]
@engcom-Hotel please reopen an issue.

**Comment by pimjansen** [comment]
Indeed. Over here also the filtering is still broken. Getting less results than expected

**Comment by rutvik-dolphin** [comment]
Issue fixed here [https://github.com/magento/magento2/commit/a9170022cce29993e586ffaa6f4c1cc357ee3b11](https://github.com/magento/magento2/commit/a9170022cce29993e586ffaa6f4c1cc357ee3b11)
