### ISSUE TITLE
Currency Symbol Disappears on Product View Page on 2.4.5-p1

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#36322]
### Preconditions and environment

- Magento 2.4.5-p1

### Steps to reproduce

- Visit any product page
- Currency symbol appears eg - $1.00
- Wait untill page fully load.
- Currency symbol disappear eg - 1.00

### Expected result

Currency Symbol to remain displayed.

### Actual result

Currency symbol disappears

### Additional information

This appears to be a reverted issue: https://github.com/magento/magento2/issues/33856

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dphilipps** [comment]
@magento give me 2.4-develop instance

**Comment by dphilipps** [comment]
Hi @engcom-Bravo 
I'm unable to reproduce this on 2.4-develop instance.  I am seeing this behaviour on a store upgraded from 2.4.3 where the issue existed but was patched.  Shall I close this issue? I've seen another user report same issue on the previous issue: https://github.com/magento/magento2/issues/33856

**Comment by engcom-Bravo** [comment]
Hi @dphilipps,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Current symbol remain displayed.

This issue is already got fixed in 2.4 develop branch.Kindly check [here](https://github.com/magento/magento2/issues/33856#issuecomment-946761019).


Hence we are closing this issue as cannot reproduce.

Thanks.

**Comment by tarunpg** [comment]
Hi @dphilipps - I am also facing this issue on the store upgraded from Version 2.4.3. Could you please let me know how you resolved this particular issue on that upgraded store. I have also upgraded from Ver 2.4.3 to Ver 2.4.5 and had earlier patched the Version 2.4.3 for resolution. I see the correct Currency.php code in vendor folder - but unable to find why the issue is still there after upgrade.

Thanks
> Hi @engcom-Bravo I'm unable to reproduce this on 2.4-develop instance. I am seeing this behaviour on a store upgraded from 2.4.3 where the issue existed but was patched. Shall I close this issue? I've seen another user report same issue on the previous issue: #33856

**Comment by kenseiatwork** [comment]
I had this issue as well.
I looks like it was fixed in 2.4.4 but the problem was re-introduced in 2.4.5

Had to re-add this line at around 422 from the commit: https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R442

` $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);`

Back into Directory/Model/Currency.php


`
diff --git a/vendor/magento/module-directory/Model/Currency.php b/vendor/magento/module-directory/Model/Currency.php
index 71b9d36..fb41b8a 100644
--- a/vendor/magento/module-directory/Model/Currency.php
+++ b/vendor/magento/module-directory/Model/Currency.php
@@ -439,7 +439,10 @@ class Currency extends \Magento\Framework\Model\AbstractModel
 
         if ((array_key_exists(LocaleCurrency::CURRENCY_OPTION_DISPLAY, $options)
             && $options[LocaleCurrency::CURRENCY_OPTION_DISPLAY] === \Magento\Framework\Currency::NO_SYMBOL)) {
-            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
+//            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
+
+            // patch missing currency symbol
+            $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);
         }
 
         return preg_replace('/^\s+|\s+$/u', '', $formattedCurrency);
`

**Comment by tarunpg** [comment]
> @dphilipps @tarunpg I had this issue as well. It looks like it was fixed in 2.4.4 but the problem was re-introduced in 2.4.5
> 
> Had to re-add this line at around 422 from the commit: [ae304d4#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R442](https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R442)
> 
> ` $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);`
> 
> Back into Directory/Model/Currency.php
> 
> ```
> diff --git a/vendor/magento/module-directory/Model/Currency.php b/vendor/magento/module-directory/Model/Currency.php
> index 71b9d36..fb41b8a 100644
> --- a/vendor/magento/module-directory/Model/Currency.php
> +++ b/vendor/magento/module-directory/Model/Currency.php
> @@ -439,7 +439,10 @@ class Currency extends \Magento\Framework\Model\AbstractModel
>  
>          if ((array_key_exists(LocaleCurrency::CURRENCY_OPTION_DISPLAY, $options)
>              && $options[LocaleCurrency::CURRENCY_OPTION_DISPLAY] === \Magento\Framework\Currency::NO_SYMBOL)) {
> -            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
> +//            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
> +
> +            // patch missing currency symbol
> +            $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);
>          }
>  
>          return preg_replace('/^\s+|\s+$/u', '', $formattedCurrency);
> ```

Thanks @kenseiatwork - this worked for me

**Comment by stkrelax** [comment]
https://github.com/magento/magento2/issues/33856#issuecomment-1327625524

**Comment by dphilipps** [comment]
> @dphilipps @tarunpg I had this issue as well. It looks like it was fixed in 2.4.4 but the problem was re-introduced in 2.4.5
> 
> Had to re-add this line at around 422 from the commit: [ae304d4#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R442](https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R442)
> 
> ` $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);`
> 
> Back into Directory/Model/Currency.php
> 
> ```
> diff --git a/vendor/magento/module-directory/Model/Currency.php b/vendor/magento/module-directory/Model/Currency.php
> index 71b9d36..fb41b8a 100644
> --- a/vendor/magento/module-directory/Model/Currency.php
> +++ b/vendor/magento/module-directory/Model/Currency.php
> @@ -439,7 +439,10 @@ class Currency extends \Magento\Framework\Model\AbstractModel
>  
>          if ((array_key_exists(LocaleCurrency::CURRENCY_OPTION_DISPLAY, $options)
>              && $options[LocaleCurrency::CURRENCY_OPTION_DISPLAY] === \Magento\Framework\Currency::NO_SYMBOL)) {
> -            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
> +//            $formattedCurrency = str_replace(' ', '', $formattedCurrency);
> +
> +            // patch missing currency symbol
> +            $formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);
>          }
>  
>          return preg_replace('/^\s+|\s+$/u', '', $formattedCurrency);
> ```

Thanks - I replaced the entire from 2.4.3-p3 for now and is working

**Comment by dphilipps** [comment]
Note this change also instantly fixed the broken credit memo https://github.com/magento/magento2/issues/34375
