### ISSUE TITLE
OrderGridCollectionFilter Plugin Breaks Mapping for `created_at` Column

### ISSUE THREAD

**Issue by nwcasebolt** [magento/magento2#36439]
### Preconditions and environment

- Magento 2.4.5-p1

### Steps to reproduce

1. Add an `afterSearch` plugin on `Magento\Framework\View\Element\UiComponent\DataProvider\Reporting` that joins the `sales_order` table to the `sales_order_grid` table.

Example:

```
$salesOrderTable = $collection->getConnection()->getTableName('sales_order');
            $collection->getSelect()->joinLeft(
                ['sales' => $salesOrderTable],
                'sales.increment_id = main_table.increment_id',
                'your_field'
            );
```

2. Filter the Order grid on purchase date.

### Expected result

The orders are filtered by purchase date.

### Actual result

- The order grid does not filter on purchase date
- An alert box says, "Attention: Something went wrong"
- A message generates that says, "Something went wrong with processing the default view and we have restored the filter to its original state"
- Error logs say, "Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous."

### Additional information

A bug was introduced in 2.4.5 when the OrderGridCollectionFilter plugin [was added in December 2021](https://github.com/magento/magento2/commits/2.4-develop/app/code/Magento/Sales/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php) to convert the `created_at` field to UTC. The plugin's `aroundAddFieldToFilter` filter returns the field without calling `$proceed`. This means that `created_at` never gets processed through `\Magento\Framework\Data\Collection\AbstractDb::addFieldToFilter`, which in turns prevents `created_at` from getting mapped to `main_table`.

It's also worth pointing out that the new plugin duplicates code which operates on `created_at` in `\Magento\Sales\Model\ResourceModel\Order\Grid\Collection::addFieldToFilter`, leaving everything in that collection's if statement unreachable.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MyroslavDobra** [comment]
I also found it an hour ago. It's impossible that people that make such mistakes are working for a corporation like Adobe.

**Comment by mohitnavik** [comment]
Hi @nwcasebolt,

I was also getting the error related to 'created_at' column when trying to apply "purchase date" filter on order grid. I have created below patch to fix this issue. I was not unable to upload with '.patch' extension. So, the '.txt' extension can be changed to '.patch'. Then the patch can be directly applied to Magento setup.
 
[Patch-Fixed-CreatedAt-Filter-Issue-At-OrderGrid.txt](https://github.com/magento/magento2/files/10244894/Patch-Fixed-CreatedAt-Filter-Issue-At-OrderGrid.txt)

Thanks,

**Comment by atty31** [comment]
For me replacing: 
` $field='sales_order.'.$field;` with `$field ='main_table.'.$field;` 
from the patch, mentioned by  @mohitnavik  worked for me.

**Comment by shmVan** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @nwcasebolt,

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**:

1. Added an afterSearch plugin  on Magento\Framework\View\Element\UiComponent\DataProvider\Reporting that joins the sales_order table to the sales_order_grid table.

![Screenshot 1945-04-29 at 12 17 40 PM](https://github.com/magento/magento2/assets/51680745/efbf9bbd-30b9-4957-9785-f8ce207e904a)



2. Filtered the Order grid on purchase date.


![Screenshot 1945-04-29 at 12 20 41 PM](https://github.com/magento/magento2/assets/51680745/1ec2e050-bc5d-4bd5-b722-58d2a812ce8c)



![Screenshot 1945-04-29 at 12 20 53 PM](https://github.com/magento/magento2/assets/51680745/e419fe9d-a3ed-41c1-901c-1fa32b130d01)



So here we are not getting error messages like something went wrong.We are able apply the filter properly.

Hence issue is not able to reproduce.It seems like issue is already fixed.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @nwcasebolt,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by sanderjongsma** [comment]
I also ran into this problem. Because my custom grid was joining some other tables with created_at. I resolved it by creating a before plugin for: `\Magento\Sales\Plugin\Model\ResourceModel\Order\OrderGridCollectionFilter::aroundAddFieldToFilter`:

```
public function beforeAroundAddFieldToFilter(
        OrderGridCollectionFilter $subject,
        SearchResult $searchResult,
        Closure $proceed,
        $field,
        $condition = null
    ): array {
        if (! $searchResult instanceof Collection) {
            return [$searchResult, $proceed, $field, $condition];
        }

        if ($field === 'created_at') {
            $field = 'main_table.created_at';
        }

        return [$searchResult, $proceed, $field, $condition];
    }
```

In this way the original plugin won't be affected. And in this before plugin you can check if the searchResult is an instance of the desired collection. And to eventually not hit the original around plugin, just add the table to the created_at field like: `main_table.created_at` or if you want the joined table created_at

**Comment by mtytula** [comment]
```diff --git a/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php b/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php
index 995bb83..3765a1d 100644
--- a/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php
+++ b/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php
@@ -52,7 +52,7 @@ class OrderGridCollectionFilter
                 }
             }

-            $fieldName = $subject->getConnection()->quoteIdentifier($field);
+            $fieldName = $subject->getConnection()->quoteIdentifier($field === 'created_at' ? 'main_table.created_at' : $field);
             $condition = $subject->getConnection()->prepareSqlCondition($fieldName, $condition);
             $subject->getSelect()->where($condition, null, Select::TYPE_CONDITION);

```

Here is a quick patch for getting it to work with any custom made that joins another tables that contains `created_at` column.

**Comment by LucScu** [comment]
> Hi @nwcasebolt,
> 
> Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.
> 
> **Steps to reproduce**:
> 
> 1. Added an afterSearch plugin  on Magento\Framework\View\Element\UiComponent\DataProvider\Reporting that joins the sales_order table to the sales_order_grid table.
> 
> ![Screenshot 1945-04-29 at 12 17 40 PM](https://private-user-images.githubusercontent.com/51680745/254802103-efbf9bbd-30b9-4957-9785-f8ce207e904a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTg3OTYsIm5iZiI6MTcxMDQ5ODQ5NiwicGF0aCI6Ii81MTY4MDc0NS8yNTQ4MDIxMDMtZWZiZjliYmQtMzBiOS00OTU3LTk3ODUtZjhjZTIwN2U5MDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEwMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTZhMDg4YTU2MjdlMzU0NTRjOTdlNDU1MTE3NzA1ZDg4ZWIwOGVlYjU0M2JkMWJjZjdhOTEwZTY1OTk3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Og5_2NwtnclGo8VGu0woWk8NXziaxAqKVcIz6AuX8iU)
> 
> 2. Filtered the Order grid on purchase date.
> 
> ![Screenshot 1945-04-29 at 12 20 41 PM](https://private-user-images.githubusercontent.com/51680745/254802150-1ec2e050-bc5d-4bd5-b722-58d2a812ce8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTg3OTYsIm5iZiI6MTcxMDQ5ODQ5NiwicGF0aCI6Ii81MTY4MDc0NS8yNTQ4MDIxNTAtMWVjMmUwNTAtYmM1ZC00YmQ1LWI3MjItNThkMmE4MTJjZThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEwMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZWFiNTZjNDkzOTdiNWE5MTlhZTI5M2JmOGVlYjJmZTJiNTg1ZTAyNDQyM2YxMDMxNDZmNTMzYzNmZmUxODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lWLPWEZ6u25L9Oo3zP861-OWoIavUVGDPCc_PtSldY4)
> 
> ![Screenshot 1945-04-29 at 12 20 53 PM](https://private-user-images.githubusercontent.com/51680745/254802159-e419fe9d-a3ed-41c1-901c-1fa32b130d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTg3OTYsIm5iZiI6MTcxMDQ5ODQ5NiwicGF0aCI6Ii81MTY4MDc0NS8yNTQ4MDIxNTktZTQxOWZlOWQtYTNlZC00MWMxLTkwMWMtMWZhMzJiMTMwZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEwMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzQ0N2Y1MTI5NGU1YjAwZWY0NTkyMDViMTAzM2MxZGE2NmE2NmRkODBjMWU4NmFmN2I4YmIwZGE4MGMxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M7kUXP_ds1Aw4XOlcphk55hQd81t-ljbAMA5UFsUbms)
> 
> So here we are not getting error messages like something went wrong.We are able apply the filter properly.
> 
> Hence issue is not able to reproduce.It seems like issue is already fixed.
> 
> Thanks.

The issue is still present in 2.4.6-p3, your test are wrong.
Please reopen.

**Comment by atIOCrON** [comment]
For anyone else looking for a fix, please see here:

https://github.com/magento/magento2/issues/38916
