### ISSUE TITLE
Catalog Search Auto Suggest Click Not Working

### ISSUE THREAD

**Issue by atishgoswami** [magento/magento2#3657]
Hello,

Getting an issue when tried to click on the auto suggested item in the catalog search dropdown.

![search results for jackets](https://cloud.githubusercontent.com/assets/2647377/13528579/e71c562c-e23c-11e5-94e2-6ba86fcd7d69.png)

It seems that when clicked it reload the same page instead of taking the user to the catalog search page.

Thanks

**Comment by mslabko** [comment]
Hello @atishgoswami,
I've checked fix, that you provided - unfortunately it will not work for all cases. When target element on click event is “li” then it will be set empty array to responseList. I hope, that event.currentTarget can help to solve this issue for all cases.

It would be great if you create PR for this issue. To learn about how to make a contribution, click [here](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html).

**Comment by mslabko** [comment]
Internal ticket: MAGETWO-50184

**Comment by atishgoswami** [comment]
Hi @mslabko 

Can you explain me the test cases, what scenarios to consider ?

Thanks

**Comment by duhon** [comment]
Hi @atishgoswami 

![selection_002](https://cloud.githubusercontent.com/assets/124924/13699232/c29ceea2-e781-11e5-8d97-396ca292102f.png)

if click red area the script works incorect

**Comment by atishgoswami** [comment]
@duhon oooh ok thanks !!

**Comment by davidalger** [comment]
@atishgoswami Would you confirm the fix pushed into the mainline for this resolves the issue you were encountering?

**Comment by atishgoswami** [comment]
@davidalger Ya sure will check this and get right back !

**Comment by atishgoswami** [comment]
Its Working @davidalger 

Thanks @duhon

**Comment by choukalos** [comment]
Closing since the fix resolved this issue.

**Comment by mapoftampa** [comment]
Hi, I know this is an old thread, but I am having the same problem in Magento 2.2.6. I tried to apply the code fix you suggested, but the code block in form-mini-js is a little different in 2.2.6. Instead of e.target, it is listed as e.currentTarget. I've tried it both ways, and I still can't get it to work. I'm also not sure if I have completely cleared that .js from the caches, but I believe I have. 

So, just to be clear, I have tried:
`                        this.responseList.indexList
                            .on('click', function (e) {
                        //     this.responseList.selected = $(e.currentTarget);
				var elem = $(e.target).parent('li');
				this.responseList.selected = $(elem);
				this.searchForm.trigger('submit');
                            }`

...and i have tried:

`                        this.responseList.indexList
                            .on('click', function (e) {
                        //      this.responseList.selected = $(e.currentTarget);
				var elem = $(e.currentTarget).parent('li');
				this.responseList.selected = $(elem);
				this.searchForm.trigger('submit');
                            }`

Any help would be appreciated. 
Thanks!
