### ISSUE TITLE
Unable to checkout with PayPal through Braintree 

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#37242]
### Preconditions and environment

Upon upgrading our production site from M2.4.5-p2 to M2.4.6 we discovered customers were unable to checkout via PayPal through Braintree.

We were unable to find any workaround.

```
Building Magento 2.4.6
+ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
+ /usr/local/apache/bin/httpd -v
Server version: Apache/2.4.46 (Unix)
Server built:   Jun 16 2021 21:29:21
+ mysql -V
mysql  Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)
+ php -v
PHP 8.1.17 (cli) (built: Mar 17 2023 09:39:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
+ php /usr/local/bin/composer -V
Composer version 2.3.5 2022-04-13 16:43:00
```

### Steps to reproduce

Fresh Install of M2.4.6 in environment as above
Open browser "incognito" window using Windows 11 and Google Chrome
Login to Magento admin backend

Nav to Admin>Stores>Configure>General>Web>Default Cookie Settings
If necessary, set the Cookie Domain to the appropriate domain value (so Demo Customer will be able to login on front end)
Save Config
Nav to Admin>Stores>Configure>Sales>Payment Methods
Select Merchant Country as United States and Save Config
Configure Braintree Payments (by GENE Commerce v4.5.0) 
Enter known valid sandbox credentials for Merchant ID, Public Key, Private Key and Validate Credentials
In the Enable PayPal through Braintree section...
Set Enable PayPal through Braintree = Yes 
Set Display on Shopping Cart = Yes
Save Config 
Flush Magento Cache

Open separate tab on incognito browser and navigate to frontend
Successfully Sign In using Demo Customer Access credentials
Click Add-to-Cart for Affirm Water Bottle (or anyother product)
Observe "spinner" remains over count box in upper right hand corner of page and does not clear
NO message "You added the Affirm Water Bottle to your shopping cart." appears
Clicking cart icon displays "You have no items in your shopping cart"
Add-to-Cart two or three more times for the Affirm Water Bottle
Click the Luma Store icon to return to home page
[ Although the website is not hung, it's useless because nothing can successfully added to cart,
this behavior appears to be related to the PayPal button appearing in the mini-cart ]

Return to backend
Nav to Admin>Stores>Configure>Sales>Payment Methods
Configure Braintree Payments (by GENE Commerce v4.5.0) 
In the Enable PayPal through Braintree section
Set Display on Shopping Cart = No
Save Config 
Flush Magento Cache

Return to frontend
You should still be on the Luma store home page
Use your web browser "refresh" function to reload the page
The green circle with the check mark and the message "You added the Affirm Water Bottle to your shopping cart." appears several times.
The count box in the upper right corner will now equal the number of times add-to-cart was previously clicked.
Click the cart icon and Proceed to Checkout
Shipping Method select Fixed Flat Rate 
Payment Method select PayPal
Click the large yellow PayPal button
Rarely, the PayPal "modal box" zooms out surrounded by dark background, and remains open as normal, 
If the PayPal modal box remains open, close it and add another item to cart then Proceed to Checkout again
In most tests the modal box zooms out for a moment and closes, then
Message "PayPal Checkout could not be initialized. Please contact store owner." appears.
and you are unable to proceed to place an order.

### Expected result

During checkout upon selecting PayPal as the Payment Method then clicking the large yellow PayPal button the PayPal modal box appears and the customer is able to successfully make payment and checkout.

### Actual result

During checkout upon selecting PayPal as the Payment Method then clicking the large yellow PayPal button the PayPal modal box appears for a moment before automatically closing and the customer is unable to make payment or complete the order.

### Additional information

Tested with both our sandbox and production Braintree creditials, in both production and development environments, PayPal as payment method is essentially not functional although for some reason under certain unknown circumstances it will work as expected for a specific customer checkout.  It did work as expected on M2.4.5-p2

I was unable to find any workaround and the PayPal payment method is currently disabled on our M2.4.6 production website.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by n2diving-dgx** [comment]
Hopefully some other user with different Braintree credentials would test in their environment to confirm the issue with checkout via PayPal through Braintree as described above is reproduceable on M2.4.6 using credentials other than mine.

**Comment by Rich07082** [comment]
same issue, thought it was just related to the PayPal buttons (was getting error when trying to add to cart) and on the cart page when PayPal through Braintree was enabled and display on shopping cart was enabled.

Was able to duplicate error when using paypal as a checkout method.

**Comment by engcom-Dash** [comment]
Hi @n2diving-dgx ,

Verified the issue in 2.4.6- Magento instance and the issue is reproducible,Hence we are confirming the issue.Kindly Refer the Screenshots.

Preconditions:
Magento version 2.4.6
PHP 8.1
Braintree Payment Module Configured.

Steps to reproduce:
 As per given main description [Steps](https://github.com/magento/magento2/issues/37242#issue-1631254518)

 Braintree configuration 
<img width="1512" alt="pay3" src="https://user-images.githubusercontent.com/60198592/228394409-7bd3a5d3-5d07-4ad1-b4a9-6cf2cb26ff93.png">
Display on Shopping Cart is YES
<img width="1512" alt="pay4" src="https://user-images.githubusercontent.com/60198592/228394739-e0c8632d-8415-4fbf-8219-18e83e2c6984.png">
Display on Shopping Cart is NO
<img width="1512" alt="pay1" src="https://user-images.githubusercontent.com/60198592/228394872-303cdc0e-f0ed-47b1-828c-6f4c865bdbd1.png">
<img width="1512" alt="pay2" src="https://user-images.githubusercontent.com/60198592/228394883-c4bd9410-2619-42f8-a765-72bd6d004227.png">

Here attached the video reference placing the order with paypal:

https://user-images.githubusercontent.com/60198592/228395014-b838e1fa-3db5-4c64-a979-84eaed6354cb.mp4

We are getting actual result as per the description ,Hence we are confirming the issue in 2.4.6-develop instance.

Regards,

**Comment by Cupropituvanso** [comment]
We have the same issue and opened another issue.
I had closed the other issue, but we have also postet the error log of the server, maybe this could be interesting: https://github.com/magento/magento2/issues/37325

**Comment by CollegeSewing** [comment]
This issue seems to stem for the "Gift Wrapping" Section within
/Magento/vendor/paypal/module-braintree-core/Gateway/Request/Level23ProcessingDataBuilder.php

Commenting out lines 186 through 232 allows PayPal via Braintree to process without errors

**Comment by n2diving-dgx** [comment]
This ticket is p0 - i.e. mission critical functionality for which there is no work around other than revert to M2.4.5  The only thing to do to remain on M2.4.6 is turn off accepting payments via PayPal, which in our case means PayPal is losing hundreds of USD and other sites are likely in the same situation in actuality is probably means thousands of USD in fees per day!  Yet two weeks have passed and it is not even assigned to a developer.

**Comment by Rich07082** [comment]
still seem to have an issue in the cart(after applying above fix).

https://test.nationalfleetparts.com/checkout/cart/

Also if you have the mini cart enabled seems to be an issue adding items to the cart.

rich

**Comment by n2diving-dgx** [comment]
> @n2diving-dgx
> 
> Have you attempted my fix [above](https://github.com/magento/magento2/issues/37242#issuecomment-1495782087)
> 
> With Magento 2.4.6 lines 186 through 232 within vendor/paypal/module-braintree-core/Gateway/Request/Level23ProcessingDataBuilder.php there is added function for "Gift Wrapping" which is not referenced in Magento 2.4.5
> 
> Commenting out the above lines in my testing "fixes" the PayPal via Braintree within Magento 2.4.6

No change, but I wasn't using the gift card functions at all.

**Comment by CollegeSewing** [comment]
@Rich07082 
Under Advanced Braintree Setttings "Send Cart Lines" Should be set to NO (
![Send_Cart_Lines](https://user-images.githubusercontent.com/77878382/230013556-588160e0-3603-4cb2-b72d-cee3e221f294.jpg)
)
Items will then be added to the Mini Cart

@n2diving-dgx 
This has nothing to do with Gift Card.... But Gift Wrapping 
![Braintree_GiftWrap](https://user-images.githubusercontent.com/77878382/230014494-7044ef7a-b754-4a94-9301-a4228d7d425c.jpg)

**Comment by Rich07082** [comment]
Under Advanced Braintree Setttings "Send Cart Lines" Should be set to NO

this worked along with commenting out the lines.

rich

**Comment by VJW-WSS** [comment]
Had same issue since upgrade to 2.4.6
Didn't actually notice until customer told me today 10 days later!

Tried commenting out lines 186-232 in Level23ProcessingDataBuilder.php but this left an error with undefined variable $baseCustomerBalAmountUsed (to do with store credits but never use them).

Have now left lines 192-195 in and payments are processing okay.

Anyone who has had this problem might want to check the inventory_reservation table in their database. It seems that stock was being reserved even though the payments were failing, resulting in stock being unavailable to order.

**Comment by CollegeSewing** [comment]
@VJW-WSS 
I've updated my original comment [above to reflect ](https://github.com/magento/magento2/issues/37242#issuecomment-1495782087)

**Comment by amjadm61** [comment]
@magento give me 2.4-develop instance

**Comment by Rich07082** [comment]
another error when trying to checkout.  Haven't seen this one mentioned yet and the above fix bypasses one error but this is comes after.

[2023-04-14T17:41:07.362337+00:00] main.CRITICAL: Exception: Warning: Undefined variable $baseCustomerBalAmountUsed in vendor/paypal/module-braintree-core/Gateway/Request/Level23ProcessingDataBuilder.php on line 240 in /public_html/vendor/magento/framework/App/ErrorHandler.php:62

Rich

**Comment by Rich07082** [comment]
anything with this?  Been over a month, seems like a pretty big issue.

rich

**Comment by quyendam2612** [comment]
Looks like we haven't had any update yet..

**Comment by nicholasfishjgm** [comment]
Hi there, is there any update on this issue? Timescale to resolution?

Is there an official patch file available in the meantime?

**Comment by nicholasfishjgm** [comment]
For anyone experiencing the same issue, here is a temporary patch file that comments out the gift wrap settings, but avoids commenting out any $variables that are required further down the file.

[ISSUE-37242-braintree-paypal-gw.patch](https://github.com/magento/magento2/files/11440337/ISSUE-37242-braintree-paypal-gw.patch)

For reference too, we did not have to update the Braintree 'Send Cart Line Items', this may vary for different stores.

**Please note: The above is untested in a production environment and so please use with caution!!**

**Comment by nordcomputer** [comment]
Hey, thanks a lot @nicholasfishjgm - that helps for now. But an official update by the maintainers would still be very appreciated.

**Comment by elioermini** [comment]
We also have this issue

**Comment by domabbott92** [comment]
Just to follow on from @nicholasfishjgm last comment...

We have had to revert this from Production due to other PayPal issues. We are not sure yet if this it directly affected by the above issue/patch, or if there are further PayPal issues with 2.4.6.

On 'high' value PayPal orders (seems to be £1900+) the customer gets the error "PayPal Checkout could not be initialized. Please contact the store owner" with a corresponding network error:
`{
    "paymentResource": {
        "errorName": "VALIDATION_ERROR",
        "errorMessage": "Invalid request - see details --- transactions[0]:Item amount must add up to specified amount subtotal (or total if amount details not specified)",
        "errorDetails": [
            {
                "field": "transactions[0]",
                "issue": "Item amount must add up to specified amount subtotal (or total if amount details not specified)"
            }
        ],
        "debugId": "8f0b04e899294",
        "paypalHttpStatus": 400
    }
}`

**Comment by ThisIsRuddy** [comment]
Same issue here,

Shipping Items Lines not including a unitTaxAmont seems to be breaking the total sum for us

**Comment by j-lloyd-slc** [comment]
paypal/module-braintree-core v4.5.0 seems to assume the existence of gift wrapping, gift card and customer balance features that are not native to Magento Open Source (perhaps they are Adobe Commerce exclusives?).

When patching, rather than commenting out lines where variables are set to values derived from non-existent extension attributes etc., it is possible to simply assign a zero value instead. This ensures that the variables are not missing when expected later in the code. Since these features do not exist, zero seems like an appropriate value for their contribution to the totals.

It is worth noting that in addition to assuming native features that do not exist, this module does not accommodate 3rd party features that provide similar functionality (and otherwise integrate well).

Patching the `canSendLineItems` function in vendor/paypal/module-braintree-core/Gateway/Config/Config.php to return false will prevent a mistaken config change from crippling PayPal checkout. (It is unfortunate that this value is only checked after the line item data is compiled.)

**Comment by andrewdaluz** [comment]
Another issue I found with Braintree was when trying to do SPLIT invoices. When I create the first invoice, everything goes fine.
When I try to create a second invoice with the other items left I get an error "Token Invalid".

The issue is related to the code in `vendor/paypal/module-braintree-core/Gateway/Request/VaultCaptureDataBuilder.php` line 43

```
        return [
            'amount' => $this->formatPrice($this->subjectReader->readAmount($buildSubject)),
            'paymentMethodToken' => is_null($paymentToken) ?? $paymentToken->getGatewayToken()
        ];
```

The **null coalesce** command is wrong as you can see if the object `$paymentToken` is not null it will return a `false` and then return `false` as a `paymentMethodToken` value.

My solution was:
```
            'paymentMethodToken' => !$paymentToken ? null : $paymentToken->getGatewayToken()
```

**Comment by andrewdaluz** [comment]
I found another issue: when you do a partial invoice with an order that doesn't have a credit card saved.
You're going to invoice 1 item in the order, this will set the transaction within this order item's amount.
But when you try to invoice another item, you'll receive an error message: "Cannot determine payment method".
By reviewing the code it seems like the partial invoice is enabled/working only with PayPal and it's not working for Credit Card with no CreditCard Token saved.

**Comment by andrewdaluz** [comment]
For the issue reported above I found out that Braintree is no longer saving tokenized credit cards for the transaction (probably for security purposes, which I agree).
The problem is that on previous version our client was able to do Partial Invoice with both scenarios: 

- With Credit Card Tokenized
- With NO Credit Card Tokenized (normal transaction without saving credit card)

This issue is related to the change on `vendor/paypal/module-braintree-core/Gateway/Request/VaultDataBuilder.php`
The code before the upgrade:
```
    public function build(array $buildSubject): array
    {
        return [
            self::OPTIONS => [
                self::STORE_IN_VAULT_ON_SUCCESS => true
            ]
        ];
    }
```

New Code:
```
    public function build(array $buildSubject): array
    {
        $result = [];
        $paymentDO = $this->subjectReader->readPayment($buildSubject);
        $payment = $paymentDO->getPayment();
        $data = $payment->getAdditionalInformation();

        if (!empty($data[VaultConfigProvider::IS_ACTIVE_CODE])) {
            $result[self::OPTIONS] = [
                self::STORE_IN_VAULT_ON_SUCCESS => true
            ];
        }

        return $result;
    }
```


To allow our client to have the ability for Partial Invoicing for all scenarios within credit cards I had to create a patch to rollback these changes.

**Comment by live4soccer7** [comment]
I had the same issues with adding to cart and not being able to checkout via braintree. I believe CC and paypal. I'm on 2.4.6-p1. Disabling line items resolved the cart for me and I just attempted to comment out the suggested lines.

**Comment by live4soccer7** [comment]
This allowed paypal payments to come through. I have seen multiple items in a single order and multiple quantities of these items as well.

It is probably a separate issue, but braintree CC payments do not work and simply hang with a loading symbol.

**Comment by Cupropituvanso** [comment]
Is this bug on any roadmap?
It prevents us from upgrading and on the other hand we have to work with other bugs which are solved in the newer versions.

**Comment by live4soccer7** [comment]
Hopefully. I the meantime the solution/workaround suggested does work.

**Comment by kartikmaniyar** [comment]
Thank you everyone for your feedback!

Apologies that you haven't got any response from the Magento/Adobe Team.

**[GENE Commerce](https://www.gene.co.uk/)** is responsible for developing the Magento Braintree extension. I would like to tell you that this issue is already been fixed in Magento **v2.4.7-beta1** that has already been released on June 13, 2023. Here, you can find the v2.4.7-beta1 release notes for the **Braintree**: https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-7.html?lang=en#braintree

We already have a patch ready for Magento/Adobe v2.4.6 and its patch versions for the issue reported here. You can download the patch from this link: https://support.gene.co.uk/support/solutions/articles/35000227790-patch-for-unable-to-checkout-via-paypal-through-braintree-in-magento-v2-4-6-and-v2-4-6-p1-p2

Also if you have any technical issues or concerns regarding our Magento Braintree extension, you can reach out to us by raising a support ticket from here: https://support.gene.co.uk/support/home

**Comment by nordcomputer** [comment]
Thank you @kartikmaniyar! I have been waiting ages for an official patch. Time to move our installation to the current release :D

**Comment by adriansanta** [comment]
@kartikmaniyar unfortunately, the patch you provided is not working for us (adobe commerce 2.4.6-p2). we still get:
`Processor Response Text: Declined (2046)
Additional Processor Response: 2046 : ITEM_TOTAL_MISMATCH`

Do we have to create a ticket on the GENE site as well?

Please advise, thank you

**Comment by nomis11uk** [comment]
We have also installed the patch on 2.4.6-p2 but still getting the same error 'PayPal Checkout could not be initialized'

**Comment by live4soccer7** [comment]
Can anyone confirm if this is fixed in 2.4.6-p3 that was released today?

**Comment by adriansanta** [comment]
also @kartikmaniyar, please note that SEPA is not working as expected.

`Transaction has not localPayment attribute`

This is happening in \PayPal\Braintree\Gateway\Helper\SubjectReader::readLocalPayment because it looks for the localPayment attribute but braintree now responds with something different.

For SEPA for example, if we dump the $transaction object, we get:

- [paymentInstrumentType] => sepa_debit_account
- [sepaDirectDebitAccountDetails] => Array

Please consider this when working on a new version/patch. We are currently working on our own workaround until the official fix is released.

Thank you

**Comment by nomis11uk** [comment]
@live4soccer7 just tried 2.4.6-p3 but still get 'PayPal Checkout could not be initialized. Please contact the store owner.'

**Comment by live4soccer7** [comment]
@nomis11uk Did you uncomment lines 192-195? This is how I have mine on p1 (updating to p3 in a couple days). It does work just fine on p1.

**Comment by nomis11uk** [comment]
@live4soccer7 No but I have already applied the patch. Waiting to hear from GENE Commerce.

**Comment by live4soccer7** [comment]
@nomis11uk after updating did you see if the patch is still installed/active?

**Comment by nomis11uk** [comment]
@live4soccer7 yes, the patched files are unchanged after upgrading to p3

**Comment by live4soccer7** [comment]
That's a bummer it still doesn't work. We are going to run out of payment gateways to use with magento. We already had to switch from paypal's actual gateway due to issues they had and no one could figure out. Please post up what GENE Commerce says and any solution you may come across.

**Comment by adriansanta** [comment]
@live4soccer7 for us it definitely helped creating a support ticket on the GENE side (https://support.gene.co.uk/support/home), they were quite responsive and we exchanged a few ideas, which led in our case to a solution. I would suggest doing that also.

For us specifically (https://github.com/magento/magento2/issues/37242#issuecomment-1746825703), we had the PayPal decline because the **unitAmount** field on the line item was also containing the **taxAmount** value, since it was not considering the sales tax display configuration. We proposed a solution to subtract **taxAmount** from the **unitAmount** if the configuration was set to **including tax**, solution that GENE support agreed upon, at least as a workaround until they finish up working on a new patch (ETA next week).

We basically did the following in the `\PayPal\Braintree\Gateway\Request\Level23ProcessingDataBuilder::build`:

Line 135 (after `$order = $paymentDO->getOrder();`) we added:

`$shouldSubtractTax = $this->scopeConfig->getValue(\Magento\Tax\Model\Config::XML_PATH_DISPLAY_SALES_PRICE, ScopeInterface::SCOPE_STORE, $order->getStoreId()) == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX;`

and line 162 (after `$itemQuantity = (float)$item->getQtyOrdered();`) we changed the line to:

`$itemUnitPrice = $shouldSubtractTax ? ((float)$item->getPrice() - (float)$item->getTaxAmount()) : (float)$item->getPrice();`

Hope this helps, for us it did.

Again, this was for our tax-specific use-case, you might experience a different issue with a different root cause, that's why it's best to reach out to GENE via a support ticket, they are the most suitable to give advice after all.

Best of luck!

**Comment by nomis11uk** [comment]
Thanks @adriansanta we tried the above but it did not resolve the error for us. Speaking to GENE Commerce tomorrow

**Comment by live4soccer7** [comment]
@nomis11uk What did GENE Commerce say about the issue? Was a a resolution provided?

**Comment by nomis11uk** [comment]
@live4soccer7 we had a separate issue with the default currency (USD) on our Braintree account which continued to cause an error. Using the original patch provided it's now working for us.

**Comment by shunmugakumaran** [comment]
Hi @kartikmaniyar  can we apply your patch.. we upgraded to 2.4.6-p2 after we faced the issue below

We have checked & found that the below API from paypal braintree is going to 422 error status code

https://api.braintreegateway.com/merchants/q8j78ffnzxtsy4wh/client_api/v1/paypal_hermes/create_payment_resource

Response : 

{
  "paymentResource": {
    "errorName": "VALIDATION_ERROR",
    "errorMessage": "Invalid request - see details --- transactions[0]:Item amount must add up to specified amount subtotal (or total if amount details not specified)",
    "errorDetails": [
      {
        "field": "transactions[0]",
        "issue": "Item amount must add up to specified amount subtotal (or total if amount details not specified)"
      }
    ],
    "debugId": "5c298921cb024",
    "paypalHttpStatus": 400
  }
}

**Comment by adriansanta** [comment]
@shunmugakumaran you are experiencing pretty much what we were experiencing, maybe this helps:

> @live4soccer7 for us it definitely helped creating a support ticket on the GENE side (https://support.gene.co.uk/support/home), they were quite responsive and we exchanged a few ideas, which led in our case to a solution. I would suggest doing that also.
> 
> For us specifically ([#37242 (comment)](https://github.com/magento/magento2/issues/37242#issuecomment-1746825703)), we had the PayPal decline because the **unitAmount** field on the line item was also containing the **taxAmount** value, since it was not considering the sales tax display configuration. We proposed a solution to subtract **taxAmount** from the **unitAmount** if the configuration was set to **including tax**, solution that GENE support agreed upon, at least as a workaround until they finish up working on a new patch (ETA next week).
> 
> We basically did the following in the `\PayPal\Braintree\Gateway\Request\Level23ProcessingDataBuilder::build`:
> 
> Line 135 (after `$order = $paymentDO->getOrder();`) we added:
> 
> `$shouldSubtractTax = $this->scopeConfig->getValue(\Magento\Tax\Model\Config::XML_PATH_DISPLAY_SALES_PRICE, ScopeInterface::SCOPE_STORE, $order->getStoreId()) == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX;`
> 
> and line 162 (after `$itemQuantity = (float)$item->getQtyOrdered();`) we changed the line to:
> 
> `$itemUnitPrice = $shouldSubtractTax ? ((float)$item->getPrice() - (float)$item->getTaxAmount()) : (float)$item->getPrice();`
> 
> Hope this helps, for us it did.
> 
> Again, this was for our tax-specific use-case, you might experience a different issue with a different root cause, that's why it's best to reach out to GENE via a support ticket, they are the most suitable to give advice after all.
> 
> Best of luck!

**Comment by kartikmaniyar** [comment]
@shunmugakumaran @live4soccer7 @nomis11uk If you are still facing the issue with PayPal through Braintree then I would suggest you raise the support ticket with us here: https://support.gene.co.uk/support/home and mention everything about the issue that you are getting along with steps to replication, etc.

Please don't forget to mention your Magento version and other required information. Thank you :pray:

**Comment by live4soccer7** [comment]
I can confirm on a stock checkout that paypal does NOT work with braintree. beyond frustrating.

**Comment by live4soccer7** [comment]
I can also confirm this change does not work either on p3:

Line 135 (after $order = $paymentDO->getOrder();) we added:

$shouldSubtractTax = $this->scopeConfig->getValue(\Magento\Tax\Model\Config::XML_PATH_DISPLAY_SALES_PRICE, ScopeInterface::SCOPE_STORE, $order->getStoreId()) == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX;

and line 162 (after $itemQuantity = (float)$item->getQtyOrdered();) we changed the line to:

$itemUnitPrice = $shouldSubtractTax ? ((float)$item->getPrice() - (float)$item->getTaxAmount()) : (float)$item->getPrice();

**Comment by adriansanta** [comment]
@live4soccer7 we actually had to change a bit the initial solution, because for cart items with quantity greater than 1 it would still fail. not sure if that's what you experience but here's what we changed:

```$itemUnitPrice = $shouldSubtractTax ? ((float)$item->getPrice() - (float)$item->getTaxAmount()) : (float)$item->getPrice();```
->
```$itemUnitPrice = $shouldSubtractTax ? ((float)$item->getRowTotal() - (float)$item->getTaxAmount()) / $itemQuantity : (float)$item->getPrice();```

looking forward to an official fix for this

**Comment by shunmugakumaran** [comment]
@adriansanta @live4soccer7  We have created a ticket & got the confirmation from gene commerce to apply the same patch given to open source 

Created by me : https://support.gene.co.uk/support/tickets/19949

Patch is available in this ticket : https://support.gene.co.uk/support/solutions/articles/35000227790-patch-for-unable-to-checkout-via-paypal-through-braintree-in-magento-v2-4-6-and-v2-4-6-p1-p2

**Comment by adriansanta** [comment]
@shunmugakumaran are you sure about this? the patch you linked is dated Sep 22, and a lot of us still had issues afterwards. doesn't seem to have been updated since.

**Comment by live4soccer7** [comment]
I also had to disable captcha v2 again. I'm on 2.4.6-p3. CC could not go through. I implemented the resolution I stated above and I had seen that the captcha issue was resolved. It is not, at least with the resolution that was implemented in my post.

**Comment by mohitnavik** [comment]
I have upgraded Magento version from 2.4.5-p2 to 2.4.6-p3 and I am also getting the same error.

Is there any patch or fixes available?

Thanks in advance!

**Comment by LucScu** [comment]
> I have upgraded Magento version from 2.4.5-p2 to 2.4.6-p3 and I am also getting the same error:
> 
> report.CRITICAL: Error: Call to undefined method Magento\Sales\Api\Data\OrderExtension::**getGwBasePrice**() in vendor/paypal/module-braintree-core/Gateway/Request/Level23ProcessingDataBuilder.php
> 
> Is there any patch or fixes available?
> 
> Thanks in advance!

same issue on 2.4.6-p3, then installed the suggested patch https://support.gene.co.uk/support/solutions/articles/35000227790-patch-for-unable-to-checkout-via-paypal-through-braintree-in-magento-v2-4-6-and-v2-4-6-p1-p2 and setted under Advanced Braintree Settings for "Send Cart Line Items" to NO, now it works.

**Comment by Calvin495** [comment]
> Thank you everyone for your feedback!
> 
> **[GENE Commerce](https://www.gene.co.uk/)** is responsible for developing the Magento Braintree extension. I would like to tell you that this issue is already been fixed in Magento **v2.4.7-beta1** that has already been released on June 13, 2023. Here, you can find the v2.4.7-beta1 release notes for the **Braintree**: https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-7.html?lang=en#braintree
> 
> We already have a patch ready for Magento/Adobe v2.4.6 and its patch versions for the issue reported here. You can download the patch from this link: https://support.gene.co.uk/support/solutions/articles/35000227790-patch-for-unable-to-checkout-via-paypal-through-braintree-in-magento-v2-4-6-and-v2-4-6-p1-p2
> 
> Also if you have any technical issues or concerns regarding our Magento Braintree extension, you can reach out to us by raising a support ticket from here: https://support.gene.co.uk/support/home

When I opened the link it only has patch for v2.4.6 and v2.4.6-p1/p2. Do you have separate patch for 2.4.6-p3 or Can we use the same patch for p3 as well?

**Comment by LucScu** [comment]
> > Thank you everyone for your feedback!
> > **[GENE Commerce](https://www.gene.co.uk/)** is responsible for developing the Magento Braintree extension. I would like to tell you that this issue is already been fixed in Magento **v2.4.7-beta1** that has already been released on June 13, 2023. Here, you can find the v2.4.7-beta1 release notes for the **Braintree**: https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-7.html?lang=en#braintree
> > We already have a patch ready for Magento/Adobe v2.4.6 and its patch versions for the issue reported here. You can download the patch from this link: https://support.gene.co.uk/support/solutions/articles/35000227790-patch-for-unable-to-checkout-via-paypal-through-braintree-in-magento-v2-4-6-and-v2-4-6-p1-p2
> > Also if you have any technical issues or concerns regarding our Magento Braintree extension, you can reach out to us by raising a support ticket from here: https://support.gene.co.uk/support/home
> 
> When I opened the link it only has patch for v2.4.6 and v2.4.6-p1/p2. Do you have separate patch for 2.4.6-p3 or Can we use the same patch for p3 as well?

i used it on 2.4.6-p3 and works well.

**Comment by neha023** [comment]
I am using M2.4.7 open source and still found the issue as I am unable to checkout using paypal through braintree.

**Comment by live4soccer7** [comment]
@neha023 What errors are you seeing?

**Comment by neha023** [comment]
It show the integration not done yet even if it is done by my side.

Below are some screenshots of admin configuration, Braintree & Paypal:
![screenshot-m247 com-2024 06 05-21_41_54](https://github.com/magento/magento2/assets/22883424/674e3e82-7957-4fdc-99e8-5e94e9c61936)

Paypal:
![screenshot-developer paypal com-2024 06 05-22_12_43](https://github.com/magento/magento2/assets/22883424/3ad2f972-5e82-4aee-ad9f-c1de03a04aa4)

Braintree:
![screenshot-sandbox braintreegateway com-2024 06 05-21_54_34](https://github.com/magento/magento2/assets/22883424/96d7460a-7261-470d-b038-0cbf4b89c98f)

Storefront: 
![Screenshot from 2024-06-05 22-09-52](https://github.com/magento/magento2/assets/22883424/464689f8-8384-41ef-bef9-9dc6ea6b8cc8)

![Screenshot from 2024-06-05 21-58-55](https://github.com/magento/magento2/assets/22883424/d9f27d22-8bdf-449f-981a-2f7fb297bfc9)

Both braintree & Paypal sandbox created with same email Id and sandbox business id have used for india country & braintree sandbox account created for country india.

**Comment by live4soccer7** [comment]
This appears to be a different issue than what this thread has been experiencing.

**Comment by nordcomputer** [comment]
@neha023 I recently got it working on the shop I am working on. The error was not in the code. I had to get in touch with braintree, because they hadnt connected the braintree account with the paypal account or smth. similar. Took us about 3 weeks through some support tickets at braintree and paypal, after they figured it out, that the error was on their end and not on ours.

**Comment by tobiasolge** [comment]
same problem with 2.4.6-p6 and patch is not working.

**Comment by dbashyal** [comment]
We are having same issue in 2.4.6-p6. 

See screenshots.

![braintree_paypal_1](https://github.com/user-attachments/assets/85ce6952-bdbb-4ac4-a4c0-8ba2830ef6e1)

![braintree_paypal_2](https://github.com/user-attachments/assets/6f3f438b-af25-4ef4-9547-b3052332a14f)

**Comment by link2light** [comment]
For anyone who reached here (like me) the issue is that PayPal through Braintree is not supposed to work in 2.4.6-p6 - even though all the settings are there in the admin area. This is what I was told by BrainTree themselves. 

Instead you have to move to Adobe Payments. Adobe tell me that BrainTree is completely gone in 2.4.7 and Adobe Payments is the 'baked in' payment method. But if you are on 2.4.6-p6 you need to go through the Adobe Payments on boarding process (which may require submitting some documentation), and then set up Adobe Payments here: https://experienceleague.adobe.com/en/docs/commerce-merchant-services/payment-services/get-started/install

This is for both Commerce and Open Source.

**Comment by CollegeSewing** [comment]
@link2light Braintree Payments are still very much available in Magento 2.4.7 (including -p2) as per the Gene Commerce docs
https://support.gene.co.uk/support/solutions/articles/35000228529

**Comment by link2light** [comment]
@CollegeSewing - fair enough. All I can tell you is what BrainTree told me which is that you can't use PayPal through BrainTree in 2.4.6-p6 or above. They actively assisted us in switching over to Adobe Payments. Perhaps if you don't want PayPal through BrainTree it's still there as a credit card processor option.

**Comment by live4soccer7** [comment]
I'm on 2.4.6-p7 and paypal works just fine with the usual fix in this thread.

**Comment by kartikmaniyar** [comment]
@link2light Braintree is completely available on all the current and upcoming Magento versions. If you don't mind then can I ask you to delete your comment as It will mislead merchants & developers.

I don't know why they have told you this but I would like to know the name of that Braintree person who has asked you this. are you able to share name of that Braintree guy with me?

**Comment by link2light** [comment]
@kartikmaniyar - sure but is there a way to private message it?

**Comment by kartikmaniyar** [comment]
> @kartikmaniyar - sure but is there a way to private message it?

can you email me on kartik.maniyar@gene.co.uk? I will remove this comment in 10 minutes, thanks! :+1:

**Comment by kartikmaniyar** [comment]
@link2light Please drop the message here once you copy the above email.

**Comment by link2light** [comment]
I have sent the email from BrainTree to your email. Let me know if you get it. It would be good to clear this up and understand if there was something very specific about our setup which lead to this advice.

**Comment by kartikmaniyar** [comment]
@link2light Thank you for sending the email.
Could you please remove your both the comments which is specifying things about PayPal through Braintree?

**Comment by engcom-Bravo** [comment]
Hi,

As per this comment https://github.com/magento/magento2/issues/37242#issuecomment-1731253868 issue has been fixed already we are closing this issue.

Thanks.

**Comment by tim-breitenstein-it** [comment]
Hello,

My Issue was more related by applying a voucher which results in a `ITEM_TOTAL_MISMATCH`.

I read all the comments and installed the patch from here:  https://support.gene.co.uk/support/solutions/articles/35000227790-patch-for-unable-to-checkout-via-paypal-through-braintree-in-magento-v2-4-6-and-v2-4-6-p1-p2 which I already had a erlier version of the patch installed.

First of all the patch works fine, but after testing some more situation and cart variants I reached the `ITEM_TOTAL_MISMATCH` error again.

If at least a single item is with more then 1 qty is in the cart the total amount calculation is incorrect.

After some research I found at least 3 errors in the provided patch!

In general: The total tax amount is deducted from each individual shopping cart item, which is totally wrong and only works in exceptional cases for a single shopping cart item.

In more detail:

```
diff --git a/view/frontend/web/js/view/payment/method-renderer/paypal.js b/view/frontend/web/js/view/payment/method-renderer/paypal.js
index f225c350a..113a1cf92 100644
--- a/view/frontend/web/js/view/payment/method-renderer/paypal.js
+++ b/view/frontend/web/js/view/payment/method-renderer/paypal.js
@@ -770,4 +770,4 @@ 
                     if (baseTaxAmount > 0 && priceIncludesTax === true) {
-                        itemUnitAmount -= baseTaxAmount;
+                        itemUnitAmount -= (parseFloat(quoteItem['base_tax_amount']) / itemQty);
                     }

```

```
diff --git a/Block/Paypal/Button.php b/Block/Paypal/Button.php
index 82092fee8..ef897fe27 100644
--- a/Block/Paypal/Button.php
+++ b/Block/Paypal/Button.php
@@ -470,5 +470,5 @@
                     $itemPrice = $this->getItemPrice($priceIncludesTax, $item);
                     if ($baseTaxAmount > 0 && $priceIncludesTax === true) {
-                        $itemPrice -= $baseTaxAmount;
+                        $itemPrice -= ($item->getBaseTaxAmount() / $item->getQty());
                     }

```

```
diff --git a/Gateway/Request/Level23ProcessingDataBuilder.php b/Gateway/Request/Level23ProcessingDataBuilder.php
index c2fa5806d..00f415be9 100644
--- a/Gateway/Request/Level23ProcessingDataBuilder.php
+++ b/Gateway/Request/Level23ProcessingDataBuilder.php
@@ -172,6 +172,6 @@
                 $itemQuantity = (float)$item->getQtyOrdered();
                 $itemUnitPrice = $includeTax === true ? (float) $item->getBasePriceInclTax() : (float) $item->getBasePrice();
                 if ($order->getBaseTaxAmount() > 0 && $includeTax === true) {
-                    $itemUnitPrice -= $order->getBaseTaxAmount();
+                    $itemUnitPrice -= ($item->getBaseTaxAmount() / $itemQuantity);
                 }

```

Note: Diff was quickly handmade so no guarantee!
