### ISSUE TITLE
Magento 2 REST API Issue: Unable to Handle Product SKU with Slash Value in stockItems Endpoint

### ISSUE THREAD

**Issue by mohammadbharmal** [magento/magento2#37830]
### Preconditions and environment

- Magento 2.4.6-p1

Magento 2 REST API Endpoint `/V1/stockItems/:productSku` is encountering a bug specifically when using OAuth 1.0 authentication. The issue arises when the product SKU contains special characters such as slashes (/) or ampersands (&). This results in an incorrect OAuth signature being generated, leading to errors in the authentication process.

The error is being triggered from the class `Magento\Framework\Oauth\Oauth::_validateSignature()` at line number 207. The root cause of the problem lies in the signature generation process, which is performed by the Laminas library. The library generates different signatures for SKUs containing slashes or ampersands, causing inconsistencies in the authentication flow.

Example:
Working URL: https://test.com/test-sku
Not Working URL: https://test.com/test-sku%2F123

The correct OAuth signature generation for the product SKU is not taking into account the special characters, leading to an incorrect signature that fails the authentication process.

To fix this issue, adjustments need to be made in the OAuth signature generation logic, ensuring that it properly handles SKUs with special characters and produces consistent signatures for all SKU variations.

Please see below screenshot for more reference.

![image](https://github.com/magento/magento2/assets/73457616/0bb71fc3-9551-42a7-bf90-524b19ac61e1)
![image](https://github.com/magento/magento2/assets/73457616/53182957-0f76-41f3-80a8-711fd03a838a)

### Steps to reproduce

1. Login to Magento admin.
2. Navigate to **System > Extensions > Integrations > Add New Integration**.
3. Activate Added Integration from the Integration grid with all rights.
4. Go to the **Catalog > Product**.
5. Add or edit product.
6. Keep sku name "demo-test/1234" or demo-test&1234
7. Save product.
8. Go to Postman
9. Set Get Request with endpoint `rest/V1/stockItems` ex:- https://your-domain/index.php/rest/V1/stockItems/demo-test%2F1234
10. Set Oauth 1.0
11. Set **Add authorization data to**  Request Headers.
12. Set Integration details in the OAuth request like consumer key, Access Token etc etc.
13. Send request

### Expected result

Should be return stock data of the sku

### Actual result

returning error "The signature is invalid. Verify and try again."

### Additional information

I have tested this with an postman

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mohammadbharmal** [comment]
@magento I am working on this

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instance

**Comment by mohammadbharmal** [comment]
I have generated tried to generate same case on the develop instance.

it's returning normal sku data, but not working with slash or ampersands.

Issue has ben generated.

SKU :- this-teste&787

URL:- https://94a8c4219b018f25698d274a8f585b17.instances-prod.magento-community.engineering/rest/V1/stockItems/this-teste%26787

![image](https://github.com/magento/magento2/assets/73457616/db86564e-e641-4410-a6da-62b29d02b077)

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @mohammadbharmal,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Login to Magento admin.
- Navigate to System > Extensions > Integrations > Add New Integration.
- Activate Added Integration from the Integration grid with all rights.
- Go to the Catalog > Product.
- Add or edit product.
- Keep sku name "demo-test/1234" or demo-test&1234
- Save product.
- Go to Postman
- Set Get Request with endpoint rest/V1/stockItems ex:- https://your-domain/index.php/rest/V1/stockItems/demo-test%2F1234
- Set Oauth 1.0
- Set Add authorization data to Request Headers.
- Set Integration details in the OAuth request like consumer key, Access Token etc etc.
- Send request

We are getting stock data for the SKU.

<img width="1408" alt="Screenshot 2023-08-07 at 5 51 05 PM" src="https://github.com/magento/magento2/assets/51680745/7331e4a2-1643-49df-a3ad-ad0f743b2262">




<img width="1200" alt="Screenshot 2023-08-07 at 5 50 58 PM" src="https://github.com/magento/magento2/assets/51680745/726d3544-553e-4f11-a14e-f877d357ae31">


 If Apache you also need to make sure you set `AllowEncodedSlashes NoDecode` as per this https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes.



<img width="579" alt="Screenshot 2023-08-07 at 5 53 36 PM" src="https://github.com/magento/magento2/assets/51680745/71faafb0-b16f-47c7-a99c-80736d132084">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by mohammadbharmal** [comment]
@engcom-Bravo , Thank you for the update, 

How we can configure `AllowEncodedSlashes NoDecode` for the nginx ?

**Comment by engcom-Bravo** [comment]
Hi @mohammadbharmal,

Thanks for your update.

Could you please refer this document http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass and let us know if you are still facing any issue.

Thanks.

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @mohammadbharmal,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instance

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instance

**Comment by mohammadbharmal** [comment]
@magento give me 2.4-develop instance

**Comment by jorgb90** [comment]
Indeed still not fixed.. https://github.com/magento/magento2/issues/37278
