### ISSUE TITLE
can not update custom customer attribute value on customer edit page in admin

### ISSUE THREAD

**Issue by GrassH** [magento/magento2#38730]
### Preconditions and environment

- Magento CE 2.4.7

Please see the following code:
https://github.com/magento/magento2/blob/fcebd3a4ad2a6863af2e2092f5e548cbd81cb0f8/app/code/Magento/Customer/Controller/Adminhtml/Index/Save.php#L378
https://github.com/magento/magento2/blob/fcebd3a4ad2a6863af2e2092f5e548cbd81cb0f8/app/code/Magento/Eav/Model/Config.php#L1020
https://github.com/magento/magento2/blob/fcebd3a4ad2a6863af2e2092f5e548cbd81cb0f8/app/code/Magento/Eav/Model/Config.php#L287

### Steps to reproduce

Create two websites: US and CA, US is default website, customer created by CA.

1. Create a custom customer attribute (**Test Attribute**) in patch:
```
$this->customerSetup->addAttribute(
          Customer::ENTITY,
          'test_attribute',
          [
              'type' => 'varchar',
              'label' => __('Test Attribute'),
              'input' => 'text',
              'is_visible' => false,
              'required' => false,
              'user_defined' => true,
              'sort_order' => 999,
              'position' => 999,
              'visible_on_front' => false,
              'unique' => true,
              'system' => false,
              'global' => ScopedAttributeInterface::SCOPE_WEBSITE
          ]
  );

  $customerEntity = $this->customerSetup->getEavConfig()->getEntityType(Customer::ENTITY);
  $attributeSetId = $customerEntity->getDefaultAttributeSetId();
  $attribute = $this->customerSetup->getEavConfig()
      ->getAttribute(Customer::ENTITY, 'test_attribute')
      ->addData([
          'attribute_set_id' => $attributeSetId,
          'attribute_group_id' => $this->attributeSet->getDefaultGroupId($attributeSetId),
          'used_in_forms' => ['adminhtml_customer', 'customer_account_edit']
      ]);

$attribute->save();
```
2. Go to customer edit page in admin
3. Type some value to **Test Attribute**, e.g: **test 1**
4. Click **Save and Continue Edit**, the value will be saved as **test 1**
5. Type a new value to **Test Attribute**, e.g: **test 2**
6. Click **Save and Continue Edit**, the value was expected to be "**test 2**", but the value is still "**test 1**"

![image](https://github.com/magento/magento2/assets/17757521/5f8620a0-f10f-43c6-8ac8-51f51a4111e1)

### Expected result

1. **Test Attribute** value is updated to **test 2**

### Actual result

1. **Test Attribute** value is still **test 1**

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by GrassH** [comment]
Hi @engcom-Bravo,

This should not be labeled as a Dev.Experience. In fact the issue also exists in the commerce, the issue still occurs for admin user adding custom attribute from admin panel. This should be a bug.

**Comment by engcom-Bravo** [comment]
Hi @GrassH,

Thanks for your reporting and collaboration.

We have verified the issue in 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.




https://github.com/magento/magento2/assets/51680745/b19be70e-efe3-4fef-8ca9-c52a1d4d46bb





Test Attribute value is updated to test 2.

Could you please let us know if we are missing anything.


Thanks.

**Comment by GrassH** [comment]
Hi @engcom-Bravo, 

Thank you for your test. I tested on 2.4.7, and this issue has been fixed in 2.4-develop. The same issue is reported in  #ACP2E-2791, I'm not sure if it is an internal ticket, I didn't find this ticket in the community. Please see https://github.com/magento/magento2/commit/2189982c0da2507149f444d254d475fd38968ce8

**Comment by engcom-Bravo** [comment]
Hi @GrassH,

Thanks for your update.

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-2791 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-2791&type=commits

Thanks.

**Comment by jignesh-baldha** [comment]
@engcom-Bravo https://github.com/magento/magento2/issues/38730#issue-2299763520 I'm facing a similar issue after the upgrade.

**Comment by jignesh-baldha** [comment]
> Hi @GrassH,
> 
> Thanks for your reporting and collaboration.
> 
> We have verified the issue in 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.
> 
>  Screen.Recording.2024-05-17.at.12.51.06.mov 
> Test Attribute value is updated to test 2.
> 
> Could you please let us know if we are missing anything.
> 
> Thanks.

Did you test with multiple websites? The default website will save the value, but others will keep the old values. It will not update customer attributes.

**Comment by ThomasNegeli** [comment]
This is still an issue with 2.4.7-p2.
Customer edit in adminhtml does not work when the customer account was not created in the default store of the customer website.
The reason is that ACP2E-2791 is not included in the release so far, but I can confirm that the commits from https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-2791&type=commits will fix the issue.

**Comment by ahsan-horani-folio** [comment]
This will be resolved in 2.4.8 as mentioned here https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/magento-open-source/2-4-8

**Comment by hnsr** [comment]
If you're on 2.4.7, here's a composer-compatible patch:

```
Fix custom customer attribute not saving for customers linked to non-default website, see
https://github.com/magento/magento2/issues/38730

@package magento/module-customer

diff --git a/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php b/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php
index 31971795d25..4589e915f90 100644
--- magento/module-customer/Controller/Adminhtml/Index/Save.php.orig
+++ magento/module-customer/Controller/Adminhtml/Index/Save.php
@@ -27,6 +27,7 @@ use Magento\Customer\Model\CustomerFactory;
 use Magento\Customer\Model\EmailNotificationInterface;
 use Magento\Customer\Model\Metadata\Form;
 use Magento\Customer\Model\Metadata\FormFactory;
+use Magento\Customer\Model\SetCustomerStore;
 use Magento\Framework\Api\DataObjectHelper;
 use Magento\Framework\Api\ExtensibleDataObjectConverter;
 use Magento\Framework\App\Action\HttpPostActionInterface as HttpPostActionInterface;
@@ -75,6 +76,11 @@ class Save extends \Magento\Customer\Controller\Adminhtml\Index implements HttpP
      */
     private $storeManager;

+    /**
+     * @var SetCustomerStore|null
+     */
+    private $customerStore;
+
     /**
      * Constructor
      *
@@ -106,7 +112,9 @@ class Save extends \Magento\Customer\Controller\Adminhtml\Index implements HttpP
      * @param SubscriptionManagerInterface $subscriptionManager
      * @param AddressRegistry|null $addressRegistry
      * @param StoreManagerInterface|null $storeManager
+     * @param SetCustomerStore|null $customerStore
      * @SuppressWarnings(PHPMD.ExcessiveParameterList)
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
      */
     public function __construct(
         Context $context,
@@ -136,7 +144,8 @@ class Save extends \Magento\Customer\Controller\Adminhtml\Index implements HttpP
         JsonFactory $resultJsonFactory,
         SubscriptionManagerInterface $subscriptionManager,
         AddressRegistry $addressRegistry = null,
-        ?StoreManagerInterface $storeManager = null
+        ?StoreManagerInterface $storeManager = null,
+        ?SetCustomerStore $customerStore = null
     ) {
         parent::__construct(
             $context,
@@ -168,6 +177,7 @@ class Save extends \Magento\Customer\Controller\Adminhtml\Index implements HttpP
         $this->subscriptionManager = $subscriptionManager;
         $this->addressRegistry = $addressRegistry ?: ObjectManager::getInstance()->get(AddressRegistry::class);
         $this->storeManager = $storeManager ?? ObjectManager::getInstance()->get(StoreManagerInterface::class);
+        $this->customerStore = $customerStore ?? ObjectManager::getInstance()->get(SetCustomerStore::class);
     }

     /**
@@ -335,6 +345,10 @@ class Save extends \Magento\Customer\Controller\Adminhtml\Index implements HttpP

         if ($this->getRequest()->getPostValue()) {
             try {
+                $this->customerStore->setStore(
+                    $this->getRequest()->getPostValue(CustomerMetadataInterface::ENTITY_TYPE_CUSTOMER)
+                );
+
                 // optional fields might be set in request for future processing by observers in other modules
                 $customerData = $this->_extractCustomerData();

@@ -370,13 +384,6 @@ class Save extends \Magento\Customer\Controller\Adminhtml\Index implements HttpP
                     }
                 }

-                $storeId = $customer->getStoreId();
-                if (empty($storeId)) {
-                    $website = $this->storeManager->getWebsite($customer->getWebsiteId());
-                    $storeId = current($website->getStoreIds());
-                }
-                $this->storeManager->setCurrentStore($storeId);
-
                 // Save customer
                 if ($customerId) {
                     $this->_customerRepository->save($customer);
diff --git a/vendor/magento/module-customer/Controller/Adminhtml/Index/Validate.php b/vendor/magento/module-customer/Controller/Adminhtml/Index/Validate.php
index 41ca037e626..0acc349d65b 100644
--- magento/module-customer/Controller/Adminhtml/Index/Validate.php.orig
+++ magento/module-customer/Controller/Adminhtml/Index/Validate.php
@@ -7,10 +7,12 @@ namespace Magento\Customer\Controller\Adminhtml\Index;

 use Magento\Customer\Api\AccountManagementInterface;
 use Magento\Customer\Api\AddressRepositoryInterface;
+use Magento\Customer\Api\CustomerMetadataInterface;
 use Magento\Customer\Api\CustomerRepositoryInterface;
 use Magento\Customer\Api\Data\AddressInterfaceFactory;
 use Magento\Customer\Api\Data\CustomerInterfaceFactory;
 use Magento\Customer\Model\Address\Mapper;
+use Magento\Customer\Model\SetCustomerStore;
 use Magento\Framework\Api\DataObjectHelper;
 use Magento\Framework\App\Action\HttpGetActionInterface;
 use Magento\Framework\App\Action\HttpPostActionInterface as HttpPostActionInterface;
@@ -33,6 +35,11 @@ class Validate extends CustomerAction implements HttpPostActionInterface, HttpGe
      */
     private $storeManager;

+    /**
+     * @var SetCustomerStore|null
+     */
+    private $customerStore;
+
     /**
      * @param \Magento\Backend\App\Action\Context $context
      * @param \Magento\Framework\Registry $coreRegistry
@@ -60,7 +67,9 @@ class Validate extends CustomerAction implements HttpPostActionInterface, HttpGe
      * @param \Magento\Backend\Model\View\Result\ForwardFactory $resultForwardFactory
      * @param \Magento\Framework\Controller\Result\JsonFactory $resultJsonFactory
      * @param StoreManagerInterface|null $storeManager
+     * @param SetCustomerStore|null $customerStore
      * @SuppressWarnings(PHPMD.ExcessiveParameterList)
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
      */
     public function __construct(
         \Magento\Backend\App\Action\Context $context,
@@ -88,7 +97,8 @@ class Validate extends CustomerAction implements HttpPostActionInterface, HttpGe
         \Magento\Framework\View\Result\PageFactory $resultPageFactory,
         \Magento\Backend\Model\View\Result\ForwardFactory $resultForwardFactory,
         \Magento\Framework\Controller\Result\JsonFactory $resultJsonFactory,
-        ?StoreManagerInterface $storeManager = null
+        ?StoreManagerInterface $storeManager = null,
+        ?SetCustomerStore $customerStore = null
     ) {
         parent::__construct(
             $context,
@@ -117,8 +127,8 @@ class Validate extends CustomerAction implements HttpPostActionInterface, HttpGe
             $resultForwardFactory,
             $resultJsonFactory
         );
-
         $this->storeManager = $storeManager ?? ObjectManager::getInstance()->get(StoreManagerInterface::class);
+        $this->customerStore = $customerStore ?? ObjectManager::getInstance()->get(SetCustomerStore::class);
     }

     /**
@@ -145,6 +155,9 @@ class Validate extends CustomerAction implements HttpPostActionInterface, HttpGe
             );
             $customerForm->setInvisibleIgnored(true);

+            $this->customerStore->setStore(
+                $this->getRequest()->getParam(CustomerMetadataInterface::ENTITY_TYPE_CUSTOMER)
+            );
             $data = $customerForm->extractData($this->getRequest(), 'customer');

             if ($customer->getWebsiteId()) {
@@ -161,11 +174,6 @@ class Validate extends CustomerAction implements HttpPostActionInterface, HttpGe
                 $entity_id = $submittedData['entity_id'];
                 $customer->setId($entity_id);
             }
-            if (isset($data['website_id']) && is_numeric($data['website_id'])) {
-                $website = $this->storeManager->getWebsite($data['website_id']);
-                $storeId = current($website->getStoreIds());
-                $this->storeManager->setCurrentStore($storeId);
-            }
             $errors = $this->customerAccountManagement->validate($customer)->getMessages();
         } catch (\Magento\Framework\Validator\Exception $exception) {
             /* @var $error Error */
diff --git a/vendor/magento/module-customer/Model/SetCustomerStore.php b/vendor/magento/module-customer/Model/SetCustomerStore.php
new file mode 100644
index 00000000000..b3334ffbdf2
--- /dev/null
+++ magento/module-customer/Model/SetCustomerStore.php
@@ -0,0 +1,55 @@
+<?php
+/************************************************************************
+ *
+ * Copyright 2024 Adobe
+ * All Rights Reserved.
+ *
+ * NOTICE: All information contained herein is, and remains
+ * the property of Adobe and its suppliers, if any. The intellectual
+ * and technical concepts contained herein are proprietary to Adobe
+ * and its suppliers and are protected by all applicable intellectual
+ * property laws, including trade secret and copyright laws.
+ * Dissemination of this information or reproduction of this material
+ * is strictly forbidden unless prior written permission is obtained
+ * from Adobe.
+ * ************************************************************************
+ */
+declare(strict_types=1);
+
+namespace Magento\Customer\Model;
+
+use Magento\Customer\Api\Data\CustomerInterface;
+use Magento\Framework\Exception\LocalizedException;
+use Magento\Store\Model\StoreManagerInterface;
+
+class SetCustomerStore
+{
+    /**
+     * @param StoreManagerInterface $storeManager
+     */
+    public function __construct(private StoreManagerInterface $storeManager)
+    {
+    }
+
+    /**
+     * Set store ID for the current customer.
+     *
+     * @param array|null $requestData
+     * @return void
+     */
+    public function setStore(array|null $requestData = null): void
+    {
+        $websiteId = $requestData[CustomerInterface::WEBSITE_ID] ?? null;
+        try {
+            $website = $this->storeManager->getWebsite($websiteId);
+            $storeId = $website ? current($website->getStoreIds()) : null;
+        } catch (LocalizedException $e) {
+            $storeId = null;
+        }
+        if (!$storeId) {
+            $storeId = $requestData[CustomerInterface::STORE_ID] ?? null;
+        }
+
+        $this->storeManager->setCurrentStore($storeId);
+    }
+}

```
