### ISSUE TITLE
Invalid option value when saving custom optons

### ISSUE THREAD

**Issue by igrslv** [magento/magento2#4085]
## Steps to reproduce
1. Add one custom option of drop-down Type
2. Add a row
3. Save the product
4. Add another row whithout filling in any data in it
5. Remove this row
6. Save product
## Expected result

Product must be saved without error messages.
## Actual result

Error message appears: "Invalid option value".

**Comment by adifucan** [comment]
Hi @igrslv I created an internal ticket MAGETWO-51756 to make errors reporting more intuitive

**Comment by igrslv** [comment]
Hi @adifucan, consider this PR https://github.com/magento/magento2/pull/4089

**Comment by adifucan** [comment]
Hi @igrslv! I cannot reproduce this bug: neither on CE nor on EE fresh develop.

After I save simple product product with 1 option and 2 values, add another 3rd row without filling in any data in it, remove this row & save the product, I get only 2 values in \Magento\Catalog\Model\Product\Option\Validator\Select::validateOptionValue without 'is_delete' key.

Can you recheck if this issue still occurs?

Thanks!

**Comment by igrslv** [comment]
Hi @adifucan, the same steps as you described:
1. saved  the product with one drop-down option and two values
2. added another empty row and immediately removed it
3. saved the product once again

This is what a have as a dump of values in Magento\Catalog\Model\Product\Option\Validator\Select::validateOptionValue

``` php
Array
(
    [44] => Array
        (
            [sort_order] => 0
            [option_type_id] => 44
            [is_delete] => 
            [title] => Red
            [price] => 
            [price_type] => fixed
            [sku] => 
        )

    [45] => Array
        (
            [sort_order] => 1
            [option_type_id] => 45
            [is_delete] => 
            [title] => Blue
            [price] => 
            [price_type] => fixed
            [sku] => 
        )

    [46] => Array
        (
            [sort_order] => 2
            [option_type_id] => -1
            [is_delete] => 1
            [title] => 
            [price] => 
            [price_type] => fixed
            [sku] => 
        )

)
```

<img width="1320" alt="invalidoptionvalue" src="https://cloud.githubusercontent.com/assets/1457489/14460638/d8e8188e-00be-11e6-8933-5360a0309c4b.png">

Version 2.0.4.

I have sent a pull request with cleaning out deleted values.

**Comment by adifucan** [comment]
Hi @igrslv!

I could not reproduce this bug because I tested it on https://github.corp.magento.com/magento2/magento2ce/tree/develop and you are talking about https://github.corp.magento.com/magento2/magento2ce/tree/2.0, right?

I do not mind to merge your pull request but you need to create it for branch 2.0 but not develop as on develop this bug is not reproduced. Or I can create pull request by myself based on your fix.

One more remark is that you need to walk through array in \Magento\Catalog\Model\Product\Option\Validator\Select::validateOptionValue (string 72) not by foreach ($option->getData('values') as $value) but by foreach ($values as $value) because filtered deleted values are in $values array but not in $option->getData('values').

**Comment by igrslv** [comment]
Hi @adifucan, please create PR. You are right, I had to create it for 2.0 branch. Thanks

**Comment by igrslv** [comment]
@adifucan, according to foreach loop, this is actually another bug which is already fixed in the develop branch.

**Comment by piotrekkaminski** [comment]
@igrslv @adifucan can this be closed?

**Comment by adifucan** [comment]
@piotrekkaminski yes please.

**Comment by shiftedreality** [comment]
Closed.

**Comment by tomasinchoo** [comment]
I am in 2.1.1 and this issue is still present. You use develop branch just as an excuse to close the issues.
Those "fixes" rarely end up in releases in any decent time.
So what should I do now? Make patch myself so next time when you end up with some security issue, I need 10 days to patch?
What should I tell my client now?!
-Excuse me, your site is made on something that even the company that invented it is not using it.
Guys, stop writing code just to pass the test. Click around sometimes!!!
