### ISSUE TITLE
Wrong parent category url_key in URL

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#4112]
## Preconditions
* Magento 2.1 and 2.2

## Steps to reproduce

We have two frontend storeviews in Magento 2.0.4, a French one and a German one. But the **parent** category url_key in the URL rewrites is always the German one, for both, the german and the french storeview.
## Expected result

Expected URL rewrite for a sub-category:
https://example.com/fr/french-parent-category/french-sub-category/

Expected URL rewrite for a product:
https://example.com/fr/french-parent-category/french-product/
## Actual result

Actual URL rewrite for sub-category:
https://example.com/fr/german-parent-category/french-sub-category/

Actual URL rewrite for a product:
https://example.com/fr/german-parent-category/french-product/

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-53443

**Comment by rganin** [comment]
Issue is not reproducible on 2.0.4, 2.0.7 and 2.1 with following combinations:
- 1 website (default), 2 store views (default & french),
- 2 websites (default, french). with one store view each (default - default, french - french)

Please verify that parent category (german-parent-category) in your instance has url-key value overriden on store view level. Please provide more details on the category entities values on different store views.

**Comment by bh-ref** [comment]
Hi @rganin

Thank you for looking into this issue.

All german url-keys are defined on default level (store view: all). The french url-keys are defined in the french store view. (In other words, no german url-keys are defined and/or overriden in the german store view).

**Comment by bh-ref** [comment]
also, just to clarify, we are using this combination: 1 website (default), 2 store views (german (sort order 0) & french (sort order 1)).

**Comment by rganin** [comment]
@bh-ref thanks for clarification, I will resume the investigation.

**Comment by rganin** [comment]
@bh-ref still cannot reproduce the issue on 2.0.4. Sorry for the silly question but do you have url-key for french store view on parent category? Or do you have some url-related extensions or customizations?

**Comment by stevenvdp** [comment]
We have a similar problem.

Category configuration:
Default config > url_key = "products"
French store > url_key = "produits"

Product configuration:
Default config > url_key: "awesome_product"
French store > url_key: "un_produit"

The url rewrite will be created after saving the product, but the category path is not store specific.
French store rewrite: products/un_produit

We are using v2.0.6 and have traced down the problem.

Inside app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php:80 the product categories are fetched, but not store specific. Later on it calls generateForSpecificStoreView() and passes the storeId, but the storeId is never used for calculating the category url path inside the following method:

getUrlPathWithSuffix (app/code/Magento/CatalogUrlRewrite/Model/ProductUrlPathGenerator.php:94)

```
    public function getUrlPathWithSuffix($product, $storeId, $category = null)
    {
        return $this->getUrlPath($product, $category) . $this->getProductUrlSuffix($storeId);
    }
```

Hope this helps for this case.

**Comment by rganin** [comment]
Could reproduce the issue.
@stevenvdp great thanks for your input, proceeding with fix.

**Comment by bh-ref** [comment]
@stevenvdp thank you for diving into it!

@rganin we actually do have some extensions related to url-keys, but they should not interact in that way. But I am happy to test the eventual fix against our extension.

**Comment by hostep** [comment]
We also run into a very similar problem, which happens after trying to create url rewrites in an automated category/product import job.

What seems to fix it, is these two changes (based on the Magento 2.1.2 codebase):

1. \Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator::generate
```diff
diff --git a/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php b/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php
index 6539a95..92ae0ec 100644
--- a/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php
+++ b/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlRewriteGenerator.php
@@ -108,7 +108,8 @@ class ProductUrlRewriteGenerator

         $productCategories = $product->getCategoryCollection()
             ->addAttributeToSelect('url_key')
-            ->addAttributeToSelect('url_path');
+            ->addAttributeToSelect('url_path')
+            ->setStoreId($storeId);

         $urls = $this->isGlobalScope($storeId)
             ? $this->generateForGlobalScope($productCategories)
```

2. \Magento\CatalogUrlRewrite\Model\Product\AnchorUrlRewriteGenerator::generate
```diff
diff --git a/app/code/Magento/CatalogUrlRewrite/Model/Product/AnchorUrlRewriteGenerator.php b/app/code/Magento/CatalogUrlRewrite/Model/Product/AnchorUrlRewriteGenerator.php
index 972b5c0..8845c7a 100644
--- a/app/code/Magento/CatalogUrlRewrite/Model/Product/AnchorUrlRewriteGenerator.php
+++ b/app/code/Magento/CatalogUrlRewrite/Model/Product/AnchorUrlRewriteGenerator.php
@@ -55,7 +55,7 @@ class AnchorUrlRewriteGenerator
             $anchorCategoryIds = $category->getAnchorsAbove();
             if ($anchorCategoryIds) {
                 foreach ($anchorCategoryIds as $anchorCategoryId) {
-                    $anchorCategory = $this->categoryRepository->get($anchorCategoryId);
+                    $anchorCategory = $this->categoryRepository->get($anchorCategoryId, $storeId);
                     $urls[] = $this->urlRewriteFactory->create()
                         ->setEntityType(ProductUrlRewriteGenerator::ENTITY_TYPE)
                         ->setEntityId($product->getId())
```

**Comment by veloraven** [comment]
This issue was fixed for ver. 2.1.
Closed.

**Comment by korostii** [comment]
Hi @veloraven could you please reference a particular version (2.1.6, 2.1.7, etc.)? Or at least a commit that fixes the issue?

**Comment by evilprophet** [comment]
Hi @veloraven you said that this was fixed for 2.1, but I still have this issue on 2.1.10 and 2.2. So where this is fixed?

**Comment by peterjaap** [comment]
This is still not fixed for the AnchorUrlRewriteGenerator.

This is the patch I'm using in the meantime;

```
diff --git a/Model/Product/AnchorUrlRewriteGenerator.php b/Model/Product/AnchorUrlRewriteGenerator.php
index a7cc894..c382d5f 100644
--- a/Model/Product/AnchorUrlRewriteGenerator.php
+++ b/Model/Product/AnchorUrlRewriteGenerator.php
@@ -61,7 +61,7 @@ class AnchorUrlRewriteGenerator
             $anchorCategoryIds = $category->getAnchorsAbove();
             if ($anchorCategoryIds) {
                 foreach ($anchorCategoryIds as $anchorCategoryId) {
-                    $anchorCategory = $this->categoryRepository->get($anchorCategoryId);
+                    $anchorCategory = $this->categoryRepository->get($anchorCategoryId, $storeId);
                     $urls[] = $this->urlRewriteFactory->create()
                         ->setEntityType(ProductUrlRewriteGenerator::ENTITY_TYPE)
                         ->setEntityId($product->getId())
-- 
2.14.1
```

**Comment by peterjaap** [comment]
Hm it seems that @hostep [already applied this fix](https://github.com/magento/magento2/pull/7667/files) but later on it was reverted again.

**Comment by hostep** [comment]
@peterjaap: it was never accepted, I purposely closed the PR since it caused too many negative side effects, I can't remember which ones though...

But there is a new pending PR which might get merged someday: https://github.com/magento/magento2/pull/14344

**Comment by ghost** [comment]
This issue is already fixed in Magento 2.2.5 and 2.3-dev version.
![default](https://user-images.githubusercontent.com/40756187/44150103-ef783f18-a0a6-11e8-93c5-68be03e959a4.png)

**Comment by slavvka** [comment]
Hi @bh-ref. Thank you for your report. 
The issue has been fixed in magento/magento2#26784 by @hostep in 2.4-develop branch
Related commit(s):
 - [cb685d15b2b590bdb4d99a3d4ebe563037d0aa31](https://github.com/magento/magento2/commit/cb685d15b2b590bdb4d99a3d4ebe563037d0aa31)
 - [acb8642c44d1ecb60ad023c81f6541fa9ebae47d](https://github.com/magento/magento2/commit/acb8642c44d1ecb60ad023c81f6541fa9ebae47d)
 - [97258e1a9ce97ad32971731eceac8fee32f66b74](https://github.com/magento/magento2/commit/97258e1a9ce97ad32971731eceac8fee32f66b74)
 - [6cf26dc19e2f80f0c2da445443d0b48a1974fc77](https://github.com/magento/magento2/commit/6cf26dc19e2f80f0c2da445443d0b48a1974fc77)
 - [0b941218dcc86dcbd518f5400934e995ad1f2e3c](https://github.com/magento/magento2/commit/0b941218dcc86dcbd518f5400934e995ad1f2e3c)
 - [b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908](https://github.com/magento/magento2/commit/b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908)
 - [28fa34531f4c7cd4bcad46500ba027b9b58ff297](https://github.com/magento/magento2/commit/28fa34531f4c7cd4bcad46500ba027b9b58ff297)
 - [bf514b0b435a75f5688f56f8e9465af9bb3284c1](https://github.com/magento/magento2/commit/bf514b0b435a75f5688f56f8e9465af9bb3284c1)

The fix will be available with the upcoming 2.4.0 release.

**Comment by PiroozMB** [comment]
@Olga Moyseyenko @veloraven
You are very funny just going around and closing the issues remaining them with no solution :-) 
I don't know how you got hired there lol. Is there nothing better to do for you there ? 
When people say the issue is not solved ,they really mean it. So don't close the issues like this. Just help to solve them.
