### ISSUE TITLE
Customer Import - Invalid data for insert

### ISSUE THREAD

**Issue by zinittest** [magento/magento2#4291]
## Steps to reproduce
1. Create CSV file for customer import with two rows: first - all columns filled with dummy content, second - without gender or dob data (example attached). 
   [test_main.csv.zip](https://github.com/magento/magento2/files/234674/test_main.csv.zip)
2. Choose "Customers Main File", "Add/Update Complex Data" options. 
3. Hit "Check Data" button - validation should be OK. 
4. Hit "Import" button.
## Expected result
1. Customer data imported to the shop.
## Actual result
1. Error message appears: "Invalid data for insert".

P. S. Error occurs because data rows which are going to be inserted have different keys (https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L1878). It happens because fields with empty values are discarded during data preparation step (https://github.com/magento/magento2/blob/develop/app/code/Magento/CustomerImportExport/Model/Import/Customer.php#L373). I was able to import data just commenting these lines, but obviously it requires more proper fix.

**Comment by piotrekkaminski** [comment]
@ilol please review

**Comment by BaDos** [comment]
Hi @zinittest 

Thank you for reporting.
We've created an internal ticket MAGETWO-58316 to resolve this issue.

**Comment by EL-Nazer** [comment]
Hi @BaDos 

Any updates - i am facing same issue with importing customers-address data

**Comment by BaDos** [comment]
Hi @EL-Nazer 

We are working on this issue.

**Comment by jvreeken** [comment]
This is still an issue in v2.1.3

**Comment by PieterCappelle** [comment]
Please add this fix in v2.1.4. This is critical! Original date reported is 25 Apr 2016. Fix was at 28 Sep 2016. Today 17 Jan 2017... #crying

PS: Fix from @mmansoorebay is working. Edited the core...

**Comment by nntoan** [comment]
I'm still facing this issue in v2.1.3 (customer composite).
@PieterCappelle : Which commit you use to fix? 8abf097 or 487ae24

**Comment by PieterCappelle** [comment]
@nntoan Both.

**Comment by nntoan** [comment]
@PieterCappelle You can choose only one commit. Because one of them add new lines to the if statement and the other one will delete the whole if statement...

Both of them mean you add new line, then you delete the whole if => only 487ae24
I tried 487ae24 and it's not working actually.

**Comment by pguedesbr** [comment]
Actually 487ae24 (removing the if statement) solved the issue for me. The question is why this commit hasnt been merged with the 2.1 branch. Therefore the fix is not live.

**Comment by uTosTan** [comment]
The issue is still there in v2.1.5. Commit https://github.com/magento/magento2/commit/487ae24056c189c63eb4427f2a5858890544e092 fixed the issue for me.

**Comment by veloraven** [comment]
This issue has already been fixed. Internal ticket for ver. 2.1. - MAGETWO-58760.
Internal ticket for ver. 2.0 - MAGETWO-58392.
These fixes should be available in some of the nearest release.

**Comment by apshahi** [comment]
Hi..
Actually In Customer CSV import in magento2.1.7
![qgmbx](https://user-images.githubusercontent.com/31069387/29364922-c4925472-82b2-11e7-82fb-ab18afb84df4.png)
, after check validation step. it occurs error to invalidate insert data.how can i fixed it..
![Uploading QGmBx.png…]()

**Comment by orlangur** [comment]
@apshahi please check latest stable version before commenting, fix should be present in `2.1.8` due to https://github.com/magento/magento2/commit/aaf85037b4db866b04ceed183578110ce1403e2c.

**Comment by apshahi** [comment]
@orlangur, I 'm not exactally getting your point. The question is which Section in commenting in code.

**Comment by orlangur** [comment]
@apshahi I don't see your comment I commented (or I commented in the wrong thread?).

AFAIR, there was something like "still see this on 2.1.7" while 2.1.8 was already released.

**Comment by heidiboh** [comment]
Using 2.2 This is still a problem. When uploading data matching the format of the sample file, get this error:
**Header contains invalid attribute(s): "reward_update_notification", "reward_warning_notification"**

M2 provides a sample file in the Import page, however, it provides an invalid file.
Also tried matching my import file to the customer main export in the Export page, but this does not work either (get a columns not matching rows error).
