### ISSUE TITLE
composer update deleted all files in mage2 folder

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4792]
I used php composer.phar update in order to update. First I thought it would just have deleted the bin/magento file, but now I am missing EVERY file on the server. File structure is still intact, but there are literally NO files anymore. 

Sure, we do have a backup, but still: how could this be possible? 

I rm -rf'd the vendor folder in order to make an update possible. Now everything is gone. How?

**Comment by stamster** [comment]
I had no issues like that with `composer update`

What are the contents of your `composer.json` ?

**Comment by sunel** [comment]
@kingalca u dont need to remove the vendor folder just use composer  update it will update only the modules that has update

**Comment by mazhalai** [comment]
@kingalca can you please provide more detailed steps. Looks like upgrade did not go through.

**Comment by grasdaggel** [comment]
Hi, we upgraded from 2.0.4 to 2.0.7. Backend still says 2.0.4. so maybe the db update hasn't went trough.

Also, I cannot use bin/magento anymore - it just does nothing. Do you need the content of composer.json?

**Comment by ghost** [comment]
Is the execute bit set on it?

**Comment by mazhalai** [comment]
@kingalca isn't this a duplicate of #4790

**Comment by grasdaggel** [comment]
@mazhalai Sorta. I first created this, then found out that there were more files missing, hence the other ticket. 

@xcomSteveJohnson Yes.

**Comment by ghost** [comment]
@kingalca Did you try `magento --list`? Just curious.

**Comment by grasdaggel** [comment]
Yes, tried that. Gave me no output.

**Comment by dmitriyprime** [comment]
Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too. Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by grasdaggel** [comment]
As the ticket is about an year old I do not know the steps anymore.

**Comment by bap14** [comment]
I have this same issue almost every time I upgrade between versions.  I'm trying to upgrade from 2.2.1 to 2.2.2 Enterprise Edition and it deletes every file under `app`, `bin`, `lib`, `dev`, `var/.htaccess` and `vendor/.htaccess`.  This appears to happen when the composer process gets to `- Updating magento/magento2-ee-base (2.2.1 => 2.2.2): Loading from cache`.

I think the "Loading from cache" is the culprit (for some reason).  After updating to 2.2.2 and noticing all the files missing I ran:

    composer clear-cache
    composer update

and all the missing files were restored and the necessary modifications for the updated Magento version were applied.  My git status went from having over 1,000 files removed to 151 modified (when upgrading from 2.2.1 to 2.2.2).

Hope this helps if someone else runs across this issue.

**Comment by netdesign** [comment]
We had the same problem.

Hope this would be useful for someone. We solved the issue  downgrading and upgrading again Magento!

Here a more detailed log: https://magento.stackexchange.com/a/210298/62913

**Comment by AymericJoubert** [comment]
Similar issue here upgrading from 2.3.0 to 2.3.1, resolved by @bap14 comment

> I have this same issue almost every time I upgrade between versions. I'm trying to upgrade from 2.2.1 to 2.2.2 Enterprise Edition and it deletes every file under `app`, `bin`, `lib`, `dev`, `var/.htaccess` and `vendor/.htaccess`. This appears to happen when the composer process gets to `- Updating magento/magento2-ee-base (2.2.1 => 2.2.2): Loading from cache`.
> 
> I think the "Loading from cache" is the culprit (for some reason). After updating to 2.2.2 and noticing all the files missing I ran:
> 
> ```
> composer clear-cache
> composer update
> ```
> and all the missing files were restored and the necessary modifications for the updated Magento version were applied. My git status went from having over 1,000 files removed to 151 modified (when upgrading from 2.2.1 to 2.2.2).
> 
> Hope this helps if someone else runs across this issue.

**Comment by antoinekociuba** [comment]
For those who are still struggling on this, simple add the following setting on your main `composer.json` file, in order to force override from `magento2-base` to project filesystem during `composer update` process:

```
"extra": {
  "magento-force": "override"
}
```

On my case, the problem was related to files from previous versions/installation which were still present/not cleared properly during the update, and then, I got the following error when using verbose composer command (`composer update -vvv`):

```
start magento deploy for magento/magento2-base
Target ./.github/CODE_OF_CONDUCT.md already exists (set extra.magento-force to override)
start magento deploy for magento/ece-tools
Target ./.magento.env.yaml.dist already exists (set extra.magento-force to override)
start magento deploy for magento/magento2-ee-base
Target ./LICENSE_EE.txt already exists (set extra.magento-force to override)
```

Hope this will help.
