### ISSUE TITLE
Magento 2.1 RC1 - Error when running CLI upgrade command

### ISSUE THREAD

**Issue by toddwolaver** [magento/magento2#4795]
Attempting to run setup:upgrade after compiling DI results in an error. I have tried with just 'setup:upgrade' and 'setup:upgrade --keep-generated'.
## Steps to reproduce
1. Install Magento 2.1 RC1 via composer.
2. Compile DI or enable production mode.
   - 'php bin/magento setup:di:compile' or
   - 'php bin/magento deploy:mode:set production' 
3. Run upgrade command (results in error)
   - 'php bin/magento setup:upgrade' or
   - 'php bin/magento setup:upgrade --keep-generated' 
## Expected result
1. For setup:upgrade to run and process necessary upgrades
## Actual result
1. Upgrade does not run and results in error:

<pre><code>php bin/magento setup:upgrade --keep-generated

  [Exception]  
  Warning: file_get_contents(/Users/twolaver/magento/magento-rc1/var/di/setup.ser): failed to open stream: No such file or directory in /Users/twolaver/magento/magento-rc1/vendor/magento/framework/App/ObjectManager/ConfigLoader/Compiled.php on line 28              </pre></code>

Note: contents of var/di are: 
- adminhtml.ser 
- crontab.ser 
- frontend.ser 
- global.ser 
- webapi_rest.ser 
- webapi_soap.ser

**Comment by mazhalai** [comment]
@toddwolaver why would you run compile before upgrade? Also, if you are installing a fresh 2.1.0-rc1 why do you need to run upgrade? did you have an older code base?
Please follow the steps specified in the following link to upgrade: http://devdocs.magento.com/guides/v2.0/comp-mgr/cli/cli-upgrade.html

**Comment by toddwolaver** [comment]
@mazhalai The steps in this issue only illustrate the basic steps to recreate the error.

In a real world example, this would be run on a production deployment of an existing codebase. I run upgrade, compile DI and generate static assets off of the production server, move the updated codebase with generated files into place on production and re-run the upgrade with --keep-generated to update the production database. With the current error introduced in 2.1 RC1, this process is no longer viable.

**Comment by mazhalai** [comment]
@toddwolaver in this case, you will need to clear your var/generation and var/di manually before pushing to the server, since the previous generated files still exist and are no longer relevant since the code has been updated.

**Comment by toddwolaver** [comment]
@mazhalai Just to be clear, are you saying that in Magento 2.1 'setup:upgrade' will no longer be supported after DI has been compiled?

If so, I would recommend updating the error message and removing the --keep-generated option from setup:upgrade, since it now serves no purpose (i.e. to keep the previously generated files)

The process of building a production 'image' 'off site' minimizes the amount of processing needed in the production environment and limits need to put the production environment into maintenance mode during code deployments. The files are relevant since they were compiled against the updated codebase, just on a different server. However there is still need to update the production database after moving the production 'image' into place in the production environment, hence the need to run 'setup:upgrade --keep-generated' with the compiled files in place.

Thank you,
Todd

**Comment by mazhalai** [comment]
@toddwolaver No, what I mean is, setup:upgrade will not work with `old` generated code. We have a mechanism to clean this automatically before upgrade runs, but if you do this locally and push it, and run it with the --keep-generated flag, there is no way to clean the old code.

**Comment by toddwolaver** [comment]
Thank you @mazhalai 

I still get an error when running 'php bin/magento setup:upgrade'. The only way to resolve the error is to manually remove var/di 

Thank you,
Todd

<pre><code>
php bin/magento setup:upgrade
                                                                                                                                                                
  [Exception]                                                                                                                                                   
  Warning: file_get_contents(/Users/twolaver/magento/magento-rc1/var/di/setup.ser): failed to open stream: No such file or directory in /Users/twolaver/magento/magento-rc1/vendor/magento/framework/App/ObjectManager/ConfigLoader/Compiled.php on line 28 
</code></pre>

**Comment by mazhalai** [comment]
@toddwolaver what version were you on prior to rc1? Also, can you give us more info on your environment like web server, php version, etc.

**Comment by mazhalai** [comment]
@toddwolaver we have created ticket MAGETWO-53777 to investigate and fix.

**Comment by toddwolaver** [comment]
@mazhalai I had been using 2.0.7 prior to RC1

Environment details:
- Ubuntu 14.04.4 LTS
- PHP 5.6.19
- MySQL 5.6.28
- Apache 2.4.18

**Comment by peec** [comment]
Same problem here. ( 2.1-RC2 ) on production deploy. ( Development local copy works with no di compilation ).

Environment:
- PHP 7.0.4
- PHP-FPM with NGINX
- Mysql 5.6
- Magento 2.1-RC2

2.0.7 worked, upgraded to RC2 and now fails.

The commands i run:

```
echo "DI Compliation"
/src/bin/magento setup:di:compile  

echo "Setup upgrade"
/src/bin/magento setup:upgrade  /// THIS FAILS.

echo "Clearing cache"
/src/bin/magento cache:clean
/src/bin/magento cache:flush
/src/bin/magento setup:di:compile 
```

Log:

```
DI Compliation
Compilation was started.
%message% 0/7 [>---------------------------]   0% 1 sec 36.0 MiB%message% 0/7 [>---------------------------]   0% 1 sec 36.0 MiBProxies code generation... 0/7 [>---------------------------]   0% 1 sec 36.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 40.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 40.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 33 secs 140.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 33 secs 140.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 33 secs 140.0 MiB
Application code generator... 3/7 [============>---------------]  42% 33 secs 140.0 MiB
Application code generator... 4/7 [================>-----------]  57% 2 mins 158.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 2 mins 158.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 3 mins 174.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 3 mins 174.0 MiB
Area configuration aggregation... 6/7 [========================>---]  85% 4 mins 244.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 4 mins 244.0 MiB
Interception cache generation... 7/7 [============================] 100% 4 mins 244.0 MiB
Generated code and dependency injection configuration successfully.
Setup upgrade



  [Exception]                                                                                                                                                                                  
  Warning: file_get_contents(/src/var/di/setup.ser): failed to open stream: No such file or directory in /src/vendor/magento/framework/App/ObjectManager/ConfigLoader/Compiled.php on line 28  



setup:upgrade [--keep-generated] [--magento-init-params="..."]
```

**Comment by davidalger** [comment]
@maksek @pboisvert This is a critical bug which I'm rather shocked was not addressed before the release of the GA for 2.1. It was reported nearly a month ago, and kills the ability to do fast atomic deployments of code either by capistrano, imaging, etc, etc.

When can we expect to see this fixed? All deployments via the [capistrano-magento2](https://rubygems.org/gems/capistrano-magento2) Gem are now busted, and there is not really a good workaround, as running setup:upgrade on a production server before setup:di:compile is run on the new code is not very feasible, as it would mean having a site in maintenance mode while the compilation (which takes ~3 min) runs.

**Comment by hostep** [comment]
We also run into this now, like wth?
Indeed very critical.

@ Magento guys, do you even know how people are deploying Magento 2 shops to a production server? I keep getting the impression you haven't got the faintest idea about how this works. Would also be great if you could write some documentation about how to do this according to you, because we have to keep guessing what steps in what order we have to execute, it seems to change with every release you are putting out ...

**Comment by pboisvert** [comment]
@davidalger @hostep bug has been raised to P0 and folks are reviewing. We will investigate why not addressed for RC. Early comments indicate cause was known and a fix was available but that fix did not pass testing and bug sat with the lower priority in error so it was not flagged as a blocker for 2.1.

**Comment by hostep** [comment]
I found a temporary fix for this issue. If you can't wait until Magento comes with an update for this issue, you can follow these steps to fix it. My solution makes sure a `setup.ser` file gets generated, so that the `setup:upgrade --keep-generated` works again.

This involves creating a very small module with the following files:
- `app/code/Vendor/TempSetupDiCompileFix/registration.php`

``` php
<?php

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'Vendor_TempSetupDiCompileFix',
    __DIR__
);
```
-  `app/code/Vendor/TempSetupDiCompileFix/etc/module.xml`

``` xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Vendor_TempSetupDiCompileFix" setup_version="0.0.1"/>
</config>
```
-  `app/code/Vendor/TempSetupDiCompileFix/etc/di.xml` (this is the actual fix)

``` xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\App\AreaList">
        <arguments>
            <argument name="areas" xsi:type="array">
                <item name="setup" xsi:type="array">
                    <item name="frontName" xsi:type="string">temporary-fix-for-magento2-github-issue-4795</item>
                </item>
            </argument>
        </arguments>
    </type>
</config>
```

And then run

``` bash
bin/magento module:enable Vendor_TempSetupDiCompileFix
```

The `frontName` xml node is a hack, but it's the only way I could get it the solution working properly.
I first tried a solution like defined in the [module-cron](https://github.com/magento/magento2/blob/3ea7fcbaa4934dea2c7e8e51ffbcf2750db46e79/app/code/Magento/Cron/etc/di.xml#L42) xml: `<item name="setup" xsi:type="null" />`, but while this does generate a `setup.ser` file, it crashes the frontend. So I had to work around it like they did in the [module-webapi](https://github.com/magento/magento2/blob/d69f4088f8d61a211e843211bdfd7a8cd57fa0fd/app/code/Magento/Webapi/etc/di.xml#L12) module, but we don't actually need a frontName for this module, so after applying this hack and surfing to http://example.com/temporary-fix-for-magento2-github-issue-4795 it will crash, but that's not really a big deal :)

**Comment by andidhouse** [comment]
same problem here!

**Comment by rob1256** [comment]
Having this issue as well on the release of 2.1.  

Is there a way to have a production server without the need for some sort of build server to compile on?  Ideally I'd like to for example:
Upgrade Magento/Install a new module
Push up to production
Compile & Run setup to run migrations

With no down-time on the production server.

**Comment by hostep** [comment]
@rob1256: When they fix this issue, it will be possible :)
Or you can use my temporary fix.

We've been using it for a couple of days, and deploys work again.

They take around 8 minutes (way too long in my opinion), with only about 10 seconds of downtime (also too long), while we put the shop in maintenance mode just before running `bin/magento setup:upgrade  --keep-generated` and disable the maintenance mode again after this.

On the devdocs project, there is also a request for proper documentation about how to perform deploys, but it hasn't been adressed yet: https://github.com/magento/devdocs/issues/419

**Comment by rob1256** [comment]
@hostep: Thanks for your help :)
Hopefully we'll get some information on the order of commands to run in the docs and potential pitfalls to look out for.  Slowly gearing up to get an M2 instance into production so hopefully this issue will be sorted before then.

**Comment by davidalger** [comment]
@pboisvert It's been seven days since this was moved to P0, but no communication regarding timeline of fix, so I figured I'd check back in on this. Can you comment on about how soon we can expect a patch release which resolves this?

**Comment by SantoDE** [comment]
We now have the same problem, which keeps us blocked from upgrading to 2.1. Is there any eta available?

**Comment by protok** [comment]
Same problem here, this really is an issue.

**Comment by andidhouse** [comment]
@mazhalai do you have a solution for us? we can´t go live with this...

**Comment by james-radweb** [comment]
Getting the same issue, when will this be fixed?

**Comment by alexpotter** [comment]
```
The module code base doesn't match the DB schema and data.
       My_Module       data:       0.0.9  ->  1.0.0      
Run 'setup:upgrade' to update your DB schema and data.
```

Same issue and cannot migrate without this command

**Comment by johnhughes1984** [comment]
Same problem here, can we get an update please @pboisvert ?

**Comment by ghost** [comment]
Same issue here as well on 2.1. The module that @hostep put together does seem to get around it but this appears to be a core issue that needs to be resolved. It would be nice to see Magento 2 in a more stable and usable state.

**Comment by dominik-eller** [comment]
Same issue here, please fix.

**Comment by kelsonzhao** [comment]
Same issue.

**Comment by kelsonzhao** [comment]
hostep's fix solution works

**Comment by kelsonzhao** [comment]
Thank you

**Comment by mwr** [comment]
Ran into the same issue.
Adding the area code using di.xml solved the problem.

**Comment by SchumacherFM** [comment]
Oh this is terrible but the hack was helpful. When is M2 2.1.1 expected? End of year?

**Comment by brian3t** [comment]
@hostep fix works, thanks a lot. 

This is very typical of Magento.

**Comment by rhiensch** [comment]
@hostep i'm getting an error trying to enable the module:

Executing the following command:
`php bin/magento module:enable Vendor_TempSetupDiCompileFix`
gives me the following error:
`Unknown module(s): 'Vendor_TempSetupDiCompileFix'`

**Comment by Ctucker9233** [comment]
Just ran into this issue myself. Any word on a patch?

**Comment by kanduvisla** [comment]
I have this issue as well in 2.1

**Comment by senthilengg** [comment]
Have the same issue with 2.1 fixed with a `'Vendor_TempSetupDiCompileFix'`

**Comment by RUjmiak** [comment]
@mazhalai do you have sollution for this?

**Comment by docus** [comment]
@hostep fix works, thanks a lot.
Magenta 2.1 CE

**Comment by famousTM** [comment]
Hello guys, do you have the fix? I'd rather not use a hack.

**Comment by bpoiss** [comment]
Issue still exists on 2.1, how should I deploy changes to my production environment now without way too long downtimes?

**Comment by slackerzz** [comment]
@hostep thank you very much!

**Comment by KevinMace** [comment]
+1 Having this issue as well

**Comment by deckside** [comment]
hostep's fix solution works, thank you

**Comment by terolahtinen** [comment]
+1 also having the issue on 2.1

**Comment by danslo** [comment]
This is actually quite a significant issue for deployments, especially if you're doing continuous integration. Could we get an expected timeframe / version for e4a94c23e451e8e5f850d91b86fd1347ce05a2a0 to land?

**Comment by piotrekkaminski** [comment]
@danslo this will land in 2.2 but I will ask to include in a fix version as well.

**Comment by hostep** [comment]
@piotrekkaminski: no offense, but I don't understand Magento's release policy at all. There a couple of very very high priority bugs currently in version 2.1.0, including this bug. I think many people in the community were expecting a version 2.1.1 which would fix these high priority bugs and it would have been released in max 2 weeks after version 2.1.0 was released. Currently we are still waiting for that to happen, it's been over 5 weeks since version 2.1.0 was released.
And now you claim it will be introduced in version 2.2.0? God knows how long that will take until it is going to be released?
@pboisvert mentioned above this bug is tagged as P0 in your internal system, yet we have to wait weeks and weeks and it is still not released in a new version...

It would be great if you could shed some light on the roadmap about when we can expect certain versions to be released and if you are ever going to release hotfixes in patch versions, because currently this sucks....

I have a suspicion that most of the Magento folks are on holidays currently and that might be the reason for the delay, but really, just a couple of high priority bugs being released in a version 2.1.1 would help out tremendously and it wouldn't take that long to test those bugs I think.

I absolutely don't mean to offend you, but we as the community would like to have a little bit more knowledge about upcoming releases and maybe a rough estimation about when a new version will be released and what fixes we can expect in there.
Maybe you can start use the milestones feature in Github? (I realize you most likely also have something like that in your Jira system and this means you'll have to maintain it in two systems. But we can't see into your Jira system, so that's a bit frustrating for us to be in the dark about this).

Sorry to start this discussion in this issue, if you'd like, I can open a new issue about this.

**Comment by piotrekkaminski** [comment]
@hostep As you guessed right, 2.0.9/2.1.1 patch update is in the works. We expected publication this week but had to delay. This update will fix multiple priority issues reported here and through support.

**Comment by davidalger** [comment]
@piotrekkaminski Fixing this in 2.2 is an unacceptable timeline, and like @hostep said, understanding release policy ATM is just about futile. Everyone's been told to expect 2 yrs of support on 2.1 and 2.0, but here we have a critical bug blocking deployments on 2.1 since before it hit a "stable" release, and the fix is being deferred to a future feature release. That does not make sense, and certainly does not fit the purported goal of having a bi-weekly patch release cycle to fix bugs. 

We have multiple CE and EE builds which are stuck on 2.0.x because of this, and it was a regression from 2.0. I understand you have to prioritize engineering resources, but this is a critical bug which was missed during QA in the 2.1 release, and should be fixed in a 2.1.x bug-fix release ASAP, not silently delayed to a future feature release after telling everyone it was even raised to P0 internally.

It's been reported in the EE Support channel as well as here, and our developer was sent a .patch file by support to "fix" the issue (which doesn't work for builds as it did on v1 since v2 is now using composer to pull in external dependencies and core code). Consider me pretty frustrated!

Please re-consider the priority of this issue. We have multiple live 2.0 EE sites which would be running 2.1 today if this was fixed, and a number more in development which are stuck on 2.0 because of this.

**Comment by piotrekkaminski** [comment]
@davidalger got it. I will see what can be done. @elenleonova

**Comment by piotrekkaminski** [comment]
@davidalger @hostep I've double checked and it seems the fix for this issue is part of the upcoming patch release.

**Comment by Maikel-B** [comment]
I tried to apply the fix, but after I've run this module I can't run setup:upgrade.

cep@web [~/public_html/magento]# php bin/magento module:enable Vendor_TempSetupDiCompileFix
The following modules have been enabled:
- Vendor_TempSetupDiCompileFix

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them.

cep@web [~/public_html/magento]# php bin/magento setup:upgrade

  [InvalidArgumentException]
  There are no commands defined in the "setup" namespace.

**Comment by yokoishioka** [comment]
Thanks, toddwolaver! I went through applying the fix when all that was needed was for me to clear the /var/di folder using: rm -rf var/di/

**Comment by stevekem** [comment]
Any update on when 2.1.1 will be released?  Docs keep updating announcing the release and then back track. Really hoping soon to keep our project moving along.

**Comment by karl-ravn** [comment]
To clarify what yokoishioka was saying: You need to remove the var/di folder, not the contents inside of it.

**Comment by ttnnkkrr** [comment]
same

**Comment by rhiensch** [comment]
I've added the temporary fix from @hostep to my magento installation, but i think there is a other way to fix this problem. Simply disable en re-enable a (random) module for example:
php bin/magento module:disable Magento_Weee
php bin/magento module:enable Magento_Weee

**Comment by Laura021** [comment]
I had this issue.

Set developer mode, run upgrade command and it started working. However I haven't moved to a production status yet-

**Comment by stevekem** [comment]
@rhiensch Thanks, your solution worked for me!

**Comment by rhiensch** [comment]
@stevekem No problem, i've been searching for hours and i finally found that this is the best solution. Glad it helped you!

**Comment by amansilla** [comment]
@rhiensch thanks your workaround worked for me as well. :+1:

**Comment by tedxas** [comment]
Thanks, all, for the many solutions offered here. Simply "rm -rf var/di" worked for me as noted by @yokoishioka and @karl-ravn and elsewhere by @antbates1991 bug issue here: https://github.com/magento/magento2/issues/5954

**Comment by elenleonova** [comment]
Hi, the issue has been solved in 2.1.1, so closing the ticket. If you have some additional comments, please feel free to reopen if needed.

**Comment by hostep** [comment]
Tnx @elenleonova for releasing version 2.1.1 so swiftly (please ignore the sarcasm 😉 )

@ everyone who used my [temporary fix](https://github.com/magento/magento2/issues/4795#issuecomment-228610110):
If you upgrade to 2.1.1 it will give you an exception if you have my temporary fix enabled:

```
1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $routerList of Magento\Framework\App\RouterList.
```

So my advice to everyone who has been using my temporary fix is that **before** you upgrade to version 2.1.1, you do these things:

1) Remove the 3 files from my temp fix
2) Run `bin/magento setup:upgrade` to remove the entry from your `app/etc/config.php` file
3) Now upgrade to Magento version 2.1.1

**Comment by amansilla** [comment]
Thx @elenleonova, was the bugfix applied to the enterprise version as well?

**Comment by wasimgit** [comment]
I did the fix.
1. Removed the /var/di folder.
2. Deleted the module entry in database setup_module table by

SELECT *
FROM tst_setup_module
LIMIT 0 , 30

then, re run the magento cammand 

 sudo ./magento setup:upgrade

and it works for me.

**Comment by thdoan** [comment]
I'm getting a similar error when running `magento sampledata:deploy` on Magento 2.1.1:

```
 [Exception]
  Warning: file_get_contents(path/to/app/code/Vendor/SomeModule/composer.json): failed to open stream: No such file or directory in path/to/vendor/magento/module-sample-data/Model/Dependency.php on line 109
```

Did anybody ever find a workaround for this?

**Comment by danslo** [comment]
@thdoan That's not related to this issue, but I have encountered that as well.

That command expects a composer.json for your modules, even when it's just in your `app/code` directory. You can either create that file (with appropriate content), or temporarily disable the module (app/etc/config.php) and move the files out of the way, while you install sampledata.

**Comment by thdoan** [comment]
@danslo Yeah sorry about that, I eventually found the right [issue #](https://github.com/magento/magento2/issues/4636) but forgot to delete this comment.

**Comment by travisdetert** [comment]
It is UNBELIEVABLE how unstable these deployment and setup processes are.  I am curious how people are suppose to deploy any updates to this platform with any level of confidence.

**Comment by esakki08** [comment]
hi team,

![image](https://cloud.githubusercontent.com/assets/18530963/24664339/05ff9ef0-1978-11e7-9d93-3bc75d4ede30.png)

How to fix this issue? need step by step procedure

**Comment by Ctucker9233** [comment]
@esakki08 First, try running the commands from your root folder where you have magento installed. Is C:\xampp\htdocs\mtgo where you have magento installed?

**Comment by esakki08** [comment]
@Ctucker9233  yes "C:\xampp\htdocs\mtgo" is the my magento root folder.

**Comment by pantaoran** [comment]
@esakki08 this is not the right place for your question. Try the forums or StackExchange. This place here is for bug reports.

**Comment by parthatr** [comment]
@pantaoran: If you suggest the links, would be better. The application is keep on crashing....

**Comment by Ctucker9233** [comment]
@esakki08 Try running the commands using php56 or php70 depending on your php version.

**Comment by Nolwennig** [comment]
On my side, the module have been enabled with the  `--force` option 

`php bin/magento module:enable Module_Name -f`

**Comment by gilles6** [comment]
This worked for me in Magento 2.1.7 :
`bin/magento i18n:collect-phrases --output="app/design/frontend/VENDOR/THEME/i18n/zh_Hans_CN.csv" -m`

The -m means that Magento should parse all its files (without -m, only the specified directory is parsed).

**Comment by fezanqadirbhatti** [comment]
Simply replace the magento file in bin directory with the new one and run the following command on magento file if your host is linux:
 
sudo chmod u+x bin/magento 

Note: Before running bash command make sure your current working directory must be Magento 2.x root.

**Comment by Logimax** [comment]
My magento theme support magento 2.1.0 so i just update magento 2.1.6 to 2.1.0 then using upgrade command to upgrade and my php bin/magento setup:static-content:deploy command not working it shows some errors so I just clear pub/static and var folders then I run the upgrade it shows the error
![untitled](https://user-images.githubusercontent.com/29723079/27676047-19e72a56-5cca-11e7-94e4-77e619e1ba16.png)
error also in deploy command

**Comment by Anantkprajapati** [comment]
Please run below commands and check it like
rm -rf var/cache/* var/page_cache/* var/di/* var/generation/* var/view_preprocessed/*
php bin/magento setup:upgrade
I am sure it will work
