### ISSUE TITLE
Lot of translations not working

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5305]
## Steps to reproduce
1. Install Magento 2.0.7
2. Add Russian translation pack in `app/i18n/<vendor>/ru_ru/` which has all the files (`composer.json`, `language.xml`, `registration.php` and `ru_RU.csv`)
3. Configure several store views e.g. English and Russian and set corresponding locales for each.
## Expected result
1. Translations appear in all places
## Actual result
1. There are lot of places were translations do not show up - default English text is shown

See http://screencast.com/t/xI8C1E8RUxny for example - "My Account" is translated and it does show up correctly in most places except breadcrumb.

Here is the incomplete list of places where translations does not work:
- breadcrumbs => every page
- minicart
- cart => at least `Total`
- checkout#shipping => all of it
- checkout#payment => discount code block (even though it gets translated in cart) and order summary

**Comment by MindConflicts** [comment]
Same for me on develop branch (pl_PL)
Magento CLI version 2.2.0-dev

https://s32.postimg.org/pz2pplgg5/translations_bug.gif

**Comment by jsakars** [comment]
Turns out to get translations working You need to deploy static content all over. Otherwise translations in Knockout templates won't work.
With all that there are still translations that do not work:
- `Pleasespecify a shipping method`
- `Provided Zip/Postal Code seems to be invalid. Example: 1234. If you believe it is the right one you can ignore this notice.`
- http://screencast.com/t/J1jCsyTB2P checkout step titles `Shipping` and `Review & Payments`
- http://screencast.com/t/wnoLHyY0BT4 `Are you sure you would like to remove this item from the shopping cart?`

**Comment by hostep** [comment]
Informational: as an alternative for flushing the knockout templates cache, you can also remove the files in:
- var/view_preprocessed/...
- pub/static/frontend/...

It works a bit faster then doing the whole static deploy dance. Although you'll still have to sit and wait for a minute or so until everything gets regenerated when you refresh your page in the browser.

**Comment by jsakars** [comment]
@hostep I believe that does not apply for production environment though

**Comment by hostep** [comment]
Yes that's correct, only for local development mode. Sorry, I should have made that more clear.

**Comment by sevos1984** [comment]
Is this still actual?

**Comment by jsakars** [comment]
@sevos1984 haven't had time to check it on latest 2.0.\* version yet

**Comment by sevos1984** [comment]
This should be fixed in latest develop branch commit https://github.com/magento/magento2/commit/14028aad37ee7435d89eb3b647e6d03ecd8e2e13. Patch will be soon delivered into 2.0 branch.

**Comment by Ctucker9233** [comment]
@sevos is this commit safe to merge into a 2.1.1 production site, or is a patch planned? Thanks.

**Comment by sevos** [comment]
@sevos1984

**Comment by Michael89s** [comment]
Hello, my first post here.

This issue still occurs on 2.1.4. Any chances for a patch?

Thanks,
Michael

**Comment by vigoss-ru** [comment]
You can install language package follow the instructions in here : https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE

- Very important: remove first js-translation.json from pub/static/frontend/Magento/luma/de_DE/js-translation.json
- Then run command: 
php bin/magento setup:static-content:deploy de_DE
php bin/magento setup:upgrade

**Comment by pixiemediaweb** [comment]
We've noticed another issue with translations which have double spaces in the strings, for example;

"This is a line of text.  This is the next line","translated version of text.  Translated version of next line"

This works fine in developer mode, but in production strings with double spaces dont work.  Remove the double spaces from templates and the corresponding translation string in your csv.

**Comment by JMLucas96** [comment]
Same issue on backend in magento 2.1.8, any fix?

**Comment by sawwd** [comment]
> Same issue on backend in magento 2.1.8, any fix?

Some are stored in the local storage of the browser, lol. Clear your browser storage and these might work.
