### ISSUE TITLE
Error occur after upgraded to 2.1.0 CE from 2.0.4 CE

### ISSUE THREAD

**Issue by davidbilly** [magento/magento2#5426]
## Steps to reproduce
1. Install 2.0.4 CE
2. Upgrade to 2.1.0 CE by composer update
3. rm -rf var/cache/\* var/page_cache/\* var/generation/*
4. php bin/magento setup:upgrade
5. chown -R www-data:www-data .
6. find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento
## Expected result
1. Get stable 2.1.0 CE system
## Actual result
1. Front-end : after add cart , not showing update counter on top right
2. Reference : 
   <img width="1918" alt="screen shot 2016-07-03 at 3 19 01 pm" src="https://cloud.githubusercontent.com/assets/3938103/16544265/b606c2bc-4131-11e6-8400-ea61dfb6c102.png">

2) Back-end : Go invoice show Notice: Undefined index: base_grand_total in /vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php on line 55
3) Back-end : Go product > catelog > Filter bar missing
4) Back-end : Go product > catelog >  Cant access/edit product details. 
- Reference : 
  <img width="1915" alt="screen shot 2016-07-03 at 5 24 43 am" src="https://cloud.githubusercontent.com/assets/3938103/16544259/654cb9ee-4131-11e6-8b6a-579769d44cb6.png">

<img width="631" alt="screen shot 2016-07-03 at 3 23 05 pm" src="https://cloud.githubusercontent.com/assets/3938103/16544273/1890f70e-4132-11e6-8f54-c34cc7b75c97.png">

Please help. Thanks.

**Comment by andimov** [comment]
@davidbilly 
Did you clean all kind of cache from server and browsers?
If you have varnish you need to restart it to.

**Comment by southerncomputer** [comment]
yeah i'd wipe rm -rf var/view\* var/di va/rcache var/page_cache 
rm  -rf  pub/adminhtml  pub/_cache  pub/deployed_version.txt  pub/frontend  pub/_requirejs
then php bin/magento deploy:mode:set developer
then do php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

service php-fpm restart
service httpd restart
service varnish restart

clear browser cache and reload the page!

**Comment by davidbilly** [comment]
@andimov 
Hi Thanks for reply.  I dint install varnish cache on my server. 
I able to solve problem 3) and 4) 
Solution : 
Step 1 : Enable dev mode on cloudflare & clear cloudflare cache. 
Step 2 : clear Browser cache.

The problem 1) and 2) still occur. 

After above problem solved, i encounter another few problem.
On product detail page : 
- Product images that i uploaded are missing on edit product details. But i can saw them on front-end.

<img width="1912" alt="screen shot 2016-07-05 at 10 18 38 am" src="https://cloud.githubusercontent.com/assets/3938103/16572559/77767c88-429c-11e6-864c-82cac13578db.png">

<img width="1783" alt="screen shot 2016-07-05 at 10 19 11 am" src="https://cloud.githubusercontent.com/assets/3938103/16572560/777ac464-429c-11e6-80d3-d1e165cf8b29.png">

<img width="1915" alt="screen shot 2016-07-05 at 10 22 17 am" src="https://cloud.githubusercontent.com/assets/3938103/16572561/777ca892-429c-11e6-8b63-c9c08ffe846d.png">

**Comment by ComputerNorth** [comment]
I have the same error as you point out in problem 2, after upgrading from 2.0.6 CE to 2.1.0 CE:

Back-end : Sales --> Invoices shows Notice: Undefined index: base_grand_total in /vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php on line 55

**Comment by BigBri41** [comment]
I had the same issue with this in two separate environments and for us it was more than just an inconvenience.  A customer placed an order that was successfully charged to Paypal and the order never showed up in the magento backend.  So basically we have an orphaned order and magento keeps trying to get the IPN info from Paypal and erroring out because the order doesn't exist.  Here is what I had to do to fix the issue:

ALTER TABLE `magento`.`sales_invoice_grid` 
ADD COLUMN `base_grand_total` DECIMAL(12,4) NULL DEFAULT NULL AFTER `shipping_and_handling`;

Apparently this column isn't getting created with the upgrade and is what was causing the issue for us.  If your database name isn't magento, you'll have to change magento in the query above to whatever your database name is.  After doing this, orders are creating successfully.  Magento is still trying to get the information from Paypal for that orphaned order, but it isn't preventing any new orders from going through.  Hope this helps someone.

**Comment by ComputerNorth** [comment]
That is the solution, thank you!

**Comment by Tellfjord** [comment]
This helped me with the invoice problem. Thanks BigBri41

**Comment by davidbilly** [comment]
Thanks @BigBri41 This solve my 2) Back-end : Go invoice show Notice: Undefined index: base_grand_total in /vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php on line 55 
problem!

**Comment by davidbilly** [comment]
I faced another one issue : 
<img width="1393" alt="screen shot 2016-07-11 at 11 49 07 pm" src="https://cloud.githubusercontent.com/assets/3938103/16737135/846a66fe-47c2-11e6-8f51-7b2483b71129.png">

After i place order,the top right mini cart is show empty. But when i go to https://domain.com/checkout/cart/ i can see all of my order. 

<img width="1908" alt="screen shot 2016-07-27 at 9 08 32 pm" src="https://cloud.githubusercontent.com/assets/3938103/17176243/4f226608-543e-11e6-9107-e992c7fff70b.png">

Previous version(2.0.4), it will show notification and let user know how many order they placed.

Any solution for this?

**Comment by marvincaspar** [comment]
I have the same issue.

I would expect that the new field `base_grand_total` is added in an upgrade schema script and not in the install schema script.

**Comment by SchumacherFM** [comment]
We ran into the same issue. Pretty annoying.

Some one at Magento forgot to put that column base_grand_total into the Upgrade Schema script.

Do you guys run tests?

At least please fix it with the 2.1.1 release.

Edit: already in the [dev](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Setup/UpgradeSchema.php#L67) branch. Thanks guys!

**Comment by GordonLesti** [comment]
@davidbilly One of your problem `Attention Something went wrong.` is https://github.com/magento/magento2/issues/5323

**Comment by davidbilly** [comment]
@GordonLesti Thanks Mate! After enable Review Module the infinite loop loading for review gone. 
Refer : https://github.com/magento/magento2/issues/5426#issuecomment-230376103

Now i still have one serious issue, that after add item to cart on front-end, not updating the cart list/notification. It's blank :(
Refer : https://github.com/magento/magento2/issues/5426#issuecomment-231778311

Update : Mini cart empty issue fixed with #5003 & #5144

**Comment by BigBri41** [comment]
I think we were getting this error too.  If I remember right, it was some type of javascript error.  I used internet explorer to figure out where the problem was.  If you go to tools, internet options, then click on the advanced tab and uncheck Disable Script debugging (other) and uncheck Disable script Debugging (Internet Explorer), then refresh the page, it should pop up any javascript errors.  Can you give that a try and let us know what error you are getting if any please?

**Comment by shiftedreality** [comment]
Hi @davidalger 

I was not able to reproduce this on 2.0.9 -> 2.1.1 upgrade flow.

This bug was fixed in https://github.com/magento/magento2/commit/1d4873bf8457afa860e823dcbf1df17894cae318
And dev https://github.com/magento/magento2/commit/7f5b6443c8aad774bb3389fca9c4d372aaa3f1af

Please create new issue if you experience any other problems.

Closed.

**Comment by sdasun** [comment]
I had the same issue, for me **cloudflare magnification** is the one who get the blame. Hope this information help some one who will have the same issue as I did :)

**Comment by NimishPawar** [comment]
Thanks @BigBri41 :)

**Comment by ChameleonDevil** [comment]
> @bh-ref, thank you for your report.
> The issue is already fixed in develop branch, 2.2.0

The issue `Unexpected identifier` about the welcome message (and not escaped `'` characters are still present).  

I have installed a new **M2.3.5** installation where I have this same error - when trying to debug customer() at the knockout section of the header template at the welcome message it returns `{}` empty object.   

````
        <!-- ko ifnot: customer().fullname  -->
        <span class="not-logged-in"
              data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
````

I am not sure if $block->escapeHtml() is supposed to output `Welcome to X's site` or `Welcome to X\'s site`, and then Knockout undo the escape in a sense?  

https://github.com/magento/magento2/issues/5426

Issue 5003 claims issue was fixed - I don't think so.
https://github.com/magento/magento2/issues/5003

Difference here is that I do not have products in this database yet.  Can someone please point me to where customer() gets populated , I need to figure out why customer() is empty object at that point.

**Comment by ChameleonDevil** [comment]
Ok so this issue is related to how knockout seems to not correctly handle (') single quote characters in some theme templates.

If your template has this:


<span data-bind="html:'<?= $block->escapeHtml($welcomeMessage) ?>'"></>


Change to this:


<span data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></>


Notice I swapped the single quote and double quote positions such that the double quotes are inside, so that in effect does this: 

`' " ' " '`
Instead of: 
`" ' ' ' "`

I am positive **anywhere (other templates)** where knockout data-bind is used with PHP `escapeHtml()` or where quote characters are present will have this issue.
