### ISSUE TITLE
Can't find category id in category page.

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#5467]
I don't see category id in category page.

Do you have any idea?

**Comment by antboiko** [comment]
Hello @duongquyet , thanks for reporting this issue. Internal ticket MAGETWO-55120 has been created.

Best,
Anton.

**Comment by duongquyet** [comment]
Hi,
Hope you can update it soon.

Best regards,

David

**Comment by olysenko** [comment]
Issue was fixed and delivered into develop branch (see commit [14028aa](https://github.com/magento/magento2/commit/14028aad37ee7435d89eb3b647e6d03ecd8e2e13) )
Issue closed as fixed

**Comment by Ctucker9233** [comment]
@olysenko is this fix safe to merge into a 2.1.2 production environment or should I wait for a backport?

**Comment by olysenko** [comment]
I think it is better to wait for backport. Expectation is the last month of autamn

**Comment by SolsWebdesign** [comment]
Hi, I have 2.1.5 and the category ID seems to be missing in my adminhtml category pages as well. Has this been fixed and am I missing something? Or is this still a problem in 2.1.5?

**Comment by andidhouse** [comment]
I really do not know what sense it makes to report bugs here. This ticket is now 1! YEAR old in the newest Version of magento 2.1.7 this is still not fixed!

Pls do not get me wrong here but i really can not see a benefit of hundreds of hundreds bugs reported here over years and simply a handful is solved. Think about the time everybody spends here reporting bugs and what do you do with these bugs? "internal ticket xyz" merged back port. etc etc.

Not helpful at all and loosing community like this!
