### ISSUE TITLE
[2.1.0][2.1.2][2.1.3] Adding a Configurable Product with options to cart leads to "You need to choose options for your item."

### ISSUE THREAD

**Issue by Hawk30100** [magento/magento2#5882]
Adding a Configurable Product with options to cart leads to error message: "You need to choose options for your item.".
### Preconditions
1. Magento version CE 2.1.0 or CE 2.1.2
2. PHP 7.0.6
### Steps to reproduce
1. Create a Configurable Product
2. Add some products to Configurations
3. Create Options for the Configurable Product
4. Open Configurable Product in Browser
5. Choose Options and e.g. Color and click "Add to Cart"-Button
6. Error message will appear
### Expected result
1. The article should have been added to the cart
### Actual result
1. A message with "You need to choose options for your item." is displayed.

This problem does not affect the Simple Product with options.

**Comment by oserediuk** [comment]
Hello! Looks like you created product with required options. Could you check it? If yes, this is correct system behavior

**Comment by Hawk30100** [comment]
Yes, we did create a product with required options.

If I try to add the product to cart without choosing an option i will get the message "This is a required field." for every option that was not set.

If I choose a entry for all required options and click on "Add to Cart" I will get the message "You need to choose options for your item.".
I did choose options for this item... all required options have been chosen.

**Comment by Hawk30100** [comment]
Just changed the title and the problem description. I found out that my problem only happens with configurable products with options.

**Comment by AVoskoboinikov** [comment]
Hi

Thank you for your request, but unfortunately I can't reproduce this issue. I have CE 2.1.0 and one configurable product with required and non required options (please, look at it on Pic 1) and there is no error like "You need to choose options for your item.". 

Probably, issue is in details, so could you help me reproduce it and provide more detailed steps what you are doing to get such error? It would be great if you can provide screenshots with product configurations.

Thanks!

Pic 1
![pic1](https://cloud.githubusercontent.com/assets/17980272/17776254/5ce328e0-6564-11e6-9d06-04c73433edf7.png)

**Comment by epadmin** [comment]
I have this issue also.  Let me try to describe it better.  On a CATEGORY page, products with configurable options are displayed with an ADD TO CART button along with the available options.  See http://foxtrotboutique.com/brands-we-love/level-99.html
You should be able to select your option and then hit add to cart, and the item goes into your cart.  Instead, what is happening is if you select the option and hit ADD TO CART it takes you to the PRODUCT page with a notification at the top of the page that states "You need to choose options for your item"  

I believe this worked correctly in CE2.0.1 but cannot confirm.  This is a seperate issue form the out of stock options beaing able to be selected (which there is a thread on) but related because you cannot tell which options are in stock on the category page prior to hitting the add to cart button.  You get the notification regardless of whether or not the option you choose is in stock.  Try it on my page to see the behavior for yourself.  Select Size 27 on one of the items and then hit the add to cart button.

**Comment by Hawk30100** [comment]
I will try to setup a test system in the next few days and give you some more information.

**Comment by AVoskoboinikov** [comment]
@epadmin, thanks for help, we already have internal ticket for issue which you have described. But as I understand it is not the same as @Hawk30100 's issue. 
@Hawk30100, I will appreciate for your effort, thanks.

**Comment by to8gal** [comment]
Yes I do have this issue too, but some users here describe it as generated in the Category page, but to me is also generated in the product view page, I also wanna add I´ve noticed a reference to Percentage prices in the back end under the customazible options menu as warning, that I don´t really understand cause all my product have no options, just configurable with children

**Comment by AVoskoboinikov** [comment]
Hi @to8gal 
Could you please create separate ticket for your problem with percentage prices? It is only for non mixing different stuff in one ticket. Thank you. But it seams to me that message "Custom options with price type "percent" is not available for configurable product." is just informative and it does not mean that you have any errors.

**Comment by to8gal** [comment]
It is cause i do not have any price setting as anything but fixed

Sent from my phone

Luca Cagnassi
Media Designer at 5preview AB

(+46) 722111977

Luca Cagnassi is also: www.to8gal.com

“Think Green – Please do not print this email or any printable file attached unless you really need to“

**Comment by AVoskoboinikov** [comment]
Hi @to8gal,
Please, could you create separate ticket If you have any issues with that price settings? It would help you and us. 

Thanks!

**Comment by to8gal** [comment]
What I meant before is I don´t really care to open a ticket on that even if incorrect, the only reason I mention that, is cause I think is related to the main problem I have, othe than that is nothing to open a ticket for me

shall I modify the ticket already open?

Thanks

L

**Comment by AVoskoboinikov** [comment]
@to8gal, no need for that, thanks.

**Comment by epadmin** [comment]
@AzVo @to8gal 
I think I know the source of the Product Page issue.     

I have found that on the PRODUCT page you get an error that says you must choose an option if you try to add an item to the cart where that OPTION is out of stock.  The error is saying you must choose an option but should say "The option you have chosen is out of stock"   

This is related to the out of stock options not being marked out.   If they were marked out like they are supposed to be then there would be no need for an error that says "the option you have chosen is out of stock"

By fixing the issue with out of stock items not being marked out and unselectable, the issue on the PRODUCT page will be fixed.  It will also help with the issue on the CATEGORY page but as I tested the CATEGORY page the behavior is the same regardless of if the product is in stock or not - it is going to the product page with the "you must select an option" message instead of just adding to the cart

**Comment by to8gal** [comment]
I will give it a try

**Comment by AVoskoboinikov** [comment]
Hi @epadmin.

Thanks for help with that. I've created internal ticket to fix this.
@Hawk30100 can you submit that this is your case too?

**Comment by Hawk30100** [comment]
I just installed a fresh Magento 2.1.1 on our development environment and it seems like the problem was solved in 2.1.1.

**Comment by Hawk30100** [comment]
I just cloned our productive 2.0.8 system in order to update it to 2.1.2 and the problem is back.

If I want to add a configurable product (color) to the bag, the page gets reloaded and the message: "You need to choose options for your item."   is displayed.

I updated the magento version using composer. In addition we are using the Porto theme 2.4.0.1 for Magento.

**Comment by KooTjoo** [comment]
Same here, I have upgraded to 2.1.2 and the add to cart issue is there when using configurable products.

**Comment by rganin** [comment]
Fixed under MAGETWO-47017 ticket.

**Comment by Ctucker9233** [comment]
@rganin Is this fix going to be released in a patch or as part of 2.1.3? I tried manually applying the fix, but it broke a lot of things.

**Comment by sneakingJ** [comment]
@rganin Could you please give us feedback in which future version this will be officially fixed?

**Comment by Hawk30100** [comment]
We updated now from 2.0.8 to 2.1.3 but still get the message "You need to choose options for your item.".
This problem exists for existing configurable products (existing before update) and new products (created after the update).

**Comment by PieterCappelle** [comment]
Any update on this? In which version will this be fixed?

**Comment by SilvanLaroo** [comment]
We also face this issue on Magento 2.1.3. 

From the category page we select the required option and click the 'add to cart' button. After this we're redirected to the product with the message 'You need to choose options for your item.'. If i select the same option from the product page and then add it to my cart it works just fine. We do not face this issue on every category page, for same categories it does work.

**Comment by helicops** [comment]
I have also this error message, has anyone a solution for this problem?

**Comment by mitcht** [comment]
I am currently running 2.1.4 and running into this bug.  

To replicate:
1) Create configurable product
2) Go to catalog, and click "Add To Cart"
3) Magento should redirect to the product view page, asking you to make a choice.
4) Upon making a choice, it will reload the page, showing the item in the cart, as well as a message to make a selection, and a message it has been added to the cart. It will clear the selection as well.


This is a little funny... On the onepage checkout success.... It says "You need to choose options".....

After checking out!



EDIT: After this, the message keep appearing on every page I navigate to.

I've cleaned the /var/www/var directory, the pub/static, magento cache:clean, reindexed. EVERYTHING.

**Comment by helicops** [comment]
I upgrade to version 2.1.4. and this bug is not solved. I have exact the same error as mitcht described.

**Comment by mitcht** [comment]
This issue was closed, so there is no telling if it will get any attention now.

**Comment by richardmlaws** [comment]
Does anyone know if there is a solution for this? I have the issue with 2.1.3 - Someone says the issue is still in 2.1.4? Was this closed because there is a fix?

**Comment by benhath** [comment]
2.1.4 and 2.1.3 same problem. Running MAMP. Issue only occurs when a file is uploaded as an option.
