### ISSUE TITLE
[2.1] "none" is not meant to be translated?

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5886]
If one translates the word "none" to anything else, the product page attribute titles are printed although they should be hidden, because of the following line of code: `<?php if ($_attributeLabel != 'none'): ?>`.

https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/view/frontend/templates/product/view/attribute.phtml#L37
### Preconditions
1. Magento 2.1
### Steps to reproduce
1. Translate the word "none" to anything else
### Expected result
1. Product attribute title should not be visible
### Actual result
1. Product attribute title is visible and shows the translated version of "none"

**Comment by paales** [comment]
👍  Experienced this as well

**Comment by azanelli** [comment]
We had the same issue.

Should be removed `translate="true"` in:

```
<argument name="at_label" translate="true" xsi:type="string">none</argument>
```

from this layout file: `app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml`.

---

As temporary solution we can extend `catalog_product_view.xml` and add this:

```
<referenceBlock name="product.info.overview">
  <arguments>
    <argument name="at_label" xsi:type="string">none</argument>
  </arguments>
</referenceBlock>
```

**Comment by vrann** [comment]
@rasmuswikman issue is fixed in the latest develop

**Comment by Ctucker9233** [comment]
@vrann Are the commit references?

**Comment by vrann** [comment]
@Ctucker9233 this is the PR https://github.com/magento/magento2/pull/6257

**Comment by mkor** [comment]
You seem to have forgotten to push this commit to the 2.1 branch.
Since the bug still occurs in Magento 2.1.7, can you push it there as well?

See https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml
and https://github.com/magento/magento2/blob/2.1.8-preview/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml

**Comment by ruudboon** [comment]
@vrann Seeing this in Magento 2.1.8 also. Can we reopen this issue to keep track?

**Comment by orlangur** [comment]
@ruudboon tracked as https://github.com/magento/magento2/issues/10738.
