### ISSUE TITLE
Product Custom Options get recreated on every save

### ISSUE THREAD

**Issue by mktudock** [magento/magento2#5931]
Possibly related to #5885
### Preconditions
1. Have Magento 2.1. (with PHP 7)
2. Install the sample data and create a new store view
3. Go to any (configurable) product and create a custom option as a dropdown with some options (for global)
### Steps to reproduce

1. Open the product again
2. Save
### Expected result
1. The custom option ID in the database should be the same as before
### Actual result
1. The custom option gets recreated with a new ID. Same for all other tables (titles, types etc.)

This is a very **critical** bug for us, since it prevents any customer from completing the checkout with certain payment methods and it propably leads to the issues in #5885.

**Comment by mktudock** [comment]
Also if anyone would have a temporary solution for us, even if it prevents custom options from being saved, I'd be very happy, this is urgent!

**Comment by mktudock** [comment]
The commit that caused this behaviour is
https://github.com/magento/magento2/commit/0f0063045b50e1dafa260b97a1a00bf9fa92e74b

**Comment by mktudock** [comment]
I also want to point out that this means that **all products in quotes with the custom options attached have their custom options removed on save, since it's no longer the same id**! That basically renders the product useless, since important custom options are missing in the final order.

**Comment by veloraven** [comment]
@mktudock thank you for your report.

We already have internal ticket for this issue: MAGETWO-56411 
Created for GitHub issue #5612 
I have linked it to this issue as well.

**Comment by philipvandebriel** [comment]
I have same problem.

**Comment by vincentwinkel** [comment]
I discovered this behaviour several months ago but I thought it was normal.
So, same problem too, and it's very critical...

**Comment by manfrinm** [comment]
@veloraven Do you have any update on this?

**Comment by JosephWein** [comment]
@veloraven The issue(s) with custom options are stopping our migration to M2 in its tracks. When will they be assigned?  Thanks

**Comment by tomasinchoo** [comment]
Does anyone @Magento knows how urgent this situation is?

**Comment by Choufourax** [comment]
The bug still here in version 2.1.3.
So disappointing...........

**Comment by kaushalsutharhs** [comment]
Does anyone have any temporary fix to resolve this issue?

**Comment by manfrinm** [comment]
Hello, I've created this patch [CustomOptions Patch](https://github.com/Hevelop/magento2-patches/blob/master/Patch-Magento_Catalog-M2.1.5-MAGETWO-56410-MAGETWO-56411-github-issues-5931-5612.patch) that solve this issue and the Cart option missing issue [#5612](https://github.com/magento/magento2/issues/5612)
The patch can be applied on CE 2.1.5 or 2.1.4 and on EE 2.1.5 or 2.1.4 but I've tested this patch only for Magento EE 2.1.5.
Hopes is helpful

**Comment by kaushalsutharhs** [comment]
@manfrinm  : Hi I've tried patch -p0 < test.patch in terminal but it's asking for file path for each file in filepath, Can you please suggest me how can I apply your provided patch?

**Comment by kaushalsutharhs** [comment]
@manfrinm  : I'm getting error 

```
 Applying patches for magento/module-catalog
    https://raw.githubusercontent.com/Hevelop/magento2-patches/master/Patch-Magento_Catalog-M2.1.5-MAGETWO-56410-MAGETWO-56411-github-issues-5931-5612.patch (Fix: https://github.com/magento/magento2/issues/5612)
   Could not apply patch! Skipping.
```

**Comment by sheldmandu** [comment]
We are also experiencing this issue. In addition to shopping cart options it also affects Reorder functionality.  This is also a problem not just for custom options on simple products but also for bundle options, which should probably be raised as a separate issue.

**Comment by sheldmandu** [comment]
Is there any indication when this issue would be resolved?  This is quite a major issue for anyone looking to use Simple Products with Custom Options as it renders them practically unusable.

**Comment by Choufourax** [comment]
Yes this is crazy such an issue is not fixed after monthes.
I had to write a special .htaccess to forbid my client to edit some products in the backend........

**Comment by scottsb** [comment]
If it helps others, I have produced a [reduced version](https://github.com/ripenecommerce/magento2-patches/blob/master/Patch-Magento_Catalog-M2.1.5-MAGETWO-56410-MAGETWO-56411-github-issues-5931-5612.patch) of @manfrinm's patch, as the original included some good but unnecessary changes that were causing patch application errors.

**Comment by tomasinchoo** [comment]
@scottsb Thanks. @veloraven Is anybody at Magento aware how urgent this situation is? It looks like community is expected to handle it of its own..

**Comment by sheldmandu** [comment]
Hi @scottsb I tried the patch and it seems to have some issues when you delete an option value (that's not the last one).  What happens it also seems to delete option values from other options too.  Would be great if someone could fix.

**Comment by piavgh** [comment]
@magento-team, @veloraven  : I'm really appreciated that the fix is finally "moved from TODO to Done in branch [develop]"
When are you guys going to release this fix?
Thank you.

**Comment by Taral-Patoliya** [comment]
@magento-team , @veloraven : would you care to at-least prepare a patch and provide us as a quick fix until it is released officially with the newer version? this is something very critical and we can not move ahead with our project.

**Comment by Taral-Patoliya** [comment]
@manfrinm , @scottsb, i tried applying your patches the options are not being replaced now but in case we are using multiple custom options, if we remove one value form a custom options, all the values from other custom options are getting removed also.

**Comment by thlassche** [comment]
@sheldmandu / @Taral-Patoliya Did you manage to find a solution for the delete other options problem?

**Comment by sheldmandu** [comment]
@magento-engcom-team Is this issue fixed in 2.2?  It's marked as Done in develop.  It's the same underlying problem as that for bundles described in https://github.com/magento/magento2/issues/9546

**Comment by magento-engcom-team** [comment]
@mktudock, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by sheldmandu** [comment]
@magento-engcom-team Any chance of this being backported to 2.1 as it's quite a major issue that stops reorders working?  Perhaps you could point me to a commit in which this issue was resolved so I can review what would be involved in backporting myself?

**Comment by vekariyajyoti173** [comment]
hello,

I have facing same issue as https://github.com/magento/magento2/issues/5612.

Can you please help me how to resolve?

I have use magento 2.1.7.

I also apply patches given by you but it creates same option again and displays two times in frontend.

**Comment by vekariyajyoti173** [comment]
If Possible then give patches for it.......

**Comment by Ctucker9233** [comment]
@magento-engcom-team Can you please provide links to the commits that fix this?

**Comment by LiamKarlMitchell** [comment]
Still a problem in Rest API with 2.2.0
Even when including option_id and option_type_id that match the previous record.
