### ISSUE TITLE
If product is in saved quote when customer is logged in, if product is then disabled, triggers infinite database query loop in Magento/Quote/Model/Quote.php and a 503 error when customer logs back in

### ISSUE THREAD

**Issue by djfordz** [magento/magento2#6144]
### Preconditions

1. If customer adds product to cart, but does not checkout and logs out it is saved to database.
2. if product is then disabled using the single action method, the disable product slider(offline) 
3. when customer logs back in it will trigger an infinite loop on the database call to the quote specifically in function getAllVisibleItems() method which calls getItemsCollection().
   if logging $this->getData() it will show a constant stream of the same database info.
4. when logging the getData() method in  lib/internal/Magento/Framework/Model/AbstractExtensibleModel.php getData() it again will flood in an infinite loop.
5. Using the massAction method to disable by the Product list dropdown will not cause this, only using the disable product slider on the product page.
### Steps to reproduce

1. create customer account.
2. select product to add to cart
3. logout customer
4. administrator disable product in admin panel using single action method (slider on product page)
5. try logging into website with the customer that has the disabled product in their cart (saved quote)
### Expected result

1. customer should be able to log in and product removed from cart (quote)
### Actual result

1. [Screenshot, logs]
   503 error due to infinite database call
   ![screenshot from 2016-08-12 15-30-04](https://cloud.githubusercontent.com/assets/5413221/17636987/45a28b16-60a6-11e6-89cd-ebfdc38d6621.png)
   ![screenshot from 2016-08-12 13-59-35](https://cloud.githubusercontent.com/assets/5413221/17637016/67969a14-60a6-11e6-9561-6d7e9b7c772e.png)

CentOS6, Apache Server, PHP7.0, php-fpm, Magento 2.0.7, Mysql

**Comment by wert2all** [comment]
Thanks for reporting this issue. Please, provide the used Magento version too.

**Comment by djfordz** [comment]
Sorry Magento 2.0.7

**Comment by heldchen** [comment]
I have seen this multiple times as well - with xdebug installed you will get the `Maximum function nesting level of '100' reached, aborting!` message when this happens. 

initially discovered this issue when playing around with the reorder functionality - if you manipulate the reorder url and replace the order id with an order that has a disabled product, the quote for this customer will be broken and show the behaviour as @djfordz described. only remedy that reliable works is to delete the quote from the db. we went on to create a plugin for `$cart->addOrderItem()` that checks if a product is really still saleable before adding it to the cart. interestingly, that also seemed to help for the case mentioned by @djfordz in our case, at least I wasn't able to reproduce the broken behaviour anymore.

also, the issue #6388 seems related to this.

**Comment by AVoskoboinikov** [comment]
Hi @djfordz 
Thanks for reporting! I've tried to reproduce this issue on 2.1 version and it works fine. Could you upgrade your code from 2.0.7 to 2.1 and check if this issue still exists?

**Comment by heldchen** [comment]
@AzVo I have seen this issue in 2.1.0 as well but was not able to reproduce it reliably.

**Comment by djfordz** [comment]
will test with 2.1 now.

**Comment by djfordz** [comment]
Hello,

I have tested with Magento 2.1.1 on Arch Linux, Nginx 1.10.1, MariaDB 10.1.17 and you are correct @AzVo it doesn't seem to be an issue on Magento 2.1.1.  

Since I am testing with a different setup than the original ticket, I cannot verify 100% however, I am satisfied the issue is resolved in 2.1.1.

I will close this issue, thank you for looking into this.  I will ensure I have the customer upgrade to latest version of Magento before I send issues in.

**Comment by AVoskoboinikov** [comment]
Ok, anyway thanks for reporting! Feel free to create any new tickets if you will have questions.

**Comment by opencubicles** [comment]
We have tested this in Magento ver. 2.1.5 and issue is still there.

**Comment by binnykumar** [comment]
Hi i am also facing this issue.

V 2.1.5

Is there any fix in this version ?

**Comment by ghost** [comment]
hi, I am facing the same issue.
 Magento version 2.1.10

Is there any solution to this issue?

**Comment by primisuimotori** [comment]
I got this issue in Magento 2.2.2, any solution ?

**Comment by rak-dynamo** [comment]
I am also getting the same issue on 2.2.6

**Comment by alujane** [comment]
Also got this issue on Magento 2.2.6, Community Edition.
After checking, it looks like the problem is related to the indexing.

When products are updated via mass action, reindex is run.
Meanwhile, when we just edit the specific product, reindex might not be initialised right away, it happens either on save/change or via cron job, depending on environment settings.

So if customer has quote with disabled product and is interacting with the page during the time period when product is already disabled but reindex did not happen yet, there will be infinite loop.

Maybe this information will help somebody, who will also run into this issue.

**Comment by amelojunior** [comment]
I got this issue in Magento 2.3.2, any solution ?

**Comment by ganedda-softfobia** [comment]
Got this same issue in 2.3.3-p1 version

**Comment by LucScu** [comment]
reopened

**Comment by LucScu** [comment]
@magento-engcom-team after @alujane hint, I reopened the issue
> Also got this issue on Magento 2.2.6, Community Edition.
> After checking, it looks like the problem is related to the indexing.
> 
> When products are updated via mass action, reindex is run.
> Meanwhile, when we just edit the specific product, reindex might not be initialised right away, it happens either on save/change or via cron job, depending on environment settings.
> 
> So if customer has quote with disabled product and is interacting with the page during the time period when product is already disabled but reindex did not happen yet, there will be infinite loop.
> 
> Maybe this information will help somebody, who will also run into this issue.

**Comment by santerref** [comment]
> Got this same issue in 2.3.3-p1 version

Same issue for me. I am testing on 2.3.4.

**Comment by santerref** [comment]
Here is what I have found :

In `vendor/magento/module-quote/Model/Quote.php`, the method _afterLoad():

```php
/**
     * Trigger collect totals after loading, if required
     *
     * @return $this
     */
    protected function _afterLoad()
    {
        // collect totals and save me, if required
        if (1 == $this->getTriggerRecollect()) {
            $this->collectTotals()
                ->setTriggerRecollect(0)
                ->save();
        }
        return parent::_afterLoad();
    }
```

If trigger_recollect is 1 (true) and an extension calls getQuote() inside the collectTotals() process, the loop starts because it will never be 0 (since the quote is not saved yet).

This is also true for the `getTotalsCollectedFlag()` in `vendor/magento/module-quote/Model/Quote.php` in : 

```php
/**
     * Collect totals
     *
     * @return $this
     */
    public function collectTotals()
    {
        if ($this->getTotalsCollectedFlag()) {
            return $this;
        }

        $total = $this->totalsCollector->collect($this);
        $this->addData($total->getData());

        $this->setTotalsCollectedFlag(true);
        return $this;
    }
```

My temporary fix is to update the Session model in the checkout module to keep to reference to _quote. That way, _quote will exist after the first load and the reference will be kept.

The units tests are good.

This might not be the best solution:

```
diff --git a/Model/Session.php b/Model/Session.php
index 332ce08..522fbbc 100644
--- a/Model/Session.php
+++ b/Model/Session.php
@@ -228,21 +228,21 @@ class Session extends \Magento\Framework\Session\SessionManager
         $this->_eventManager->dispatch('custom_quote_process', ['checkout_session' => $this]);
 
         if ($this->_quote === null) {
-            $quote = $this->quoteFactory->create();
+            $this->_quote = $this->quoteFactory->create();
             if ($this->getQuoteId()) {
                 try {
                     if ($this->_loadInactive) {
-                        $quote = $this->quoteRepository->get($this->getQuoteId());
+                        $this->_quote = $this->quoteRepository->get($this->getQuoteId());
                     } else {
-                        $quote = $this->quoteRepository->getActive($this->getQuoteId());
+                        $this->_quote = $this->quoteRepository->getActive($this->getQuoteId());
                     }
 
                     $customerId = $this->_customer
                         ? $this->_customer->getId()
                         : $this->_customerSession->getCustomerId();
 
-                    if ($quote->getData('customer_id') && (int)$quote->getData('customer_id') !== (int)$customerId) {
-                        $quote = $this->quoteFactory->create();
+                    if ($this->_quote->getData('customer_id') && (int)$this->_quote->getData('customer_id') !== (int)$customerId) {
+                        $this->_quote = $this->quoteFactory->create();
                         $this->setQuoteId(null);
                     }
 
@@ -251,14 +251,14 @@ class Session extends \Magento\Framework\Session\SessionManager
                      * need recalculate totals of quote. It is possible if customer use currency switcher or
                      * store switcher.
                      */
-                    if ($quote->getQuoteCurrencyCode() != $this->_storeManager->getStore()->getCurrentCurrencyCode()) {
-                        $quote->setStore($this->_storeManager->getStore());
-                        $this->quoteRepository->save($quote->collectTotals());
+                    if ($this->_quote->getQuoteCurrencyCode() != $this->_storeManager->getStore()->getCurrentCurrencyCode()) {
+                        $this->_quote->setStore($this->_storeManager->getStore());
+                        $this->quoteRepository->save($this->_quote->collectTotals());
                         /*
                          * We mast to create new quote object, because collectTotals()
                          * can to create links with other objects.
                          */
-                        $quote = $this->quoteRepository->get($this->getQuoteId());
+                        $this->_quote = $this->quoteRepository->get($this->getQuoteId());
                     }
                 } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                     $this->setQuoteId(null);
@@ -271,25 +271,24 @@ class Session extends \Magento\Framework\Session\SessionManager
                         ? $this->_customer->getId()
                         : $this->_customerSession->getCustomerId();
                     try {
-                        $quote = $this->quoteRepository->getActiveForCustomer($customerId);
-                        $this->setQuoteId($quote->getId());
+                        $this->_quote = $this->quoteRepository->getActiveForCustomer($customerId);
+                        $this->setQuoteId($this->_quote->getId());
                     } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                         $this->logger->critical($e);
                     }
                 } else {
-                    $quote->setIsCheckoutCart(true);
-                    $this->_eventManager->dispatch('checkout_quote_init', ['quote' => $quote]);
+                    $this->_quote->setIsCheckoutCart(true);
+                    $this->_eventManager->dispatch('checkout_quote_init', ['quote' => $this->_quote]);
                 }
             }
 
             if ($this->_customer) {
-                $quote->setCustomer($this->_customer);
+                $this->_quote->setCustomer($this->_customer);
             } elseif ($this->_customerSession->isLoggedIn()) {
-                $quote->setCustomer($this->customerRepository->getById($this->_customerSession->getCustomerId()));
+                $this->_quote->setCustomer($this->customerRepository->getById($this->_customerSession->getCustomerId()));
             }
 
-            $quote->setStore($this->_storeManager->getStore());
-            $this->_quote = $quote;
+            $this->_quote->setStore($this->_storeManager->getStore());
         }
 
         if (!$this->isQuoteMasked() && !$this->_customerSession->isLoggedIn() && $this->getQuoteId()) {

```

**Comment by engcom-Oscar** [comment]
Hi @djfordz, I couldn't reproduce this issue on latest 2.4-develop version of Magento according your description.

### Steps to reproduce
1. create customer account on homepage
2. add product to the cart
3. logout customer
4. disable product in admin panel using single action method (slider on product page)
5. login back to the customer account on homepage - I have no errors

![image](https://user-images.githubusercontent.com/60198413/92385968-85d59700-f11b-11ea-899d-3b35b2b206b0.png)

Probably the issue was fixed by some other PRs. I'm closing this ticket now, if you will have any more info about it, feel free to reopen it with providing more information.

**Comment by Muhamann** [comment]
I have the same problem.

When customer has a product in cart, which gets disabled via admin, the login of the customer ends in a infinity loop / 503 error.
The same happens, if i search for the customer in admin customer-list, click inside the customers-details and just click on "save".

We had the problem with M 2.2, then upgraded to M 2.3.5-p1 and the issue still exists.

The only difference to a different M 2.3.5-p1 we are running is the module:
Best4Mage FCPM

Maybe someone can confirm this or maybe this informtion helps to get ahead?

**Comment by Sharmilasrini95** [comment]
Hello, according to your description, I was able to reproduce this issue on Magento 2.4.0.

Logged in as a customer Add a product to the cart Logged out Change any data of the added product from the admin end Do a reindex and cache clean Again try to login as a customer login It keeps loading and gets to 504 page

Expected Outcome: Account dashboard with expected data should be accessed.

**Comment by Muhamann** [comment]
> Hello, according to your description, I was able to reproduce this issue on Magento 2.4.0.
> 
> Logged in as a customer Add a product to the cart Logged out Change any data of the added product from the admin end Do a reindex and cache clean Again try to login as a customer login It keeps loading and gets to 504 page
> 
> Expected Outcome: Account dashboard with expected data should be accessed.

Same problem should occure, if customer tries a normal login with any access of pages, which include cart-data. => keeps loading and ends in error page.

**Comment by Muhamann** [comment]
Hello @engcom-Oscar 
could you please re-open this really important issue?
Please look at @Sharmilasrini95 Posts, she also could reproduce it.

Thank you

**Comment by jayankaghosh** [comment]
@magento-engcom-team Give me 2.0.7 instance

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.4.0 instance

**Comment by raghuiamsingh** [comment]
Any solution for this? I still have this issue with 2.3.2

**Comment by CUTTRHOAT69** [comment]
Got this issue on 2.3.3 and the best solution for now seems to be the double save patch, the quote will still make the collect totals and will not end up in a loop. I tried some other things, but most of the cases I ended up not making the collect totals on the quote. After doing the double save, I searched about it and found this issue with the same outcome that I have made...

Sad that Magento didn't provide what they modified that solved the problem, OR it's still not even solved.
