### ISSUE TITLE
Newsletter subscription not working on create customer account

### ISSUE THREAD

**Issue by Umfi** [magento/magento2#6183]
Some how i get an wrong email when register an customer account and check the "newsletter" checkbox.

![image](https://cloud.githubusercontent.com/assets/13978552/17697782/17f99f1a-63b7-11e6-80f4-0260e70ee92b.png)

But i got the wrong email - an wrong action is triggered.
I get an unsubscribe mail and when i check in customer area i am not subscribed to the newsletter.

![image](https://cloud.githubusercontent.com/assets/13978552/17697795/32683cee-63b7-11e6-90b2-ad3239e6577b.png)

I am on Magento 2.0.8 CE

**Comment by picamator** [comment]
@Umfi  thanks for reporting.
1. Could you please add more detailed steps to reproduce?
2. Could you please provide details how German localization was implemented?

**Comment by Umfi** [comment]
@andimov 

1) 
- Navigate to base-url/customer/account/create/
- Fill out everythin, check "Sign Up for Newsletter" and submit form

2)
- I added a language pack 
  https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE

FYI, i have a added some custom fields on this form but they work as expected, maybe this could be an error source?

EDIT: i have exactly the same configuration/problem as @stevecantlay

**Comment by stevecantlay** [comment]
We have a similar issue - Magento is set confirmation required with is_subscribed set to true on the registration form.

Upon registering the confirmation required email is sent.  When confirming registration the welcome email is sent - followed by the unsubscribe email.

**Comment by picamator** [comment]
@Umfi Thank you for details.

Unfortunately we can not reproduce this issue.
1. Could you please describe what customization do you have?
2. Do you have several store views? What localization they have?
3. Could you confirm that problem is reproduced on a clear Magento 2 installation with the German package?

**Comment by andypimlett** [comment]
1. Magento 2.0.8 Luma
2. Single store
3. en_GB

Also seen this on custom theme on 2.0.8. Account creation set to confirm, subscribe set to confirm. On account confirm - account creation confirmation arrives plus email unsubscribe. 

Also tried disabling subscribe confirmation and still get the unsubscribe following account creation confirmation.

**Comment by Umfi** [comment]
Magento 2.0.8 CE - LUMA 
Multistore - de_AT

I just added some EAV fields for customer attributes.

Config->Customer->Customer Configuration: Require Emails Confirmation=Yes

Config->Customer->Newsletter
![image](https://cloud.githubusercontent.com/assets/13978552/17805077/066f5656-65fe-11e6-9695-b65341fcd826.png)

**Comment by picamator** [comment]
@andypimlett , @Umfi , @stevecantlay 
Thank you very much for putting details. We have reproduced the problem and created our internal ticket MAGETWO-57222.

**Comment by unailopez16** [comment]
looks like fixed here: 
https://github.com/magento/magento2/commit/13e1acdcb0f859c948957c9c9f36a03131e96888#diff-8b13fe3225a8e5f17fa52fa6c5b74edaR34

**Comment by Ctucker9233** [comment]
@unailopez16 do you know if this fix is safe to integrate into a 2.1.1 production environment or is there a patch being created for it?

**Comment by pitangaweb** [comment]
Is there any news on that matter?
The fix linked by @unailopez16 looks risky to integrate, it looks like many files are involved.

**Comment by unailopez16** [comment]
The issue is solved in Magento 2.1.2 version. 

You can upgrade you Magento version @pitangaweb

**Comment by pitangaweb** [comment]
No, the issue is not solved with Magento 2.1.2
I'm still experiencing it on Magento 2.1.2 when customer account confirmation is required.

**Comment by pyyick** [comment]
Does 2.1.3 solved?

**Comment by eldonbite** [comment]
Upgraded one of our projects to 2.1.3 and I can confirm that subscription email notifications are still not being sent when ticking the "Subscribe to Newsletter" checkbox upon registration.

**Comment by webspeaks** [comment]
Any update on this? How to fix?

**Comment by anarchalienweb** [comment]
Can we get an update on this?

**Comment by anarchalienweb** [comment]
My workaround: http://pastebin.com/8nnA6AvV

**Comment by eldonbite** [comment]
Hi @anarchalienweb. What Magento version are you using? I tried to apply your workaround to a 2.1.3 website, but I'm still just getting the welcome email and no newsletter subscription email after registering with the "Subscribe" checkbox ticked.

Here's the DIFF file/patch I created based on your workaround (added .txt for it to be attached here).

[GIT-6183.diff.txt](https://github.com/magento/magento2/files/697747/GIT-6183.diff.txt)

**Comment by willfrombrazil** [comment]
Hi, I've managed to reproduce this issue:

1) The option **Require Emails Confirmation** (sic, should be Required Email Confirmation) is set to **Yes** on /admin/admin/system_config/edit/section/customer/

2) Customer creates a new account on customer/account/create/, checking the **subscribe to newsletter** option

3) Before the customer confirms his email address, the newsletter **Status** is **Unconfirmed** on admin/newsletter/subscriber/index/

4) After the customer confirms the email address, the newsletter **Status** is **Usubscribed** on admin/newsletter/subscriber/index/

Also, the **Requires Emails Confirmation** option on **Customer Configuration** overwrites the **Need to Confirm** option on **Newsletter**. They should be independent.

**Comment by cherreman** [comment]
We are experiencing this issue on 2.1.6. Any update on this?

**Comment by SchumacherFM** [comment]
Please switch to 2.2 because 2.1 gets only security updates.

**Comment by korostii** [comment]
Hi @SchumacherFM,
> Please switch to 2.2 because 2.1 gets only security updates.

Is that the official stance of Magento, Inc.? Do you have a reference for it?
(Asking because I've heard somewhat different responses towards 2.1.x updates previously, not sure what to believe now)

BTW, 2.2 isn't production-ready neither - is that correct?

**Comment by roman-snitko-vaimo** [comment]
Magento EE 2.1.6, customer confirmation is turned on.
When you check "Subscribe to newsletter" while creating customer account, it will send you "Newsletter unsubscription success" confirmation email.

**Comment by roman-snitko** [comment]
Magento EE 2.1.6, customer confirmation is turned on.
When you check "Subscribe to newsletter" while creating customer account, it will send you "Newsletter unsubscription success" confirmation email after you confirm your account.

**Comment by magento-engcom-team** [comment]
@Umfi, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by puneetk00** [comment]
@anarchalienweb thank bro its work for me.

**Comment by Reslinator** [comment]
Hi @anarchalienweb,

I checked the commits on  branch [2.3-develop], but could not find the changes to the files to get this fixed as a patch on an earlier version.

Could you guide me where you found it, or did you check it by testing the dev branch?

Thank you for your help.
Regards,
Andreas

BTW: I am looking for a way to get this issue fixed in a Magento 2.1.7 Community Edition...
