### ISSUE TITLE
Unable to override invoice, shipment and credit memo templates

### ISSUE THREAD

**Issue by devonto** [magento/magento2#6302]
**Preconditions**
1.  Magento 2.1
2.  Custom module created at `app/code/Vendor/Module`

**Steps to reproduce**
1.  Place override XML files at `app/code/Vendor/Module/view/frontend/layout/`
2.  Place override phtml files at `app/code/Vendor/Module/view/frontend/templates/`
3.  Resend email from admin - Sales->Invoices->[Specific invoice]->Send Email

**Expected result**
1.  Changes made within the phtml file are shown in the email

**Actual result**
1. Core Magento phtml file loaded and displayed

**Additional information**
I am trying to remove the SKU from the email notifications which are sent out.
By following the above steps, this **works** for initial order emails, but not for invoice, shipment or credit memo emails.

Specifically, I have the files below - which **work** for order emails:
**XML File**
`app/code/Vendor/Module/view/frontend/layout/sales_email_order_renderers.xml`
**Contents**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.renderers">
            <block class="Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder" as="default" template="email/items/order/default.phtml"/>
        </referenceBlock>
    </body>
</page>
```

**PHTML File**
`app/code/Vendor/Module/view/frontend/template/email/items/order/default.phtml`
**Contents**

``` <?php
/**
 * ALL THE SAME IN THIS FILE EXCEPT REMOVING THE SKU FROM LINE  19
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
```

Similarly, I have the files below for an invoice email, which **does not work**:
**XML File**
`app/code/Vendor/Module/view/frontend/layout/sales_email_order_invoice_renderers.xml`
**Contents**

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.invoice.renderers">
            <block class="Magento\Sales\Block\Order\Email\Items\DefaultItems" as="default" template="email/items/invoice/default.phtml"/>
        </referenceBlock>
    </body>
</page>
```

**PHTML File**
`app/code/Vendor/Module/view/frontend/template/email/items/shipment/default.phtml`
**Contents**

``` <?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem() ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd>
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
</tr>
```

**Comment by mikebox** [comment]
I am also facing the same problem for past few days. I guess this is because of load order of configuration files. Hope there will be a solution.

**Comment by devonto** [comment]
I have also tried to use the `<sequence>` tag in `module.xml` to have it load after `Magento_Sales`, but no joy.

**Comment by mikebox** [comment]
Up to my observation, because of loading after Magento_Sales, it is not working. I tried to move before Magento_Sales(just for checking), working fine but it affects other things.

**Comment by R4c00n** [comment]
Is there anything new on this?
I can still observe this bug and the hotfix (not really) with changing the loading order.

**Comment by shruti-ranium** [comment]
app/code/Vendor/Module/view/frontend/layout/sales_email_order_renderers.xml

<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.renderers">
            <block class="Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder" as="default" **template="Vendor_Module::email/items/order/default.phtml"/>**
        </referenceBlock>
    </body>
</page>
Above highlighted code should work.

**Comment by amanuni** [comment]
Hi,

Have issue like that but its resolved for me changes are taking effect in mail but getting a exception here is my code.

`app/code/Vendor/Module/view/frontend/layout/sales_email_order_renderers.xml`

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.renderers">
            <block class="Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder" as="default" template="Vendor_Module::email/items/order/default.phtml"/>
        </referenceBlock>
    </body>
</page>
```

Here is my exception :

> exception 'Magento\Framework\Exception\LocalizedException' with message 'The element 'sales.email.order.renderers' already has a child with alias 'default'' in /home/amanwebi/public_html/magento21/vendor/magento/framework/Data/Structure.php:611

**Comment by amanuni** [comment]
Hi,

Have issue like that but its resolved for me changes are taking effect in mail but getting a exception here is my code.

`app/code/Vendor/Module/view/frontend/layout/sales_email_order_renderers.xml`

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.renderers">
            <block class="Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder" as="default" template="Vendor_Module::email/items/order/default.phtml"/>
        </referenceBlock>
    </body>
</page>
```

Here is my exception :

> exception 'Magento\Framework\Exception\LocalizedException' with message 'The element 'sales.email.order.renderers' already has a child with alias 'default'' in /home/amanwebi/public_html/magento21/vendor/magento/framework/Data/Structure.php:611

**Comment by magento-engcom-team** [comment]
@devonto, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0, 2.1.12

**Comment by parekhreena** [comment]
For those facing this issue, Just for your knowledge the issue happens in previous magento versions because of following line in core code: 
**File:** vendor/magento/module-sales/view/frontend/layout/sales_email_order_invoice_items.xml
**Line:** `<block class="Magento\Sales\Block\Order\Email\Invoice\Items" name="items" template="email/invoice/items.phtml">`

The template value here should have been `Magento_Sales::email/invoice/items.phtml`

Solution For Magento versions other then 2.2.3, 2.3.0, 2.1.12 where this core bug fix is still not available, following can be done:

```
<type name="Magento\Sales\Block\Order\Email\Invoice\Items">
    <plugin name="vendor_module_sales_order_email_invoice_item" type="Vendor\Module\Plugin\Block\Sales\Order\Email\Invoice\Items" />
</type>

namespace Vendor\Module\Plugin\Block\Sales\Order\Email\Invoice;
class Items
{
    public function beforeToHtml(
        \Magento\Sales\Block\Order\Email\Invoice\Items $subject
    ) {
        if ($subject->getTemplate() === 'email/invoice/items.phtml') {
            $subject->setTemplate('Vendor_Module:email/invoice/items.phtml');
        }
    }
}
```
Note that the magento team has already fixed this issue in later versions in the core code. The above fix is for older versions only where the issue still exists.

**Comment by korostii** [comment]
Hi @magento-engcom-team,

As far as I can see, there's a number of commits and corresponding PRs fixing this issue, most notably 2e70f00 (for `2.3.x` branch) and 118c86c (backport for `2.2.x` branch)

However, the `2.1.x` branch does NOT seem to contain this fix as of latest (2.1.14) patch version.
Please the below file to see that the file discussed above still doesn't contain a name attribute:
https://github.com/magento/magento2/blob/2.1.14/app/code/Magento/Bundle/view/frontend/layout/sales_email_order_shipment_renderers.xml

Could you please correct the issue labels (and possibly comments) in order to show that this issue is **not**, in fact, fixed in 2.1.x?
