### ISSUE TITLE
Uploaded custom option file/images not download from order screen

### ISSUE THREAD

**Issue by magentodevleper** [magento/magento2#6558]
### Preconditions

1. Magento 2.1.0 
### Steps to reproduce

1. Create configurable product (Ex : Test product) with custom option file
2. Front-end : Order this item with upload any image
3. Open recently place order from backend (Ex - Order No : 0001)
4. Download uploaded image from order screen - It is working fine.
5. Update configurable product (Test product).
6. Reopen order (Order No : 0001) and download image. It will show 404 page.
### Expected result

1. We want to download images from order screen after updating products.
### Actual result

1. After updating product, Uploaded Image/File is not download. It will show 404 page.

Could you please help me on this. How to resolve this issue?

**Comment by miakusha** [comment]
Hi @magentodevleper thank for report

We've created internal ticket MAGETWO-59345 to address this issue.

**Comment by paales** [comment]
Custom options seem to be recreated on every save or something (ImportExport does this anyways), causing the error.. Ideas how to fix this?

**Comment by paales** [comment]
In `Magento\Sales\Controller\Download\DownloadCustomOption::execute` comment out the following code:

```PHP
if ($optionId) {
    /** @var $productOption \Magento\Catalog\Model\Product\Option */
    $productOption = $this->_objectManager->create('Magento\Catalog\Model\Product\Option')->load($optionId);
}

if (!$productOption || !$productOption->getId() || $productOption->getType() != 'file') {
    return $resultForward->forward('noroute');
}
```

**Comment by pini-girit** [comment]
Hi,
I have a similar issue.
I already tried @paales suggestion (overrided by module) but it didn't solve the problem.
I kept exploring & noticed that the execute() method on the DownloadCustomOption controller returns $resultForward->forward('noroute') on line 34, after failing to load the quote item option by id.
I checked on the database & found out that the row on `sales_order_item` exists but the row on `quote_item_option`  is indeed missing.
Another thing I checked was the serialized data on `sales_order_item`.`product_options`, there I saw the path of the quote item option file & the path of the order item option file. the first one exists, the second one doesn't.

So... 
-- Any idea?

**Comment by pini-girit** [comment]
Update:
I managed to solve it  (for my case at least).
You may copy this module if it works for you:
https://github.com/GiritInteractive/Girit_FixCustomOptionFileDownloadOnAdmin

**Comment by magento-engcom-team** [comment]
@magentodevleper, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by uandiweb** [comment]
I've this issue in version 2.2.5. Paales solution does work, but I wish this issue could be fixed permanently.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Please point out where in 2.2 this fix is present? It seems to still be an issue for some.

**Comment by dverkade** [comment]
I'm reopening this issue again, because this is still present in 2.2.X and 2.3.0 according to my research in ticket https://github.com/magento/magento2/issues/20277, so this issue was closed while it was not resolved.

**Comment by ghost** [comment]
@dverkade I'm closing this one, as  duplicate  to this one -> https://github.com/magento/magento2/issues/20277

**Comment by ChintanKaneriya** [comment]
Is this issue fixed yet?

I have tried the solution which was given by @paales but still, I am getting 404 while trying to download the image.
