### ISSUE TITLE
Cannot add product to the shopping cart (after deleting of selected address on the checkout) 

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6574]
### Preconditions

Magento 2.1.1 with sample data
### Steps to reproduce
1. Log in and add new address
2. Add any product to the shopping cart
3. Go to the checkout page and select created address as shipping (do not place an order)
4. Go to my account and delete created shipping address 
5. Try to add any product to the shipping cart
### Expected result
1. A product is added to the shopping cart
### Actual result
1. Product is not added to the shopping cart and error message is shown
   <img width="1299" alt="screen shot 2016-09-11 at 20 19 41" src="https://cloud.githubusercontent.com/assets/6418650/18419136/1cea743a-785d-11e6-88a4-99674fa10af7.png">

**Comment by JDavidVR** [comment]
I followed steps you mention, and seems like it is fixed on develop branch (right now it is 2.2.0-dev), I think this will be released as a 2.1.x patch.

**Comment by ytorbyk** [comment]
Hm, it's interesting. I still can replicate the issue even on develop branch (2.2.0-dev)

**Comment by sevos1984** [comment]
Not reproduced for me as well, try clearing your browser caches

**Comment by ytorbyk** [comment]
I just retested it locally on develop branch. The bug is still replicable.
Are you sure you go to the last step on checkout page (step 3)?
And are you sure you delete the same address which is chosen during checkout?

I cannot add new product to the shopping cart and even cannot delete a product from the shopping cart.

**Comment by RomanKrut** [comment]
Internal ticket was created for this issue - MAGETWO-69936

**Comment by magento-engcom-team** [comment]
@ytorbyk, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
