### ISSUE TITLE
System -> Web setup wizard missing

### ISSUE THREAD

**Issue by Malansocosio** [magento/magento2#6655]
I need to access the component manager in my fresh Magento 2.1.1 installation, but the web setup wizart link is not present under the System catergory in the backend. Is there an alternative way to get to the component manager? I have tried just adding /setup to my url, but that doesn't work. Any other suggestions?

_My magento environment:_
- Arch Linux
- Magento 2.1.1 CE
- PHP 7.0.11-1
- 10.1.17-MariaDB (SQL server)
- Nginx 1.10.1-1

Many thanks in advance.

**Comment by commcad** [comment]
In your NGINX site enabled cfg, change:

**root $MAGE_ROOT/pub;**
for
**root $MAGE_ROOT/**

ps: don't forget to put it back on /pub when you've finished with Web Wizzard ;)

**Comment by Malansocosio** [comment]
Thanks a lot for your quick response, it worked perfectly.

**Comment by stamster** [comment]
This is front-end only bug.

If you access it with 'hidden' redirect, it works, you don't need to reconfigure your web root (plain wrong thing to do, and still official Magento devs suggests it!):

https://github.com/magento/magento2/issues/4159#issuecomment-244483087

> Web Setup Wizard menu still missing, but when you type http://www.shop.com/admin_xxxx/admin/backendapp/redirect/app/setup/
> redirects tohttp://www.shop.com/setup/#/home and then all works as expected...

**Comment by commcad** [comment]
I have no idea what you worry about, but thanks for the shortcut/tip none the less ;)
1. You'd need to know the shop's admin_xxxx
2. For the redirect to function, you need to be logged in (does work!)
3. More importantly; Web Wizard have never really worked anyway.

With that said, who cares then lolll

![fixwebsetup](https://cloud.githubusercontent.com/assets/19387951/18681021/b9bafe1e-7f98-11e6-8552-cf486bd6ec9e.jpg)

@stamster

**Comment by stamster** [comment]
@commcad one topic is if you cannot even access it, while whole another is whenever it works as expected. We're talking here about just accessing it.

**Comment by ghost** [comment]
cannot setup magento 2.1.1, magento setup wizard getting blank screen

MacOS
MAMP
php 5.6
nginx

```
angular.js:7715 GET http://localhost:7888/Magento/setup/index.php/navigation 404 (Not Found)

angular.js:7715 GET http://localhost:7888/Magento/setup/index.php/navigation/side-menu 404 (Not Found)

angular.js:7715 GET http://localhost:7888/Magento/setup/index.php/navigation/header-bar 404 (Not Found)
```

**Comment by stamster** [comment]
Officially, only GNU/Linux is supported for Magento2. I would strongly advise you not to play with Windows or OSX here. For the start both are case insensitive.

**Comment by veloraven** [comment]
@Malansocosio , do I understand correctly that this issue is resolved and can be closed?

**Comment by veloraven** [comment]
@brody182 you should create separate issue for your problem formatting its description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). 
However I'm afraid that in your case it will be just closed as MacOS is not supported: [Magento technology stack requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html)

**Comment by ghost** [comment]
well that not true,  I can still install it on my local machine ( macOS ) if I have the right environment, apache or nginx, php ect.  The only problem i'm having is with nginx, it works fine on apache.  
must  be a misconfiguration or something

**Comment by timstoel** [comment]
@commcad Is this a good idea in production?  

I do not feel that this issue should be closed.  Changing the Nginx config to use it, and changing it back, is not a solution in a production environment.  I have also tried the URL workaround method and it does not work if you are using Varnish because it redirects to domain.com:8080/setup which gives a 404 because it is bypassing Varnish and 8080 is not open to the outside world.

**Comment by drpit** [comment]
Hello,

I have tried all the above recommendations but still cannot access Web Setup Wizard.
when I use 
http://www.shop.com/admin_xxxx/admin/backendapp/redirect/app/setup/
I get a half loaded page 
and a lot of error messages 

Access to the script '/var/www/html/mag/setup/index.php/session/prolong' has been denied (see security.limit_extensions)" while reading response header from upstream, client: xx.xx.xx.xx, server: _, request: "POST /setup/index.php/session/prolong HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.shop.com", referrer: "https://shop.com/setup/"

**Comment by ghost** [comment]
Hello,

This issue should not be flagged as closed. As this is not a fix:

In your NGINX site enabled cfg, change:

    root $MAGE_ROOT/pub;
    for
    root $MAGE_ROOT/

This issue happens on a fresh install and it more than likely has to do with the nginx.config.sample file and NGINX vhost. 

A valid permanent solution is welcome. 

Tested on Ubuntu 16.04 LTS LAMP using Magento 2.2.1 w/ NGINX 1.10.3

Using Magento's NGINX recommended configuration. 

Thanks!

A.I 

Blame it on the wizard for making it disappear ;-)

**Comment by RWCC-LTD** [comment]
Just to note that I have the same issue. The offical magento secutiy scanner tool reccomended we make the change from 

```
root $MAGE_ROOT;
TO
root $MAGE_ROOT/pub;
```
Upon doing this the security scanner passes but now the web wizard has dissapeared Our site is set in production mode.

**Comment by lucscu** [comment]
We need to know how to fix this ridiculous bug. Why with document root setted to /pub **Web Setup Wizard** disappear from menu and it is not reachable directly with url?

**Comment by RWCC-LTD** [comment]
@LucScu - I have since found a work around for the time being.

While i cant access it from the magento navigation if i create a symlink to the /setup directory from html/pub directory i can then access the web wizard through https://www.**WEBSITE**.com/setup  In order to do this you need to already be logged into an admin session in the same browser.

**Comment by lucscu** [comment]
@sjhill-rwcc Did you run in pub folder `ln -s /home/magento/htdocs/setup/ setup`?

**Comment by RWCC-LTD** [comment]
@LucScu  - my folder structure is slightly different but based on your folder structure you need to place your shortcut in /home/magento/htdocs/pub which should be called "setup" and route to /home/magento/htdocs/setup   

Does that make better sense? - basically you are allowing magento back access from the pub directory to the setup

.. if you are in the pub directory already then yes, your command will do the trick

**Comment by lucscu** [comment]
@sjhill-rwcc yes, i did it correctly, but this trick not works for me, thx for your hint.

**Comment by aliasifmse** [comment]
how about configuring nginx documentroot to serve without pub , if url contains setup ?
