### ISSUE TITLE
New product is hanging after adding 300.000 products and 40.000 categories

### ISSUE THREAD

**Issue by 12impress** [magento/magento2#6904]
### Preconditions

1. Magento 2.0
2. PHP 7.0.8
3. MySQL 5.6.30
### Steps to reproduce

1. While having a clean install adding a product bij backend works fine. Also after adding 15 products manually, everything is fine. After adding 40.000 categories and 300.000 products adding a new product manual is not possible, because it stays on loading. Maybe the amount of categies is the problem?
2. Tested in Firefox, Chrome, Edge and Safari
3. 
### Expected result

1. I thinks the Admin side does not use the Category index, but i'm not sure about that
### Actual result

1. [Screenshot, logs]
   [http://www.hifimax.eu/Screen.jpg](url)
   <img src="http://www.hifimax.eu/Screen.jpg" alt="Screen shot" style="width:304px;height:228px;">

**Comment by sevos1984** [comment]
This was fixed in develop branch https://github.com/magento/magento2/commit/bebb2ceb000b9296f9b04ecd5424ef66cd723fbf. Soon will be delivered to 2.0

**Comment by Ctucker9233** [comment]
@sevos1984 Is this only a 2.0 problem?

**Comment by 12impress** [comment]
No, We are now at 2.1.2 and have the same problems..... There is no solution untill now.

**Comment by romainruaud** [comment]
Hello @carfantasy .

I had similar issue : See https://github.com/magento/magento2/issues/7193

The patch provided by @sevos1984 solved my problem (you need to process the setup:static-content:deploy command), maybe you should give it a try.

**Comment by 12impress** [comment]
Hello @romainruaud .

I tryed this patch, but it didn't help me :-(

It looks like it is in the media or base image. But still don't know what the problem is..

**Comment by 12impress** [comment]
By debugging I see a big amount of product information. It looks like it is building some list of products (we have almost 450.000 of them in our database):

Here's the difficult part:

```
<span>Add Attribute</span>
</button>
    </div>
</div><div id="page:main-container" class="page-columns"><div class="admin__old"><div id="container" class="main-col"><!--
/**
 * Copyright &copy; 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
--><div>
    <div data-role="spinner" data-component="product_form.product_form" class="admin__form-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>
    <div data-bind="scope: 'product_form.product_form'" class="entry-edit form-inline">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
<script type="text/x-magento-init">{"*": {"Magento_Ui/js/core/app": {"types":{"dataSource":{"component":"Magento_Ui\/js\/form\/provider"},"select":{"extends":"product_form"},"form.select":{"extends":"select"},"checkbox":{"extends":"product_form"},"form.checkbox":{"extends":"checkbox"},"container":{"extends":"product_form"},"input":{"extends":"product_form"},"form.input":{"extends":"input"},"fieldset":{"component":"Magento_Ui\/js\/form\/components\/fieldset","extends":"product_form"},"date":{"extends":"product_form"},"form.date":{"extends":"date"},"wysiwyg":{"extends":"product_form"},"form.wysiwyg":{"extends":"wysiwyg"},"textarea":{"extends":"product_form"},"form.textarea":{"extends":"textarea"},"media":{"extends":"product_form"},"actionDelete":{"extends":"product_form"},"text":{"component":"Magento_Ui\/js\/form\/element\/text","extends":"product_form"},"product_form":{"component":"Magento_Ui\/js\/form\/form","provider":"product_form.product_form_data_source","deps":"product_form.product_form_data_source","namespace":"product_form"},"html_content":{"component":"Magento_Ui\/js\/form\/components\/html","extends":"product_form"}},"components":{"product_form":{"children":{"product_form":{"type":"product_form","name":"product_form","children":{"advanced_inventory_modal":{"type":"container","name":"advanced_inventory_modal","children":{"stock_data":{"type":"fieldset","name":"stock_data","children":{"container_manage_stock":{"type":"container","name":"container_manage_stock","children":{"manage_stock":{"type":"form.select","name":"manage_stock","dataScope":"manage_stock","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Manage Stock","formElement":"select","rawOptions":true,"scopeLabel":"[GLOBAL]","value":0,"options":[{"value":1,"label":"Yes"},{"value":0,"label":"No"}]}},"use_config_manage_stock":{"type":"form.checkbox","name":"use_config_manage_stock","dataScope":"use_config_manage_stock","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":0,"keyInConfiguration":"manage_stock","links":{"linkedValue":"${$.provider}:data.product.stock_data.manage_stock"},"exports":{"checked":"${$.parentName}.manage_stock:disabled"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Manage Stock","sortOrder":"100","scopeLabel":"[GLOBAL]"}},"container_min_qty":{"type":"container","name":"container_min_qty","children":{"min_qty":{"type":"form.input","name":"min_qty","dataScope":"min_qty","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","label":"Out-of-Stock Threshold","formElement":"input","scopeLabel":"[GLOBAL]","validation":{"validate-number":true},"value":0}},"use_config_min_qty":{"type":"form.checkbox","name":"use_config_min_qty","dataScope":"use_config_min_qty","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.min_qty:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":0,"keyInConfiguration":"min_qty","links":{"linkedValue":"${$.provider}:data.product.stock_data.min_qty"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Out-of-Stock Threshold","sortOrder":"300","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock"}}},"container_max_sale_qty":{"type":"container","name":"container_max_sale_qty","children":{"max_sale_qty":{"type":"form.input","name":"max_sale_qty","dataScope":"max_sale_qty","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","label":"Maximum Qty Allowed in Shopping Cart","formElement":"input","scopeLabel":"[GLOBAL]","validation":{"validate-number":true},"value":10000}},"use_config_max_sale_qty":{"type":"form.checkbox","name":"use_config_max_sale_qty","dataScope":"use_config_max_sale_qty","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.max_sale_qty:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":10000,"keyInConfiguration":"max_sale_qty","links":{"linkedValue":"${$.provider}:data.product.stock_data.max_sale_qty"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Maximum Qty Allowed in Shopping Cart","sortOrder":"500","scopeLabel":"[GLOBAL]"}},"container_backorders":{"type":"container","name":"container_backorders","children":{"backorders":{"type":"form.select","name":"backorders","dataScope":"backorders","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Backorders","formElement":"select","rawOptions":true,"scopeLabel":"[GLOBAL]","value":0,"options":[{"value":0,"label":"No Backorders"},{"value":1,"label":"Allow Qty Below 0"},{"value":2,"label":"Allow Qty Below 0 and Notify Customer"}]}},"use_config_backorders":{"type":"form.checkbox","name":"use_config_backorders","dataScope":"use_config_backorders","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.backorders:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":0,"keyInConfiguration":"backorders","links":{"linkedValue":"${$.provider}:data.product.stock_data.backorders"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Backorders","sortOrder":"800","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock"},"exports":{"visible":"${$.name}.backorders:visible"}}},"container_deferred_stock_update":{"type":"container","name":"container_deferred_stock_update","children":{"deferred_stock_update":{"type":"form.select","name":"deferred_stock_update","dataScope":"deferred_stock_update","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Use Deferred Stock Update","scopeLabel":"[GLOBAL]","formElement":"select","rawOptions":true,"value":null,"options":[{"value":1,"label":"Yes"},{"value":0,"label":"No"}]}},"use_config_deferred_stock_update":{"type":"form.checkbox","name":"use_config_deferred_stock_update","dataScope":"use_config_deferred_stock_update","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.deferred_stock_update:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":null,"keyInConfiguration":"deferred_stock_update","links":{"linkedValue":"${$.provider}:data.product.stock_data.deferred_stock_update"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Use Deferred Stock Update","sortOrder":"850","scopeLabel":"[GLOBAL]"}},"container_notify_stock_qty":{"type":"container","name":"container_notify_stock_qty","children":{"notify_stock_qty":{"type":"form.input","name":"notify_stock_qty","dataScope":"notify_stock_qty","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","label":"Notify for Quantity Below","formElement":"input","scopeLabel":"[GLOBAL]","validation":{"validate-number":true},"value":1}},"use_config_notify_stock_qty":{"type":"form.checkbox","name":"use_config_notify_stock_qty","dataScope":"use_config_notify_stock_qty","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.notify_stock_qty:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":1,"keyInConfiguration":"notify_stock_qty","links":{"linkedValue":"${$.provider}:data.product.stock_data.notify_stock_qty"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Notify for Quantity Below","sortOrder":"900","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock"}}},"container_enable_qty_increments":{"type":"container","name":"container_enable_qty_increments","children":{"enable_qty_increments":{"type":"form.select","name":"enable_qty_increments","dataScope":"enable_qty_increments","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Enable Qty Increments","formElement":"select","rawOptions":true,"scopeLabel":"[GLOBAL]","value":0,"options":[{"value":1,"label":"Yes"},{"value":0,"label":"No"}]}},"use_config_enable_qty_increments":{"type":"form.checkbox","name":"use_config_enable_qty_increments","dataScope":"use_config_enable_qty_inc","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.enable_qty_increments:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":0,"keyInConfiguration":"enable_qty_increments","links":{"linkedValue":"${$.provider}:data.product.stock_data.enable_qty_increments"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Enable Qty Increments","sortOrder":"1000","scopeLabel":"[GLOBAL]"}},"container_qty_increments":{"type":"container","name":"container_qty_increments","children":{"qty_increments":{"type":"form.input","name":"qty_increments","dataScope":"qty_increments","config":{"component":"Magento_CatalogInventory\/js\/components\/qty-validator-changer","template":"ui\/form\/field","label":"Qty Increments","formElement":"input","scopeLabel":"[GLOBAL]","validation":{"validate-number":true,"validate-digits":true},"value":1,"imports":{"handleChanges":"${$.provider}:data.product.stock_data.is_qty_decimal"}}},"use_config_qty_increments":{"type":"form.checkbox","name":"use_config_qty_increments","dataScope":"use_config_qty_increments","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-settings","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","exports":{"checked":"${$.parentName}.qty_increments:disabled"},"class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":1,"keyInConfiguration":"qty_increments","links":{"linkedValue":"${$.provider}:data.product.stock_data.qty_increments"}}}},"dataScope":"stock_data","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Qty Increments","sortOrder":"1100","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.enable_qty_increments"}}},"container_is_in_stock":{"type":"container","name":"container_is_in_stock","children":{"is_in_stock":{"type":"form.select","name":"is_in_stock","dataScope":"is_in_stock","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Stock Status","scopeLabel":"[GLOBAL]","formElement":"select","value":"1","options":[{"value":"1","label":"In Stock"},{"value":"0","label":"Out of Stock"}]}}},"dataScope":"quantity_and_stock_status","config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","label":"Stock Status","sortOrder":"1200","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock"}}},"qty":{"type":"form.input","name":"qty","dataScope":"quantity_and_stock_status.qty","config":{"component":"Magento_CatalogInventory\/js\/components\/qty-validator-changer","template":"ui\/form\/field","label":"Qty","formElement":"input","validation":{"validate-number":true,"validate-digits":true,"less-than-equals-to":"99999999"},"sortOrder":"200","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock","handleChanges":"${$.provider}:data.product.stock_data.is_qty_decimal","disabled":"!ns = ${ $.ns }, index = configurable-matrix:isEmpty"}}},"is_qty_decimal":{"type":"form.select","name":"is_qty_decimal","dataScope":"stock_data.is_qty_decimal","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Qty Uses Decimals","formElement":"select","rawOptions":true,"value":"0","sortOrder":"600","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock"},"options":[{"value":1,"label":"Yes"},{"value":0,"label":"No"}]}},"is_decimal_divided":{"type":"form.select","name":"is_decimal_divided","dataScope":"stock_data.is_decimal_divided","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","label":"Allow Multiple Boxes for Shipping","formElement":"select","value":"0","sortOrder":"700","scopeLabel":"[GLOBAL]","imports":{"visible":"${$.provider}:data.product.stock_data.manage_stock"},"options":[{"value":"1","label":"Yes"},{"value":"0","label":"No"}]}},"container_min_sale_qty":{"type":"fieldset","name":"container_min_sale_qty","children":{"min_sale_qty":{"type":"form.input","name":"min_sale_qty","dataScope":"min_sale_qty","config":{"component":"Magento_CatalogInventory\/js\/components\/qty-validator-changer","template":"ui\/form\/field","label":"Minimum Qty Allowed in Shopping Cart","formElement":"input","validation":{"validate-number":true,"validate-digits":true},"sortOrder":"0","value":1,"imports":{"handleChanges":"${$.provider}:data.product.stock_data.is_qty_decimal"},"scopeLabel":"[GLOBAL]","visible":false}},"use_config_min_sale_qty":{"type":"form.checkbox","name":"use_config_min_sale_qty","dataScope":"use_config_min_sale_qty","config":{"component":"Magento_CatalogInventory\/js\/components\/use-config-min-sale-qty","template":"ui\/form\/field","description":"Use Config Settings","formElement":"checkbox","valueMap":{"true":"1","false":"0"},"value":"1","inputField":"ns = ${ $.ns }, index=min_sale_qty","dynamicRowsField":"ns = ${ $.ns }, index=min_qty_allowed_in_shopping_cart","sortOrder":"2","class":"Magento\\CatalogInventory\\Ui\\Component\\Product\\Form\\Element\\UseConfigSettings","valueFromConfig":1,"keyInConfiguration":"min_sale_qty","unserialized":true,"additionalClasses":{"admin__field-no-label":true,"admin__field-use-config":true}}},"min_qty_allowed_in_shopping_cart":{"type":"container","name":"min_qty_allowed_in_shopping_cart","children":{"record":{"type":"container","name":"record","children":{"customer_group_id":{"type":"form.select","name":"customer_group_id","dataScope":"customer_group_id","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","dataType":"text","formElement":"select","label":"Customer Group","disabled":true,"options":[{"label":"ALL GROUPS","value":"32000"},{"label":"NOT LOGGED IN","value":"0"},{"label":"General","value":"1"},{"label":"Wholesale","value":"2"},{"label":"Retailer","value":"3"}]}},"min_sale_qty":{"type":"form.input","name":"min_sale_qty","dataScope":"min_sale_qty","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","dataType":"number","formElement":"input","visible":true,"label":"Minimum Qty","disabled":true}}},"config":{"component":"Magento_Ui\/js\/dynamic-rows\/record","isTemplate":true,"is_collection":true,"componentType":"container"}}},"config":{"component":"Magento_Ui\/js\/dynamic-rows\/dynamic-rows","template":"ui\/dynamic-rows\/templates\/default","componentType":"dynamicRows","sortOrder":"1","addButton":false,"label":"Minimum Qty Allowed in Shopping Cart","scopeLabel":"[GLOBAL]","visible":false,"dndConfig":{"enabled":false}}}},"dataScope":"stock_data","config":{"label":"","sortOrder":"400","scopeLabel":"[GLOBAL]"}}},"dataScope":"","config":{"label":""}}},"dataScope":"data.product","config":{"component":"Magento_Ui\/js\/modal\/modal-component","options":{"type":"slide","title":"Advanced Inventory","buttons":[{"text":"Done","class":"action-primary","actions":[{"targetName":"${ $.name }","actionName":"actionDone"}]}]},"provider":"product_form.product_form_data_source","onCancel":"actionDone"}},"product-details":{"type":"fieldset","name":"product-details","children":{"container_status":{"type":"container","name":"container_status","children":{"status":{"type":"form.checkbox","name":"status","dataScope":"status","config":{"component":"Magento_Ui\/js\/form\/element\/single-checkbox","template":"ui\/form\/field","dataType":"number","formElement":"checkbox","visible":"1","required":"0","notice":null,"default":"1","label":"Enable Product","code":"status","source":"product-details","scopeLabel":"[WEBSITE]","globalScope":false,"sortOrder":0,"options":[{"value":1,"label":"Enabled"},{"value":2,"label":"Disabled"}],"componentType":"field","prefer":"toggle","valueMap":{"true":"1","false":"2"}}}},"config":{"component":"uiComponent","formElement":"container","componentType":"container","breakLine":false,"label":"Enable Product","required":"0","sortOrder":0,"scopeLabel":"[WEBSITE]"}},"container_name":{"type":"container","name":"container_name","children":{"name":{"type":"form.input","name":"name","dataScope":"name","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","dataType":"text","formElement":"input","visible":"1","required":"1","notice":null,"default":null,"label":"Product Name","code":"name","source":"product-details","scopeLabel":"[STORE VIEW]","globalScope":false,"sortOrder":10,"componentType":"field","validation":{"required-entry":true,"max_text_length":"255"},"valueUpdate":"keyup"}}},"config":{"component":"uiComponent","formElement":"container","componentType":"container","breakLine":false,"label":"Product Name","required":"1","sortOrder":10,"scopeLabel":"[STORE VIEW]"}},"container_sku":{"type":"container","name":"container_sku","children":{"sku":{"type":"form.input","name":"sku","dataScope":"sku","config":{"component":"Magento_Catalog\/js\/components\/import-handler","template":"ui\/form\/field","dataType":"text","formElement":"input","visible":"1","required":"1","notice":null,"default":null,"label":"SKU","code":"sku","source":"product-details","scopeLabel":"[GLOBAL]","globalScope":true,"sortOrder":20,"componentType":"field","validation":{"required-entry":true,"max_text_length":"64"},"mask":"{{sku}}","imports":{"handleNameChanges":"${$.provider}:data.product.name","handleDescriptionChanges":"${$.provider}:data.product.description","handleSkuChanges":"${$.provider}:data.product.sku","handleColorChanges":"${$.provider}:data.product.color","handleCountryChanges":"${$.provider}:data.product.country_of_manufacture","handleGenderChanges":"${$.provider}:data.product.gender","handleMaterialChanges":"${$.provider}:data.product.material","handleShortDescriptionChanges":"${$.provider}:data.product.short_description","handleSizeChanges":"${$.provider}:data.product.size"},"allowImport":true,"elementTmpl":"ui\/form\/element\/input","autoImportIfEmpty":true}}},"config":{"component":"uiComponent","formElement":"container","componentType":"container","breakLine":false,"label":"SKU","required":"1","sortOrder":20,"scopeLabel":"[GLOBAL]"}},"container_price":{"type":"container","name":"container_price","children":{"price":{"type":"form.input","name":"price","dataScope":"price","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","dataType":"price","formElement":"input","visible":"1","required":"1","notice":null,"default":null,"label":"Price","code":"price","source":"product-details","scopeLabel":"[WEBSITE]","globalScope":false,"sortOrder":30,"componentType":"field","validation":{"required-entry":true,"validate-zero-or-greater":true},"addbefore":"\u20ac","additionalClasses":"admin__field-small","imports":{"disabled":"!ns = ${ $.ns }, index = configurable-matrix:isEmpty"}}},"advanced_pricing_button":{"type":"container","name":"advanced_pricing_button","config":{"component":"Magento_Ui\/js\/form\/components\/button","displayAsLink":true,"formElement":"container","componentType":"container","template":"ui\/form\/components\/button\/container","actions":[{"targetName":"product_form.product_form.advanced_pricing_modal","actionName":"toggleModal"}],"title":"Advanced Pricing","additionalForGroup":true,"provider":false,"source":"product_details","sortOrder":31,"imports":{"disabled":"!ns = ${ $.ns }, index = configurable-matrix:isEmpty","visible":"ns = ${ $.ns }, index = configurable-matrix:isEmpty"}}}},"config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","componentType":"container","breakLine":false,"label":"Price","required":"1","sortOrder":30,"scopeLabel":"[WEBSITE]"}},"container_tax_class_id":{"type":"container","name":"container_tax_class_id","children":{"tax_class_id":{"type":"form.select","name":"tax_class_id","dataScope":"tax_class_id","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","dataType":"select","formElement":"select","visible":"1","required":"0","notice":null,"default":"13","label":"Tax Class","code":"tax_class_id","source":"product-details","scopeLabel":"[WEBSITE]","globalScope":false,"sortOrder":40,"options":[{"value":"0","label":"None"},{"value":"13","label":"BTW"},{"value":"14","label":"VAT"}],"componentType":"field"}}},"config":{"component":"uiComponent","formElement":"container","componentType":"container","breakLine":false,"label":"Tax Class","required":"0","sortOrder":40,"scopeLabel":"[WEBSITE]"}},"container_quantity_and_stock_status":{"type":"container","name":"container_quantity_and_stock_status","children":{"quantity_and_stock_status":{"type":"form.select","name":"quantity_and_stock_status","dataScope":"quantity_and_stock_status.is_in_stock","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","dataType":"select","formElement":"select","visible":"1","required":"0","notice":null,"default":"1","label":"Stock Status","code":"quantity_and_stock_status","source":"product-details","scopeLabel":"[GLOBAL]","globalScope":true,"sortOrder":50,"options":[{"value":1,"label":"In Stock"},{"value":0,"label":"Out of Stock"}],"componentType":"field","value":"1"}}},"config":{"component":"uiComponent","formElement":"container","componentType":"container","breakLine":false,"label":"Stock Status","required":"0","sortOrder":50,"scopeLabel":"[GLOBAL]"}},"container_weight":{"type":"container","name":"container_weight","children":{"weight":{"type":"form.input","name":"weight","dataScope":"weight","config":{"component":"Magento_Ui\/js\/form\/element\/abstract","template":"ui\/form\/field","dataType":"weight","formElement":"input","visible":"1","required":"0","notice":null,"default":null,"label":"Weight","code":"weight","source":"product-details","scopeLabel":"[GLOBAL]","globalScope":true,"sortOrder":60,"componentType":"field","validation":{"validate-zero-or-greater":true},"additionalClasses":"admin__field-small","addafter":"kgs","imports":{"disabled":"!${$.provider}:data.product.product_has_weight:value"}}},"product_has_weight":{"type":"form.select","name":"product_has_weight","dataScope":"product_has_weight","config":{"component":"Magento_Ui\/js\/form\/element\/select","template":"ui\/form\/field","dataType":"boolean","formElement":"select","componentType":"field","label":"","options":[{"label":"This item has weight","value":1},{"label":"This item has no weight","value":0}],"value":1}}},"config":{"component":"Magento_Ui\/js\/form\/components\/group","formElement":"container","componentType":"container","breakLine":false,"label":"Weight","required":"0","sortOrder":60,"scopeLabel":"[GLOBAL]"}},"container_category_ids":{"type":"container","name":"container_category_ids","children":{"category_ids":{"type":"form.select","name":"category_ids","dataScope":"category_ids","config":{"component":"Magento_Catalog\/js\/components\/new-category","template":"ui\/form\/field","dataType":"text","formElement":"select","visible":"1","required":"0","notice":null,"default":null,"label":"Categories","code":"category_ids","source":"product-details","scopeLabel":"[GLOBAL]","globalScope":true,"sortOrder":70,"componentType":"field","filterOptions":true,"chipsEnabled":true,"disableLabel":true,"levelsVisibility":"1","elementTmpl":"ui\/grid\/filters\/elements\/ui-select","options":[{"value":"2","is_active":"1","label":"Default Category","optgroup":[{"value":"3","is_active":"1","label":"Verlichting","optgroup":[{"value":"4636","is_active":"1","label":"Koplampsproeiers"},{"value":"4994","is_active":"1","label":"Stelmotoren"},{"value":"39184","optgroup":[{"value":"4","is_active":"1","label":"Koplampen\/Achterlichten","optgroup":[{"value":"5","is_active":"1","label":"Audi","optgroup":[{"value":"8","is_active":"1","label":"A2 (2000-2005)"},{"value":"9","is_active":"1","label":"A8 D3 2002-2005"},{"value":"10","is_active":"1","label":"80\/100"},{"value":"50","is_active":"1","label":"A3 (8L) 1995-2003"},{"value":"53","is_active":"1","label":"A4 (8E) 2001-2005"},{"value":"55","is_active":"1","label":"A4 (B5) 1995-2001"},{"value":"57","is_active":"1","label":"A6 (4B) 1997-2004"},{"value":"58","is_active":"1","label":"TT 8N (1998-2006)"},{"value":"154","is_active":"1","label":"A3 (8P) 2003-"},{"value":"155","is_active":"1","label":"A4 (B7) 2004-2008"},{"value":"157","is_active":"1","label":"A6 1994-1997"},{"value":"169","is_active":"1","label":"A8 (D2) 1994-2002"},{"value":"353","is_active":"1","label":"A6 4F2 2004-2012"},{"value":"1051","is_active":"1","label":"Q7"},{"value":"3645","is_active":"1","label":"A4 (8H) Cabrio 2002-2005"},{"value":"4739","is_active":"1","label":"A4 (B8) 2008-.."},{"value":"7666","is_active":"1","label":"Q5"},{"value":"7671","is_active":"1","label":"TT 8J"},{"value":"7677","is_active":"1","label":"A3 Cabrio 08-09"},{"value":"7678","is_active":"1","label":"A5"},
```

and so on.... (40.000 categories !)

**Comment by bangnguyen47** [comment]
@carfantasy you can try to set maximum limit timeout and execution time for web server

**Comment by 12impress** [comment]
The sollution:
I empty the database table catalog_category_product_index.
Problem solved!
