### ISSUE TITLE
Payflow Authorization currency missing

### ISSUE THREAD

**Issue by H3dz** [magento/magento2#7719]
The currency is missing when doing an Authorization with Payflow.

The currency setting was already missing in other places and was fixed by @kriby in
https://github.com/magento/magento2/commit/337c63c438a511a8e4aa95508ebb4849057d1be5
and was merged into the develop branch
https://github.com/magento/magento2/commit/152dbdcac63f976aa7b69ae619693839427bb2ee

but it seems that the Authorization code was forgotten.

### Preconditions
1. Magento version 2.1.2
2. PHP 7.0.11
3. MySQL 5.6

### Steps to reproduce
1. Set the store currency to CAD
2. Set Payflow "Payment Action" to "Authorization"
3. Make a purchase

### Expected result
1.  The authorization should be made in CAD and the payment should be approved.

### Actual result
1. On PayPal the authorization transaction was made in USD.
2. The payment fails with error "Invalid or unsupported currency code".

### Fix
In app/code/Magento/Paypal/Model/Payflowpro.php in the buildBasicRequest method
Add

`$request->setCurrency('CAD'); // Hardcoded to CAD`

**Comment by YevSent** [comment]
Hi, @H3dz, thanks for reporting.

This issue (internal ticket MAGETWO-58376) is already fixed on develop branch and fix will be available in Magento 2.1.4 version.

Some notes: the `\Magento\Paypal\Model\Payflowpro::authorize` is not using for authorization the `\Magento\Paypal\Model\Payflow\Transparent::authorize` is used instead (the issue has been fixed in this method).

**Comment by H3dz** [comment]
Hi @joni-jones  it's strange because it only started to work when I updated `\Magento\Paypal\Model\Payflowpro::buildBasicRequest `

But I did cherry pick a lot of code from the develop branch to make my current installation work.

I'll re-open this issue if the problem persists in 2.1.4.

Thanks

**Comment by YevSent** [comment]
> it's strange because it only started to work when I updated `Magento\Paypal\Model\Payflowpro::buildBasicRequest`

`\Magento\Paypal\Model\Payflow\Transparent::authorize` uses `\Magento\Paypal\Model\Payflowpro::buildBasicRequest` here's why it's working for you.

**Comment by mariamghalleb** [comment]
i'm on 2.2.3 and still having the same problem ... Any solution?

**Comment by mariamghalleb** [comment]
i have two websites one is with CAD the other is with USD, since the authorization is always in USD,  the USD website works, but the CAD website's authorization is also in CAD, if I hard code it , wouldn't it cause a problem for the US website? 
Any other solution for this?

**Comment by Hailong** [comment]
@mariamghalleb You can refer to my PR at https://github.com/magento/magento2/pull/22399, which would fix the problem with CAD.
