### ISSUE TITLE
Composer.json extra/map node requires at least empty app/code to work

### ISSUE THREAD

**Issue by wsheldon** [magento/magento2#7856]
I'm writing an extension that uses the extra/map node to copy images from our extension to pub/media.  The files aren't copied successfully unless I create an empty app/code directory. 

### Preconditions (*)

1. Magento CE 2.3.x installed via composer & 2.4-develop

### Steps to reproduce (*)

1.  Create an extension as composer package
2.  In composer.json, include extra/map node for copying files when composer update runs
3.  Set relative path for target, i.e.

`"extra": {
        "map": [
            [
                "pub/media/*",
                "../../pub/media"
            ]
        ]
    }`

### Expected result (*)
Files in pub/media in extension are copied to the pub/media directory of the Magento install
### Actual result (*)
Nothing is copied unless I manually create an empty directory at app/code, then files are copied successfully.
![image](https://user-images.githubusercontent.com/51680850/71413244-eee2b080-2659-11ea-9570-06cc8d58fea6.png)

**Comment by veloraven** [comment]
@wsheldon thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If it is rather a question than an issue and you are looking for help or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by wsheldon** [comment]
@veloraven I've updated my issue now.  Thanks!

**Comment by magento-engcom-team** [comment]
@wsheldon thank you for report.
The issue was fixed in 2.2 versions

**Comment by magento-engcom-team** [comment]
@wsheldon, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by hostep** [comment]
@magento-engcom-team: I think you guys have to remove the label `Fixed in 2.2.x` and re-open this issue, based on your latest comment, no?

**Comment by brandontamm** [comment]
Do you guys have a primer on Magento's recommended usage of mapping via composer, or any documentation to show how to map files? particularly, how to map all files in a directory so we dont have to map each and every file?

**Comment by hostep** [comment]
@brandontamm, see documentation over here: https://github.com/magento/magento-composer-installer

To see some examples, you can take a look at the file: `vendor/magento/magento2-base/composer.json` (not available in the git repo, only after setting up a magento2 project using composer).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30063` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by unailopezvdshop** [comment]
still reproduced in magento 2.3.7 and 2.4.2-p1, any update about that?

**Comment by mortenbirkelund** [comment]
Still relevant.
