### ISSUE TITLE
Configurable product tax class from simple product

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#7997]
### Preconditions

1. I use Magento 2.1.2
2. PHP 5.6.X, MySQL 5.4 and APACHE.

### Steps to reproduce

1. I have a configurable product, which have two simple products.
2. One product have tax_class "VAT20" and second simple product have tax_class "None".
3. VAT20 tax_class have vat 20% on product price.

### Expected result

1. Tax should be applied to the product.

### Actual result

1. Tax of 20% is not applied to the product.

**Comment by choukalos** [comment]
Hi @RishabhRkRai ; currently with configurable products and as we did in Magento 1.x we use the tax class of the meta product (not the underlying simple products).  

What country are you in?

Can you provide some insight/examples of where a configurable product's selection would have different tax classes?  I'm aware of some situations where goods (such as clothing) below a certain price isn't taxed as an example.  But in all the cases we reviewed and feedback from merchants pointed us to pricing differences between product variants wouldn't have changed enough to trigger a different tax class.

Thanks!

**Comment by rishabhrkrai** [comment]
Hi @choukalos , Suppose I have a goods like Shirt with two different varients (White, Blue) with tax 10% and 15%. But when i order the shirt with Blue varient, tax is not applied and if i put this tax to configurable product tax is applied for both of its varients.
Is there any way to add different tax to different varients?

**Comment by jghaanstra** [comment]
Duplicate of https://github.com/magento/magento2/issues/6729

**Comment by okorshenko** [comment]
Hi @jghaanstra thank for linking the issues.
@RishabhRkRai the issue #6729 has been fixed in 2.2-develop branch and will be available with release 2.2.1 soon

**Comment by tmorcet** [comment]
Hi Guyz,

I have this issue with in 2.2.2 magento. 

The correct class tax (set in the simple product) is not applied because of the process quote items is focused in the configurable product. 

Can you tell me if @magento-engcom-team have a patch for the 2.2.2 ?

Best regards

**Comment by tp-gibert** [comment]
Hi guyz,

This issue is not fixed in the 2.2.2.

Indeed, the simple product tax class is not apply because the quote items process is focused on the configurable.

Can you tell me if @magento-engcom-team has a patch for 2.2.2 ?

Best regards

**Comment by tp-gibert** [comment]
Hi @magento-engcom-team , 

can you give us the related commits of the fix ?

The bug with simple product with different rates is reproduced on our 2.2.2.

Best regards

**Comment by MattFluidDigital** [comment]
Hello,
are there any updates on this? The fix in #6729 does not resolve this issue. If a configurable product has a simple product with tax and one without tax, then the final price is not calculated correctly when added to the basket. It takes the tax class of the configurable product and applies this class to the product.

**Comment by rishabhrkrai** [comment]
Hi,

This issue is still not resolved on Magento 2.2.4 installation. I install new version and didn't see anything changed on this version. Is there anything else?

**Comment by sandipansaha** [comment]
Hi @RishabhRkRai @MattFluidDigital 

For the time being who is looking for a workaround I have built a module to change the Magento behaviour according to our requirement.

You can check the answer below -

https://magento.stackexchange.com/questions/228276/how-can-i-allow-a-configurable-product-price-tax-to-apply-as-per-tax-class-of/228277#228277

**Comment by anilios** [comment]
Hi,
I am using Magento2.2, I have 2 different product class. When I have created new product, tax calculation working fine while after editing old product and change product class to none its still showing taxes in the cart. I have also tried with clear cache and reindexed.
Can someone help me?
Thanks in advance.

**Comment by tomekjordan** [comment]
Tax issue exists even on Magento 2.3.1.
It should be fixed, and tax rate should be inherited from child products on configurables.
Or at least - there should be option for it - to use Main product tax rate, or from child.
Dissapointed that so simple and basic tax "bug" still exists in all Magento 2 releases

**Comment by iloa08** [comment]
Same here with magento 2.3.1 : is there a fix ?
Thanks
