### ISSUE TITLE
Special characters in store name converted to numerical character references in email subject

### ISSUE THREAD

**Issue by mattcoz** [magento/magento2#8094]
If your store name has a special character in it, such as an apostrophe, it will be converted to a numerical character reference in any email subject. For example:

Store name: Bob's Burgers
Reset password email subject: Reset your Bob&#039;s Burgers password

I've tried sending the email directly with php and with Zend_Mail without issues, so it must be somewhere in Magento's email template handling.

**Comment by veloraven** [comment]
@mattcoz thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by mattcoz** [comment]
Steps to reproduce:

1. Set store name to "Bob's Burgers"
2. Request a password reset

Expected result:

Subject should be "Reset your Bob's Burgers password"

Actual result:

Subject is "Reset your Bob&amp;#039;s Burgers password"

**Comment by veloraven** [comment]
@mattcoz thank you for update.
I have created internal ticket for this issue: MAGETWO-63154

**Comment by bat553** [comment]
@veloraven Is there a way to track this ticket ?

**Comment by rudik99** [comment]
Im not sure if you want me to raise another issue, but this happens all the way through the emails.

So If a customer submits via contact form the same thing happens - apostrophe is converted like the example above.

**Comment by korostii** [comment]
I can confirm that this issue appears in other email as well. For example, when you share a wishlist via email,  the subject according to [this line](https://github.com/magento/magento2/blob/develop/app/code/Magento/Wishlist/view/frontend/email/share_notification.html#L7) and then in your inbox it is also shown with this weird `&#39;` inside.

**Comment by korostii** [comment]
In particular case of the wishlist, the issues seems to be coming out of [this little quirk](https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/Template/Filter.php#L569) which doesn't seem to care whether the directive is invoked inside subject or body of the email. 

To anyone struggling, this is quite an easy workaround: in a given template just add that `|raw` part at the end of the directive, like in the following:
`<!--@subject {{trans "Take a look at %customer_name's Wish List" customer_name=$customerName|raw}} @-->`

**Comment by hardyjohnson** [comment]
Probably related #6597 and MAGETWO-58663 which is referenced in that issue.

**Comment by mattcoz** [comment]
@korostii Thanks for the workaround, unfortunately it's a pain to have to override every single email template file to fix this. Instead I created a simple plugin to reverse the encoding.

```
public function afterGetSubject(\Magento\Email\Model\Template $subject, $result)
{
	return htmlspecialchars_decode((string)$result, ENT_QUOTES);
}
```

**Comment by PieterCappelle** [comment]
Any update on this one?

**Comment by PieterCappelle** [comment]
Quick fix is in `di.xml`

```<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Email\Model\Template">
        <plugin name="mail_subject" type="VENDOR\MODULE\Plugin\Template" sortOrder="100" />
    </type>
</config>
```

In Template.php
```<?php
namespace VENDOR\MODULE\Plugin;

class Template
{
    public function afterGetSubject(
        \Magento\Email\Model\Template $subject,
        $result
    ) {
        return htmlspecialchars_decode((string)$result, ENT_QUOTES);
    }
}
```

**Comment by veloraven** [comment]
This issue was fixed in develop branch.
Closed.

**Comment by korostii** [comment]
Hi @veloraven, having a fix on develop isn't the same as resolving the issue.

Are there any plans to backport this issue on Magento side? 
If not, please reopen the issue and mark it as "up for grabs" so that people would know it is okay to create a pull request targeting `2.1-develop` in order to help with the backporting process.

**Comment by ziiljuks** [comment]
`return htmlspecialchars_decode((string)$result, ENT_QUOTES);`

This didn't work for me but this did:

`return mb_encode_mimeheader((string)$result,"UTF-8");`

**Comment by kanduvisla** [comment]
In what develop branch is this fixed then? Because it still persists in 2.1.8.

**Comment by korostii** [comment]
@magento-engcom-team The issue is still present, please reopen (see the comment above).

**Comment by ihor-sviziev** [comment]
@korostii this issue was fixed in 2.2.0. You can find related commits there:
https://github.com/magento/magento2/search?q=MAGETWO-63154&type=Commits&utf8=%E2%9C%93

@magento-engcom-team looks like it wasn't fixed in 2.1.x

**Comment by KM-HM** [comment]
This issue is still in in 2.2.4


### Preconditions

1.  Magento Version 2.2.4
2. PHP 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce
1. Create a e-mail template containing a "ü" (üäö  german stuff)  in the subject
2. Create an Order to get the E-mail
3. View the email in outlook

### Expected result
1. E-mail subject should display the "ü" like it was authored

### Actual result
1. E-mail subject shows "?" question mark in the same position as the "ü" should be

Also the System does not retrieve the subject line when opening the email template.

**Comment by ihor-sviziev** [comment]
Hi @kemexyz ,
It looks very similar, but it's different. Could you report it as separate issue?

**Comment by KM-HM** [comment]
Hey @ihor-sviziev ,

sure, not quite sure if got 2 issues mixed up here ... sorry!

**Comment by bewithmanoj** [comment]
> Quick fix is in `di.xml`
> 
> ```
> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
>     <type name="Magento\Email\Model\Template">
>         <plugin name="mail_subject" type="VENDOR\MODULE\Plugin\Template" sortOrder="100" />
>     </type>
> </config>
> ```
> 
> In Template.php
> 
> ```
> namespace VENDOR\MODULE\Plugin;
> 
> class Template
> {
>     public function afterGetSubject(
>         \Magento\Email\Model\Template $subject,
>         $result
>     ) {
>         return htmlspecialchars_decode((string)$result, ENT_QUOTES);
>     }
> }
> ```



> Quick fix is in `di.xml`
> 
> ```
> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
>     <type name="Magento\Email\Model\Template">
>         <plugin name="mail_subject" type="VENDOR\MODULE\Plugin\Template" sortOrder="100" />
>     </type>
> </config>
> ```
> 
> In Template.php
> 
> ```
> namespace VENDOR\MODULE\Plugin;
> 
> class Template
> {
>     public function afterGetSubject(
>         \Magento\Email\Model\Template $subject,
>         $result
>     ) {
>         return htmlspecialchars_decode((string)$result, ENT_QUOTES);
>     }
> }
> ```

Where i can put the code can you help i am new in magento
