### ISSUE TITLE
Wrong default price configurable product if default display currency different from base currency

### ISSUE THREAD

**Issue by Diowyn** [magento/magento2#8921]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.15

### Steps to reproduce

1. Set base currency to USD
2. Set default display currency to another currency, ie. INR
3. Create configurable product
4. Switch currency to default display currency
5. Go to configurable product detail view

### Expected result

1. Default price is basePrice * conversionRate

### Actual result

1. Default price become basePrice * conversionRate * conversionRate
2. When variation selected price become right

**Comment by jugalpatelkrish** [comment]
I confirm this issue exists in **Magento Enterprise Edition 2.1.3**
We are facing the same issue when we have set the base currency to "KWD" and our default display currency is "USD".

**This issue happens only on the product detail page and not on the listing page.  Listing page displays the price correctly.**

**Comment by vincent2090311** [comment]
I get this issue on magento CE 2.1.5. Another thing, magento CE cached simple product price
**Steps to reproduce**
- Create multi-store view with multi-currency but same base currency (eg: base currency is USD, store US display USD, store UK display EUR)
- when select configurable option, store US is ok, but store UK show price from store US.
eg: configurable and simple product have same price value ($10), after changed currency display to EUR and select configurable option, price show as 10EUR. Disable block html cache then price is ok
**Expected result**
after select configurable option, price show right value

**Comment by jugalpatelkrish** [comment]
> when select configurable option, store US is ok, but store UK show price from store US.
eg: configurable and simple product have same price value ($10), after changed currency display to EUR and select configurable option, price show as 10EUR. Disable block html cache then price is ok
Expected result
after select configurable option, price show right value

This is caching issue.  Disabling the "Page blocks HTML" cache resolves this issue.

**Comment by antbates91** [comment]
We recently came across this issue and created a fix. You can try and install this module and see if it works. https://github.com/WeareJH/m2-core-bug-currency-conversion

**Comment by jugalpatelkrish** [comment]
Thanks @antbates1991 
We have also fixed this issue for one of our clients.  Thanks for sharing the solution with all.

**Comment by jworthy89** [comment]
Fix from @antbates1991 works great. Thanks for the fix.

**Comment by petterkj** [comment]
Confirmed 2.1.6. And antbates1991 fix works as a workaround!

**Comment by nitinwaves** [comment]
Guys this a critical bug and Magento Should fix into next release

**Comment by AlexWorking** [comment]
Hello @Diwyn. An internal issue - MAGETWO-70366 has been created based on Your issue. You”ll be informed as the issue is fixed. Thank You for applying.

**Comment by epicglows** [comment]
So, I downloaded all the files from https://github.com/WeareJH/m2-core-bug-currency-conversion to fix this issue, but where do I have to put all them files?

-- Fixed: /app/code/Jh/CoreBugCurrencyConversion/

**Comment by antbates91** [comment]
@epicglows The easiest way is to pull the module in via composer. 

If you don't have composer on your Magento repo you can create the following folders `Jh/CoreBugCurrencyConversion` in `Magento-Root/app/code` and drop the files in there.

**Comment by HedonieBrazil** [comment]
It is crazy magneto 2 have such huge bug !! CoreBugCurrencyConversion Module work great for me ! Thanks !

**Comment by niko7869** [comment]
@antbates1991 i still have the problem i tried your solution also it didn't work for me i am using 2.1.8, can you suggest or tell another way please

**Comment by niko7869** [comment]
can anyone help in this issue please its urgent please please

**Comment by magento-engcom-team** [comment]
@Diwyn, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
