### ISSUE TITLE
Catalog price rules not working with Magento 2.1.4 and 2.1.5

### ISSUE THREAD

**Issue by tejasvyas1988** [magento/magento2#9032]
### Preconditions
1. Magento 2.1.4 and 2.1.5
2. PHP 5.6

### Steps to reproduce
1. Create catalog rule from backend
2. Check on the specific product.

### Expected result
1. Catalog price rules price not displaying

### Actual result

1. Catalog price rules price should apply

**Comment by orlangur** [comment]
Did you assure that reindexing worked correctly?

**Comment by tejasvyas1988** [comment]
Hi Vlad..Yes..That I have done..Every possible thing I have done from my end..

**Comment by korostii** [comment]
Wait, are you implying that the whole feature is not working?
Have you followed the [user guide](http://docs.magento.com/m2/ce/user_guide/marketing/price-rules-catalog.html)? 
The documentation seems to imply that you need the crons running, but you can ensure a reindex via `bin/magento indexer:reindex`

Or is this there a specific rule that doesn't work for you? In that case, could you please post its condition and action here, as well?
Are you sure any products match the rule? If so, could you maybe also post a screenshot of the relevant product attributes?

FYI the issues which aren't present on a clean version of Magento 2 CE aren't likely to get resolved in here. If you have any custom or 3rd-party modules installed, I'd suggest disabling them and trying to reproduce the issue with them being inactive.

**Comment by orlangur** [comment]
@tejasvyas1988 I see... The problem here is that vanilla Catalog Rule functionality is covered with automated test suite and cannot be broken for any release.

Thus either indexer didn't complete properly (some fatal error during manual execution or no  cron/no manual run) or there are some special circumstances on your instance.

For example, if you install clean Magento 2 CE with official sample data, most likely catalog rules will work properly.

**Comment by emb-resmi** [comment]
@orlangur 

  We are also facing same issue for catalog price rule in version EE 2.1.5. Have manually executed the indexing as well . But the discounted price are not updating in front-end.

For simple product it works. The issue is happening for configurable products.

**Comment by tejasvyas1988** [comment]
Hi, Just tried on magento EE 2.1.6 and its still not working..anyone can please suggest if it is magento bug?

**Comment by tejasvyas1988** [comment]
@orlangur How can i debug the indexing process?
@korostii i am using plain fresh magento with magento given sample data.

**Comment by korostii** [comment]
@tejasvyas1988, you seem to be answering a question I didn't ask while ignoring the questions I actually did ask. 

I was pointing out that the description you provided for the issue was lacking some essential information. Would It kill you to create a couple screenshots? I don't think anyone will take your bugreport seriously unless you add more information, because guess what: the feature as a whole works.
Here are a couple of counter-examples for your claims 
https://www.youtube.com/watch?v=i0uEHjnH3x0
https://www.youtube.com/watch?v=cOrIiWPFbpM

There might be some corner case bug or a misconfiguration or a misunderstanding of how a certain condition should work, but no-one else here on the Internet will be able to guess which is it - *unless you provide more information about the issue*

You didn't even bother mentioning you were running EE, which reminds me:
> Please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
> That way, your issue should probably get acknowledged and solved faster. GitHub is intended for the Community Edition issue reports.

Please add more details to the issue, otherwise there is a high probability that some community manager will just add either a "needs update" label or a "couldn't reproduce" comment.

**Comment by magento-engcom-team** [comment]
@tejasvyas1988, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by juergengp** [comment]
i have the same issuie on 2.1.9. CE

**Comment by juergengp** [comment]
itws always funny seeing developer requesting exaples instead of heavily testing their code...

**Comment by orlangur** [comment]
@juergengp what do you mean? Do you have steps revealing this issue on a clean Magento installation? It is not possible to "heavily testing their code" when problem is not reproducible.

**Comment by udovicic** [comment]
For me it wasn't working as admin interface had not *status* toggle. But if you change it manually, it actually works (as in calculates the price). Though I am not sure why was the *status* button missing in the first place.

**Comment by kamalj27** [comment]
1.) Catalog Rule not updated in frontend in magento 2.2.2
2.) After delete Catalog Rule its showing in frontend.

Not working ... Only first time Rule add then its applied thenafter its not updated in frontend.

**Comment by kamalj27** [comment]
1.) Catalog Rule not updated in frontend in magento 2.2.2
2.) After delete Catalog Rule showing in frontend.

Not working ... Only first time Rule add then its applied thenafter its not updated in frontend.

**Comment by israelguido** [comment]
Same problem with EE 2.1.8

**Comment by spraxis** [comment]
Same in 2.2.2 (clean installation). I created a simple catalog rule with only one condition: "SKU is xxx". 

I tried removing everything in pub/static and var folders, reindexing, etc., but still nothing.

**Comment by eugenbg** [comment]
i just wandered to this issue after seeing that the table catalogrule_product_price does not change after applying the rules..
but after executing the cron the table refreshed, so i guess this is the problem everyone here are having

**Comment by angelo983** [comment]
As stated in #11326, check var/log and auto_increment values in your magento db, in particular catalogrule_product_price

**Comment by devendra1991** [comment]
**is_active** field is there in Catalog rule form but it has inline CSS " display: none"

**Comment by zugangxue** [comment]
Same problem with CE 2.1.0

**Comment by aayushivadhva** [comment]
I am also facing the same issue that catalog rule is working fine for simple products but its not working for configurable product. I have used magento version 2.2.5

**Comment by alexmorco** [comment]
Thanks for sharing this video tutorial, I was working to set catalog price rules in my Magento store, Your vide and this post helped me a lot, https://www.cloudways.com/blog/shopping-cart-and-catalog-price-rules-in-magento/.﻿

**Comment by dan-ding** [comment]
as @devendra1991 points out -- if you can't set the rule status to "active", then the admin UI has a problem and the rule isn't applying because it's *not* active by default.

why the rule status option is hidden ... ?

**Comment by mageprashant** [comment]
> **is_active** field is there in Catalog rule form but it has inline CSS " display: none"

any solution for this?

**Comment by DMaterka** [comment]
In my case it was content staging module that prevented the is_active select to show. The indexers were set on schedule.  
I found that setting end date of scheduled changes in content staging dashboard magically allowed cron to launch catalog rules indexers
