### ISSUE TITLE
Stock status not saved when 'Manage Stock' is set to 'No'

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#9774]
When I'm trying to change the stock status to 'Out of stock' and 'Manage stock' is set to 'No', the stock status stays 'In Stock'. I'm not sure if this is intended behaviour or not, but if I recall correctly, when 'Manage stock' was set to 'No', it would only affect the increment / decrement of the stock qty. You were always able to set the status to 'in stock' or 'out of stock'.

### Preconditions

1. Magento 2.1.6

### Steps to reproduce

1. Create a (simple) product
2. Set 'Manage Stock' to 'No'. (tested it with global configuration setting)
3. Set 'Stock Status' to 'Out of Stock'.
4. Save product

### Expected result

1. Product should be saved with out of stock status

### Actual result

1. Product is still in stock

**Comment by Turv** [comment]
I can confirm I have the same problem too. I do not want to manage stock levels, only a binary in stock / out of stock.

**Comment by veloraven** [comment]
@kanduvisla thank you for your report but I'm closing this issue as not a bug.
As there is no need in status when you do not manage stock.
However you can report an improvement to  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96))

**Comment by Turv** [comment]
Hi @veloraven,

I disagree that this is not a bug. When you choose not to Manage Stock Levels you should still be able to set a product as in stock, or out of stock manually.

Instead when a product has the value of In Stock, you change this to Out of Stock and click save, it simply doesn't save the value and the value remains as In Stock with no feedback on the screen. This is incredibly confusing for users of the system who simply believe there is a fault that this status field is not being saved.

The work around is that we have to set to "Manage Stock" - Yes, and only then change the status to Out of Stock. There is no longer a way to set a product as Out of Stock without changing Manage Stock to yes. Are you saying that you are now enforcing users to manage their stock levels?

The consequence of the above is that once you have had to change the settings to forcibly manage the stock to simply mark a product as out of stock you can't just select "In Stock" as the Quantity is 0 and Manage Stock is set, so you have to tell the system you no longer wish to manage the stock.

All of which is very hacky, so I can't believe that this is intended functionality?

**Comment by klimart** [comment]
I'm also experiencing this bug on 2.1.8.
I have virtual products and do not need to manage stock quantities at all.
But ability to change 'in stock' or 'out of stock' is still required.
This is bug and should be resolved as bug and not as improvement.

**Comment by erfanimani** [comment]
I agree with everyone saying that this is a bug. I don't want to manage stock **levels**, but still want the ability to mark a product as out of stock.

**Comment by ewth** [comment]
I believe this to be a bug too. Forcing stock management in order to able to flag an item as out of stock seems absurd; levels vs status seem like they should be independent?

**Comment by tylers-username** [comment]
Seems like this may still be an issue in the latest 2.2.

**Comment by brohon** [comment]
This is still an issue on 2.4.3 I too, wish to control the boolean Stock Status without worrying about stock quantity. We have another system that manages our inventory. We don't want to use Magento for this. The problem becomes really annoying because when "Manage Stock" is enabled, Magento deducts the shipped item from the quantity. But we're syncing our inventory through the API, so if we don't want to show committed items, then the magento quantity is already 0.
