### ISSUE TITLE
Configurable products preview images/color swatches not working when "Use Flat Catalog Product" is enabled.

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#9965]
### Preconditions
1. Install Magento CE 2.1.7

### Steps to reproduce
1. In the admin, edit the color attribute: enable "Used in product listing", set input type to "Visual Swatch", enable "Update Product Preview Image", enable "Use Product Image for Swatch if Possible"
2. In the admin, create a configurable product with a couple child products, with each their own set of images
3. Go to the category page, or product page, and change swatches.

### Expected result

1. Image changes depending on which swatch you selected

### Actual result

1. Image stays the same

**Comment by MattND** [comment]
I also have the exact same issue! Very frustrating............

**Comment by MattND** [comment]
Any news on this? Our whole collection of sites since upgrading to 2.1.7 no longer have swatches that operate whilst flat catalog is enabled.

**Comment by VasylShvorak** [comment]
Thanks for reporting this issue. Created internal issue MAGETWO-70169 to investigate and track this issue.

**Comment by MattND** [comment]
Any update?

**Comment by nihachi** [comment]
same here , im using m2.1.6

**Comment by sinsitde** [comment]
Enabled Options "Visible on Catalog Pages on Storefront" and "Used in Product Listing" in color attribute fix the problem for me.

**Comment by MattND** [comment]
Yes that works  temporarily  but as soon as you reindex it breaks again. Any other update on this yes? Basically it stops all visbale swatches from working- we can't be the only ones here?

**Comment by aliantech** [comment]
using 2.1.7
i have the same problem, sometime it works, but after flush the cache or reindex it breaks again, it can not show swatch image, only show swatch words!!!!!!!

**Comment by IndigoLV** [comment]
The problem is also present in 2.1.8.

**Comment by mtlkrlg** [comment]
Tried to use different size and format for the images with 2.1.7 and 2.1.8 but no luck, please post if someone able to make it work.

**Comment by OZZlE** [comment]
I think this is more related to this: https://github.com/magento/magento2/issues/5142

**Comment by magento-engcom-team** [comment]
@erfanimani, thank you for your report.
The issue is already fixed in 2.1.9

**Comment by aahmed2479** [comment]
hi, i'm using 2.1.9 and still the issue is there. swatches on product page don't work!

**Comment by u12206050** [comment]
Hi I updated to 2.1.10 and it still seems to be an issue, however I found that when I disabled "Use Flat Catalog Product" then it works again, but then Magento is very slow. Anyone have any advice regarding this?

**Comment by s00071609** [comment]
![website](https://user-images.githubusercontent.com/19631643/33376139-8d5617ea-d560-11e7-8874-b82a0641b979.PNG)

I hope someone can help. Magento 2.2.1 update shows unwanted fields in configurable products as shown by the arrow. For some reason that field fill itself with a number as in the image when the option is selected. 

Anyone else having this issue?

**Comment by Andrease89** [comment]
Yes, have the same issue as above in 2.2.1.
The original problem still precists for me...

**Comment by salelsol** [comment]
- Just uncheck: Hide from Product Page for images stay the same.

**Comment by OZZlE** [comment]
Magento has told us at least not to use Flat tables in M2, might be interesting to know..

**Comment by gfxguru** [comment]
anyone else still having issues with swatch image not showing up? I'm on 2.3.2.  Tried with and without Flat tables, nothing. 
Is there a size limitation to this file? the preview shows when uploading but not on the display of the product.
